### ISSUE TITLE
support for upgrade tests

### ISSUE THREAD

**Issue by dachary** [metacloud/molecule#1005]
# Issue Type

- Feature request

# Desired Behaviour

In the real world we have long lived machines. We run playbooks against them to change from state X to state Y. The tests in molecule only verify it works to go from nothing to state Y. It should offer support to check that going from nothing to state X, with a previous version of the playbooks, and then running a more recent version of the playbooks to go to state Y is successful and passes molecule verify.

**Comment by retr0h** [comment]
This exists as of Molecule 2.2.  A prepare playbook was introduced.  You can place the steps necessary in prepare to put your system into a specific state.  Then the playbook.yml can be used to upgrade.
