### ISSUE TITLE
ANSIBLE_ROLES_PATH path component relative to the previous one

### ISSUE THREAD

**Issue by dachary** [metacloud/molecule#1008]
# Issue Type

- Bug report

# Molecule and Ansible details

```
ansible --version = ansible 2.4.0.0
molecule --version =  version 2.3.1
```

- Molecule installation method: pip
- Ansible installation method: pip

# Desired Behaviour

ANSIBLE_ROLES_PATH: roles:../../../infrastructure/roles:../../../postfix/roles:../../../bind/roles

Each path component is relative to a fixed directory

# Actual Behaviour (Bug report only)

ANSIBLE_ROLES_PATH: roles:../../../infrastructure/roles:../postfix/roles:../bind/roles

When converted to absolute directory, each path component is evaluated relative to the directory name of the previous path component.

**Comment by retr0h** [comment]
Thanks @dachary
