### ISSUE TITLE
Add proxy_env values for Docker and default to none for logger

### ISSUE THREAD

**Issue by mkinney** [metacloud/molecule#1015]
# Issue Type
- Feature request

# Molecule and Ansible details

```
ansible 2.4.0.0
molecule, version 2.3.1
```

- Molecule installation method: pip
- Ansible installation method: pip

# Desired Behaviour

'molecule converge' should bring up a docker instance, but since we're behind a proxy, we need to add proxy info before we can pull docker images. We also need to change logger to none.

Add ability to provide proxy values for Dockerfile.j2. Something like this:
ENV http_proxy 'http://192.168.64.1:3128'
ENV https_proxy 'http://192.168.64.1:3128'
ENV no_proxy '192.168.64.1,127.0.0.1,localhost,localhost.localdomain'

# Actual Behaviour (Bug report only)
virtualenv venv
source venv/bin/activate
pip install ansible molecule docker-py
molecule init role --role-name foo
cd foo
molecule --debug converge
(fails)

If the three lines are added...
    $ head -n 7 molecule/default/Dockerfile.j2
    # Molecule managed
    
    FROM {{ item.image }}
    
    ENV http_proxy 'http://192.168.64.1:3128'
    ENV https_proxy 'http://192.168.64.1:3128'
    ENV no_proxy '192.168.64.1,127.0.0.1,localhost,localhost.localdomain'

and...
    sed -i '' -e 's/log_driver: syslog/log_driver: none/' molecule/default/create.yml

then 'molecule converge' works

**Comment by retr0h** [comment]
You are free to do this as you please.  The templates are merely templates intended for you to customize how you see fit.

**Comment by mkinney** [comment]
What about the changing of the log_driver?

**Comment by retr0h** [comment]
You're free to change the generated files how you see fit.

**Comment by retr0h** [comment]
@mkinney thank you for the issue.  Closing out.
