### ISSUE TITLE
Question about code for installing goss

### ISSUE THREAD

**Issue by marcinpraczko** [metacloud/molecule#1017]
Hi,

I am wondering whether you are OK to create ansible-galaxy role for installing goss based on your code (for example from file: 
- cookiecutter/verifier/goss/{{cookiecutter.repo_name}}/tests/test_default.yml

If you are OK with this - I am happy to create this role. I think that will be valuable to community have this as separate role as well, especially that ansible module for goss has been created already?
- https://github.com/indusbox/goss-ansible

**Comment by retr0h** [comment]
Sure, @marcinpraczko feel free to create it.  So long as the role is actively maintained I don't see a problem with it.  

👍

**Comment by marcinpraczko** [comment]
Hi,

So simple role has been created:
- https://galaxy.ansible.com/marcinpraczko/goss-install/
I will try add more feature soon, however following role looks also very good.

During this work I also discovered another role which allows install and run goss as well:
- https://galaxy.ansible.com/naftulikay/degoss/

Hope that helps.
