### ISSUE TITLE
Looking for information on how to use molecule with vagrant

### ISSUE THREAD

**Issue by jamesla** [metacloud/molecule#1022]
I've been a long time user and fan of Molecule 1 and I am trying to make Molecule 2 use the vagrant driver rather than a container to test my role. I've looked for examples everywhere on how to do this but I can only find Molecule 1.25 examples.

I've followed the guide and created a role using:

    molecule init role -r my_role

Then I changed the driver in molecule.yml to use vagrant and the platform to use a box rather than an image.

    molecule test

It calls the create.yml playbook which basically ignores anything to do with vagrant and just uses containers (which fails).

Firstly is using vagrant with molecule 2 currently supported? Am I doing something wrong? Am I missing something in the documentation?

Secondly, I've been unable to find an example of an open source project that implements vagrant with molecule2. If you know of a project could you point me in it's direction?

**Comment by retr0h** [comment]
You need to initialize the role with the proper driver.

`molecule init role -r my_role -d vagrant`

**Comment by jamesla** [comment]
Thank you!
