### ISSUE TITLE
vagrant plugin is importing ansible as module from the same python env

### ISSUE THREAD

**Issue by gzm55** [metacloud/molecule#1023]
# Issue Type

- Bug report

# Desired Behaviour

molecule and ansible-{playbook,galaxy,etc} should be integrated via cli commands, as the ansible may run in a different python env to molecule's, such as, testing via tox, with env=python3.5-ansible-2.4, and molecule works as a external command of tox. 

# Actual Behaviour (Bug report only)

in code: [`molecule/provisioner/ansible/plugins/libraries/molecule_vagrant.py`](https://github.com/metacloud/molecule/blob/master/molecule/provisioner/ansible/plugins/libraries/molecule_vagrant.py#L390), `AnsibleModule` is imported and passed to `VagrantClient`. This may cause the testing fail or passed in an undesired way.

**Comment by retr0h** [comment]
> molecule and ansible-{playbook,galaxy,etc} should be integrated via cli commands, as the ansible may run in a different python env to molecule's, such as, testing via tox, with env=python3.5-ansible-2.4, and molecule works as a external command of tox.

I'm going to need more details on this.  I don't understand how molecule and ansible-{playbook,galaxy,etc} would be integrated via cli commands.  In this [tox](https://github.com/metacloud/molecule/blob/master/tox.ini) file, the tox environment installs the necessary dependencies required to run molecule, which include ansible-{playbook,galaxy,etc}.

**Comment by gzm55** [comment]
Hi @retr0h 

what i mean is that, ansible is installed in tox, but molecule itself is not. Python module relation is like this:
```
system-python-2.7
|
|--molecule
|--tox
\--ansible 2.4 (installed from molecule)

ansible-role-project
|
\--.tox
   |
   \--py35 (defined in tox.ini)
      |
      \--ansible 2.2 (defined in tox.ini)
```
in tox.ini:
```
[tox]
envlist = py{35}-ansible{22}
skipsdist = True

[testenv]
deps =
    ansible22: ansible>=2.2,<2.3
commands = molecule
whitelist_externals = molecule
```

As molecule is not tested and announced working in py35, so it should be treated as an external command by tox, is it right? Then in each molecule stage, we need to play man ansible books. If molecule imports AnsibleModule, it is selected from ansible 2.4 in system python27, because molecule is from there. But ansible2.2 in py35 of .tox env is what we really want.

**Comment by retr0h** [comment]
Everything should be in the tox venv including ansible and molecule.

**Comment by gzm55** [comment]
in molecule tox.ini, we have env list:
>     py{27}-ansible{22,23,24}-{functional}
>     py{27,36}-ansible{22,23,24}-{unit}

in molecule installing document, we have:
> Ansible >= 2.2
> Python 2.7

Whereas, ansible doc says, version 2.2, 2.3, 2.4 is now suppored, and the controlling machine should have python 2.6, 2.7, 3.5(preview) or 3.6(preview).

So if everything should be in the tox venv, can we add py{2.6,3.5}-ansible{22,23,24}-* to testing matrix?

**Comment by retr0h** [comment]
> So if everything should be in the tox venv, can we add py{2.6,3.5}-ansible{22,23,24}-* to testing matrix?

3.5 and 3.6 do not pass Molecule functional tests for various reasons.  I will enable py3 support once they do.

**Comment by gzm55** [comment]
Many Redhat 6.x are still in production phase with py2.6 as default system python, and the developers may need or have to test and execute their playbooks on py2.6 environments, which is supported by ansible. Can molecule be used in these cases?
IMO, if molecule works fine as a external command to ansible venv, we can drop the py2.6 any way.

**Comment by retr0h** [comment]
Unfortunately Molecule doesn't support py2.6.

**Comment by retr0h** [comment]
Closing as not much else can come out of this issue.
