### ISSUE TITLE
Integrate azure driver

### ISSUE THREAD

**Issue by claudio-viola** [metacloud/molecule#1025]
# Issue Type

- Feature request

Is it possible to integrate an Azure driver? 
What are the steps to add another driver into molecule?

**Comment by kireledan** [comment]
If you're interested in integrating an azure driver to molecule, go ahead and checkout how its done with the openstack driver. `molecule/molecule/cookiecutter/scenario/driver/openstack/{{cookiecutter.molecule_directory}}/{{cookiecutter.scenario_name}}/` is where you'll find the files created when using openstack. Azure should follow a similar procedure except you will use the corresponding azure ansible modules.

You'd then want to take a look at the files in `molecule/molecule/driver/` to get a sense of how these are implemented. They are pretty simple and usually consist of variables needed for the basic functionality of the driver.

If you just want to use the `delegated` driver, you could do all of this without having to change any of the internals of molecule. Just modify the create/destroy playbooks in your local directory and utilize the azure modules.

**Comment by retr0h** [comment]
Thanks @kireledan ! I'm not planning to add Azure anytime soon, so feel free to follow the steps @kireledan pointed out.  Thanks!
