### ISSUE TITLE
Add flag for molecule converge that performs a dependency grab.

### ISSUE THREAD

**Issue by rwaweber** [metacloud/molecule#1029]
# Issue Type
- Feature request

# Molecule and Ansible details
```
ansible 2.4.1.0
molcule 2.4.0
```

- Molecule installation method: pip
- Ansible installation method: pip

# Desired Behaviour
`molecule converge -s my_scenario --with-deps`
When testing larger playbooks with many dependent roles, I often forget to precede my `molecule converge -s my_scenario`'s with a `molecule dependency -s my_scenario`.

Also a thought, maybe have `dependency` added as an extra task under the `converge` task matrix similar to the `prepare` statement?
 
# Actual Behaviour (Bug report only)
`molecule dependency -s my_scenario`
`molecule converge -s my_scenario`

**Comment by retr0h** [comment]
Hi @rwaweber thank you for your issue.

This makes sense when developing locally.  I will add `dependency` to the converge sequence.  This will force molecule to run dependencies first.  How does this sound?

**Comment by rwaweber** [comment]
Sounds perfect! You think there might be any situations when one may want to skip the dependency phase? I imagine if it doesn't detect a requirements file in the given path it just moves along without doing anything, right?

If you'd want a hand with the PR I'd be happy to lend some thoughts!
