### ISSUE TITLE
molecule to spin up vagrant on remote machine?

### ISSUE THREAD

**Issue by rakeshtechie** [metacloud/molecule#1031]
# Question

currently am running molecule locally and it works like charm. i want to check if i can spin up a vagrant instance on remote node ? i see **create.yml** has hostname, i tried to change the hostname to remote node and connection type as **remote** but this not able to establish connection.

will the molecule able to do this ?

**Comment by retr0h** [comment]
Hi @rakeshtechie.  Molecule currently does not have the functionality to connect to a vagrant on a remote node.  The create/destroy playbooks are expected to run locally.

**Comment by rakeshtechie** [comment]
Thank you @retr0h
