### ISSUE TITLE
How to mention inventory in molecule.yml to query it as dictionary index ?

### ISSUE THREAD

**Issue by rakeshtechie** [metacloud/molecule#1037]
# Issue Type
- Question
# Molecule and Ansible details

```
ansible --version : 2.4.0.0

molecule --version : 2.3.1
```

- Molecule installation method:  pip
- Ansible installation method: OS package

my inventory file for nonprod is like below

[inventory_qa]
....
[inventory_dev]
qzushyd-[01:04].local 

one of my ansible role uses group_var as "https://{{ groups["inventory_dev"][0] }}:8001"  , so when executing with molecule this is failing with below error

 fatal: [instance]: FAILED! => {"failed": true, "msg": "The task includes an option with an undefined variable. The error was: https://{{ groups[\"inventory_dev\"][0] }}:8001: 'dict object' has no attribute 'inventory_dev'

my molecule.yml has declaration for inventory_dev as shown below, is it possible to mention the inventory in anyway so that my role can find the hostname ?

provisioner:
    name: ansible
    inventory:
       group_vars:
           inventory_dev:

**Comment by retr0h** [comment]
@rakeshtechie you are referencing two different things.  Ansible has `host` inventory and `variable inventory`.

In the case of the following, this is variable inventory.

```
provisioner:
  name: ansible
  inventory:
    group_vars:
      inventory_dev:
```

When referencing `groups`, that is referencing `groups` from the host inventory.  If you wish for Molecule to understand groups, then you must add [groups to your platforms] (http://molecule.readthedocs.io/en/latest/configuration.html#platforms) section.

**Comment by rakeshtechie** [comment]
Thank you @retr0h , i added to platforms and its working

platforms:
  - name: instance
    box: ubuntu/trusty64
    groups:
      - inventory_dev
