### ISSUE TITLE
EC2 limitation: driver depends on hardcoded ip address

### ISSUE THREAD

**Issue by azhurbilo** [metacloud/molecule#1046]
# Issue Type

- Feature request

# Molecule and Ansible details

```
ansible 2.3.0.0
molecule, version 2.3.1
```

- Molecule installation method: pip
- Ansible installation method: pip

# Desired Behaviour

We don't depend on any hardcoded instance configuration (ip address) 
https://github.com/metacloud/molecule/blob/03bc442b15b5ee0f04e40990ea58a3b25cdb837c/molecule/driver/ec2.py#L86

Framework should provide some lib abstractions to dynamically fetch new VMs ip and store it may be in .molecule dir to have possibility reuse this dynamic address in "converge" state

**Comment by retr0h** [comment]
It does.

**Comment by azhurbilo** [comment]
@retr0h could you share example?

**Comment by retr0h** [comment]
It is populated by a config read off disk, which is populated by the create playbook.  You don't need to touch it.
