### ISSUE TITLE
Allow configuration of MOLECULE_EPHEMERAL_DIRECTORY

### ISSUE THREAD

**Issue by ragingpastry** [metacloud/molecule#1048]
# Issue Type

- Feature request

# Molecule and Ansible details

```
ansible --version: ansible 2.4.0.0
molecule --version: molecule, version 2.4.0
```

- Molecule installation method: pip
- Ansible installation method: pip

# Desired Behaviour
Allow overwriting of the MOLECULE_EPHEMERAL_DIRECTORY variable via ENV vars.

Reasoning:
I utilize Gitlab-CI, Docker, and Openstack for my CI builds of ansible roles. These builds utilize Tox to test against multiple versions of Ansible. There is a significant speed advantage to utilizing DeTox, a python package which allows for concurrent Tox runs. Instead of each tox environment being run serially we can run them in parallel.

However, running tox tests concurrently will pollute the molecule ephemeral directory. Tox will attempt to run `molecule test` in the same `.molecule` directory at the same time which will break molecule runs in strange ways.

This issue is being submitted to go with a PR which will add functionality to accommodate this use-case.

**Comment by retr0h** [comment]
Merged at #1055.
