### ISSUE TITLE
molecule init --driver docker

### ISSUE THREAD

**Issue by Strijd** [metacloud/molecule#1049]
- Bug report

# Molecule and Ansible details

```
ansible 2.4.1
molecule version 2.5.0
```

- Molecule installation method: pip 
- Ansible installation method: pip 

I want to start using molecule with my ansible roles. The only options I see with `init` are: 
```
Commands:
  role      Initialize a new role for use with Molecule.
  scenario  Initialize a new scenario for use with...
  template  Initialize a new role from a Cookiecutter...
```
Found the  following command while googling this issue : 
```molecule init --driver docker```
``Error: no such option: --driver``   
I'm I missing something?

**Comment by martinwalsh** [comment]
Hi @Strijd! I am also just getting started with molecule and ran into the same problem. I found a number of blog posts and articles referencing the molecule v1 syntax; molecule v2, it seems, introduced a number of [breaking changes](https://molecule.readthedocs.io/en/latest/changelog.html#id11), including a renaming of cli parameters.

It may be helpful to follow along with the [official docs](https://molecule.readthedocs.io) too, but here's the command I used to create my first new role:

```
cd path/to/my/roles/directory && \
  molecule init role --role-name myrole --driver-name docker
```

HTH

**Comment by Strijd** [comment]
Thanks @martinwalsh 
I found a workaround for now 
```
molecule init scenario -r role-name -s role_test -d docker --verifier-name testinfra
```
Working for me

**Comment by retr0h** [comment]
> I found a workaround for now

Thats not a work-a-round, thats what you should be doing.  It's [in the docs](https://molecule.readthedocs.io/en/latest/usage.html#init).

**Comment by brahim-git-7** [comment]
user-ansible@node-manager:~/roles$ molecule init role  --role-name ansible-role-redis --driver-name docker
Usage: molecule init role [OPTIONS] ROLE_NAME
Try 'molecule init role --help' for help.

Error: no such option: --role-name
