### ISSUE TITLE
Proxy support

### ISSUE THREAD

**Issue by mtbvang** [metacloud/molecule#1054]
# Issue Type
- Feature request

# Molecule and Ansible details

```
ansible --version
ansible 2.2.1.0
molecule --version
molecule, version 2.3.1

```

- Molecule installation method: Pip
- Ansible installation method: Pip

# Desired Behaviour
I posted the same issue on the google user group https://groups.google.com/forum/#!topic/molecule-users/NQzulzRoXtk.

I'm trying to get molecule running behind a corporate proxy . The only information I could find was in this issue https://github.com/metacloud/molecule/issues/575. 

How does one add proxy settings for the vagrant and docker providers so that apt-get and yum work wih proxies. When I use vagrant directly I'm using the vagrant-proxyconf plugin and that seems to be enough to get proxies working for centos/rhel because yum just reads the environment varialbes.

  if Vagrant.has_plugin?("vagrant-proxyconf")
    config.proxy.http     = HTTP_PROXY
    config.proxy.https    = HTTPS_PROXY
    config.proxy.no_proxy = NO_PROXY
  end

# Actual Behaviour (Bug report only)

The vagrant provider error output for a molecule --debut test fails during the create playbook:

```
PLAYBOOK: create.yml ***********************************************************
    1 plays in /home/osboxes/code/test-role-vagrant/molecule/default/create.yml
    
    PLAY [Create] ******************************************************************
    
    TASK [Create molecule instance(s)] *********************************************
....

failed: [localhost] (item={'box': 'ubuntu/xenial64', 'name': 'instance'}) => {
        "failed": true,
        "invocation": {
            "module_name": "molecule_vagrant"
        },
        "item": {
            "box": "ubuntu/xenial64",
            "name": "instance"
        },
        "module_stderr": "The following SSH command responded with a non-zero exit status.\nVagrant assumes that this means the command failed!\n\napt-get install -y
....
 Could not connect to archive.ubuntu.com:80 (10.254.3.15). - connect (111: Connection refused)\nErr:2 http://archive.ubuntu.com/ubuntu xenial-updates/main amd64 binutils amd64 2.26.1-1ubuntu1~16.04.5\n  Unable to connect to archive.ubuntu.com:http:\nErr:3 http://archive.ubuntu.com/ubuntu xenial/main amd64 libisl15 amd64 0.16.1-1\n
```

Looks like apt-get can't connect connect because of the proxy. I searched throught he group, but am surprised that there's no mention of proxy issues so far.

**Comment by mtbvang** [comment]
I'm looking into the code base to see if I can figure out if there's already existing functionality that I haven't seen or how I can update the providers to support proxies.

**Comment by retr0h** [comment]
> How does one add proxy settings for the vagrant and docker providers so that apt-get and yum work wih proxies.

* Docker: #1015

**Comment by mtbvang** [comment]
I didn't have any any luck trying to add instance_raw_config_args like so:

```
platforms:
  - name: centos
...
    instance_raw_config_args: |
      if Vagrant.has_plugin?("vagrant-proxyconf")
        config.proxy.http     = ENV['HTTP_PROXY'] 
        config.proxy.https    = ENV['HTTP_PROXY'] 
        config.proxy.no_proxy = ENV['NO_PROXY'] 
      end
....
```
I ended up with a syntax error because of the line brakes, but I did get it working for vagrant with the solution from Florian on the google molecule-users group [How to set proxy settings in version 2.3.1](https://groups.google.com/forum/#!topic/molecule-users/NQzulzRoXtk)

Thanks for the help.

**Comment by retr0h** [comment]
@mtbvang would you mind creating a PR with an [example of this](https://github.com/metacloud/molecule/blob/master/doc/source/examples.rst)?

**Comment by mtbvang** [comment]
@retr0h Yes, will do.
