### ISSUE TITLE
Is there a way molecule can accept vault file as parameter to decryption 

### ISSUE THREAD

**Issue by rakeshtechie** [metacloud/molecule#1061]
# Question

# Molecule and Ansible details

```
ansible 2.4.1.0
molecule, version 2.3.1
```
I am looking for a way where i can pass vault file so that molecule can decrypt the encrypted var files.

error: 
"message": "Attempting to decrypt but no vault secrets found"

**Comment by retr0h** [comment]
You can pass command line flags to `ansible-playbook` in `molecule.yml` under `provisioner.options`.  See the docs.

**Comment by rakeshtechie** [comment]
Thank you @retr0h
