### ISSUE TITLE
Variables declared inside inventory file not visible to molecule

### ISSUE THREAD

**Issue by r0ckyte** [metacloud/molecule#1062]
# Issue Type
- Feature request

# Molecule and Ansible details

```
ansible 2.4.1.0
molecule, version 2.3.1
```

- Molecule installation method: One of source, pip
- Ansible installation method: One of source, pip, OS package

# Desired Behaviour
our ansible repository has inventory file as below with its contents
dev/inventory  - hostname-dev0[1:5]  addn_flag=false cron=true
qa/inventory    - hostname-qa0[1:3]  addn_flag=false cron=true 

my roles has conditions based on flag "addn_flag" and cron
    {% if addn_flag == "false" -%}
.....
i want to molecule to initialize the addn_flag from inventory file.

# Actual Behaviour (Bug report only)
dev/
qa/
molecule/dev ..
molecule/qa ..

molecule.yml - provisioner.inventory is linked to respective group_vars as shown below. can i also tell molecule to look for vaiables decalred inside dev/inventory ?

i tried to manually override this variables in playbook.yml and its working good But this manual work needs replicating changes of repo to molecule's playbook.yml whenever there is a change in future.

.....

> provisioner:
>    name: ansible
>    playbooks:
>       create: ../../molecule/create.yml
>       destroy: ../../molecule/destroy.yml
>    inventory:    
>       links:
>         group_vars: ../../../dev/group_vars

I'm running as molecule --scenario-name dev and its failing with undefined variable error.

currently molecule is failing with undefinedVariable message.
    fatal: [instance]: FAILED! => {
        "changed": false,
        "failed": true,
        "msg": "AnsibleUndefinedVariable: 'addn_flag' is undefined"
    }

Please let me know if am doing something wrong.

**Comment by retr0h** [comment]
You probably need to add the servers into [groups](http://molecule.readthedocs.io/en/latest/configuration.html#platforms), since you are linking to inventory with group vars.

**Comment by r0ckyte** [comment]
@retr0h   - thank you for your time.

i tried to declare as advised but i'm still unable to get the parameters declared in inventory file.
[here is the code ](https://github.com/r0ckyte/ansible-testing/blob/master/molecule/default/molecule.yml#L17)

apart from this, i also noticed that variables declared in files inside group_vars also not reflecting even after linking them in molecule.yml

for example : i have linked dev/group_vars in molecule.yml , while running a variable inside dev/group_vars/file is shown as undefined.
[here is the code](https://github.com/r0ckyte/ansible-testing/blob/master/dev/group_vars/file)
[role](https://github.com/r0ckyte/ansible-testing/blob/master/roles/common/tasks/main.yml)

Please let me know if am doing it wrong.

**Comment by retr0h** [comment]
@r0ckyte if you want to use host_vars and group_vars with molecule the host_vars and group_vars directory you are symlinking needs to be in the proper format.

I reworked your dev inventory to the following format:

```
tree dev
dev
├── group_vars
│   └── foo
│       ├── all.yml
│       └── file.yml
└── inventory
```

Made the following change to your molecule.yml

```
diff --git a/molecule/default/molecule.yml b/molecule/default/molecule.yml
index 0c74c7b..3829015 100644
--- a/molecule/default/molecule.yml
+++ b/molecule/default/molecule.yml
@@ -12,8 +12,9 @@ lint:
 platforms:
   - name: instance
     box: ubuntu/trusty64
-    groups:
-      - etcd_master
+    groups:
+      - etcd_master
+      - foo
     children:
       - addn_flag
 provisioner:
```

This allowed Molecule to read your group vars and load them properly.  Obviously, you can name this group whatever you choose.

Also, Molecule does not read host inventory in host/group_vars so variables defined in there are out of scope.  So  `addn_flag=false install=false` in `dev/inventory` will remain an unknown var.

**Comment by r0ckyte** [comment]
Thank you @retr0h 

i reworked on dev as per your suggestion, that's working to take groups_vars declared in other files.

regarding the other flags declared in inventory i will try some wrapper script 

Thanks again for the help :)
