### ISSUE TITLE
Bug in required module required (winrm vs pywinrm)

### ISSUE THREAD

**Issue by mkinney** [metacloud/molecule#1071]
# Issue Type
- Bug report

# Molecule and Ansible details

```
ansible 2.4.2.0
molecule, version 2.5.0
```

- Molecule installation method: pip
- Ansible installation method: pip

# Desired Behaviour

The required library should state "No module named pywinrm" instead of "No module named winrm".

# Actual Behaviour (Bug report only)

When preparing a windows vm, you need to have pywinrm installed. 

If you configure molecule to use this configuration:

driver:
  name: vagrant
  provider:
    name: vmware_desktop

Then, molecule should report that you need the pywinrm module installed. (not 'winrm' as it is shown)

    PLAYBOOK: prepare.yml **********************************************************
    1 plays in /Users/s003477/code/ansible-windows/molecule/default/prepare.yml

    PLAY [Prepare] *****************************************************************
    META: ran handlers

    TASK [Install python for Ansible] **********************************************
    task path: /Users/s003477/code/ansible-windows/molecule/default/prepare.yml:6
    fatal: [win1]: FAILED! => {
        "msg": "winrm or requests is not installed: No module named winrm"
    }

    PLAY RECAP *********************************************************************
    win1                       : ok=0    changed=0    unreachable=0    failed=1

$ pip install winrm
Collecting winrm
  Could not find a version that satisfies the requirement winrm (from versions: )
No matching distribution found for winrm

However, there is pywinrm:

$ pip install pywinrm
Collecting pywinrm
  Using cached pywinrm-0.2.2-py2.py3-none-any.whl
Collecting requests-ntlm>=0.3.0 (from pywinrm)
<snip>

**Comment by retr0h** [comment]
Windows VMs are not really supported with Molecule unfortunately.  There are just too many weird edge cases to try and make this work, and I don't have the resources or will to make Molecule work against windows vms.

**Comment by mkinney** [comment]
I understand. We would like to use molecule for both windows and linux. If we do PR's on them, would you be open to accepting them?

Molecule is awesome and is extremely valuable to us. Good job on its creation and maintenance. You keep adding things that we didn't know we needed until you added them. (ex: yamllint as part of the validation)

On this one issue, I was not sure where I might find the area to look. (grep was not finding anything)

**Comment by retr0h** [comment]
> I understand. We would like to use molecule for both windows and linux. If we do PR's on them, would you be open to accepting them?

Of course 👍

**Comment by retr0h** [comment]
@mkinney not sure what you want me to do with this particular issue.  I don't see much Molecule can do to change this error message, since it's being thrown from Ansible.  Am I being crazy?

**Comment by retr0h** [comment]
Closing, nothing we can do about Ansible messaging.
