### ISSUE TITLE
Ansible 2.2 does not allow "log_driver: none"

### ISSUE THREAD

**Issue by robertdebock** [metacloud/molecule#1087]
# Issue Type
- Bug report

# Molecule and Ansible details
```
ansible --version
ansible 2.2.3.0
  config file = 
  configured module search path = Default w/o overrides

molecule --version
molecule, version 2.6.0
```

- Molecule installation method: pip
- Ansible installation method: pip

# Desired Behaviour
Molecule would be able to test using Ansible 2.2, as that is what's described in README.md.

# Actual Behaviour (Bug report only)
Molecule now fails when using Ansible 2.2 with this error:
```
"msg": "value of log_driver must be one of: json-file,syslog,journald,gelf,fluentd,awslogs,splunk, got: none"
```

This error can be seen on [Travis](https://travis-ci.org/robertdebock/ansible-role-bootstrap/jobs/327612173), with this code from [GitHub](https://github.com/robertdebock/ansible-role-bootstrap/tree/bdeee41e62dbe20b0477361dd611a47cf75d03c8)

I think either:
- Ansible 2.3 or higher should be supported. (in that case change README.md)
- or the log_driver should be changed to something that is supported. (in that case change create.yml in molecule/cookiecutter/scenario/driver/docker/%7B%7Bcookiecutter.molecule_directory%7D%7D/%7B%7Bcookiecutter.scenario_name%7D%7D/)

**Comment by retr0h** [comment]
Merged.  Thnks @robertdebock !
