### ISSUE TITLE
`molecule test` interrupted if one of step failed.

### ISSUE THREAD

**Issue by bborysenko** [metacloud/molecule#109]
Just realized that actually it's not possible to use just `molecule test` on CI environment. Since we use `sys.exit` [here](https://github.com/metacloud/molecule/blob/master/molecule/ansible_playbook.py#L156) and [here](https://github.com/metacloud/molecule/blob/master/molecule/commands.py#L279), if `converge` or `verify` step is failed we stuck with a VM that need to be destroed manually. 

As workaround I run molecule on CI server like this: 

```
molecule test || molecule destroy
```

But it will be great if molecule will take care about that point itself.

**Comment by dhutty** [comment]
About using molecule in CI:
* I wanted to emphasize which step of molecule failed
* I wanted to ensure that VMs were destroyed no matter what happened in my Jenkins job

So I ended up with jobs that looked like:
```
            #!/bin/sh
            trap "molecule destroy" INT TERM EXIT
            die() {{
                msg=$1
                echo "$msg" >&2
                molecule destroy
                exit 1
            }}
            molecule create --provider=openstack || die "Failed to create"
            molecule converge || die "Failed to converge"
            molecule verify || die "Failed to verify"
            molecule idempotence || die "Failed idempotence"
            molecule destroy
            trap - INT TERM EXIT
```

This might be useful to you until we get around to having molecule take care of it internally.

**Comment by bborysenko** [comment]
@dhutty thanks a lot for sharing!

**Comment by retr0h** [comment]
@dhutty we have a Jira tracking this feature?  Seems like a good molecule update.

**Comment by abrown-sg** [comment]
CIA-399. Thinking I'll add an --always-destroy flag to `molecule test`

**Comment by conorsch** [comment]
Consider mimicking the test-kitchen pragma:

```
molecule test --destroy passing # default
molecule test --destroy always # CI
molecule test --destroy never # development
```

**Comment by abrown-sg** [comment]
@conorsch Yeah, good idea, that'll work out fine.

**Comment by retr0h** [comment]
@conorsch \m/
