### ISSUE TITLE
Roles not found by molecule when previously installed

### ISSUE THREAD

**Issue by Puhapig** [metacloud/molecule#1093]
# Issue Type

- Bug report

# Molecule and Ansible details

```
ansible 2.4.2.0
molecule, version 2.6.0
```

- Molecule installation method: pip
- Ansible installation method: pip

# Desired Behaviour

If a role has been installed before using `ansible-galaxy install ...` or similar, it is installed to `~/.ansible/roles/` (default on OSX). When I run `molecule test` with my role specified in requirements.yml or similar, I would expect it to be installed to `molecule/<scenario>/.molecule/roles/` so it can be used.

# Actual Behaviour (Bug report only)

Installing a role with `ansible-galaxy install` seems to ignore the `--roles-path` flag when a role is already installed - even when using --force. This means that the role is only installed to `~/.ansible/roles/<role_name>`.

Molecule, by default, does not include this path in `ANSIBLE_ROLES_PATH` and so any commands which use said role will fail.

## Recreating

Install the role to ~/.ansible/roles
```
ansible-galaxy install jdauphant.nginx -vvv
```

Creating a role which depends on said role
```
$ molecule init role -r my_role
$ cd my_role
$ vim tasks/main.yml

### tasks/main.yml ###
---
- name: include a role
  include_role:
    name: jdauphant.nginx

$ vim requirements.yml
### requirements.yml ###
---
- src: jdauphant.nginx

$ vim molecule/default/molecule.yml
### molecule/default/molecule.yml ###
...
dependency:
  name: galaxy
  options:
    role-file: requirements.yml
...

$ molecule test
```

Note: if the dependent role is not installed, `molecule test` will pass and the role `jdauphant.nginx` will be installed in `molecule/default/.molecule/roles/jdauphant.nginx/`. If it is already installed using `ansible-galaxy install jdauphant.nginx`, molecule won't be able to find it.

I have been able to work around this by adding the following to `molecule.yml`:
```
provisioner:
  name: ansible
  env:
    ANSIBLE_ROLES_PATH: $HOME/.ansible/roles
```

I'm curious if either of the following is possible:
* Molecule will include Ansible's `ANSIBLE_ROLES_PATH` instead of just overriding it
* Ansible-galaxy will support installing multiple copies of a role

**Comment by retr0h** [comment]
Yes, you must set `ANSIBLE_ROLES_PATH` to find your roles if you are installing them into a location other than `$scenario/.molecule/roles/`, which is the default location Molecule will look.

**Comment by retr0h** [comment]
@Puhapig wow this really seems like a flaw with `ansible-galaxy`.  You cannot force galaxy to install the role into another path, once the role is already installed into a known location.

```
[jodewey:~/git/molecule_2/my_role] [molecule2-env-2.7.13] master+* ± ansible-galaxy install jdauphant.nginx
- downloading role 'nginx', owned by jdauphant
- downloading role from https://github.com/jdauphant/ansible-role-nginx/archive/v2.13.tar.gz
- extracting jdauphant.nginx to /Users/jodewey/.ansible/roles/jdauphant.nginx
- jdauphant.nginx (v2.13) was installed successfully
```

```
[jodewey:~/git/molecule_2/my_role] [molecule2-env-2.7.13] master+* ± ansible-galaxy install jdauphant.nginx -p /tmp/foo --force
- changing role jdauphant.nginx from v2.13 to unspecified
- downloading role 'nginx', owned by jdauphant
- downloading role from https://github.com/jdauphant/ansible-role-nginx/archive/v2.13.tar.gz
- extracting jdauphant.nginx to /Users/jodewey/.ansible/roles/jdauphant.nginx
- jdauphant.nginx (v2.13) was installed successfully
```

**Comment by retr0h** [comment]
Galaxy is just redonk.  We stopped messing with thing all together and wrote [gilt](http://gilt.readthedocs.io/en/latest/).  Molecule has native gilt support.
