### ISSUE TITLE
Feature idea: Add a new molecule command to perform a syntax check

### ISSUE THREAD

**Issue by bborysenko** [metacloud/molecule#110]
**IDEA:**  Add a new molecule command to run `ansible-playbook` locally with `--syntax-check` option. Something like:

```
ANSIBLE_CONFIG=.molecule/ansible.cfg ansible-playbook playbook.yml --inventory-file='localhost,' --connection=local --syntax-check
```

Change sequence of commands to run when performing `molecule test` to 

```
  test:
    # sequence of commands to run when performing `molecule test`
    sequence:
      - destroy
      - syntax-check
      - create
```

The main goal is to fail as soon as possible.

**NOTE:** #105 then should go from `converge` step to `syntax-check`

**Comment by retr0h** [comment]
@bborysenko Sounds reasonable to me.

**Comment by retr0h** [comment]
This work was completed.
