### ISSUE TITLE
EC2 driver configuration

### ISSUE THREAD

**Issue by hmarlo** [metacloud/molecule#1101]
# Issue Type

- Bug report

# Molecule and Ansible details

```
ansible --version
ansible 2.4.2.0
  config file = None
  configured module search path = ['/home/hector/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/hector/.local/lib/python3.5/site-packages/ansible
  executable location = /home/hector/.local/bin/ansible
  python version = 3.5.2 (default, Nov 23 2017, 16:37:01) [GCC 5.4.0 20160609]
```
```
molecule --version
molecule, version 2.7.0
```

- Molecule installation method: pip
- Ansible installation method: pip

# Desired Behaviour

Fail to find EC2 credentials (they are not set in the ENVIRONMENT).

# Actual Behaviour (Bug report only)

Fail searching for the instance_config.yml file inside the .molecule folder.

# Steps to reproduce
```
molecule init role -r test-ec2 -d ec2
cd test-ec2
molecule test
```

Output https://pastebin.com/be4AMutS

Edit: this relates somehow with #1094 I suppose, but it is not failing in the region or ec2_url.

**Comment by retr0h** [comment]
> Fail searching for the instance_config.yml file inside the .molecule folder.

The credentials need set in the environment.  Thats how the driver is intended to be used.

**Comment by hmarlo** [comment]
OK! Now it works :D

I set the variables AWS_ACCESS_KEY_ID, AWS_SECRET_ACCESS_KEY and AWS_DEFAULT_REGION, modified the "image" (didn't exist) and the "vpc_subnet_id" in "molecule/default/molecule.yml".

As side note, molecule created a key_pair and a security group, both named "molecule".

Sorry for bothering and thank you!

**Comment by retr0h** [comment]
> As side note, molecule created a key_pair and a security group, both named "molecule".

Yeah, the EC2 create files are mostly setup for my ability to test, and people can customize them as they choose.  I am hoping they will evolve and become better as more people use them and submit PRs.

> Sorry for bothering and thank you!

No problem at all.
