### ISSUE TITLE
Support for systemd-nspawn driver

### ISSUE THREAD

**Issue by baccenfutter** [metacloud/molecule#1106]
# Issue Type
- Feature request

# User-story
`Systemd` comes with builtin container support. See:
- https://www.freedesktop.org/software/systemd/man/systemd-nspawn.html

As a user of Molecule, I would like to select `systemd` as the driver for a scenario.

**Comment by retr0h** [comment]
Hi @baccenfutter this is not a feature we will be implementing anytime soon.

**Comment by baccenfutter** [comment]
That's really too bad:
- Docker driver requires extra effort to spin up a container with an init process inside, necessary for testing service-stacks. Testing things like `role-resolvconf` or `role-hosts` can't really be tested production-near unless production is run with Docker.

- LXC/D drivers require extra service stacks to be fully configured before using `Molecule`.

- Vagrant driver requires extra service stacks to be fully configured before using `Molecule`. Spinning up VMs is tremendously slow for continuous integration testing.

- Systemd-nspawn would be the only driver that would simply just work on any systemd-driven OS. Its containers automatically spin up with an init-process. Lightweight containers that look and feel like a VM from the inside. Paradise for testing.

----

Are there technical reasons for not supporting nspawn? Would you accept a pull-request with systemd-nspawn driver support?

**Comment by kireledan** [comment]
Pull requests are definitely welcome,

**Comment by retr0h** [comment]
> Are there technical reasons for not supporting nspawn?

The reason would be us (the developers of Molecule) not needing such a feature at this time.  Developing and testing drivers is a lot of work.  Especially, ensuring the drivers work with each release.  

I actually think Molecule supports too many Drivers. most of which people do not use.  Unless we find ourselves needing this driver, I am not very motivated to implement it.
