### ISSUE TITLE
ReadTheDocs Video

### ISSUE THREAD

**Issue by Seluj78** [metacloud/molecule#1107]
A quick tip, you should use asciinema.org instead of recording a terminal window and converting it to a gif 😉 

Cheers 👋

**Comment by retr0h** [comment]
I'm aware of asciinema.  A good tip when telling people what to do, is to explain why they should consider the alternative.

**Comment by Seluj78** [comment]
Well quite obvious, easy to embed, way quicker than converting the video, and many more
