### ISSUE TITLE
Unable to ssh to few vagrant instances created by molecule

### ISSUE THREAD

**Issue by r0ckyte** [metacloud/molecule#1108]
# Issue Type

- Question

```
ansible 2.4.1.0
molecule, version 2.3.1
```
I'm using molecule with 2 vagrant instances to test mutually exclusive roles. They are working good without any issue, However i noticed that i can only ssh to one vagrant instance even though my vagrant global-status lists 2 instance ids as below

12598f6  instance-1 virtualbox running /home/xxx/ansible-testing/molecule/default/.molecule 
fbfd564  instance-2 virtualbox running /home/xxx/ansible-testing/molecule/default/.molecule 

when i try to ssh to instance-1 - i see a message as not configured but i can run roles on instance-1 using molecule converge via playbook.yml.  I can ssh to instance-2

XXX@host1:~/ansible-testing$ vagrant ssh 12598f6
The machine with the name 'instance-1' was not found configured for
this Vagrant environment.

i read the documentation at https://molecule.readthedocs.io/en/latest/configuration.html#molecule-vagrant-module but my create.yml and destroy.yml are different may be the documentation is out dated or am doing something wrong.

[my configuration](https://github.com/r0ckyte/ansible-testing) is available here

**Comment by retr0h** [comment]
Use `molecule login`.

**Comment by r0ckyte** [comment]
Thank you !!
