### ISSUE TITLE
add an --host parameter to filter molecule run

### ISSUE THREAD

**Issue by lalmeras** [metacloud/molecule#1122]
# Issue Type

- Feature request

# Desired Behaviour

Allow to use a ``--host`` parameter to filter molecule run to the desired platform. Useful to work quickly on an platform-related issue.

# Actual Behaviour

Maybe I miss something, but if I want to run molecule on a specific platform, I need to comment the other platforms in my scenario's molecule.yml.

# Proposed behavior

I work on a proposition that adds ``--host`` parameter on all relevant commands and use it to filter molecule operations.
It is available here: https://github.com/metacloud/molecule/compare/master...lalmeras:ft-host?expand=1

It is currently working as expected with a docker provisionner.

If you agree with the feature and the way to implement it, I can work with your help on the missing parts (docstring, documentation, templates for other provisionners and tests)

**Comment by retr0h** [comment]
@lalmeras I've turned this feature down in the past, however, I'll think about it.  Molecule really wasn't designed to work this particular way, especially around how it handles state (`molecule list`).  Molecule assumes a subcommand was successful if Ansible didn't exit, and updates state for all platforms.

**Comment by retr0h** [comment]
@lalmeras You can also leverage Molecule's ability to pass [arbitrary Ansible arguments](http://molecule.readthedocs.io/en/latest/usage.html#converge) to Molecule's converge sub command `molecule converge -- --limit instance-1`.

It still boots all the platforms (which isn't ideal), but it will only converge the one you specify.  Should be working shortly.  Fixing a bug found #1123.

**Comment by lalmeras** [comment]
@retr0h thanks for your feedback.

I understand the issue you highlight with state management. If I also work on the state issue (not sure I can handle it, but I can try to), are you interested, or do you think it'll be too intrusive and complex and you'll reject any proposition on this feature ?

If you don't want to handle it in molecule, which I can understand, I think I'll work on a wrapper for molecule that can generate custom scenario folder with filtered platforms.

**Comment by retr0h** [comment]
This isn't something molecule will be tackling at this time.  Thank you for the issue.
