### ISSUE TITLE
adding localhost to vagrant driven ansible inventory

### ISSUE THREAD

**Issue by nathanhruby** [metacloud/molecule#1124]
# Issue Type

- Feature request

# Molecule and Ansible details

```
[nhruby@lappy ~]$ ansible --version
ansible 2.4.3.0
  config file = None
  configured module search path = [u'/Users/nhruby/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /Users/nhruby/.pex/install/ansible-2.4.3.0-py2-none-any.whl.f0343d091132c5d864b863540f56241a54b6ab20/ansible-2.4.3.0-py2-none-any.whl/ansible
  executable location = ansible
  python version = 2.7.14 (default, Feb  6 2018, 20:03:13) [GCC 4.2.1 Compatible Apple LLVM 9.0.0 (clang-900.0.39.2)]
molecule --version[nhruby@lappy ~]$ molecule --version
molecule.pex, version 2.7.0
[nhruby@lappy ~]$
```

- Molecule installation method: pip + pex
- Ansible installation method:pip + pex

# Desired Behaviour

_This is totally an edge case._  

Currently I build ansible+molecule with pex into a single file with all dependencies in order to reduce the pain of getting everything installed similarly across multiple developer laptops.  This works well but as a result I need to set `ansible_python_interpreter` to point at a shim script to use the pex bundle.  We set this in the vars on various playbooks now, but would like to set this as a host var in inventory for localhost to make it simpler for folks to set up.

We also use the vagrant driver to avoid nested docker-in-docker situations and as a result that setting doesn't propagate because localhost isn't a stated platform in molecule.yml and the inventory isn't there during create and destroy actions.

Is it possible to add localhost to the inventory, and for vagrant driven configs, add that to the inventory early?  If not, would you be willing to accept a patch to enable that behavior?

**Comment by retr0h** [comment]
Hi @nathanhruby can you give more details?  What consumes the localhost inventory?  Can you show an example?

**Comment by nathanhruby** [comment]
The ansible-playbook command that molecule runs consumes the inventory. 

For us when ansible runs a module on localhost, it needs to use the pex bundle as python because that's where the requisite libraries are, similar to using the bin/python in a virtualenv.

**Comment by retr0h** [comment]
Pretty sure you can set [connection and hosts](https://github.com/metacloud/molecule/blob/master/molecule/cookiecutter/scenario/driver/vagrant/%7B%7Bcookiecutter.molecule_directory%7D%7D/%7B%7Bcookiecutter.scenario_name%7D%7D/create.yml#L4-L5) which make localhost unnecessary in inventory.

**Comment by nathanhruby** [comment]
Yeah, so we set `ansible_python_interpreter` in `vars:` in create, destroy, etc.. and that works.  

Setting in the inventory would be ideal so we can just set it in one place and not have to remember to touch the generated files.

**Comment by retr0h** [comment]
Could you do this?

```
provisioner:
  name: ansible
  inventory:
    host_vars:
      localhost: 
        ansible_python_interpreter: /path/to/python
```

**Comment by nathanhruby** [comment]
I tried that
- inventory isn't there for vagrant driver during create at all
- localhost doesn't land in the inventory once created for some reason (I assume because it's not in platforms, but haven't found the bit of code that creates the inventory from the state)

**Comment by retr0h** [comment]
It's added to host vars not the inventory file.  It's written before Molecule even executes ansible.

```
[jodewey:~/git/molecule_2/test/scenarios/driver/docker] [molecule2-env-2.7.13] master(+6/-0)+* ± cat molecule/default/.molecule/host_vars/localhost
# Molecule managed

---
ansible_python_interpreter: /foo/bar/baz
```

Should work.

```
[jodewey:~/git/molecule_2/test/scenarios/driver/docker] [molecule2-env-2.7.13] master(+6/-0)+* ± rm -rf molecule/default/.molecule/host_vars/localhost
[jodewey:~/git/molecule_2/test/scenarios/driver/docker] [molecule2-env-2.7.13] master(+6/-0)+* ± molecule create
--> Test matrix

└── default
    ├── create
    └── prepare

here
--> Scenario: 'default'
--> Action: 'create'

    PLAY [Create] ******************************************************************

    TASK [Create Dockerfiles from image names] *************************************
    fatal: [localhost]: FAILED! => {"msg": "Failed to get information on remote file (/Users/jodewey/git/molecule_2/test/scenarios/driver/docker/molecule/default/.molecule/Dockerfile_centos_latest): /bin/sh: /foo/bar/baz: No such file or directory\n"}

    PLAY RECAP *********************************************************************
    localhost                  : ok=0    changed=0    unreachable=0    failed=1


ERROR:
```

**Comment by retr0h** [comment]
@nathanhruby ping

**Comment by nathanhruby** [comment]
Sorry, missed this update.  Let me re-test with vagrant driver because my understanding and testing is that does not work with the vagrant driver, but perhaps I am mistaken.

**Comment by nathanhruby** [comment]
With a fresh test role made from current molecule I am unable to reproduce the create problems I was seeing.  I'll chalk this up to my templates being older and possible divergent from current?  Anyway, since it works with current, this is my problem to solve.

But, destroy still fails.  It appears that host_vars/localhost is removed before destroy.yml is run so the vars are not there.

**Comment by retr0h** [comment]
@nathanhruby Can you try running Molecule built off master and see if #1140 fixes this issue?
