### ISSUE TITLE
Vagrant instances failing with module_failure after accidental delete of "Virtual VM's" 

### ISSUE THREAD

**Issue by r0ckyte** [metacloud/molecule#1127]
# Issue Type

- Bug report

# Molecule and Ansible details

```
ansible 2.4.1.0
molecule, version 2.3.1
```
- Molecule installation method: One of source, pip
- Ansible installation method: One of source, pip, OS package

# Desired Behaviour
create vagrant instances on running jenkins job

# Actual Behaviour (Bug report only)
I have jenkins job which runs molecule in 4 scenarios parallel, Yesterday i noticed that my disk was filling with lot of images in /home/user/"Virtual VM's" and jenkins workspace -  cleared them all , hoping that molecule create/converge will automatically create them on demand.

i noticed my jenkins job failing with below module_error on running "molecule create" command ( running as jenkins user)

i tried to reproduce the error running with my user account and noticed that i get same error if i run "molecule create" 

i created "/home/user/**VirtualBox VMs**" - ran "molecule create" ( non sudo ) - observed that ubuntu vmdk files are downloaded into it.  all my scenarios are running good with my user account.

i'm not able to understand why jenkins user is still failing with below error - while i can run with my account. please note - this was working till yesterday until i accidentally deleted all images inside jenkins workspace "Virtual VM's"

    failed: [localhost] (item={'box': u'ubuntu/trusty64', 'name': u'instance-2', 'groups': [u'molecule_var']}) => {
        "changed": false,
        "failed": true,
        "item": {
            "box": "ubuntu/trusty64",
            "groups": [
                "molecule_var"
            ],
            "name": "instance-2"
        },
        "module_stderr": "The box 'ubuntu/trusty64' could not be found or\ncould not be accessed in the remote catalog. If this is a private\nbox on HashiCorp's Atlas, please verify you're logged in via\n`vagrant login`. Also, please double-check the name. The expanded\nURL and error message are shown below:\n\nURL: [\"https://atlas.hashicorp.com/ubuntu/trusty64\"]\nError: The requested URL returned error: 404 Not Found\nTraceback (most recent call last):\n  File \"/tmp/ansible_SmHBUx/ansible_module_molecule_vagrant.py\", line 417, in <module>\n    main()\n  File \"/tmp/ansible_SmHBUx/ansible_module_molecule_vagrant.py\", line 410, in main\n    v.up()\n  File \"/tmp/ansible_SmHBUx/ansible_module_molecule_vagrant.py\", line 297, in up\n    for line in self._vagrant.up(no_provision, stream_output=True):\n  File \"/var/lib/jenkins/.local/lib/python2.7/site-packages/vagrant/__init__.py\", line 1005, in _stream_vagrant_command\n    raise subprocess.CalledProcessError(p.returncode, command)\nsubprocess.CalledProcessError: Command '['/usr/bin/vagrant', 'up', '--no-provision']' returned non-zero exit status 1\n",
        "module_stdout": "<vagrant_output> Bringing machine 'instance-2' up with 'virtualbox' provider...\n\n<vagrant_output> ==> instance-2: Box 'ubuntu/trusty64' could not be found. Attempting to find and install...\n\n<vagrant_output>     instance-2: Box Provider: virtualbox\n\n<vagrant_output>     instance-2: Box Version: >= 0\n\n",
        "msg": "MODULE FAILURE",
        "rc": 0
    }

Please give some details of what is actually happening.
Include a [minimum complete verifiable example](http://stackoverflow.com/help/mcve) with
output of running `molecule --debug`.

**Comment by retr0h** [comment]
If the VMs were killed and not destroyed through `molecule destroy` you may have a bad state file.
Simply `rm -rf molecule/$scenario_name/.molecule` and try again.

**Comment by r0ckyte** [comment]
thanks @retr0h  for the response

i tried deleting .molecule - that didnt worked.

since all scenarios are running good with my user account XXX - i just tried copying this 2 directories  **/home/XXX/Virtual VM's** and **/home/XXX/.vagrant.d/** to **/var/lib/jenkins** ( jenkins home directory ).  

Now my jenkins job also working good. not sure why it was not able to download earlier using jenkins username.

**Comment by retr0h** [comment]
Weird :(

**Comment by r0ckyte** [comment]
thank you - closing this
