### ISSUE TITLE
Molecule destroy sometime fails when running multiple scenarios

### ISSUE THREAD

**Issue by r0ckyte** [metacloud/molecule#1129]
# Issue Type

- Bug report

# Molecule and Ansible details

```
ansible 2.4.1.0
molecule, version 2.3.1
```

- Molecule installation method: One of source, pip
- Ansible installation method: One of source, pip, OS package

# Actual Behaviour (Bug report only)
currently i have 4 scenarios, each scenario using 2 vagrant instances for testing ansible roles.
i tried setting up execution using parallel feature in jenkins where all 4 scenarios execute simultaneously. 

though all roles run good successfully , while clean up the instances using 'molecule destroy --all'
sometimes i noticed few scenarios hang at 'molecule destroy' and finally without any error message they say FAILED. is there any timeout in destroying instances that's terminating the process ?

```
[Pipeline] // parallel
[Pipeline] stage
[Pipeline] { (Post Cleanup)
[Pipeline] sh
[ansible] Running shell script
+ molecule destroy --scenario-name XYZ
--> Test matrix
    
└── XYZ
    └── destroy
    
--> Inventory /var/lib/jenkins/workspace/Tests/Molecule_repo_pipelinescript/ansible/molecule/XYZ/.molecule/../../../XYZ/group_vars linked to /var/lib/jenkins/workspace/Tests/Molecule_repo_pipelinescript/ansible/molecule/XYZ/.molecule/group_vars
--> Scenario: 'XYZ'
--> Action: 'destroy'
    
    PLAY [Destroy] *****************************************************************
    
    TASK [Destroy molecule instance(s)] ********************************************
[Pipeline] }
[Pipeline] // stage
[Pipeline] }
[Pipeline] // dir
[Pipeline] }
[Pipeline] // node
[Pipeline] End of Pipeline
ERROR: script returned exit code -1
Finished: FAILURE

```
Please give some details of what is actually happening.
Include a [minimum complete verifiable example](http://stackoverflow.com/help/mcve) with
output of running `molecule --debug`.

**Comment by r0ckyte** [comment]
i removed parallel execution and running them after the other scenario - all working good.

i do not have a error message to report as jenkins job fails without giving any logs. I'm suspecting if there is any timeouts from vagrant or molecule which is returning error.

**Comment by retr0h** [comment]
Vagrant doesn't work well under parallel execution.  I suggest using another driver, or not using parallel execution when using Vagrant.

**Comment by r0ckyte** [comment]
removed parallel execution and my job is stable - thank you @retr0h
