### ISSUE TITLE
Molecule setup for existing Playbook with multiple roles.

### ISSUE THREAD

**Issue by damianoneill** [metacloud/molecule#1133]
# Issue Type

- Feature request

# Molecule and Ansible details

```
ansible --version
ansible 2.4.3.0

molecule --version
molecule, version 2.8.2
```

- Molecule installation method: One of source, pip
pip

- Ansible installation method: One of source, pip, OS package
pip

# Desired Behaviour

Request for information - Initial setup. 

Given a directory structure similar to below.  For a playbook with existing roles.  How should molecule be initialised.  I've looked through the docs / online tutorials and a few videos but dont see any guidance on the approach that should be used.   

Apologies if this is covered somewhere else.  

```sh
$ tree .
.
├── group_vars
│   └── all
├── playbook.yml
└── roles
    ├── cassandra
    │   ├── files
    │   ├── handlers
    │   │   └── main.yml
    │   ├── meta
    │   ├── tasks
    │   │   └── main.yml
    │   ├── templates
    │   └── vars
    ├── common
    │   ├── files
    │   ├── handlers
    │   │   └── main.yml
    │   ├── meta
    │   ├── tasks
    │   │   └── main.yml
    │   ├── templates
    │   └── vars
    └── web
        ├── files
        ├── handlers
        │   └── main.yml
        ├── meta
        ├── tasks
        │   └── main.yml
        ├── templates
        └── vars
```

**Comment by damianoneill** [comment]
To provide some context, in this playbook I'd like to test against a vagrant based, 3 vm cluster with scenarios for both CentOS and Ubuntu.   With the common and cassandra roles applied on all nodes and the web role applied on a single node.

**Comment by r0ckyte** [comment]
@damianoneill  - may try something like this
[molecule.yml](https://github.com/r0ckyte/ansible-testing/blob/master/molecule/prod/molecule.yml)
 [playbook](https://github.com/r0ckyte/ansible-testing/blob/master/molecule/prod/playbook.yml)

**Comment by retr0h** [comment]
http://molecule.readthedocs.io/en/latest/examples.html#monolith-repo

**Comment by damianoneill** [comment]
@r0ckyte thanks I'll look through this later today.   

@retr0h I read this when I went through the docs.  This statement 'The role initialized with Molecule (baz in this case) would simply reference the dependant roles via it’s playbook.yml or meta dependencies.' implies that an existing role can be initialized.  I tried a number of combinations of the tooling but it seemed that you had to create a new role, you couldn't init an existing role.  Maybe I was doing something stupid.

**Comment by damianoneill** [comment]
Similar question found when googling "molecule monolith-repo' - https://github.com/metacloud/molecule/issues/1010 

Useful text in previous question - https://github.com/metacloud/molecule/issues/1010#issuecomment-339035427

**Comment by retr0h** [comment]
> mkdir -p monolith-repo/{roles/{bar,baz,foo},library,plugins/filters}
> cd monolith-repo/roles

Your mkdir is messing you up.  If you want to create role foo, don't mkdir the directory first ;)

**Comment by damianoneill** [comment]
@retr0h understood, point I'm making is you cant run the init command on an existing role, I was just using your example to demonstrate.  I've seen a few examples online for molecule v1 where this functionality seems to exist.  Is this no longer supported in v2?

Thanks,
Damian.

**Comment by retr0h** [comment]
Sure you can, you jsut need to run the proper command ;)

Check the docs [Initialize an existing role with Molecule](http://molecule.readthedocs.io/en/latest/usage.html#init).

**Comment by damianoneill** [comment]
@retr0h appreciate your patience.  

Again I had tried that previously and got an error.  

```sh
$ ls
bar baz foo
$ molecule init scenario --scenario-name default --role-name baz
ERROR: The role 'baz' not found. Please choose the proper role name. 
```

Is the init scenario looking for anything other than a directory name? 

Thanks,
Damian.

**Comment by retr0h** [comment]
You need to be in the proper directory.

**Comment by retr0h** [comment]
https://github.com/metacloud/molecule#testing-an-existing-role

**Comment by damianoneill** [comment]
Thankyou @retr0h, honestly that was the only combo I didnt try.

**Comment by retr0h** [comment]
> Thankyou @retr0h, honestly that was the only combo I didnt try.

My apologies it was confusing.  I have updated the README with the screen cast, and updated the docs to ensure the developer knows to cd into the role first.

**Comment by damianoneill** [comment]
Not at all, the support from yourself and @r0ckyte has been great, thanks.
