### ISSUE TITLE
molecule (v2) with ansible arguments 

### ISSUE THREAD

**Issue by wissemmahjoub** [metacloud/molecule#1136]
Hello,
I would like to know if there is a command wich enables me to launch molecule command with ansible arguments.
i saw the official documentation but i didn't found that.
Thank you for your help.

**Comment by retr0h** [comment]
Not sure what you're referring to.

**Comment by wissemmahjoub** [comment]
I want to run molecule tests on ansible roles,
knowing that my roles are done with parameters,
so, I want to specify these parameters when launching the command "molecule test".
