### ISSUE TITLE
VirtualBox: enable promiscuous mode on guests

### ISSUE THREAD

**Issue by 0xDEC0DE** [metacloud/molecule#114]
When standing up OpenStack with molecule + vagrant, it is not possible to pass traffic to VMs, since doing so relies on the network interfaces being set to promiscuous mode, and VirtualBox blocks promiscuous mode on VMs by default.

This can be worked around in the `molecule.yml` with the following:

    raw_config_args:
      - "vm.provider :virtualbox do |vb| vb.customize ['modifyvm', :id, '--nicpromisc1', 'allow-all', '--nicpromisc2', 'allow-all', '--nicpromisc3', 'allow-all'] end"

...but the VirtualBox provider should set that on all guests by default.

**Comment by conorsch** [comment]
Seems like #9 foresaw problems like this. Wouldn't it be better to support OpenStack as a separate backend provider?

**Comment by retr0h** [comment]
I'm going to close this out for now.

Mostly b/c we are no longer testing openstack with vagrant so this feature isn't something we need any longer.
