### ISSUE TITLE
Change >>> to $ in the documentation 

### ISSUE THREAD

**Issue by bngsudheer** [metacloud/molecule#1143]
# Issue Type

- Documentation improvement

# Desired Behaviour
For shell commands use the prefix $ 

# Actual Behaviour (Bug report only)
For shell commands >>> prefix is used.
```
>>> 
```
indicates Python interpreter and $ indicates shell.

I would be happy to send a PR if you like this idea.

**Comment by retr0h** [comment]
Sure, thanks!

**Comment by retr0h** [comment]
Implemented in #1146.
