### ISSUE TITLE
provisioner vagrant default username should be vagrant instead of ubuntu

### ISSUE THREAD

**Issue by Raffaello** [metacloud/molecule#1154]
# Issue Type

- Bug report
# Molecule and Ansible details

molecule 2.8.3
ansible 2.4.3

- Molecule installation method: pip
- Ansible installation method: pip

# Actual Behaviour (Bug report only)

the `instance_config.yml` is generated with `user: ubuntu` as default, in the case of vagrant provider it will simplify to use default `user: vagrant`. Also in the documentation i was not able to find a way to override the default `user: ubuntu`.

**Comment by retr0h** [comment]
Vagrant is providing that information to Molecule.

```
[jodewey:/tmp/test/chrony] [.venv] 1 % molecule create
```

```
cd molecule/default/.molecule
[jodewey:/tmp/test/chrony/molecule/default/.molecule] [.venv] % VAGRANT_VAGRANTFILE=Vagrantfile 
vagrant ssh-config

Host instance
  HostName 127.0.0.1
  User ubuntu
  Port 2222
  UserKnownHostsFile /dev/null
  StrictHostKeyChecking no
  PasswordAuthentication no
  IdentityFile /private/tmp/test/chrony/molecule/default/.molecule/.vagrant/machines/instance/virtualbox/private_key
  IdentitiesOnly yes
  LogLevel FATAL
```

**Comment by Raffaello** [comment]
could you please advise how to override that user?

**Comment by retr0h** [comment]
Vagrant is doing it, try a different box?

**Comment by Raffaello** [comment]
I meant the `Vagrantfile` is generated by molecule, if i would like to override some parameters on the generated Vagrantfile like for example specify `config.ssh.username`, would it be possible?

**Comment by retr0h** [comment]
Yes, I understand.  That cannot be changed.  Why is the `ubuntu` user such a problem?  The `ubuntu/xenial64` box is setting this.  If you do not like that user you will need to select another box.

**Comment by Raffaello** [comment]
because it seems it cannot login. the default user should be `vagrant`, but i might be wrong, in that box could be `ubuntu`.
Anyway i have the log that hangs here:
```
[   27.966894] cloud-init[1303]: Cloud-init v. 0.7.9 running 'modules:final' at Fri, 23 Feb 2018 17:17:48 +0000. Up 27.26 seconds.
[   28.028448] cloud-init[1303]: ci-info: no authorized ssh keys fingerprints found for user ubuntu.
[   28.028683] cloud-init[1303]: Cloud-init v. 0.7.9 finished at Fri, 23 Feb 2018 17:17:48 +0000. Datasource DataSourceNoCloud [seed=/dev/sdb][dsmode=net].  Up 27.96 seconds
[[0;32m  OK  [0m] Started Execute cloud user/final scripts.
[[0;32m  OK  [0m] Reached target Cloud-init target.


Ubuntu 16.04.2 LTS ubuntu-xenial ttyS0

ubuntu-xenial login: 
```

and then going on time out because no ssh and ask for username/password authentication.

with this error
```
fatal: [instance]: UNREACHABLE! => {
        "changed": false, 
        "msg": "Failed to connect to the host via ssh: Warning: Permanently added '[127.0.0.1]:2222' (ECDSA) to the list of known hosts.\r\nvagrant@127.0.0.1: Permission denied (publickey,password).\r\n", 
        "unreachable": true
    }
    
```

**Comment by Raffaello** [comment]
and the error seems related to:
```
fatal: [instance]: UNREACHABLE! => {
        "changed": false, 
        "msg": "Failed to connect to the host via ssh: Warning: Permanently added '[127.0.0.1]:2222' (ECDSA) to the list of known hosts.\r\nvagrant@127.0.0.1: Permission denied (publickey,password).\r\n", 
        "unreachable": true
    }
```

**Comment by Raffaello** [comment]
changing box using ubuntu14 seems working properly, but it would invalidate the value of testing.... ok i will try to find another ubuntu16 box... thanks for help

**Comment by Raffaello** [comment]
tried just now from `molecule/default/.molecule` path, where `Vagrantfile` is located. runnin `vagrant ssh` is able to ssh into the machine without anyproblem with user `ubuntu` by default. i do not know what i might miss.

**Comment by retr0h** [comment]
Can you describe what you are doing?  How are you trying to log into the box and it fails?  Can you cut and paste?  Have you tried `molecule login`?  This handles it all for you.

**Comment by Raffaello** [comment]
`molecule login` is login in properly. 

my issue was: I left the `connection_options.ansible_ssh_user: vagrant` from the previous box and i was looking for an error where it was just merely mine (misconfiguration). 
Basically it is all working, my mistake.
Thank you.
