### ISSUE TITLE
can't run test : no filter named 'molecule_get_docker_networks'

### ISSUE THREAD

**Issue by wissemmahjoub** [metacloud/molecule#1158]
TASK [Delete docker network(s)] ************************************************
    fatal: [localhost]: FAILED! => {"msg": "template error while templating string: no filter named 'molecule_get_docker_networks'. String: {{ molecule_yml.platforms | molecule_get_docker_networks }}"}
    
    PLAY RECAP *********************************************************************
    localhost                  : ok=2    changed=1    unreachable=0    failed=1

**Comment by retr0h** [comment]
This bug is missing information from the issue template.  Closing.  Please open a ticket with the asked information.
