### ISSUE TITLE
ansible-galaxy dependencies installed but not found

### ISSUE THREAD

**Issue by bartmeuris** [metacloud/molecule#1162]
# Issue Type

- Bug report

# Molecule and Ansible details

```
ansible 2.4.3.0
  config file = None
  configured module search path = [u'/home/vagrant/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /home/vagrant/.virtualenvs/ansible-python2/local/lib/python2.7/site-packages/ansible
  executable location = /home/vagrant/.virtualenvs/ansible-python2/bin/ansible
  python version = 2.7.12 (default, Dec  4 2017, 14:50:18) [GCC 5.4.0 20160609]

molecule, version 2.8.2

Python 2.7.12
```

- Molecule installation method: virtualenv + pip
- Ansible installation method: virtualenv + pip

# Desired Behaviour

Dependencies defined in/installed with the `requirements.yml` should be found.

I created a `requirements.yml` in the `molecule/default/` folder of a role containing:

```
---
- src: geerlingguy.docker
```

When I run `molecule converge`, the dependency is correctly installed:

```
(ansible-python2) vagrant@vagrant:/ansible/roles/testrole$ molecule converge
--> Test matrix

└── default
    ├── dependency
    ├── create
    ├── prepare
    └── converge

--> Scenario: 'default'
--> Action: 'dependency'
    - changing role geerlingguy.docker from 2.1.0 to unspecified
    - downloading role 'docker', owned by geerlingguy
    - downloading role from https://github.com/geerlingguy/ansible-role-docker/archive/2.1.0.tar.gz
    - extracting geerlingguy.docker to /home/vagrant/.ansible/roles/geerlingguy.docker
    - geerlingguy.docker (2.1.0) was installed successfully
Dependency completed successfully.
...
```

Expected behavior would be that after this, the role would be found, and the converge step would succeed.

# Actual Behaviour (Bug report only)

The issue seems to be that Molecule does not search the `${HOME}/.ansible/roles/` folder where `ansible-galaxy` installs them:

After installing the dependency correctly (to `/home/vagrant/.ansible/roles/geerlingguy.docker`), molecule fails to find the `geerlingguy.docker` role (in this example):

```
(ansible-python2) vagrant@vagrant:/ansible/roles/testrole$ molecule converge
...
    - geerlingguy.docker (2.1.0) was installed successfully
Dependency completed successfully.
--> Scenario: 'default'
--> Action: 'create'
Skipping, instances already created.
--> Scenario: 'default'
--> Action: 'prepare'
Skipping, instances already prepared.
--> Scenario: 'default'
--> Action: 'converge'
ERROR! the role 'geerlingguy.docker' was not found in /ansible/roles/testrole/molecule/default/roles:/ansible/roles/testrole/molecule/default/.molecule/roles:/ansible/roles:/ansible/roles:/ansible/roles/testrole/molecule/default

The error appears to have been in '/ansible/roles/docker/meta/main.yml': line 5, column 5, but may
be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:

dependencies:
  - role: geerlingguy.docker
    ^ here

ERROR:
(ansible-python2) vagrant@vagrant:/ansible/roles/testrole$
```

It seems that at least in my environment, `molecule` doesn't provide the `--roles-path` to `ansible-galaxy install`, I would expect it to pass something like `molecule/default/.molecule/roles` - or another folder that molecule puts in the `ANSIBLE_ROLES_PATH` env var.

**Comment by asg1612** [comment]
Are you add the role in molecule/playbook.yml file?

like this:
roles:
    - role: geerlingguy.docker

**Comment by bartmeuris** [comment]
No, I have 2 roles: one I am testing, one 'own' `docker` role, which has a dependency on the `geerlingsguy.docker` role. Adding that role to the `molecule/playbook.yml` file doesn't change anything - it just says now that it can't find the `geerlingguy.docker` role defined in the `molecule/default/playbook.yml` file.

The `geerlingguy.docker` role is also downloaded to the `~/.ansible/roles/` directory every time I launch a converge, since molecule fails to detect it.

**Comment by retr0h** [comment]
This is a problem with galaxy.  Not much I can do here.  See discussion at #1121.

**Comment by retr0h** [comment]
Going to close this out since a work-a-round and problem is identified above.

**Comment by Dmitry1987** [comment]
I have the same issue while experimenting with molecule, but I install role with galaxy as separate step with forcing it to put the "role" into my "**/opt/app/roles**" folder,
in addition to the fact that I already downloaded the role with git clone into **/opt/app** itself,
so I DO have the ansible role actually both thrown around inside /opt/app   +  inside /opt/app/roles/ansible-vpn-docker    (inside /opt/app we have the same content from ansible-vpn-docker, the root of role).  And the funny thing is - molecule says after few "successful" lint steps that it doesn't find the role! 😩 

and I have these logs which prove that "at first" molecule **knows** where to look for the role and its files

```
--> Validating schema /opt/app/molecule/default/molecule.yml.
Validation completed successfully.
--> Test matrix
    
└── default
    ├── lint
    ├── syntax
    ├── converge
    ├── verify
    └── destroy
    
--> Scenario: 'default'
--> Action: 'lint'
--> Executing Yamllint on files found in /opt/app/...
Lint completed successfully.
--> Executing Flake8 on files found in /opt/app/molecule/default/tests/...
Lint completed successfully.
--> Executing Ansible Lint on /opt/app/molecule/default/playbook.yml...
Lint completed successfully.
--> Scenario: 'default'
--> Action: 'syntax'
ERROR! the role 'ansible-vpn-docker' was not found in /opt/app/molecule/default/roles:/tmp/molecule/app/default/roles:/opt:/opt/app/molecule/default

The error appears to have been in '/opt/app/molecule/default/playbook.yml': line 7, column 7, but may
be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:

  roles:
    - role: ansible-vpn-docker
      ^ here
ERROR: 
An error occurred during the test sequence action: 'syntax'. Cleaning up.
```

so after few lint + check steps, it goes crazy about "where's the role?" 🤣   how is that possible?

this is SO weird, especially after some previous linter and syntax steps were "completed successfully" 👎 
why does it behave like that?

**Comment by Dmitry1987** [comment]
I think it can look recursively inside all folders where it runs (especially when it found its own molecule.yml already, then the role content "is out there somewhere") and find the role name folder (because the role name folder exists in /opt/app/roles/ansible-vpn-docker  in my specific case and it doesn't see it).
Can be a nice improvement to make it smarter :) .   For example nodejs NPM knows how to look inside folders and such, both inside and above its own hierarchy where you run its commands it always finds everything.  Consider this a "feature request" :)  should I open a ticket with the request?
