### ISSUE TITLE
run test scenarios in parallel

### ISSUE THREAD

**Issue by wissemmahjoub** [metacloud/molecule#1165]
Is it possible to run several test scenarios in **parallel**, and not in sequence?
because I have several scenarios that take a lot of time to perform.
Thank you.

**Comment by retr0h** [comment]
You can use detox.

http://molecule.readthedocs.io/en/latest/testing.html#detox

**Comment by wissemmahjoub** [comment]
Thank you, but how can i specify the envname ?
tox.init file : 

[tox]
minversion = 1.8
envlist = py{27}_ansible{24}
skipsdist = true

[testenv]
deps =
    -rrequirements.txt
    ansible24: ansible==2.4
commands =
    molecule test --all
setenv =
    MOLECULE_EPHEMERAL_DIRECTORY={envname}

**Comment by retr0h** [comment]
Closing as question looks to be answered.  Please reopen if that is not the case.
