### ISSUE TITLE
Failed to import docker-py

### ISSUE THREAD

**Issue by EmilyAzevedo** [metacloud/molecule#1167]
# Issue Type

- Bug report

# Molecule and Ansible details

```
ansible --version 2.4.3.0
molecule --version 2.9.0
```

- Molecule installation method: pip
- Ansible installation method:  pip

# Desired Behaviour
I want my code to create a virtual box

# Actual Behaviour (Bug report only)
 
The full traceback is:
      File "/var/folders/v9/tj4rpqrs6ml5hv9g_mb8gd180000gn/T/ansible_NyyiDo/ansible_module_docker_container.py", line 683, in <module>
        from docker import utils
      File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/docker/__init__.py", line 6, in <module>
        from .client import Client, AutoVersionClient, from_env # flake8: noqa
      File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/docker/client.py", line 11, in <module>
        from . import api
      File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/docker/api/__init__.py", line 2, in <module>
        from .build import BuildApiMixin
      File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/docker/api/build.py", line 6, in <module>
        from .. import constants
    
    failed: [localhost] (item={'_ansible_parsed': True, '_ansible_item_result': True, '_ansible_no_log': False, u'ansible_job_id': u'781407831652.8247', 'failed': False, u'started': 1, 'changed': True, 'item': {'image': u'centos:7', 'name': u'instance'}, u'finished': 0, u'results_file': u'/Users/emilyazevedo/.ansible_async/781407831652.8247', '_ansible_ignore_errors': None}) => {
        "ansible_job_id": "781407831652.8247", 
        "attempts": 1, 
        "changed": false, 
        "finished": 1, 
        "invocation": {
            "module_args": {
                "api_version": null, 
                "auto_remove": false, 
                "blkio_weight": null, 
                "cacert_path": null, 
                "capabilities": null, 
                "cert_path": null, 
                "cleanup": false, 
                "command": null, 
                "cpu_period": null, 
                "cpu_quota": null, 
                "cpu_shares": null, 
                "cpuset_cpus": null, 
                "cpuset_mems": null, 
                "debug": false, 
                "detach": true, 
                "devices": null, 
                "dns_opts": null, 
                "dns_search_domains": null, 
                "dns_servers": null, 
                "docker_host": null, 
                "entrypoint": null, 
                "env": null, 
                "env_file": null, 
                "etc_hosts": null, 
                "exposed_ports": null, 
                "filter_logger": false, 
                "force_kill": true, 
                "groups": null, 
                "hostname": null, 
                "ignore_image": false, 
                "image": null, 
                "interactive": false, 
                "ipc_mode": null, 
                "keep_volumes": true, 
                "kernel_memory": null, 
                "key_path": null, 
                "kill_signal": null, 
                "labels": null, 
                "links": null, 
                "log_driver": null, 
                "log_options": null, 
                "mac_address": null, 
                "memory": "0", 
                "memory_reservation": null, 
                "memory_swap": null, 
                "memory_swappiness": null, 
                "name": "instance", 
                "network_mode": null, 
                "networks": null, 
                "oom_killer": null, 
                "oom_score_adj": null, 
                "paused": false, 
                "pid_mode": null, 
                "privileged": false, 
                "published_ports": null, 
                "pull": false, 
                "purge_networks": false, 
                "read_only": false, 
                "recreate": false, 
                "restart": false, 
                "restart_policy": null, 
                "restart_retries": null, 
                "security_opts": null, 
                "shm_size": null, 
                "ssl_version": null, 
                "state": "absent", 
                "stop_signal": null, 
                "stop_timeout": null, 
                "sysctls": null, 
                "timeout": null, 
                "tls": null, 
                "tls_hostname": null, 
                "tls_verify": null, 
                "tmpfs": null, 
                "trust_image_content": false, 
                "tty": false, 
                "ulimits": null, 
                "user": null, 
                "uts": null, 
                "volume_driver": null, 
                "volumes": null, 
                "volumes_from": null, 
                "working_dir": null
            }
        }, 
        "item": {
            "ansible_job_id": "781407831652.8247", 
            "changed": true, 
            "failed": false, 
            "finished": 0, 
            "item": {
                "image": "centos:7", 
                "name": "instance"
            }, 
            "results_file": "/Users/emilyazevedo/.ansible_async/781407831652.8247", 
            "started": 1
        }, 
        "msg": "Failed to import docker-py - No module named ssl_match_hostname. Try `pip install docker-py`"
    }

**Comment by retr0h** [comment]
I suggest following the method in the [quickstart](http://molecule.readthedocs.io/en/latest/#quick-start) and using a virtualenv.

**Comment by retr0h** [comment]
Closing as this looks like a local python env issue.  Please follow the quickstart.
