### ISSUE TITLE
Can't set a fact within VM that can be used by the role being tested

### ISSUE THREAD

**Issue by mattthehearn** [metacloud/molecule#1177]
# Issue Type

- Bug Report

# Molecule and Ansible details

```
ansible 2.4.2.0
  config file = None
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /bin/ansible
  python version = 2.7.5 (default, May  3 2017, 07:55:04) [GCC 4.8.5 20150623 (Red Hat 4.8.5-14)]
```

```
molecule, version 2.7.0
```

Molecule installation method (one of):

- pip

Ansible installation method (one of):

- OS package

# Desired Behavior

I am testing a role that is dependent on another role to set a fact named "datacenter" based on the IP address of the client server.  In the molecule test environment, a totally different set of private IPs is used, that don't correspond to the ones known by the dependency role.  I need to be able to set the "datacenter" fact manually in the testing environment.  I tried putting it in prepare.yml and create.yml, but they always report the fact was unchanged, and then the tested role fails because the fact isn't set.  I tried putting it in molecule's playbook.yml but it runs the role being tested *before* setting the fact, no matter the order in the file.

# Actual Behaviour (Bug report only)
    PLAY [Prepare] *****************************************************************
    
    TASK [Gathering Facts] *********************************************************
    ok: [centos7-vm]
    
    TASK [Install python for Ansible] **********************************************
    ok: [centos7-vm]
    
    TASK [Build hosts file] ********************************************************
    --- before: /etc/hosts (content)
    +++ after: /etc/hosts (content)
    @@ -1,3 +1,3 @@
    -127.0.0.1	centos7-vm	centos7-vm
    +192.168.88.110 centos7-vm
     127.0.0.1   localhost localhost.localdomain localhost4 localhost4.localdomain4
     ::1         localhost localhost.localdomain localhost6 localhost6.localdomain6
    
    changed: [centos7-vm] => (item=centos7-vm)
    
    TASK [Install net-tools] *******************************************************
    changed: [centos7-vm]
    
    TASK [Set testing datacenter fact] *********************************************
    ok: [centos7-vm]
    
    PLAY RECAP *********************************************************************
    centos7-vm                 : ok=5    changed=2    unreachable=0    failed=0
    
  
    PLAY [Converge] ****************************************************************
    
    TASK [Gathering Facts] *********************************************************
    ok: [centos7-vm]
    
    TASK [ansible-role_facts : set DC1 fact] ***************************************
    skipping: [centos7-vm]
    
    TASK [ansible-role_facts : set DC2 fact] ***************************************
    skipping: [centos7-vm]
    
    TASK [ansible-role_netbackup : Check and see what version of netbackup is installed, if any] ***
    ok: [centos7-vm]
    
    TASK [ansible-role_netbackup : Print installed and "should be" versions] *******
    fatal: [centos7-vm]: FAILED! => {"msg": "The task includes an option with an undefined variable. The error was: {{ '6.5.6-1' if (ansible_architecture=='i386') else ('7.6.0.4-2' if (datacenter=='spr') else netbackup_version) }}: 'datacenter' is undefined\n\nThe error appears to have been in '/home/ermhearn/git/ansible-role_netbackup/tasks/main.yml': line 9, column 3, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n- name: Print installed and \"should be\" versions\n  ^ here\n\nexception type: <class 'ansible.errors.AnsibleUndefinedVariable'>\nexception: {{ '6.5.6-1' if (ansible_architecture=='i386') else ('7.6.0.4-2' if (datacenter=='spr') else netbackup_version) }}: 'datacenter' is undefined"}
    
    PLAY RECAP *********************************************************************
    centos7-vm                 : ok=2    changed=0    unreachable=0    failed=1   

The task in the "prepare" play named "TASK [Set testing datacenter fact]":
     - name: Set testing datacenter fact
       set_fact:
         'datacenter': "dc1"

But as you can see, it reaches "TASK [ansible-role_netbackup : Print installed and "should be" versions]" and fails because datacenter isn't set.  My *guess* is that prepare.yml isn't actually running on the Vagrant box, it's running on my host, which already has a "datacenter" value set.  How do I get a fact set on the guest vagrant box such that the role I'm testing can see it?

**Comment by retr0h** [comment]
You would set this in `playbook.yml`.   You would want your playbook.yml to look similar to the following.

```
---
- name: Converge
  hosts: all
  become: true
  roles:
    - dependent_role_which_sets_a_fact
    - role_to_test
```

**Comment by mattthehearn** [comment]
I can run the "dependent" role; the issue is that I want to *supplement* the dependent role to set a fact that would not otherwise be handled.

Here's what I mean: normally all our internal IPs are in a massive private 10.*.*.* class-A network, all divvied up into different subnets for various purposes.  I have a role that does a "set_fact" based on the IP.

When I do my vagrant or docker tests, they get assigned IPs that don't fit any of our existing subnets, so the role that does the set_fact doesn't actually set the fact.  Now, I can modify that role to apply some kind of default, but that would only be relevant in testing, and I'd rather not have code in a "production" role that's only needed to make tests work.  What I'd like to do is find some way of setting the fact manually when testing.  But if I add a task to set the fact in playbook.yml, the role runs *before* the task.

Is there anyplace in the molecule process I can run a specialized set_fact task on the vagrant or docker guest *prior* to the converge testing the role?

**Comment by mattthehearn** [comment]
I realized (when opening my other issue) that I can pass this value in via extra-vars, which is probably a good enough work-around.

**Comment by retr0h** [comment]
Prepare is run under a separate `ansible-playbook` invocation therefore facts set there will not be seen by subsequent `ansible-playbook` invocations (e.g. Converge, Destroy).

**Comment by retr0h** [comment]
Closing at this was adequately discussed.
