### ISSUE TITLE
Dependency Provider: shell 

### ISSUE THREAD

**Issue by lxhunter** [metacloud/molecule#1182]
Hi, 

its me again :) , i was looking through v1 and saw there was a shell dependency provider. I wrote a tool ([gooh](https://github.com/lxhunter/gooh)), close to gilt, which uses [tilde and caret](https://blog.madewithlove.be/post/tilde-and-caret-constraints/) like bundler, npm or composer does, so that i get updates on patch and minor changes. 

like so:
```yml
- src: https://github.com/lxhunter/versions.git
  version: '~1.0.0'
```
Is there any plan to implement this, i could give it a try, as i see it is really close to the Tilt Provider.

What do you think?

Cheers,
Alex

**Comment by retr0h** [comment]
Shell is probably one of the dependency managers I should forward port from v1.  Also, would you be interested in adding gooh semver support to Gilt?

**Comment by lxhunter** [comment]
Aside from a lot of excuses which directly spring into mind, like i am a python beginner and don't know a lot about the whole build stack. I can give it a try. I really like to contribute... but you have to be honest if i made a mess in my code. What do you think, still try?

**Comment by retr0h** [comment]
> What do you think, still try?

Sure!  Looking at `gooh` it is solving a similar problem to `Gilt`.  If `Gilt` could do semver tag checkout, that would give you what you wanted, yeah?
