### ISSUE TITLE
Dynamic platforms variable issue with multiple instances in molecule.yml

### ISSUE THREAD

**Issue by hahaki** [metacloud/molecule#1183]
# Issue Type

- Bug report

# Molecule and Ansible details

I am using delegated mode to testing and own script launch the machines on aws separately. The test is working if i have 1 or more instance hardcoded into molecule.yml platforms variable like this
platforms:
  - name: vm1
  - name: vm2

If i want to use in a dynamic way and load the machine names from a file, it does not want to work.

platforms: "{{ lookup('file', '/tmp/test2.txt' )| from_json }}"

or 

platforms: 
  - "{{ lookup('file', '/tmp/test2.txt' )| from_json }}"

json content 1st trial:
[
    {
      "name": "vm1"
    },
    {
      "name": "vm2"
    }
]

json content 2nd trial:
{
  "platforms": [
    {
      "name": "vm1"
    },
    {
      "name": "vm2"
    }
  ]
}

ansible --version
ansible 2.4.3.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/home/konczi.ext/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python2.7/dist-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 2.7.14 (default, Sep 23 2017, 22:06:14) [GCC 7.2.0]

```
molecule --version
molecule, version 2.9.0

Molecule installation method (one of):
- pip

Ansible installation method (one of):
- pip

# Desired Behavior

Please give some details of the feature being requested or what
should happen if providing a bug report.

# Actual Behaviour (Bug report only)

Error message of running:

Traceback (most recent call last):
  File "/usr/local/bin/molecule", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/molecule/command/check.py", line 75, in check
    base.get_configs(args, command_args), scenario_name)
  File "/usr/local/lib/python2.7/dist-packages/molecule/command/base.py", line 119, in get_configs
    ansible_args=ansible_args, ) for c in glob.glob(MOLECULE_GLOB)
  File "/usr/local/lib/python2.7/dist-packages/molecule/config.py", line 91, in __init__
    self.config = self._combine()
  File "/usr/local/lib/python2.7/dist-packages/molecule/config.py", line 265, in _combine
    schema.validate(base)
  File "/usr/local/lib/python2.7/dist-packages/molecule/model/schema.py", line 205, in validate
    return schema.load(c)
  File "/usr/local/lib/python2.7/dist-packages/marshmallow/schema.py", line 580, in load
    result, errors = self._do_load(data, many, partial=partial, postprocess=True)
  File "/usr/local/lib/python2.7/dist-packages/marshmallow/schema.py", line 701, in _do_load
    raise exc
marshmallow.exceptions.ValidationError: {'platforms': [u'Not a valid list.']}

**Comment by retr0h** [comment]
Molecule.yml is not an ansible file, therefore it does not understand ansible'isms.

**Comment by hahaki** [comment]
Is there any nice solution for that or just a workaround to generate from bash the whole molecule.yml file?

**Comment by retr0h** [comment]
People generally use [Interpolation](http://molecule.readthedocs.io/en/latest/configuration.html#molecule.interpolation.Interpolator) with ENV vars.

**Comment by hahaki** [comment]
If i use the following: export WEB_SERVERS="vm1"

and 

platforms: 
  -name: ${WEB_SERVERS}

That works,

But when i use the following:

export WEB_SERVERS=( 'vm1' 'vm2' )

platforms: 
  -name: ${WEB_SERVERS[0]}

That fails 

with 

platforms: 
  - name: ${WEB_SERVERS[@]}

also fails

If i try the following:

export WEB_SERVERS=( 'name' 'vm1' )

with 

platforms: ${WEB_SERVERS}

or 

platforms: ${WEB_SERVERS[@]}

fails.

I think, that feature is completely missing to bypass molecule in a dynamic way more than 1 servers to test. 

Any other idea to solve it?

**Comment by retr0h** [comment]
> Any other idea to solve it?

no, can't think of any dynamic way other than mapping the instances statically.

**Comment by rollerd** [comment]
Just a thought, but we generally run our molecule tests from inside a docker container that includes molecule, ansible, etc in the image. You might be able to do that and use [Kelsey Hightowers confd](https://github.com/kelseyhightower/confd) to dynamically build that molecule.yml file each time you spin up the molecule host container to run your tests.

This short video probably gives a better idea of what it can do before jumping into the docs: https://youtu.be/QeepkWC-qM0?t=492
