### ISSUE TITLE
Passing --extra-vars only works with converge, but not imdempotence or test

### ISSUE THREAD

**Issue by mattthehearn** [metacloud/molecule#1184]
# Issue Type

- Feature request

# Molecule and Ansible details

```
ansible 2.4.2.0
  config file = None
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /bin/ansible
  python version = 2.7.5 (default, May  3 2017, 07:55:04) [GCC 4.8.5 20150623 (Red Hat 4.8.5-14)]
```

```
molecule, version 2.7.0
```

Molecule installation method (one of):

- pip

Ansible installation method (one of):

- OS package

# Desired Behavior

We have roles that require variables to be passed to them, generally credentials that we store externally (Jenkins or Tower).  When we run the role as part of a playbook, we can use "--extra-vars" to pass those in.  When testing, we can do "molecule converge -- --extra-vars='variable=data'", but it only works with the converge step, not with idempotence or test.  So end-to-end testing isn't possible.  Can molecule be updated so that all the commands that actually run a playbook using the role (test, idempotence, etc.) can accept the "--extra-vars" option?

Edit to add: I know that these variables can probably be added to provisioner in molecule.yml; the point is that we want to pass them on the command-line, so that we aren't storing passwords in plain-text in our code.

**Comment by retr0h** [comment]
`--extra-vars` is not something you should rely on for anything other than a quick `molecule converge`.  It is not there for `test` or any other sub command.  If you wish to set variables/facts you should see the discussion in #1177 or check the docs on setting inventory in `molecule.yml`.

**Comment by mattthehearn** [comment]
My concern with storing them in the code is exposing credentials (passwords, etc.) that become visible inside our github.  For example, we have a role that joins new VMs to our AD environment using SSSD.  To do this, we need the username and password of a Domain Administrator.  We can put that into Jenkins or Tower because it gets stored securely, but if we put it unobscured into our molecule configuration files, it is visible to anyone with access to our GitHub organization.

Obviously, we can just exclude the files with exposed passwords from Git, but the end-goal is to have code that can be forked, cloned, and tested as-is without having to re-create a bunch of files.  It's easier for a tester to look at a README and determine what needs to be passed via extra-vars than it is to download the code and then have to go rooting around elsewhere to find the necessary molecule.yml file.

**Comment by retr0h** [comment]
> My concern with storing them in the code is exposing credentials (passwords, etc.)

Thats why `molecule.yml` supports [Interpolation](http://molecule.readthedocs.io/en/latest/configuration.html#molecule.interpolation.Interpolator) with ENV vars.  This ties perfectly into CI and not checking secrets in.

> Edit to add: in an ideal world for our use-case, it would actually be possible to prompt the tester for the necessary variables, though I realize that somewhat defeats the entire purpose of automated testing. It'd be a cool option to have, though.

Yeah, don't really see the point of that.

**Comment by retr0h** [comment]
Also, if you are concerned about secrets see #1061.

**Comment by retr0h** [comment]
Closing at this was adequately discussed.
