### ISSUE TITLE
Molecule replace latest jinja2 2.10 to 2.2.9.6 buggy version which causes template issue in ansible with namespace

### ISSUE THREAD

**Issue by hahaki** [metacloud/molecule#1187]
# Issue Type

- Bug report

# Molecule and Ansible details

ansible --version
ansible 2.4.3.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python2.7/dist-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.14 (default, Sep 23 2017, 22:06:14) [GCC 7.2.0]

molecule --version
molecule, version 2.10.1

Molecule installation method (one of):

- pip

Ansible installation method (one of):

- pip

# Desired Behavior

do not replace jinja2 2.2.10 to 2.2.9.6

# Actual Behaviour (Bug report only)

root@OED-EX-DIG-L:~# pip install molecule --upgrade
Requirement already up-to-date: molecule in /usr/local/lib/python2.7/dist-packages
Requirement already up-to-date: pbr==3.0.1 in /usr/local/lib/python2.7/dist-packages (from molecule)
Requirement already up-to-date: python-gilt==1.1.0 in /usr/local/lib/python2.7/dist-packages (from molecule)
Requirement already up-to-date: colorama==0.3.7 in /usr/local/lib/python2.7/dist-packages (from molecule)
Requirement already up-to-date: yamllint==1.11.0 in /usr/local/lib/python2.7/dist-packages (from molecule)
Collecting Jinja2==2.9.6 (from molecule)
  Using cached Jinja2-2.9.6-py2.py3-none-any.whl
Requirement already up-to-date: pexpect==4.2.1 in /usr/lib/python2.7/dist-packages (from molecule)
Requirement already up-to-date: click==6.7 in /usr/local/lib/python2.7/dist-packages (from molecule)
Requirement already up-to-date: tree-format==0.1.2 in /usr/local/lib/python2.7/dist-packages (from molecule)
Requirement already up-to-date: cookiecutter==1.5.1 in /usr/local/lib/python2.7/dist-packages (from molecule)
Requirement already up-to-date: tabulate==0.7.7 in /usr/local/lib/python2.7/dist-packages (from molecule)
Requirement already up-to-date: PyYAML==3.12 in /usr/lib/python2.7/dist-packages (from molecule)
Requirement already up-to-date: ansible-lint==3.4.19 in /usr/local/lib/python2.7/dist-packages (from molecule)
Requirement already up-to-date: testinfra==1.7.1 in /usr/local/lib/python2.7/dist-packages (from molecule)
Requirement already up-to-date: flake8==3.3.0 in /usr/local/lib/python2.7/dist-packages (from molecule)
Requirement already up-to-date: click-completion==0.2.1 in /usr/local/lib/python2.7/dist-packages (from molecule)
Requirement already up-to-date: psutil==5.2.2; sys_platform != "win32" and sys_platform != "cygwin" in /usr/local/lib/python2.7/dist-packages (from molecule)
Requirement already up-to-date: sh==1.12.14 in /usr/local/lib/python2.7/dist-packages (from molecule)
Requirement already up-to-date: anyconfig==0.9.1 in /usr/local/lib/python2.7/dist-packages (from molecule)
Requirement already up-to-date: marshmallow==2.13.5 in /usr/local/lib/python2.7/dist-packages (from molecule)
Requirement already up-to-date: fasteners in /usr/local/lib/python2.7/dist-packages (from python-gilt==1.1.0->molecule)
Requirement already up-to-date: git-url-parse in /usr/local/lib/python2.7/dist-packages (from python-gilt==1.1.0->molecule)
Requirement already up-to-date: pathspec>=0.5.3 in /usr/local/lib/python2.7/dist-packages (from yamllint==1.11.0->molecule)
Requirement already up-to-date: MarkupSafe>=0.23 in /usr/lib/python2.7/dist-packages (from Jinja2==2.9.6->molecule)
Requirement already up-to-date: whichcraft>=0.4.0 in /usr/local/lib/python2.7/dist-packages (from cookiecutter==1.5.1->molecule)
Requirement already up-to-date: binaryornot>=0.2.0 in /usr/local/lib/python2.7/dist-packages (from cookiecutter==1.5.1->molecule)
Requirement already up-to-date: future>=0.15.2 in /usr/local/lib/python2.7/dist-packages (from cookiecutter==1.5.1->molecule)
Requirement already up-to-date: poyo>=0.1.0 in /usr/local/lib/python2.7/dist-packages (from cookiecutter==1.5.1->molecule)
Requirement already up-to-date: jinja2-time>=0.1.0 in /usr/local/lib/python2.7/dist-packages (from cookiecutter==1.5.1->molecule)
Requirement already up-to-date: ansible in /usr/local/lib/python2.7/dist-packages (from ansible-lint==3.4.19->molecule)
Requirement already up-to-date: six in /usr/local/lib/python2.7/dist-packages (from ansible-lint==3.4.19->molecule)
Requirement already up-to-date: pytest!=3.0.2 in /usr/local/lib/python2.7/dist-packages (from testinfra==1.7.1->molecule)
Requirement already up-to-date: enum34; python_version < "3.4" in /usr/lib/python2.7/dist-packages (from flake8==3.3.0->molecule)
Requirement already up-to-date: configparser; python_version < "3.2" in /usr/local/lib/python2.7/dist-packages (from flake8==3.3.0->molecule)
Requirement already up-to-date: pyflakes<1.6.0,>=1.5.0 in /usr/local/lib/python2.7/dist-packages (from flake8==3.3.0->molecule)
Requirement already up-to-date: mccabe<0.7.0,>=0.6.0 in /usr/local/lib/python2.7/dist-packages (from flake8==3.3.0->molecule)
Requirement already up-to-date: pycodestyle<2.4.0,>=2.0.0 in /usr/local/lib/python2.7/dist-packages (from flake8==3.3.0->molecule)
Requirement already up-to-date: monotonic>=0.1 in /usr/local/lib/python2.7/dist-packages (from fasteners->python-gilt==1.1.0->molecule)
Requirement already up-to-date: chardet>=3.0.2 in /usr/local/lib/python2.7/dist-packages (from binaryornot>=0.2.0->cookiecutter==1.5.1->molecule)
Requirement already up-to-date: arrow in /usr/local/lib/python2.7/dist-packages (from jinja2-time>=0.1.0->cookiecutter==1.5.1->molecule)
Requirement already up-to-date: cryptography in /usr/local/lib/python2.7/dist-packages (from ansible->ansible-lint==3.4.19->molecule)
Requirement already up-to-date: setuptools in /usr/local/lib/python2.7/dist-packages (from ansible->ansible-lint==3.4.19->molecule)
Requirement already up-to-date: paramiko in /usr/local/lib/python2.7/dist-packages (from ansible->ansible-lint==3.4.19->molecule)
Requirement already up-to-date: attrs>=17.2.0 in /usr/local/lib/python2.7/dist-packages (from pytest!=3.0.2->testinfra==1.7.1->molecule)
Requirement already up-to-date: py>=1.5.0 in /usr/local/lib/python2.7/dist-packages (from pytest!=3.0.2->testinfra==1.7.1->molecule)
Requirement already up-to-date: funcsigs; python_version < "3.0" in /usr/local/lib/python2.7/dist-packages (from pytest!=3.0.2->testinfra==1.7.1->molecule)
Requirement already up-to-date: pluggy<0.7,>=0.5 in /usr/local/lib/python2.7/dist-packages (from pytest!=3.0.2->testinfra==1.7.1->molecule)
Requirement already up-to-date: backports.functools-lru-cache>=1.2.1; python_version == "2.7" in /usr/local/lib/python2.7/dist-packages (from arrow->jinja2-time>=0.1.0->cookiecutter==1.5.1->molecule)
Requirement already up-to-date: python-dateutil in /usr/local/lib/python2.7/dist-packages (from arrow->jinja2-time>=0.1.0->cookiecutter==1.5.1->molecule)
Requirement already up-to-date: cffi>=1.7; platform_python_implementation != "PyPy" in /usr/local/lib/python2.7/dist-packages (from cryptography->ansible->ansible-lint==3.4.19->molecule)
Requirement already up-to-date: idna>=2.1 in /usr/local/lib/python2.7/dist-packages (from cryptography->ansible->ansible-lint==3.4.19->molecule)
Requirement already up-to-date: asn1crypto>=0.21.0 in /usr/local/lib/python2.7/dist-packages (from cryptography->ansible->ansible-lint==3.4.19->molecule)
Requirement already up-to-date: ipaddress; python_version < "3" in /usr/local/lib/python2.7/dist-packages (from cryptography->ansible->ansible-lint==3.4.19->molecule)
Requirement already up-to-date: pynacl>=1.0.1 in /usr/local/lib/python2.7/dist-packages (from paramiko->ansible->ansible-lint==3.4.19->molecule)
Requirement already up-to-date: pyasn1>=0.1.7 in /usr/local/lib/python2.7/dist-packages (from paramiko->ansible->ansible-lint==3.4.19->molecule)
Requirement already up-to-date: bcrypt>=3.1.3 in /usr/local/lib/python2.7/dist-packages (from paramiko->ansible->ansible-lint==3.4.19->molecule)
Requirement already up-to-date: pycparser in /usr/local/lib/python2.7/dist-packages (from cffi>=1.7; platform_python_implementation != "PyPy"->cryptography->ansible->ansible-lint==3.4.19->molecule)
Installing collected packages: Jinja2
  Found existing installation: Jinja2 2.10
    Uninstalling Jinja2-2.10:
      Successfully uninstalled Jinja2-2.10
Successfully installed Jinja2-2.9.6

Current workaround solution

after pip install molecule --upgrade you have to run pip install ansible --upgrade to fix the jinja2 version

**Comment by retr0h** [comment]
Do you have the Ansible bug where this version of jinja2 is an issue?

**Comment by hahaki** [comment]
I can reproduce it any time and provide that info if it helps. Should i paste an example here?

**Comment by hahaki** [comment]
Playbook:

---

- name: jinja2 test
  hosts: all
  gather_facts: no

  tasks:
  - name: create template
    local_action:
      module: template
      src: "{{ playbook_dir }}/test.j2"
      dest: "{{ playbook_dir }}/test.template"
    run_once: yes
   

template (test2.j2):

{% set ns = namespace(_something = true) %}
anything

You can see the different result
