### ISSUE TITLE
Bash completion not found 

### ISSUE THREAD

**Issue by chrisduong** [metacloud/molecule#1193]
# Issue Type

- Bug report

# Desired Behavior

According to this guide, [http://molecule.readthedocs.io/en/stable-1.22/bash.html](http://molecule.readthedocs.io/en/stable-1.22/bash.html). I can download Bash completion script at https://github.com/metacloud/molecule/blob/master/asset/bash_completion/molecule.bash-completion.sh

# Actual Behaviour (Bug report only)

The completion script is not there.

**Comment by retr0h** [comment]
Please use Molecule v2, as Molecule v1 is no longer a supported.    Bash completion works with v2.
