### ISSUE TITLE
Add i18n support

### ISSUE THREAD

**Issue by retr0h** [metacloud/molecule#1199]
# Issue Type

- Feature request

# Desired Behavior

Add i18n support to Molecule command help and log messages.  We cannot change the output printed by Ansible and related commands.  However, we will report translation where possible.

**Comment by wilmardo** [comment]
Is this a real issue? Is this not slightly overkill and over complicating things? Ansible does not support this and if you look at large projects, all the docs/command output is in English. Why bother with translation?

Also this might start a snowball of translations, if you translate the command output why not the docs, why not a Ansible callback plugin which translation support etc.

Just a sidenote from a different perspective to start a discussion :+1:

**Comment by retr0h** [comment]
> this a real issue? Is this not slightly overkill and over complicating things?

no and yes

> Why bother with translation?

why not :)

Ansible output will be untouched, simply want to investigate  this.

**Comment by retr0h** [comment]
Holding off on this.
