### ISSUE TITLE
provide a platforms.yml file besides molecule.yml to define scenarios easier

### ISSUE THREAD

**Issue by Sephtex** [metacloud/molecule#1205]
# Issue Type

- Feature request
linked to #1204 

# Molecule and Ansible details

```
ansible 2.4.3.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/home/yi/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/dist-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.12 (default, Dec  4 2017, 14:50:18) [GCC 5.4.0 20160609]
```

```
$ pip show molecule
Name: molecule
Version: 2.8.2
Summary: Molecule aids in the development and testing of Ansible roles.
Home-page: https://github.com/metacloud/molecule
Author: UNKNOWN
Author-email: UNKNOWN
License: MIT
Location: /usr/local/lib/python2.7/dist-packages
Requires: anyconfig, marshmallow, click-completion, Jinja2, pexpect, click, PyYAML, tabulate, python-gilt, pbr, ansible-lint, tree-format, cookiecutter, yamllint, sh, flake8, colorama, psutil, testinfra

```

Molecule installation method (one of):

- pip

Ansible installation method (one of):

- OS package

# Desired Behavior

When creating multiple scenario's to have just 1 variable with multiple different options per test case to be tested with multiple setups you need to copy the molecule.yml file multiple times where there is just 1 value changed.
This change request is to have all the molecule yaml files staying in default test case, but by just providing platforms.yml where you can specify the list of platforms. The platforms.yml would be the same as having the molecule.yml file being duplicated, where the platforms list would have changed.

This would make it easy to make multiple scenarios where you have a different set of platforms and maybe options like groups which are then defined in molecule/default/molecule.yml.

This change could also include a default behaviour where platforms.yml could be specified besides the molecule.yml to populate the platforms list with the default option not being removed but appended to the list provided in platforms.yml.

If this change can be made possible, then it's even more easy to create a global molecule test file which can be consumed by all scenario's.

**Comment by retr0h** [comment]
Hi @Sephtex thank you for the feedback.  Unfortunately, this is not something I am going to implement at this time.  It is somewhat related to #1099.

However, I will leave this open for now as we decide if/how we wish to solve config duplication.
