### ISSUE TITLE
Show source to dind molecule:latest

### ISSUE THREAD

**Issue by snoby** [metacloud/molecule#1220]
# Issue Type

- Feature request

# Molecule and Ansible details

Can you please publish the Dockerfile for building the retr0h/molecule:latest container?
Thanks

**Comment by retr0h** [comment]
It's in the base of the repo.

**Comment by retr0h** [comment]
Moved to it's own directory to keep context manageable.  New [link](https://github.com/metacloud/molecule/blob/master/build/Dockerfile).
