### ISSUE TITLE
I and not able to set a different ANSIBLE_ROLE_PATH  my modifying the molecule.yml or by an export while running molecule in a shell script. 

### ISSUE THREAD

**Issue by bnikolaus** [metacloud/molecule#1221]
# Issue Type
- Bug report

# Molecule and Ansible details
I and not able to set a different ANSIBLE_ROLE_PATH  my modifying the molecule.yml or by an export while running molecule in a shell script. 

```
ansible --version
```
ansible 2.5.0

```
molecule --version
```
molecule, version 2.11.0

Molecule installation method (one of):
- pip

Ansible installation method (one of):
- pip

I have included environmental variables the test molecule.yml like so...
cat test/molecule/default/molecule.yml
---
dependency:
  name: galaxy
driver:
  name: docker
lint:
  name: yamllint
platforms:
  - name: instance
    image: centos:7
provisioner:
  name: ansible
  env:
    ANSIBLE_CONFIG: "../ansible.cfg"
    ANSIBLE_ROLES_PATH: "../playbooks/roles/"
  lint:
    name: ansible-lint
scenario:
  name: default
verifier:
  name: testinfra
  lint:
    name: flake8

When I run a debug these are the values that come accross.
molecule --debug test
ANSIBLE_CONFIG: ../ansible.cfg
ANSIBLE_ROLES_PATH=/Users/lol/git/lol/test/molecule/default/.molecule/roles:/Users/lol/git/lol:/Users/lol/git/lol/test/molecule/playbooks/roles

I have tried exporting this and kicking this off in a shell and nothing seems to set the ENV correctly. It looks like its getting the absolute path to the role paths. Where can I set this?

**Comment by retr0h** [comment]
Molecule expands the path defined in `ANSIBLE_ROLES_PATH` into a fully qualified path relative to the scenario ephemeral directory.  You cannot set ANSIBLE_ROLES_PATH outside molecule.yml, Molecule will override it.  

And as you see I set this var in our [scenario tests](https://github.com/metacloud/molecule/blob/master/test/scenarios/driver/docker/molecule/default/molecule.yml#L21-L22).  I suggest changing the value and rerunning `molecule --debug` until you get it right.

I suggest
