### ISSUE TITLE
Verify task is not able to change user.

### ISSUE THREAD

**Issue by anaelChardan** [metacloud/molecule#1240]
# Issue Type

- Bug report

# Molecule and Ansible details

```
ansible --version
```

ansible 2.4.3.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/home/nanou/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/dist-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.14 (default, Sep 23 2017, 22:06:14) [GCC 7.2.0]

```
molecule --version
```

molecule, version 2.12.1

Molecule installation method (one of):
- pip

Ansible installation method (one of):

- OS package

# Desired Behavior

Please give some details of the feature being requested or what
should happen if providing a bug report.

My machines are GCE one and have particular user, verify method should be able to connect via this user and then become a particular user.

# Actual Behaviour (Bug report only)

Please give some details of what is actually happening.
Include a [minimum complete verifiable example](http://stackoverflow.com/help/mcve) with
output of running `molecule --debug`.

I provided this on my playbooks
 ```  
  become: "yes"
  remote_user: admin
  become_method: sudo
```

so it works for everything except the verify one because it connects only on admin but not on root afterwrards.

If I set correct environnement variables it works but it is not what I want.

I already checked those issues : 
https://github.com/metacloud/molecule/issues/983

but it does not works on testinfra as the inventory generated does not contain those information.

Thanks you ;)

**Comment by anaelChardan** [comment]
Hi, me again! ;)

So, I have found a workaround, tell me if it is the good way to do it ;):

On my molecule.yml I've that:

provisioner:
  name: ansible
  config_options:
    defaults:
      become: 'True'
      become_method: 'sudo'
      become_user: 'root'
      remote_user: 'admin'

which will write on the ansible.cfg

and then on my test_default.py, if have that :

import os
import configparser
import testinfra.utils.ansible_runner

config = configparser.ConfigParser()
config.read(os.environ['ANSIBLE_CONFIG'])

if config.has_option('defaults', 'become_user'):
    os.environ['ANSIBLE_BECOME_USER'] = config['defaults']['become_user']

if config.has_option('defaults', 'become'):
    os.environ['ANSIBLE_BECOME'] = config['defaults']['become']

testinfra_hosts = testinfra.utils.ansible_runner.AnsibleRunner(
    os.environ['MOLECULE_INVENTORY_FILE']).get_hosts('all')


with this, it works well with GCE and other providers ;)

**Comment by retr0h** [comment]
Testinfra uses the ansible connection.  If the ansible connection isn't setup right, then the verifier isn't going to connect properly.  So what you define in provisioner.config_options would be passed to testinfra b/c the ansible connection is used to connect to your instance.

**Comment by shtouff** [comment]
Hi there, 

Sorry to re-open this, but I did not get it: I'm not able to make the verifier run with 'become: True'. I need it to verify some iptables rules in a test, so the test has to be run as root.

What is the recommended setup to run the verifier as root ?
