### ISSUE TITLE
Good example of how scenarios work

### ISSUE THREAD

**Issue by batman1007** [metacloud/molecule#1241]
https://github.com/metacloud/molecule/blob/cb3639371be98d8b1711bd0e4e54ae3841301f47/molecule/scenarios.py#L33

Can someone help me to explain a good working example of how 'scenarios' in molecule work? What it looks like when defining it in molecule.yml, etc?

I have two scenario's at the moment, default & unregister. I run them independently using the molecule test -s <scenario> name option, but the 'scenarios' feature looks like something I might use, but there's no info on how to actually use it. Can someone elaborate.

Any help would be appreciated.

**Comment by batman1007** [comment]
@retr0h - I know that they are scenario's, what I'm trying to ask is within the molecule.yml file, the specific use of the 'scenarios' option, as mentioned in the doc's here:
https://molecule.readthedocs.io/en/latest/configuration.html#scenarios

How do you use this particular option and can someone provide a good example of it's usage?

**Comment by retr0h** [comment]
Molecule.yml doesn't reference other scenarios.  Scenarios are tested in isolation.  Your `default` and `unregister` scenarios are simply scenarios. 

The docs you linked to are simply documenting the `Scenarios` class and what that class is responsible for.  It has nothing to do with molecule.yml.

**Comment by batman1007** [comment]
Ah I see, ok that makes sense. Thanks.
