### ISSUE TITLE
`molecule login` should infer single host

### ISSUE THREAD

**Issue by conorsch** [metacloud/molecule#125]
When running `molecule login`, it requires a hostname, even if there's only one host running. If there's only one host running, `molecule login` should _not_ require a hostname, and should assume that the only running machine is the SSH target.

**Comment by abrown-sg** [comment]
@conorsch I think #113 covers this. It's merged but not on PyPi yet. We're due for a new release.

**Comment by rgreinho** [comment]
PR #113 solves this issue.

**Comment by conorsch** [comment]
@abrown-sg Missed that, thanks!
