### ISSUE TITLE
After molecule update facing issue with links 

### ISSUE THREAD

**Issue by r0ckyte** [metacloud/molecule#1252]
# Issue Type

- Bug report
- Feature request

# Molecule and Ansible details

```
ansible 2.2.1
```

```
molecule 2.12.0
```

Molecule installation method (one of):
- pip

Ansible installation method (one of):
- OS package

# Desired Behavior
i have symlinks in [molecule.yml ](https://github.com/r0ckyte/ansible-testing/blob/master/molecule/default/molecule.yml#L26) which works good with molecule 2.3 

# Actual Behaviour (Bug report only)
looks like the TMPDIR change is impacting my existing repo. can you please help how i can modify molecule.yml to get it working 
`
--> Test matrix
    
└── default
    ├── create
    └── prepare
    
ERROR: The source path '/tmp/molecule/ansible-testing/default/../../../dev/group_vars' does not exist.
`

**Comment by retr0h** [comment]
@r0ckyte please make sure the links are relative to the scenario directory once Molecule 2.13 is released.  My apologies for breaking your workflow.

**Comment by r0ckyte** [comment]
@retr0h  - thank you

can you please let me know when next release is ? if its too long, i would rather download and compile

Thank you
