### ISSUE TITLE
any plant to support docker?

### ISSUE THREAD

**Issue by linearregression** [metacloud/molecule#126]

**Comment by dhutty** [comment]
Not currently. But that doesn't mean that we wouldn't make a plan if it's desired and demonstrably viable/valuable. The best way forward would be if you would expand a little on what you have in mind.

**Comment by skornehl** [comment]
we need the possibility to describe [this](https://www.vagrantup.com/docs/provisioning/docker.html) in molecule.yml - or am I just missing something here?

**Comment by tjanez** [comment]
@dhutty, our use case would be using Molecule in an environment where one can't easily spin up virtual machines with Vagrant, but can easily create Docker containers.

An example of such an environment are most CI services which usually only provide a single or a couple of very customized operating system options (e.g. [Travis CI's build environment](https://docs.travis-ci.com/user/ci-environment/#Virtualization-environments)) but offer Docker support for spinning up containers from any operating system image.

It would be great if one could use Molecule with e.g. [Travis CI](https://travis-ci.org/) to test an Ansible role on various operating systems via their official Docker images.

The way I see this could be implemented is to create a new provisioner as an alternative to the `VagrantProvisioner` but I don't know which Docker tool could provide similar capabilities to Vagrant?

**Comment by retr0h** [comment]
@tjanez Having molecule work on travisci is paramount.  We are knees deep in some platform work, but happy to look into this in the next couple months.

**Comment by azenk** [comment]
I decided to take a stab at this.  It's a work in progress at https://github.com/azenk/molecule/tree/docker_provisioner

It looks to me like a change in the provisioner injection code is required, as well as a config file change.  Without it, I don't believe that the provisioner can be changed from vagrant without modifying the default.yml file.  I'd propose adding a provisioner option to the molecule section.

**Comment by kireledan** [comment]
I decided to give this a try because I urgently desired this feature. So far all of the commands except verify are supported and right now I have it only building off of one static image name. But at the moment, a molecule converge does run the playbooks against the specified docker containers. Molecule test also works (except the verify states that integration tests are skipped). 

https://github.com/kireledan/molecule/tree/docker_provision

My next step is to do some cleanup and add some more abstraction.

**Comment by retr0h** [comment]
Completed.
