### ISSUE TITLE
reload session after converge sequence ?

### ISSUE THREAD

**Issue by wissemmahjoub** [metacloud/molecule#1267]
Hello,
is it possible to reload session after converge sequence?

**Comment by retr0h** [comment]
I don't know what this means.

**Comment by wissemmahjoub** [comment]
I need the effect of having to close and open the linux terminal. after finishing the converge sequence.

**Comment by retr0h** [comment]
Not sure how this would be accomplished.

**Comment by wissemmahjoub** [comment]
ok, thank you
