### ISSUE TITLE
Support Python 3

### ISSUE THREAD

**Issue by blentz** [metacloud/molecule#1269]
Python 2 is EOL relatively soon (~2 years) and Python 3 has been around quite a while. With 2.7 being very closely compatible with Python 3.x, there's little reason to not support Python 3 and even less reason to hard-fail when running under a Python 3.x interpreter.

Also, distros like Fedora are currently discussing their approach to Python 2's EOL. Molecule's hard stance on Python 2-only makes it very difficult to include it into a mainstream distro.

# Issue Type

- Bug report

Molecule installation method (one of):

- source

Ansible installation method (one of):

- OS package

# Desired Behavior

Molecule should not fail when running with python 3

# Actual Behaviour (Bug report only)

ERROR: Python version '3.6.5' not supported. Molecule only supports python version = 2.7.

**Comment by retr0h** [comment]
Already [done](https://github.com/metacloud/molecule/pull/1250).  It's slated for 2.13 release of Molecule.
