### ISSUE TITLE
The way to provide vars for molecule

### ISSUE THREAD

**Issue by freeseacher** [metacloud/molecule#1271]
# Issue Type

Question

As currently mentioned from docs and source there are two ways to get vars for converge stage. I have pretty big monolith repo for our opensource microservices app. During deploy i have to put at about 35 roles in correct order on different nodes. 

While trying to implement testing i found molecule second time (previous was at about 1.10 version). I already has goss tests so i plan to use it as verifier.

The simplest installation as about 29 roles on one server. the main problem i have is vars. 
for single server app there are 816 lines of vars. Here they are https://gist.github.com/freeseacher/2dbe848705389bb83fda7bcdb6ecdc3a 

The node info was get from 
`./bin/ansible-inventory  -i ./bin/tower-inv  --host node1 -y`
and full_list from
`./bin/ansible-inventory  -i ./bin/tower-inv --list -y`

Full_list file have to be in format compatible with ansible-inventory format

Of cause that vars list have to be modified to remove connectivity info and replaced with molecule provided one.

The question is how do i insert var for molecule ?
I am using molecule 2.12.1 and ansible 2.5.1

**Comment by freeseacher** [comment]
As far as i can understand logic i want to have one file with inventory for one scenario. 
Both ways provided as current options looks not reasonable. 
I do not have host_vars ans group_vars splited. so i can't link them. 
And due of number of vars i can't place them to just hosts section

**Comment by retr0h** [comment]
You probably want to use [links](http://molecule.readthedocs.io/en/latest/configuration.html#provisioner).  If that doesn't work and you are using ansible >= 2.4 you could try updating `provisioner.options` with another inventory path (`i`: path/to/extra/inventory`), which would result in `ansible-playbook` getting an additional inventory source directory.

**Comment by freeseacher** [comment]
tnx. works for me. any ideas to document this behavior ?

**Comment by retr0h** [comment]
You're simply using an ansible feature to add an additional inventory path.  Your situation is out of the ordinary, and don't believe it is the norm.
