### ISSUE TITLE
Parallel testing of scenario is broken in 2.12.1

### ISSUE THREAD

**Issue by suonto** [metacloud/molecule#1272]
# Issue Type

- Bug report

# Molecule and Ansible details
- Ansible version: 2.4.4.0
- Molecule version: 2.12.1
- Molecule installation method: pip

Ansible installation method: pip

# Desired Behavior
Executing `molecule test` in different working directories at the same time does not cause collisions.

# Actual Behaviour
Executing `molecule test` in different working directories at the same time causes collision of ephemeral directory that was moved from current dir to under /tmp.

# Root cause
Documented in https://github.com/metacloud/molecule/commit/cab17ea2e9f171bc38735c4bbc352663afe7aa6a.
Hence the ping @retr0h.

# Fix proposition
Revert ephemeral directory back into current working directory

# Additional details
Molecule is likely to be executed by CI like for example Jenkins. Multiple changes for the same role trigger PR validation. PR validation in parallel collides when you take ephemeral out from current working directory. Please put it back there.

**Comment by retr0h** [comment]
How does it break?  The files are placed inside the /tmp/molecule/$name_of_role/$name_of_scenario/.  How would that cause a problem.  This is effectively the same thing as it was before.

> Revert ephemeral directory back into current working directory

That isn't a possibility.

**Comment by suonto** [comment]
@retr0h when you say "Running multiple checkouts of the same role, and running the same scenario in parallel is not supported.", it was working perfectly until now. In my opinion that is a rather big price to pay for one line reduction in `.gitignore`. Or was there some other motivation to make testing of roles not be contained inside their working directory any longer?

Also, I read the source code for `MOLECULE_EPHEMERAL_DIRECTORY` and it only sets a **subpath** under global `/tmp ...`-prefix. Don't you think it would be simpler to give people the possibility to contain role testing within their working dir rather than enforcing writes to a global `/tmp`-prefixed collection of ephemeral files? In some extreme cases, /tmp might not be even available to the user executing molecule.

**Comment by retr0h** [comment]
> /tmp might not be even available to the user executing molecule.

Why wouldn't it?  Molecule isn't supported on Windows.

> In my opinion that is a rather big price to pay for one line reduction in .gitignore

That isn't why the change was made.  See #1218.

> Also, I read the source code for MOLECULE_EPHEMERAL_DIRECTORY and it only sets a subpath under global /tmp

Yes, so you are free to change to a subdir under /tmp and it will do what you wish.  It just needs to be unique.  Again, see #1218 for rationale.
