### ISSUE TITLE
ansible parameters break test action

### ISSUE THREAD

**Issue by loomsen** [metacloud/molecule#1287]
# Issue type

- Bug report

# Molecule and Ansible details

```
ansible 2.5.2
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/home/user/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /home/user/python-venv/ansible-2.5.2/lib/python2.7/site-packages/ansible
  executable location = /home/user/python-venv/ansible-2.5.2/bin/ansible
  python version = 2.7.14 (default, Mar 14 2018, 16:45:33) [GCC 8.0.1 20180222 (Red Hat 8.0.1-0.16)]
```

```
molecule, version 2.13.1
```

Molecule installation method (one of):

- pip

Ansible installation method (one of):

- pip

# Desired Behavior

Provide command line parameters to ansible for the test action. This is somehow related to #1286, but not directly.

So, with the converge command, this works:
```
molecule converge -s virtualbox -- --vault-id @"$HOME"/playground/vault-pw.txt
```

For automated testing, it would be great if this would work for the test subcommand as well.

# Actual Behaviour (Bug report only)

When I try and pass the ansible params to the test subcommand, it doesn't:
```
$ molecule test -s virtualbox -- --vault-id @"$HOME"/playground/vault-pw.txt
Usage: molecule test [OPTIONS]

Error: Got unexpected extra arguments (--vault-id @/home/nvarz/playground/vault-pw.txt)
```

**Comment by retr0h** [comment]
Looks like the following works.

`molecule converge -s virtualbox -- --vault-id @"$HOME"/playground/vault-pw.txt`

However, this ticket is about having this work via `molecule test`, correct?

**Comment by loomsen** [comment]
Correct. It does work with converge, but not with test. I will try your suggested solution and report back. 
Thank you for your great work!

**Comment by retr0h** [comment]
@loomsen any luck?
