### ISSUE TITLE
stat reports file does not exist

### ISSUE THREAD

**Issue by treblesome** [metacloud/molecule#1288]
# Issue Type

- Bug report
[root]snaxl96/> ansible snaxl94 -m copy -a "src=/tmp/snaxl96.f1 dest=/tmp/"
snaxl94 | FAILED! => {
    "msg": "module (copy) is missing interpreter line"
}

With -vvv:
<snaxl94> (0, '\r\n{"invocation": {"module_args": {"checksum_algorithm": "sha1", "get_checksum": true, "path": "/tmp/snaxl96.f1", "checksum_algo": "sha1", "follow": false, "get_md5": false, "get_mime": true, "get_attributes": true}}, **"stat": {"exists": false},** "changed": false}\r\n', 'Shared connection to snaxl94 closed.\r\n')

# Molecule and Ansible details
[root]snaxl96/> ansible --version
ansible 2.4.2.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /opt/freeware/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.13 (default, Oct 17 2017, 05:37:56) [C]

molecule --version
N/A

Ansible installation method (one of):
- source

# Desired Behavior
**Sanity Check:**
[root]snaxl96/> ansible aixnonprod -m ping
snaxl94 | SUCCESS => {
    "changed": false,
    "ping": "pong"
}
snaxl95 | SUCCESS => {
    "changed": false,
    "ping": "pong"
}

[root]snaxl96/>ansible aixnonprod -m copy -a "src=/tmp/snaxl96.f1 dest=/tmp/"
snaxl94 | FAILED! => {
    "msg": "module (copy) is missing interpreter line"
}
snaxl95 | SUCCESS => {
    "changed": false,
    "checksum": "5d3b1b2104a778ce68a788672b8cdcd8013d7540",
    "gid": 0,
    "group": "system",
    "mode": "0644",
    "owner": "root",
    "path": "/tmp/snaxl96.f1",
    "size": 21,
    "state": "file",
    "uid": 0
}

# Actual Behaviour (Bug report only)
[root]snaxl96/> ansible -vvv snaxl94 -m copy -a "src=/tmp/snaxl96.f1 dest=/tm>
ansible 2.4.2.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /opt/freeware/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.13 (default, Oct 17 2017, 05:37:56) [C]
Using /etc/ansible/ansible.cfg as config file
Parsed /etc/ansible/hosts inventory source with ini plugin
META: ran handlers
<snaxl94> ESTABLISH SSH CONNECTION FOR USER: None
<snaxl94> SSH: EXEC ssh -C -o ControlMaster=auto -o ControlPersist=60s -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o ConnectTimeout=10 -o ControlPath=/.ansible/cp/25e7a432a7 snaxl94 '/bin/sh -c '"'"'echo ~ && sleep 0'"'"''
<snaxl94> (0, '/root\n', '')
<snaxl94> ESTABLISH SSH CONNECTION FOR USER: None
<snaxl94> SSH: EXEC ssh -C -o ControlMaster=auto -o ControlPersist=60s -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o ConnectTimeout=10 -o ControlPath=/.ansible/cp/25e7a432a7 snaxl94 '/bin/sh -c '"'"'( umask 77 && mkdir -p "` echo /root/.ansible/tmp/ansible-tmp-1525812633.67-280557380256783 `" && echo ansible-tmp-1525812633.67-280557380256783="` echo /root/.ansible/tmp/ansible-tmp-1525812633.67-280557380256783 `" ) && sleep 0'"'"''
<snaxl94> (0, 'ansible-tmp-1525812633.67-280557380256783=/root/.ansible/tmp/ansible-tmp-1525812633.67-280557380256783\n', '')
Using module file /opt/freeware/lib/python2.7/site-packages/ansible/modules/files/stat.py
<snaxl94> PUT /tmp/tmpzqGWmd TO /root/.ansible/tmp/ansible-tmp-1525812633.67-280557380256783/stat.py
<snaxl94> SSH: EXEC sftp -b - -C -o ControlMaster=auto -o ControlPersist=60s -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o ConnectTimeout=10 -o ControlPath=/.ansible/cp/25e7a432a7 '[snaxl94]'
<snaxl94> (0, 'sftp> put /tmp/tmpzqGWmd /root/.ansible/tmp/ansible-tmp-1525812633.67-280557380256783/stat.py\nUploading /tmp/tmpzqGWmd to /root/.ansible/tmp/ansible-tmp-1525812633.67-280557380256783/stat.py\n', '')
<snaxl94> ESTABLISH SSH CONNECTION FOR USER: None
<snaxl94> SSH: EXEC ssh -C -o ControlMaster=auto -o ControlPersist=60s -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o ConnectTimeout=10 -o ControlPath=/.ansible/cp/25e7a432a7 snaxl94 '/bin/sh -c '"'"'chmod u+x /root/.ansible/tmp/ansible-tmp-1525812633.67-280557380256783/ /root/.ansible/tmp/ansible-tmp-1525812633.67-280557380256783/stat.py && sleep 0'"'"''
<snaxl94> (0, '', '')
<snaxl94> ESTABLISH SSH CONNECTION FOR USER: None
<snaxl94> SSH: EXEC ssh -C -o ControlMaster=auto -o ControlPersist=60s -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o ConnectTimeout=10 -o ControlPath=/.ansible/cp/25e7a432a7 -tt snaxl94 '/bin/sh -c '"'"'/usr/bin/python /root/.ansible/tmp/ansible-tmp-1525812633.67-280557380256783/stat.py && sleep 0'"'"''
<snaxl94> (0, '\r\n{"invocation": {"module_args": {"checksum_algorithm": "sha1", "get_checksum": true, "path": "/tmp/snaxl96.f1", "checksum_algo": "sha1", "follow": false, "get_md5": false, "get_mime": true, "get_attributes": true}}, **"stat": {"exists": false},** "changed": false}\r\n', 'Shared connection to snaxl94 closed.\r\n')
<snaxl94> PUT /tmp/snaxl96.f1 TO /root/.ansible/tmp/ansible-tmp-1525812633.67-280557380256783/source
<snaxl94> SSH: EXEC sftp -b - -C -o ControlMaster=auto -o ControlPersist=60s -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o ConnectTimeout=10 -o ControlPath=/.ansible/cp/25e7a432a7 '[snaxl94]'
<snaxl94> (0, 'sftp> put /tmp/snaxl96.f1 /root/.ansible/tmp/ansible-tmp-1525812633.67-280557380256783/source\nUploading /tmp/snaxl96.f1 to /root/.ansible/tmp/ansible-tmp-1525812633.67-280557380256783/source\n', '')
<snaxl94> ESTABLISH SSH CONNECTION FOR USER: None
<snaxl94> SSH: EXEC ssh -C -o ControlMaster=auto -o ControlPersist=60s -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o ConnectTimeout=10 -o ControlPath=/.ansible/cp/25e7a432a7 snaxl94 '/bin/sh -c '"'"'chmod u+x /root/.ansible/tmp/ansible-tmp-1525812633.67-280557380256783/ /root/.ansible/tmp/ansible-tmp-1525812633.67-280557380256783/source && sleep 0'"'"''
<snaxl94> (0, '', '')
Using module file /opt/freeware/lib/python2.7/site-packages/ansible/modules/files/copy.mod
snaxl94 | FAILED! => {
    "msg": "module (copy) is missing interpreter line"
}

[root]snaxl96/> ls -al /tmp/snaxl96.f1
-rw-r--r--    1 root     system           21 May  1 14:41 /tmp/snaxl96.f1

**Compared to the other remote host, the copy works perfectly:**

[root]snaxl96/> ansible -vvv snaxl95 -m copy -a "src=/tmp/snaxl96.f1 dest=/tm>
ansible 2.4.2.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /opt/freeware/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.13 (default, Oct 17 2017, 05:37:56) [C]
Using /etc/ansible/ansible.cfg as config file
Parsed /etc/ansible/hosts inventory source with ini plugin
META: ran handlers
<snaxl95> ESTABLISH SSH CONNECTION FOR USER: None
<snaxl95> SSH: EXEC ssh -C -o ControlMaster=auto -o ControlPersist=60s -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o ConnectTimeout=10 -o ControlPath=/.ansible/cp/73a6d1ca54 snaxl95 '/bin/sh -c '"'"'echo ~ && sleep 0'"'"''
<snaxl95> (0, '/root\n', '')
<snaxl95> ESTABLISH SSH CONNECTION FOR USER: None
<snaxl95> SSH: EXEC ssh -C -o ControlMaster=auto -o ControlPersist=60s -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o ConnectTimeout=10 -o ControlPath=/.ansible/cp/73a6d1ca54 snaxl95 '/bin/sh -c '"'"'( umask 77 && mkdir -p "` echo /root/.ansible/tmp/ansible-tmp-1525812868.44-12315645995874 `" && echo ansible-tmp-1525812868.44-12315645995874="` echo /root/.ansible/tmp/ansible-tmp-1525812868.44-12315645995874 `" ) && sleep 0'"'"''
<snaxl95> (0, 'ansible-tmp-1525812868.44-12315645995874=/root/.ansible/tmp/ansible-tmp-1525812868.44-12315645995874\n', '')
Using module file /opt/freeware/lib/python2.7/site-packages/ansible/modules/files/stat.py
<snaxl95> PUT /tmp/tmpFhvJB4 TO /root/.ansible/tmp/ansible-tmp-1525812868.44-12315645995874/stat.py
<snaxl95> SSH: EXEC sftp -b - -C -o ControlMaster=auto -o ControlPersist=60s -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o ConnectTimeout=10 -o ControlPath=/.ansible/cp/73a6d1ca54 '[snaxl95]'
<snaxl95> (0, 'sftp> put /tmp/tmpFhvJB4 /root/.ansible/tmp/ansible-tmp-1525812868.44-12315645995874/stat.py\nUploading /tmp/tmpFhvJB4 to /root/.ansible/tmp/ansible-tmp-1525812868.44-12315645995874/stat.py\n', '')
<snaxl95> ESTABLISH SSH CONNECTION FOR USER: None
<snaxl95> SSH: EXEC ssh -C -o ControlMaster=auto -o ControlPersist=60s -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o ConnectTimeout=10 -o ControlPath=/.ansible/cp/73a6d1ca54 snaxl95 '/bin/sh -c '"'"'chmod u+x /root/.ansible/tmp/ansible-tmp-1525812868.44-12315645995874/ /root/.ansible/tmp/ansible-tmp-1525812868.44-12315645995874/stat.py && sleep 0'"'"''
<snaxl95> (0, '', '')
<snaxl95> ESTABLISH SSH CONNECTION FOR USER: None
<snaxl95> SSH: EXEC ssh -C -o ControlMaster=auto -o ControlPersist=60s -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o ConnectTimeout=10 -o ControlPath=/.ansible/cp/73a6d1ca54 -tt snaxl95 '/bin/sh -c '"'"'/usr/bin/python /root/.ansible/tmp/ansible-tmp-1525812868.44-12315645995874/stat.py && sleep 0'"'"''
<snaxl95> (0, '\r\n{"invocation": {"module_args": {"checksum_algorithm": "sha1", "get_checksum": true, "path": "/tmp/snaxl96.f1", "checksum_algo": "sha1", "follow": false, "get_md5": false, "get_mime": true, "get_attributes": true}}, "stat": {"charset": "unknown", "uid": 0, "exists": true, "attr_flags": "", "generation": -979456329, "woth": false, "isreg": true, "device_type": 0, "mtime": 1525790207.0, "block_size": 4096, "inode": 10, "isgid": false, "size": 21, "executable": true, "isuid": false, "readable": true, "version": null, "pw_name": "root", "gid": 0, "ischr": false, "wusr": true, "writeable": true, "mimetype": "unknown", "blocks": 8, "xoth": false, "islnk": false, "nlink": 1, "issock": false, "rgrp": true, "gr_name": "system", "path": "/tmp/snaxl96.f1", "xusr": false, "atime": 1525812533.0, "isdir": false, "ctime": 1525790208.0, "isblk": false, "wgrp": false, "checksum": "5d3b1b2104a778ce68a788672b8cdcd8013d7540", "dev": 655367, "roth": true, "isfifo": false, "mode": "0644", "xgrp": false, "rusr": true, "attributes": []}, "changed": false}\r\n', 'Shared connection to snaxl95 closed.\r\n')
Using module file /opt/freeware/lib/python2.7/site-packages/ansible/modules/files/file.py
<snaxl95> PUT /tmp/tmpeYLhIg TO /root/.ansible/tmp/ansible-tmp-1525812868.44-12315645995874/file.py
<snaxl95> SSH: EXEC sftp -b - -C -o ControlMaster=auto -o ControlPersist=60s -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o ConnectTimeout=10 -o ControlPath=/.ansible/cp/73a6d1ca54 '[snaxl95]'
<snaxl95> (0, 'sftp> put /tmp/tmpeYLhIg /root/.ansible/tmp/ansible-tmp-1525812868.44-12315645995874/file.py\nUploading /tmp/tmpeYLhIg to /root/.ansible/tmp/ansible-tmp-1525812868.44-12315645995874/file.py\n', '')
<snaxl95> ESTABLISH SSH CONNECTION FOR USER: None
<snaxl95> SSH: EXEC ssh -C -o ControlMaster=auto -o ControlPersist=60s -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o ConnectTimeout=10 -o ControlPath=/.ansible/cp/73a6d1ca54 snaxl95 '/bin/sh -c '"'"'chmod u+x /root/.ansible/tmp/ansible-tmp-1525812868.44-12315645995874/ /root/.ansible/tmp/ansible-tmp-1525812868.44-12315645995874/file.py && sleep 0'"'"''
<snaxl95> (0, '', '')
<snaxl95> ESTABLISH SSH CONNECTION FOR USER: None
<snaxl95> SSH: EXEC ssh -C -o ControlMaster=auto -o ControlPersist=60s -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o ConnectTimeout=10 -o ControlPath=/.ansible/cp/73a6d1ca54 -tt snaxl95 '/bin/sh -c '"'"'/usr/bin/python /root/.ansible/tmp/ansible-tmp-1525812868.44-12315645995874/file.py; rm -rf "/root/.ansible/tmp/ansible-tmp-1525812868.44-12315645995874/" > /dev/null 2>&1 && sleep 0'"'"''
<snaxl95> (0, '\r\n{"group": "system", "uid": 0, "changed": false, "owner": "root", "state": "file", "gid": 0, "mode": "0644", "path": "/tmp/snaxl96.f1", "invocation": {"module_args": {"directory_mode": null, "force": false, "remote_src": null, "path": "/tmp/snaxl96.f1", "owner": null, "follow": false, "group": null, "unsafe_writes": null, "state": "file", "content": null, "serole": null, "diff_peek": null, "setype": null, "dest": "/tmp/", "selevel": null, "original_basename": "snaxl96.f1", "regexp": null, "validate": null, "src": "snaxl96.f1", "seuser": null, "recurse": false, "delimiter": null, "mode": null, "attributes": null, "backup": null}}, "diff": {"after": {"path": "/tmp/snaxl96.f1"}, "before": {"path": "/tmp/snaxl96.f1"}}, "size": 21}\r\n', 'Shared connection to snaxl95 closed.\r\n')
snaxl95 | SUCCESS => {
    "changed": false,
    "checksum": "5d3b1b2104a778ce68a788672b8cdcd8013d7540",
    "diff": {
        "after": {
            "path": "/tmp/snaxl96.f1"
        },
        "before": {
            "path": "/tmp/snaxl96.f1"
        }
    },
    "gid": 0,
    "group": "system",
    "invocation": {
        "module_args": {
            "attributes": null,
            "backup": null,
            "content": null,
            "delimiter": null,
            "dest": "/tmp/",
            "diff_peek": null,
            "directory_mode": null,
            "follow": false,
            "force": false,
            "group": null,
            "mode": null,
            "original_basename": "snaxl96.f1",
            "owner": null,
            "path": "/tmp/snaxl96.f1",
            "recurse": false,
            "regexp": null,
            "remote_src": null,
            "selevel": null,
            "serole": null,
            "setype": null,
            "seuser": null,
            "src": "snaxl96.f1",
            "state": "file",
            "unsafe_writes": null,
            "validate": null
        }
    },
    "mode": "0644",
    "owner": "root",
    "path": "/tmp/snaxl96.f1",
    "size": 21,
    "state": "file",
    "uid": 0
}
META: ran handlers
META: ran handlers

aixnonprod:
root@snaxl94 / # python  -V
Python 2.7.13

root@dr-snaxl95 / # python -V
Python 2.7.13

**Comment by retr0h** [comment]
Has nothing to do with molecule.

**Comment by treblesome** [comment]
Oh geez ya thanks very much...what was I thinking.  Never mind the fact that this was my first post and still trying to navigate the github maze list
and ansible innards and I got a “has nothing to do”....serves me right.  Sorry to waste your time.

Don’t bother to feel sorry...I’ve already blacklisted you and any metacloud/molecule strings.
