### ISSUE TITLE
Logging output - need a middle ground between 'no_log' and 'full debug'

### ISSUE THREAD

**Issue by zswanson** [metacloud/molecule#1289]
# Issue Type

Feature request

# Molecule and Ansible details

```
ansible 2.5.2
molecule, version 2.13.1
```

Molecule installation method (one of):
- pip

Ansible installation method (one of):
- pip

# Desired Behavior

Currently the output options for Molecule are:
- No error logging (tasks that fail show a message indicating logging is disabled)
- enable --debug and get full debug output for every action Molecule takes

The former isn't helpful at all when you're trying to establish new testing environments or new providers. The latter is too much information when all I need to see is the error output from vagrant/libvirt/etc that might say something like "user is not in the vboxusers group" and is difficult to parse through. 

Example:

     PLAY [Create] ******************************************************************

    TASK [Log into a Docker registry] **********************************************
    skipping: [localhost] => (item=None)

    TASK [Create Dockerfiles from image names] *************************************
    failed: [localhost] (item=None) => {"censored": "the output has been hidden due to the fact that 'no_log: true' was specified for this result", "changed": false}

    PLAY RECAP *********************************************************************
    localhost                  : ok=0    changed=0    unreachable=0    failed=1

It would be much more helpful if the default output of Molecule included the actual stderr or failure messages. With the --debug off, anytime there's a failure I'm left with 0 information about the issue. With it on, there's a flood of debug info mostly about the internal state of molecule, when the root issue has (so far) been with the external providers or the operating environment or the role itself.

**Comment by retr0h** [comment]
Unfortunately this is the way we have developed Molecule.  Not something I'm looking to change.  However, you are free to maintain your own create/destroy playbooks that have no_log set to true, so it looks the way you like.
