### ISSUE TITLE
Using docker.py for having Dynamic inventories in molecule

### ISSUE THREAD

**Issue by scampuza** [metacloud/molecule#1293]
# Issue Type

- Feature request

# Molecule and Ansible details

```
ansible 2.5.2

```

```
molecule 2.13
```

Molecule installation method (one of):

- pip

Ansible installation method (one of):

- pip

# Desired Behavior

Trying to retrieve some group_vars and host_vars inside an Ansible Role

zookeeper_servers:
  - "{{ hostvars[groups['docker-zookeeper'][0]].docker_network_settings.IPAddress }}"
  - "{{ hostvars[groups['docker-zookeeper'][1]].docker_network_settings.IPAddress }}"
  - "{{ hostvars[groups['docker-zookeeper'][2]].docker_network_settings.IPAddress }}"

zookeeper_myid: "{{ docker_network_settings.IPAddress.replace('.', '') }}"

Is giving me the following errors:

    TASK [ansible-role-zookeeper : Setup the myid file with the last digit of the Ip address] ***
    fatal: [ubuntu_xenial0065fccae7c9b5901ed72d1987a498920c71c09e]: FAILED! => {"changed": false, "msg": "AnsibleUndefinedVariable: 'docker_network_settings' is undefined"}
    fatal: [ubuntu_trusty0065fccae7c9b5901ed72d1987a498920c71c09e]: FAILED! => {"changed": false, "msg": "AnsibleUndefinedVariable: 'docker_network_settings' is undefined"}

That docker_network_settings variable/fact should be returned by the docker.py Dynamic inventory plugin.  

I have this configuration in molecule.yml for having a pre defined inventory with group vars:

provisioner:
  name: ansible
  config_options:
    defaults:
      vault_password_file: ${PWD}/molecule/resources/.vault
  inventory:
    links:
      group_vars: ../inventory/group_vars/

So, the question is, where is supposed to be the docker.py and docker.ini  which is the official Ansible Dynamic inventory for Docker.... ?

Following is the link to official Ansible Dynamic Inventory script.....

https://github.com/ansible/ansible/blob/devel/contrib/inventory/docker.py

I would appreciate any help with this... let me know if you need further info !

Thanks so much !

# Actual Behaviour (Bug report only)

Please give some details of what is actually happening.
Include a [minimum complete verifiable example](http://stackoverflow.com/help/mcve) with
output of running `molecule --debug`.

**Comment by retr0h** [comment]
Could it be your container needs iproute?  Does this help #836 ?

**Comment by scampuza** [comment]
@retr0h .... thanks for the promptly help... I think that could be my issue... do you know how to install that module to the Container ? I mean.. my containers are both Ubuntu 16 and 14...  is it a apt-get install package ???

Thanks !
