### ISSUE TITLE
tests discover

### ISSUE THREAD

**Issue by pawelkopka** [metacloud/molecule#1294]
# Issue Type

- Feature request

# Molecule and Ansible details

```
ansible 2.5.2
```

```
molecule 2.13
```

Molecule installation method (one of):

- source
- pip

Ansible installation method (one of):

- source
- pip
- OS package

# Desired Behavior

Run molecule test, will find all molecule in dir tree, like for unittest discover

```
molecule test --discover
```

**Comment by retr0h** [comment]
Hi @pawelkopka, unfortunately this is not something we will be adding.

**Comment by retr0h** [comment]
`Molecule verify` runs your tests.  Is that what you were asking about?
