### ISSUE TITLE
Example config molecule with ec2 driver

### ISSUE THREAD

**Issue by wissemmahjoub** [metacloud/molecule#1299]
Hello,
I don't found a good example to use molecule with ec2 driver, ( step by step)
Thank you

**Comment by retr0h** [comment]
There is no ec2 step by step instructions.  However, the playbooks molecule creates when selecting the ec2 driver should get you going.  You will need to populate the playbooks properly, but I don't plan to create ec2 instructions, since thats fairly specialized, and is a more advanced topic.
