### ISSUE TITLE
Validating schema fails: {'verifier': [{'lint': [{'name': ['unallowed value flake8']}]}]}

### ISSUE THREAD

**Issue by robertdebock** [metacloud/molecule#1300]
# Issue Type
- Bug report

# Molecule and Ansible details

```
ansible --version
ansible 2.5.2
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/home/robertdb/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.15 (default, May  2 2018, 14:12:52) [GCC 8.0.1 20180324 (Red Hat 8.0.1-0.20)]
```

```
molecule --version
molecule, version 2.14.0
```

Molecule installation method (one of):
- pip

Ansible installation method (one of):
- pip

# Desired Behavior
Builds run successful.

# Actual Behaviour (Bug report only)
Since the [latest release of molecule](https://github.com/metacloud/molecule/releases/tag/2.14) I'm seeing this error:
```
--> Validating schema /home/travis/build/robertdebock/ansible-role-postfix/molecule/debian-buster/molecule.yml.
ERROR: Failed to validate.
{'verifier': [{'lint': [{'name': ['unallowed value flake8']}]}]}
```

The [code on GitHub](https://github.com/robertdebock/ansible-role-postfix) and [build on Travis](https://travis-ci.org/robertdebock/ansible-role-postfix/jobs/379845418) related.

I don't really understand what's happening and what should be changed, please help.

Thanks!

**Comment by robertdebock** [comment]
I think I found a way to work with this issue:

Add a lint: name: under the goss section, like so:
```
verifier:
  name: goss
  lint:
    name: yamllint
```

Still I don't understand the initial error about flake8, I guess there is a default set in molecule somewhere that's invalid.

The [documentation](http://molecule.readthedocs.io/en/latest/configuration.html#goss) also does not mention that setting a linter for goss is required.

**Comment by retr0h** [comment]
Hi @robertdebock Molecule 2.14 introduced a Goss linter.  Previously, when someone selected the Goss verifier, flake8 was populated in the lint section as disabled.  This really didn't make any sense, since flake8 was specific to testinfra (python).

Molecule's schema validator did the correct thing, but I understand it was confusing, and a new change.  I am however, glad you were able to fix the problem.
