### ISSUE TITLE
Port to using 'docker' instead of 'docker-py' pip module

### ISSUE THREAD

**Issue by samiam** [metacloud/molecule#1303]
# Issue Type

- Feature request

# Molecule and Ansible details

```
ansible 2.5.2
```

```
molecule.pex, version 2.13.1
```

Molecule installation method (one of):

- pip

Ansible installation method (one of):

- pip

# Desired Behavior

http://molecule.readthedocs.io/en/latest/configuration.html#docker

The docker module docs seem to imply you have to install 'docker-py'  in order for molecule to work.  

'docker-py' is deprecated and has been replaced by the 'docker' pip module.

I was wondering what porting effort is required to drop 'docker-py' and use 'docker' instead?

I use molecule in a pex bundle with ansible, molecule, etc.  I would prefer to include 'docker' instead of 'docker-py' in the pex bundle.  

Thoughts?

**Comment by retr0h** [comment]
Closing as not related to Molecule at this time.
