### ISSUE TITLE
Pre destroy step. 

### ISSUE THREAD

**Issue by freeseacher** [metacloud/molecule#1304]
After implementing all scheme i found that there are mission step.

Now i can download minio client during prepare step and fetch pkgs cache for VM. 
Two dirs actually /root/.cache/pip and /var/cache/apt/archives/ and the same for other oses. 
After converge or maybe even after verify there should be stage that will be executed on vm and should upload current cache if tis was changed back to minio server.

In my case i want to have var CACHE_ENABLED. 
Var will verify playbook with cache on each commit and without cache nightly or weekly or on release.

**Comment by retr0h** [comment]
I would say if you want a pre-destroy setp, this should be added to your destroy.yml.  As of now it feels very custom to your use case.  However, in the future if more people have this issue, we may look to add a pre-destroy.  However, if you need pre-destroy now, it should jsut go in your destroy.yml.

**Comment by freeseacher** [comment]
yep. i done it that way for now. just to looking up better solution not to mix stages with each other

**Comment by freeseacher** [comment]
But there are trouble with that approach. Cause destroy step cause to be unindempotent. 
If node was already destroyed second run will get 
`Failed to connect to the host via ssh: ssh: Could not resolve hostname noc_node_debian8: Name or service not known`

**Comment by retr0h** [comment]
I'm going to close this for now, but keep in mind we may want to evaluate this use case in the future.
