### ISSUE TITLE
Not working: Providing additional command line arguments to the ansible-playbook command

### ISSUE THREAD

**Issue by weand** [metacloud/molecule#1306]
# Issue Type

- Bug report

# Molecule and Ansible details

```
ansible --version
2.5.0
```

```
molecule --version
2.14
```

Molecule installation method (one of):
- pip

Ansible installation method (one of):
- pip

# Desired Behavior

Use ansible-playbook command line arguments via molecule command line arguments, like stated in [docu](http://molecule.readthedocs.io/en/latest/usage.html#converge).

# Actual Behaviour (Bug report only)

Additional ansible-playbook arguments can not be passed using command line arguments. [Docu](http://molecule.readthedocs.io/en/latest/usage.html#converge) states:

> Providing additional command line arguments to the ansible-playbook command. Use this option with care, as there is no sanitation or validation of input. Options passed on the CLI override options provided in provisioner’s options section of molecule.yml.
$ molecule converge – -vvv -tags foo,bar

Running something like this (e.g. use tags argument) results in 
```
Error: no such option: --tags
```

**Comment by retr0h** [comment]
This option is only available on the `converge` subcommand.

**Comment by retr0h** [comment]
I'm not sure if it's the cut and paste, but it works for me:

```
[jodewey:~/git/molecule_2/test/scenarios/driver/docker] [venv] master(+15/-14)+ ± molecule converge -- -vvv --tags foo,bar
--> Validating schema /Users/jodewey/git/molecule_2/test/scenarios/driver/docker/molecule/default/molecule.yml.
Validation completed successfully.
--> Validating schema /Users/jodewey/git/molecule_2/test/scenarios/driver/docker/molecule/multi-node/molecule.yml.
Validation completed successfully.
--> Test matrix

└── default
    ├── dependency
    ├── create
    ├── prepare
    └── converge

--> Scenario: 'default'
--> Action: 'dependency'
```

**Comment by weand** [comment]
Confirmed. With double dash its all working as expected. Thanks

**Comment by weand** [comment]
A lot of documentation is affected by this, just try CTRL-F with '–'. 
In case you want to fix the sphinx rendering see this answer: https://stackoverflow.com/a/15354148
