### ISSUE TITLE
Molecule_yml is undefined

### ISSUE THREAD

**Issue by AjG1tHub** [metacloud/molecule#1309]
# Issue Type

- Bug report

# Molecule and Ansible details

```
ansible 2.4.3.0
```

```
molecule, version 2.9.0
```

Molecule installation method (one of):

- pip

Ansible installation method (one of):

- pip

# Desired Behavior

Running the molecule creates and runs normally 

# Actual Behaviour (Bug report only)

```
    TASK [Log into a Docker registry] **********************************************
    task path: /Users/anthonyletizia/Documents/GitHub/ansible-role-base-java/molecule/default/create.yml:11
    fatal: [localhost]: FAILED! => {
        "msg": "'molecule_yml' is undefined"
    }

```
The create file has not been edited, and is the same as when used as molecule init, molecule destroy has the same error

**Comment by retr0h** [comment]
I suggest upgrading to newest version of molecule.  The version you are running is fairly old.
