### ISSUE TITLE
Regression: Interpolation not compatible with driver name

### ISSUE THREAD

**Issue by nbering** [metacloud/molecule#1310]
# Issue Type

- Bug report

# Molecule and Ansible details

```
ansible --version
ansible 2.4.3.0 (detached HEAD 8a7f9beab7) last updated 2018/03/21 16:06:26 (GMT -400)
  config file = None
  configured module search path = [u'/Users/nicholasbering/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /Users/nicholasbering/git/ansible/ansible/lib/ansible
  executable location = /Users/nicholasbering/git/ansible/ansible/bin/ansible
  python version = 2.7.15 (default, May  6 2018, 12:01:05) [GCC 4.2.1 Compatible Apple LLVM 9.1.0 (clang-902.0.39.1)]
```

```
molecule --version
molecule, version 2.14.0
```

Molecule installation method (one of):

- pip

Ansible installation method (one of):

- source

# Desired Behavior

I recently upgraded molecule from v2.10.1. I was using environment variable interpolation to select the driver, so that I wouldn't need to manipulate files in CI (where I was ec2 driver) and local (where I use Vagrant).

This was working fine, with the relevant molecul.yml portion looking like this:
```yml
driver:
  name: ${MOLECULE_DRIVER:-vagrant}
  provider:
    name: virtualbox
platforms:
  - name: instance
    # virtualbox stuff
    box: debian/jessie64
    # ec2 stuff
    instance_type: t2.micro
    vpc_subnet_id: ${VPC_SUBNET_ID}
    image: ${DEBIAN_AMI}
```

And a .envrc file with direnv looking this this, to override for EC2.

```
# General Molecule Settings
# export MOLECULE_DRIVER=vagrant
export MOLECULE_DRIVER=ec2

# AWS settings for EC2 driver
export AWS_REGION=ca-central-1
export AWS_PROFILE=default
export VPC_SUBNET_ID=subnet-xxxxxxxx
export DEBIAN_AMI=ami-a1fe43c5
```

This worked in v2.10.1.

# Actual Behaviour (Bug report only)

When I upgraded to v2.14.0, I received this error:

```
$ molecule test --all
Traceback (most recent call last):
  File "/usr/local/bin/molecule", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/molecule/command/test.py", line 113, in test
    base.get_configs(args, command_args), scenario_name)
  File "/usr/local/lib/python2.7/site-packages/molecule/command/base.py", line 120, in get_configs
    ) for c in glob.glob(MOLECULE_GLOB)
  File "/usr/local/lib/python2.7/site-packages/molecule/config.py", line 61, in __call__
    obj.after_init()
  File "/usr/local/lib/python2.7/site-packages/molecule/config.py", line 107, in after_init
    self.config = self._reget_config()
  File "/usr/local/lib/python2.7/site-packages/molecule/config.py", line 278, in _reget_config
    env = util.merge_dicts(os.environ.copy(), self.env)
  File "/usr/local/lib/python2.7/site-packages/molecule/config.py", line 186, in env
    'MOLECULE_INSTANCE_CONFIG': self.driver.instance_config,
  File "/usr/local/lib/python2.7/site-packages/molecule/util.py", line 307, in wrapper
    rv = function(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/molecule/config.py", line 170, in driver
    driver.name = driver_name
AttributeError: 'NoneType' object has no attribute 'name'
```

I traced that down to this function:

https://github.com/metacloud/molecule/blob/ffab458f10bb638106e9fa56431c37a575beee22/molecule/config.py#L145-L172

When I changed my interpolated string back to a plain literal, the error goes away.

```yml
driver:
  name: ec2
```

So my guess would be the it is not interpolating the value from the environment variable before using it in this function.

This used to work... so I'd think of it as a type of regression. However, I understand if this pattern is considered to be unsupported. It is quite convenient though, as it allows team members to use different drivers without changing any source-controlled files.

Either way... it would probably be ideal to raise a meaningful error as an `else` condition to that long `if...elif` chain. Other cases - like a simple typo - would also benefit from a better error.

**Comment by retr0h** [comment]
Yeah, this is actually a case where your environment variable name should not be named `MOLECULE_`.  If you name it something else it will continue to work.  It's a bit of a chicken and egg problem. 

In a recent release molecule took ownership of any variable named `MOLECULE_` in moleucle.yml so that variables molecule sets (e.g. MOLECULE_SCENARIO_DIRECTORY) could be referenced in `molecule.yml`.

I suggest using a different env var for the variable.  Too much inception going on.  I'll look into why the schema validator didn't catch this, b/c it should have seen a none value for driver and reported a scehma validation error.

Hope this answer helps.

**Comment by nbering** [comment]
Cool. I actually wondered about that a little when I saw the changelog entry about MOLECULE_ variables being special somehow. I'll try and some up with some other naming scheme, and try that out.

**Comment by nbering** [comment]
I've confirmed that using a variable without `MOLECULE_` in the name solves my problem.

In looking for an alternative variable prefix that shouldn't conflict with some other program, I found that "molecule" is a synonym for "unit". I always thought the name was appropriate, but I didn't quite get it until I saw them together in a list of words. 😃

**Comment by nbering** [comment]
Thanks!
