### ISSUE TITLE
Docker_host environmental variable

### ISSUE THREAD

**Issue by uberjew666** [metacloud/molecule#1312]
- Bug report
ansible --version 2.6.0
molecule --version 2.13, 2.13.1, 2.14

Molecule installation method (one of):
- pip

Ansible installation method (one of):
- source
- pip

# Desired Behavior
Before Molecule 2.13 onwards, I had set $DOCKER_HOST variable in my .bashrc. So I never had to explicitly state this in the molecule.yml
# Actual Behaviour (Bug report only)

Since 2.13 onwards, it doesn't seem to acknowledge it. I have to explicitly state this parameter in the Molecule.yml.

Please give some details of what is actually happening.
Include a [minimum complete verifiable example](http://stackoverflow.com/help/mcve) with
output of running `molecule --debug`.

**Comment by retr0h** [comment]
Does #1238 explain it ?

**Comment by uberjew666** [comment]
@retr0h 
Yes, this appears to be the fault.
How about changing the line to:
docker_host: "{{ item.item.docker_host | default(lookup('env', 'DOCKER_HOST') or 'unix://var/run/docker.sock') }}"?

**Comment by uberjew666** [comment]
@retr0h 
I've made the changes to both create.yml and destroy.yml and I can confirm it works as it did before.

**Comment by ju5t** [comment]
Oh wow, I spent hours digging around why everything Docker related in our CI was working apart from Molecule. This explains everything. 

For now we'll work around the issue by specifying docker_host in `molecule.yml`. This breaks our local tests unfortunately, as `DOCKER_HOST` differs from our CI.

It would be great if Molecule could support `DOCKER_HOST` again.

**Comment by uberjew666** [comment]
@ju5t I completely forgot to fix this and sort the pull request!
I'll give it done as soon as possible.

**Comment by ju5t** [comment]
Thanks! I hope it can be included into Molecule soon.
