### ISSUE TITLE
inspec should be run against instances, not on them.

### ISSUE THREAD

**Issue by brucellino** [metacloud/molecule#1319]
# Issue Type

- Feature request

# Desired Behavior

Inspec should be executed on the control machine - the same one that runs Ansible - _against_ the instances. _i.e._ 
`inspec exec -t {{ transport }}://{{ instance }}`

where `{{ transport }}` is the transport mechanism (ssh, local, docker, etc) and `{{ instance }}` is the instance.

The reason that this would represent a step forward are essentially that Inspec has a pretty big impact on the machine being tested. This is a case of the [observer effect](https://en.wikipedia.org/wiki/Observer_effect_(physics)). Instead of installing Inspec with it's attendant dependencies, the verifier should probe the instance to determine whether it is compliant with a profile.

I would like to discuss updating the way in which this verifier runs to address this.

**Comment by retr0h** [comment]
Closing as described above.  Thank you for the issue.

**Comment by jujugrrr** [comment]
hi @skhoroshavin, did you ever look into that?
It looks like if we can have molecule-inspec understand the ansible inventory file, we could use inspec docker and ssh transport at least. Then for everything else we fallback to the current ansible transport approach.

For docker/ssh transport we can implement passing an attribute file from verifier options.

For now a workaround is to pass ENV to the provisioner(as the inspec verifier never uses the verifier env). You can then retrieve them from the verify.yml and do something with it(like iterate though a list for remote profiles, or pass an input-file)

example:
molecule.yml:
```
provisioner:
  name: ansible
  env:
    INSPEC_INPUT_FILE: input.yml
```
verify.yml:
```
    - name: Execute Inspec tests
      command: "{{ inspec_bin }} exec {{ item }} --chef-license=accept --input-file={{ lookup('env','MOLECULE_VERIFIER_TEST_DIRECTORY') }}/{{ lookup('env','INSPEC_INPUT_FILE') }}"
      register: test_results
      with_items: "{{ test_files.stdout_lines }}"
      ignore_errors: true
```
