### ISSUE TITLE
Adding links value in molecule.yml breaks converging 

### ISSUE THREAD

**Issue by ruimoreira** [metacloud/molecule#1326]
# Issue Type

- Bug report

# Molecule and Ansible details

```
ansible 2.5.3

```

```
molecule --version
molecule, version 2.14.0
```

Molecule installation method (one of):

- pip

Ansible installation method (one of):

- pip

# Desired Behavior

Adding links works as expected 

inventory:
  links:
    group_vars: "../../../../group_vars/"

# Actual Behaviour (Bug report only)

instead molecule breaks 

--> Scenario: 'default'
--> Action: 'converge'

    PLAY [Converge] ****************************************************************

    TASK [Gathering Facts] *********************************************************
    fatal: [instance]: UNREACHABLE! => {"changed": false, "msg": "Failed to connect to the host via ssh: Warning: Permanently added '[127.0.0.1]:2222' (ECDSA) to the list of known hosts.\r\nno such identity: /Users/ru.moreira/.ssh/wsclnx-dev.pem: No such file or directory\r\nPermission denied (publickey,gssapi-keyex,gssapi-with-mic).\r\n", "unreachable": true}

    PLAY RECAP *********************************************************************
    instance                   : ok=0    changed=0    unreachable=1    failed=0

**Comment by ruimoreira** [comment]
Of course, removing those lines from molecule.yml brings the whole thing back to a working state.

**Comment by retr0h** [comment]
So we test this very [scenario](https://github.com/metacloud/molecule/tree/master/test/scenarios/host_group_vars/molecule/links).  I cannot reproduce this error.  Also, this was corrected in #1252, where the link is relative to the scenario directory.

**Comment by retr0h** [comment]
I see.  This can be reproduced when using Vagrant driver.

**Comment by retr0h** [comment]
Cannot reproduce
