### ISSUE TITLE
How to use --base-config correctly?

### ISSUE THREAD

**Issue by slickvoodoo** [metacloud/molecule#1328]
# Issue Type

- Question / Bug Report

# Molecule and Ansible details

```
ansible 2.5.4
```

```
molecule, version 2.14.0
```

Molecule installation method (one of):

- pip

Ansible installation method (one of):

- pip

# Desired Behavior

I am trying to configure base settings for Molecule. It will not honor settings I put in a separate file (and give the path with -c or --base-config) or ~/.config/molecule/config.yml.

Example base-config file (just testing one setting):
```
---
platforms:
  - force: false
```

In my scenario molecule.yml I am intentionally leaving out 'force'.

# Actual Behaviour (Bug report only)

In debug output under task '[Build an Ansible compatible image]', in module_args I see that force is still set to True:
`"force": true`

**Comment by slickvoodoo** [comment]
Also I should specify I am using the __create__ command

**Comment by slickvoodoo** [comment]
thanks, is there any docs on what I can and can't use in base config?

**Comment by retr0h** [comment]
You should be good with anything that isn't a list.  Molecule reads the base config first, so if you have a list in your molecule.yml, that will clobber what was originally loaded in the base config.  I hope this helps.  Thanks for also taking the time to submit an issue.  My apologies you ran into trouble. :(

**Comment by tace** [comment]
using 2.19 molecule. 
In addition to platform section it seem I have to define also
provisioner:
  name: ansible

in the role's molecule.yml and it's repeated in base.yml 
provisioner:
  name: ansible
  log: true

But attributes in base.yml (like log:true above) does not get into affect.
