### ISSUE TITLE
Custom inventory file

### ISSUE THREAD

**Issue by Manouchka94** [metacloud/molecule#1333]
# Issue Type

- Feature request

# Molecule and Ansible details

```
ansible --version
ansible 2.4.2.0
```

```
molecule --version
molecule, version 2.15.0
```

Molecule installation method (one of):

- pip

Ansible installation method (one of):

- pip

# Desired Behavior

Hello,

I try to use molecule with an existing inventory file.

In this post you explain how to set this option in molecule.yml.
https://github.com/metacloud/molecule/issues/598

However, this option is not actually available for the 2.15.0 version of molecule.

I found a way to use the inventory_file option in delegated mode without regression.
Is this feature could be integrated in molecule or it will be not supported ?

**Comment by retr0h** [comment]
What was discussed in #598 really isn't something Molecule supports.  I provided a work-a-round off the top of my head.  However, it may or may not work.  What was requested in #598 isn't supported.
