### ISSUE TITLE
[feature] add command for "print test matrix on stdout"

### ISSUE THREAD

**Issue by HalisCz** [metacloud/molecule#1337]
# Issue Type

- Feature request

# Molecule and Ansible details

```
# ansible --version
ansible 2.5.4
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/home/halis/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /home/halis/.virtualenvs/molecule/lib/python2.7/site-packages/ansible
  executable location = /home/halis/.virtualenvs/molecule/bin/ansible
  python version = 2.7.15 (default, May 16 2018, 17:50:09) [GCC 8.1.1 20180502 (Red Hat 8.1.1-1)]
```

```
# molecule --version
2.15.0
```

Molecule installation method:

- pip

Ansible installation method (one of):

- pip

# Desired Behavior

Purpose is to provide command to **print test matrix on stdout**

Would be nice to provide command for showing "test matrix" to check what steps will be taken. It could be something like `molecule matrix` or `molecule matrix -s non-default-scenario`. Output can be something like (this one is visible by running `molecule test --help` above options):
```
lint, destroy, dependency, syntax, create, prepare, converge, idempotence, side_effect, verify, destroy
```
or
```
--> Test matrix
    
└── default
    ├── lint
    ├── destroy
    ├── dependency
    ├── syntax
    ├── create
    ├── prepare
    ├── converge
    ├── idempotence
    ├── side_effect
    ├── verify
    └── destroy
```
or it could be both, distinguished by `--brief` or something.

What do you think?

# Actual Behaviour (Bug report only)

**Comment by retr0h** [comment]
Hi @HalisCz thanks for your feature request.  At this time it isn't something we are going to implement.  If one wishes to see the matrix then could run `molecule converge` which displays it.  I know that is not ideal, but at this time it isn't a feature we wish to add.  However, if others do find this useful we can revisit.  Hope you understand.

**Comment by retr0h** [comment]
Hi @HalisCz can you provide details as to why you want this information, so that I can understand why it would be useful to you?

**Comment by HalisCz** [comment]
Of course:

I am rewriting some ansible roles to include molecule tests and configuration. During it, I don't want to loose debugging time by repeatedly recreate virtual instances and destroying them.

My prefered workflow would be:

1. Get list of test matrix (hence this feature request) to know **what steps will be taken and what is their order** 
1. Try step 1 (i.e. `molecule lint`), try to fix all the stuff, repeat for certainty until there are no errors
1. Try step 2 (i.e. `molecule destroy`), try to fix all the stuff, repeat for certainty
1. ... and so on.
