### ISSUE TITLE
pip install docker OR docker-py ? 

### ISSUE THREAD

**Issue by rgarrigue** [metacloud/molecule#1347]
# Issue Type

- Bug report

# Molecule and Ansible details

No need it's about the doc

# Desired Behavior

I see in the changelog this entry

> 1.21
> 
> ...
> 
> Breaking Changes
> 
>     The docker-py pip package has been deprecated in favor of docker.

But the doc and the generated INSTALL.rst say `pip install docker-py`.  Which sdk is the good one ?

**Comment by dhoppeIT** [comment]
This is an interesting question and would require a change of my pull request:
https://github.com/Homebrew/homebrew-core/pull/29280

**Comment by retr0h** [comment]
You're looking at the 1.x release history.  2.x was completely rewritten.

**Comment by retr0h** [comment]
> But the doc and the generated INSTALL.rst say pip install docker-py. Which sdk is the good one ?

Use what the docs say :)

**Comment by rgarrigue** [comment]
Thanks
