### ISSUE TITLE
Change the default callback

### ISSUE THREAD

**Issue by dhoppeIT** [metacloud/molecule#1349]
# Issue Type

- Feature request

# Molecule and Ansible details

```
ansible 2.5.5
  config file = None
  configured module search path = [u'/Users/dhoppe/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /Users/dhoppe/.virtualenvs/molecule/lib/python2.7/site-packages/ansible
  executable location = /Users/dhoppe/.virtualenvs/molecule/bin/ansible
  python version = 2.7.15 (default, Jun 17 2018, 12:46:58) [GCC 4.2.1 Compatible Apple LLVM 9.1.0 (clang-902.0.39.2)]
```

```
molecule, version 2.15.0
```

Molecule installation method (one of):

- pip

Ansible installation method (one of):

- pip

# Desired Behavior

I think it would be useful to add the following lines by default to the molecule.yml file because it makes the output of Ansible much easier to read (json vs yaml).

```
diff --git a/molecule/default/molecule.yml b/molecule/default/molecule.yml
index ec8a2bd..20fafbc 100644
--- a/molecule/default/molecule.yml
+++ b/molecule/default/molecule.yml
@@ -10,6 +10,10 @@ platforms:
     image: centos:7
 provisioner:
   name: ansible
+  config_options:
+    defaults:
+      stdout_callback: yaml
+      bin_ansible_callbacks: true
   lint:
     name: ansible-lint
 scenario:
```

JSON output:
```
    TASK [ansible-ssh : start service] **************************************
    fatal: [instance]: FAILED! => {"changed": false, "msg": "Could not find the requested service ssh: host"}
```

YAML output:
```
    TASK [ansible-ssh : start service] **************************************
    fatal: [instance]: FAILED! => changed=false
      msg: 'Could not find the requested service ssh: host'
```

**Comment by kdask** [comment]
Looks like yaml callback was introduced in 2.5 (https://docs.ansible.com/ansible/2.5/plugins/callback/yaml.html) and a lot of people still use 2.4.

**Comment by retr0h** [comment]
Ya, unfortunately this is not a backward compatible change for others.  We support 2.2 and forward.

**Comment by retr0h** [comment]
I should think about this further.  2.2 and 2.3 are [EOL](https://docs.ansible.com/ansible/2.5/reference_appendices/release_and_maintenance.html).

**Comment by retr0h** [comment]
After looking into this further, there are still many Molecule users which use unsupported versions of Ansible.  Switching the default callback plugin would cause issues with these users.  For now we need to be a little conservative.  Not everyone is able to upgrade releases.

**Comment by TomaszKlosinski** [comment]
Was this implemented?
