### ISSUE TITLE
Bitbucket pipeline

### ISSUE THREAD

**Issue by Uwila** [metacloud/molecule#1373]
# Issue Type

- Question

# Molecule and Ansible details

```
ansible 2.6.1
```

```
molecule, version 2.15.0
```

Molecule and ansible installation methods: `pip`

# Question

I'm trying to make molecule work with bitbucket pipelines and I'm stuck. I hope that perhaps someone here has gotten it to work and can help me. I have a very simple pipeline:

```
image: ubuntu:18.04

pipelines:
  default:
    - step:
        services:
          - docker
        script:
          - apt update ; apt install -y python-pip
          - pip install molecule ansible docker
          - cd roles/redis
          - molecule test
```
(the `cd` is because the repository is a playbook)

This fails:

```
--> Validating schema /opt/atlassian/pipelines/agent/build/roles/redis/molecule/default/molecule.yml.
Validation completed successfully.
--> Test matrix
    
└── default
    ├── lint
    ├── destroy
    ├── dependency
    ├── syntax
    ├── create
    ├── prepare
    ├── converge
    ├── idempotence
    ├── side_effect
    ├── verify
    └── destroy
    
--> Scenario: 'default'
--> Action: 'lint'
--> Executing Yamllint on files found in /opt/atlassian/pipelines/agent/build/roles/redis/...
Lint completed successfully.
--> Executing Flake8 on files found in /opt/atlassian/pipelines/agent/build/roles/redis/molecule/default/tests/...
Lint completed successfully.
--> Executing Ansible Lint on /opt/atlassian/pipelines/agent/build/roles/redis/molecule/default/playbook.yml...
 [WARNING] Ansible is in a world writable directory (/opt/atlassian/pipelines/agent/build/roles/redis), ignoring it as an ansible.cfg source.
Lint completed successfully.
--> Scenario: 'default'
--> Action: 'destroy'
 [WARNING] Ansible is in a world writable directory (/opt/atlassian/pipelines/agent/build/roles/redis/molecule/default), ignoring it as an ansible.cfg source.
    
    PLAY [Destroy] *****************************************************************
    
    TASK [Destroy molecule instance(s)] ********************************************
    changed: [localhost] => (item=None)
    changed: [localhost]
    
    TASK [Wait for instance(s) deletion to complete] *******************************
    failed: [localhost] (item=None) => {"attempts": 1, "censored": "the output has been hidden due to the fact that 'no_log: true' was specified for this result", "changed": false}
    fatal: [localhost]: FAILED! => {"censored": "the output has been hidden due to the fact that 'no_log: true' was specified for this result", "changed": false}
    
    PLAY RECAP *********************************************************************
    localhost                  : ok=1    changed=1    unreachable=0    failed=1
    
    
ERROR: 
An error occured during the test sequence.  Cleaning up.
--> Scenario: 'default'
--> Action: 'destroy'
 [WARNING] Ansible is in a world writable directory (/opt/atlassian/pipelines/agent/build/roles/redis/molecule/default), ignoring it as an ansible.cfg source.
    
    PLAY [Destroy] *****************************************************************
    
    TASK [Destroy molecule instance(s)] ********************************************
    changed: [localhost] => (item=None)
    changed: [localhost]
    
    TASK [Wait for instance(s) deletion to complete] *******************************
    failed: [localhost] (item=None) => {"attempts": 1, "censored": "the output has been hidden due to the fact that 'no_log: true' was specified for this result", "changed": false}
    fatal: [localhost]: FAILED! => {"censored": "the output has been hidden due to the fact that 'no_log: true' was specified for this result", "changed": false}
    
    PLAY RECAP *********************************************************************
    localhost                  : ok=1    changed=1    unreachable=0    failed=1
    
    
ERROR: 
```

Using `--debug` I find that the error is the following (both times): `"Error connecting: Error while fetching server API version: ('Connection aborted.', error(2, 'No such file or directory'))"`

I thought that perhaps Docker just wasn't working; so I tried `docker run ubuntu:18.04 echo lol`, which works so that can't be it.

Out of interest I tried `create` instead of `test`. It also fails, same error, on the task `Discover local Docker images`. (So I guess it has to do with docker in some way)

I also tried using a different pip package: `docker-py`. This gives the same error.

I have also tried installing virtualenv and running it inside a virtualenv, this didn't change anything either.

Finally, what I did was open a shell in a fresh `ubuntu:18.04` container on my local machine and executing the commands (in addition to installing `docker.io`). I also mounted the docker socket in the container to the one on the host, which I remember reading bitbucket does as well. This  I did in order to debug it locally, but it just worked without problems, so my attempt to get as close as possible to what the pipeline was doing gets me a working container, and I still can't figure out what is wrong.

I have no idea where to go from here.

**Comment by lwm** [comment]
From a quick dig around, you might want to check out https://github.com/requests/requests/issues/4160.

**Comment by Uwila** [comment]
@lwm I don't really get what you're trying to say. Are you suggesting I downgrade this specific module, or do you think there could be a similar issue, or something else? I'm not really familiar with the pip ecosystem so I don't really know how these pieces fit together. I do see some interested links in that issue though; I'll try them out tomorrow.

**Comment by ju5t** [comment]
It's probably related to the `DOCKER_HOST` variable being set but not used by Molecule. I don't know what Bitbucket sets for you but you can find out by adding `echo $DOCKER_HOST` to your script. 

You can use the output in `docker_host` in `molecule/default/molecule.yml`. For example:

```yaml
platforms:
  - name: instance
...
    environment: { container: docker }
    docker_host: "tcp://docker:2375"
```

We had a similar issue with Gitlab CI.

Related issues: #1312 and #1355.

**Comment by Uwila** [comment]
Thanks, especially the second issue seems like it could be similar, I'll come back to this somewhere tomorrow I think.

**Comment by ju5t** [comment]
Using `docker_host` is a workaround as it will likely break your local tests. It should be fixed in 2.16.

**Comment by retr0h** [comment]
> Just to add: using docker_host is a workaround as it will likely break your local tests. It should be fixed in 2.16.

Working on releasing 2.16 today.  Currently, churning through the functional tests.

**Comment by retr0h** [comment]
2.16 released, should be good now.

**Comment by Uwila** [comment]
Nice! Using 2.16 everything works as expected. Thanks!
