### ISSUE TITLE
packaging vagrant boxes

### ISSUE THREAD

**Issue by r0ckyte** [metacloud/molecule#1377]
# Issue Type
- Feature request

# Molecule and Ansible details

```
ansible --version
 2.5.3
```
```
molecule --version
2.14.0
```

Molecule installation method (one of):
- source
- pip

Ansible installation method (one of):
- source
- pip
- OS package

# Desired Behavior
currently we are using molecule with vagrant driver in multiple dependent repositories.  We are trying to export vagrant instance which passed all molecule tests to other repo for running other end of roles.

for example: 
i have repositories like main-repo ( set of core roles ), env-specific-repo1(env-specific-roles) ...
i'm running molecule on main-repo and exporting the molecule tested vagrant box to env-specific-repo1, env-specific-repo2 ..etc and running respective test on top of main-repo.

currently using 'vagrant package' command from MOLECULE_EPHEMERAL_DIRECTORY directory and uploading output.box to shared space so that it can be imported at env-specific-repo1.

can this be included naively in molecule with some option like "molecule package --scenario-name <> instance-name < >" ?

if you interested to look, i can share my python code which does some hack with MOLECULE_EPHEMERAL_DIRECTORY/Vagratfile 

Thanks

**Comment by retr0h** [comment]
Hi @r0ckyte thats not a horrible idea.  At the moment we probably wont include this.  However, if we get more requests for such a feature we may break this request out of the backlog, and I can ping you for more details.
