### ISSUE TITLE
molecule converge with delegated driver executes create and all other tasks

### ISSUE THREAD

**Issue by mihai-satmarean** [metacloud/molecule#1378]
# Issue Type

- Bug report

# Molecule and Ansible details

```
ansible --version
ansible 2.6.1
```

```
molecule --version
molecule, version 2.15.0
```

Molecule installation method (one of):

- pip

Ansible installation method (one of):

- pip

# Desired Behavior
driver: delegated

when using molecule converge we expect that only the converge playbook is executed against the target hosts

# Actual Behaviour (Bug report only)

molecule executes all other tasks like create, prepare etc

**Comment by retr0h** [comment]
You need to set [managed: False](https://molecule.readthedocs.io/en/latest/configuration.html#delegated).
