### ISSUE TITLE
Suggestion: Distinct default Docker container name for distinct roles

### ISSUE THREAD

**Issue by Uwila** [metacloud/molecule#1380]
# Issue Type

- Feature request

# Desired Behavior

At the moment the default is to have the container name always be `instance`. This makes it such that testing multiple roles at the same time doesn't work. This can be fixed by the user by changing the platform name to a name that won't be used by something else. However, it seems like sane default behavior to me to just do this by default. Why not by default use `role-name-instance`, `instance-role-name`, `molecule-role-name` or `role-name-molecule`. Where of course by `role-name` I mean the actual name of the role.

**Comment by retr0h** [comment]
The way we address this is by creating the instance with a unique name.  The default instance name is simply a default.  For some users that is perfectly fine for others it is not.  However, the effort to change the instance name is minimal on your part.  Thank you for the suggestion.  I hope you enjoy using Molecule.
