### ISSUE TITLE
redhat.repo copied from physical host

### ISSUE THREAD

**Issue by dazzla76** [metacloud/molecule#1381]
# Issue Type

- Bug report

# Molecule and Ansible details

```
ansible --version
ansible 2.5.0
  config file = None
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /opt/ansible/venv/lib/python2.7/site-packages/ansible
  executable location = /opt/ansible/venv/bin/ansible
  python version = 2.7.12 (default, Nov  1 2016, 15:53:58) [GCC 4.8.5 20150623 (Red Hat 4.8.5-4)]

```

```
molecule --version
molecule, version 2.15.0

```

Molecule installation method (one of):

- pip

Ansible installation method (one of):

- pip

# Platform
```
cat /etc/redhat-release
Red Hat Enterprise Linux Server release 7.4 (Maipo)
```
```
docker version
Client:
 Version:         1.12.6
 API version:     1.24
 Package version: docker-1.12.6-71.git3e8e77d.el7.x86_64
 Go version:      go1.8.3
 Git commit:      3e8e77d/1.12.6
 Built:           Wed Dec 13 12:18:58 2017
 OS/Arch:         linux/amd64

Server:
 Version:         1.12.6
 API version:     1.24
 Package version: docker-1.12.6-71.git3e8e77d.el7.x86_64
 Go version:      go1.8.3
 Git commit:      3e8e77d/1.12.6
 Built:           Wed Dec 13 12:18:58 2017
 OS/Arch:         linux/amd64
```

# Desired Behavior

Attempting to run test suite on ansible role, it should create the docker container, install role  dependencies, run the playbook and then run the tests

# Actual Behaviour (Bug report only)

This one is a little hard to explain so i hope i can express it properly.

When running converge we are installing a custom yum repo that contains a local copy of kibana and then installing kibana through yum.

Somewhere along the line the redhat.repo from the physical host is being copied to the docker container which causes errors when running the yum install.

We have confirmed that just running molecule create only results in the auto generated redhat.repo file, it is copied at a later stage.

When running the role on its own outside of molecule it doesn't install the redhat.repo file.  So where is the file coming from when running inside of molecule.

**Comment by retr0h** [comment]
I can't really offer any suggestions off the top of my head.  Is this a weird redhat issue?  What if you simply run `docker run -it <image name> bash` and inspect the container further?

**Comment by dazzla76** [comment]
before run create manually there is just a skeleton redhat.repo in /etc/yum.repos.d.  during converge the unwanted file appears.  

I've not seen then running plain old Ansible with the same role.

**Comment by retr0h** [comment]
I can't really help based on info provided.  This sounds like a docker on RHEL issue than molecule.

**Comment by dazzla76** [comment]
Agreed, it looks like it’s nothing to do with molecule.
