### ISSUE TITLE
Support Python 3.7

### ISSUE THREAD

**Issue by webknjaz** [metacloud/molecule#1382]
# Issue Type

- Bug report

# Desired Behavior

I want to be able to run it under Python 3.7, there's no fatal difference, which would prevent it from running under forward-compatible pythons, so it should be possible to painlessly change the check to be >= 3.6

# Actual Behaviour (Bug report only)

```
$ molecule check
ERROR: Python version '(3, 7)' not supported.  Molecule only supports Python versions '2.7' and '3.6'.
```

**Comment by retr0h** [comment]
At some point.
