### ISSUE TITLE
pyyaml dependeny

### ISSUE THREAD

**Issue by bbaassssiiee** [metacloud/molecule#1387]
molecule 2.16.0 has requirement PyYAML==3.12, but you'll have pyyaml 3.13 which is incompatible.

**Comment by bbaassssiiee** [comment]
https://snyk.io/vuln/SNYK-PYTHON-PYYAML-42159

**Comment by retr0h** [comment]
4.1 isn't released to pypi.

**Comment by retr0h** [comment]
See #1392

**Comment by retr0h** [comment]
Closing.

**Comment by JGalego** [comment]
Is it safe to bump the PyYAML requirement to **version 5.1**?

**Comment by decentral1se** [comment]
Hi @JGalego, we have https://github.com/ansible/molecule/pull/2064 for this.
