### ISSUE TITLE
molecule_local/amazonlinux:2017.09 docker image is actually 2018:03

### ISSUE THREAD

**Issue by xavicarrillo** [metacloud/molecule#1395]
# Issue Type

- Bug report

# Molecule and Ansible details

```
ansible --version
```
2.6.1, but also with 2.3.0
```
molecule --version
```
2.16, but also with 2.13.1

Molecule installation method (one of):
- pip

Ansible installation method (one of):
- pip

# Desired Behavior

Specify an `amazonlinux` image:
```
  - name: rundeck
    image: amazonlinux
    image_version: 2017.09
```

The docker container should use `amazonlinux 2017:09`

# Actual Behaviour (Bug report only)

The docker container is not `amazonlinux v1 2017:09`

From a `molecule login`:
```
bash-4.2# grep VERSION /etc/os-release
VERSION="2018.03"
VERSION_ID="2018.03"
```

The official amazonlinux image is correct:
```
 ➜  docker run -it amazonlinux:2017.09 /bin/cat /etc/os-release
NAME="Amazon Linux AMI"
VERSION="2017.09"
ID="amzn"
ID_LIKE="rhel fedora"
VERSION_ID="2017.09"
PRETTY_NAME="Amazon Linux AMI 2017.09"
ANSI_COLOR="0;33"
CPE_NAME="cpe:/o:amazon:linux:2017.09:ga"
HOME_URL="http://aws.amazon.com/amazon-linux-ami/"
```

but molecule's one is not:
```
 ➜  docker run -it molecule_local/amazonlinux:2017.09 /bin/cat /etc/os-release
NAME="Amazon Linux AMI"
VERSION="2018.03"
ID="amzn"
ID_LIKE="rhel fedora"
VERSION_ID="2018.03"
PRETTY_NAME="Amazon Linux AMI 2018.03"
ANSI_COLOR="0;33"
CPE_NAME="cpe:/o:amazon:linux:2018.03:ga"
HOME_URL="http://aws.amazon.com/amazon-linux-ami/"
```

**Comment by retr0h** [comment]
Might want to check your `moleucle.yml` [syntax](http://molecule.readthedocs.io/en/latest/configuration.html#docker).

```
  - name: rundeck
    image: amazonlinux:2017.09
```

However, the problem is the Dockerfile doing a `yum upgrade`.  That will bump the version reported in os-release.

```
[jodewey:~/git/molecule_2/test/scenarios/driver/docker] [molecule2-env-2.7.13] master(+3/-11)+* ± docker images
REPOSITORY                   TAG                 IMAGE ID            CREATED              SIZE
molecule_local/amazonlinux   2017.09             10f0bca874c7        About a minute ago   242MB
amazonlinux                  2017.09             199a7ae8f1db        3 months ago         165MB
[jodewey:~/git/molecule_2/test/scenarios/driver/docker] [molecule2-env-2.7.13] master(+3/-11)+ ± molecule login
--> Validating schema /Users/jodewey/git/molecule_2/test/scenarios/driver/docker/molecule/default/molecule.yml.
Validation completed successfully.
--> Validating schema /Users/jodewey/git/molecule_2/test/scenarios/driver/docker/molecule/multi-node/molecule.yml.
Validation completed successfully.
bash-4.2# cat /etc/os-release
NAME="Amazon Linux AMI"
VERSION="2017.09"
ID="amzn"
ID_LIKE="rhel fedora"
VERSION_ID="2017.09"
PRETTY_NAME="Amazon Linux AMI 2017.09"
ANSI_COLOR="0;33"
CPE_NAME="cpe:/o:amazon:linux:2017.09:ga"
HOME_URL="http://aws.amazon.com/amazon-linux-ami/"
```

I suggest updating the Dockerfile template shipped with Molecule to suit your needs.

**Comment by xavicarrillo** [comment]
Thanks @retr0h, I understand that `image_version` is deprecated?

Removing the `apt-get upgrade` bit fixed the issue but why is that command run in the `Dockerfile`? Upgrading the OS defeats the whole point of specifing a version, doesn't it?

Thank you!

**Comment by retr0h** [comment]
> Removing the apt-get upgrade bit fixed the issue but why is that command run in the Dockerfile? Upgrading the OS defeats the whole point of specifing a version, doesn't it?

Ya, that seems like a poor decision on my part.
