### ISSUE TITLE
Doing something after test, inverse of prepare

### ISSUE THREAD

**Issue by Uwila** [metacloud/molecule#1398]
# Issue Type

- Feature request/Question

# Feature

To do something before running tests we have `prepare` with its own playbook, but nothing to do after tests. An example of where this could be useful is when connecting to external services. For example, using the `iam` module one might create a test user on AWS. You want to remove this user after the test, because otherwise you'll already have it next time you run the test.

Something like `prepare` but after the test would be nice, a `cleanup` phase perhaps?

**Comment by lwm** [comment]
You can use the `destroy.yml` and the destroy step to tear things down after the tests.

https://molecule.readthedocs.io/en/latest/usage.html#destroy

**Comment by retr0h** [comment]
Yeah for now this isn't something we want to develop.  As it stands today we already have quite a few steps, I'd like to avoid adding another step.  If you wish to do this, just maintain your own destroy.yml and add it there.

Thank you for the suggestion @Uwila.
