### ISSUE TITLE
vagrant driver: support openvz as a provider

### ISSUE THREAD

**Issue by lwm** [metacloud/molecule#1400]
# Issue Type

- Feature request

# Issue

From the internal molecule vagrant documentation:

> https://molecule.readthedocs.io/en/latest/configuration.html#molecule-vagrant-module

We see that the following providers are supported:

    * VirtualBox (default)
    * VMware (vmware_fusion, vmware_workstation and vmware_desktop)
    * Parallels
    * Libvirt (requires vagrant-libvirt plugin)

I would like to support https://openvz.org/ as a provider.

Would you accept a pull request for this?

If so, is there any help / past pull requests / information you can provide to help me along the way?

Thanks.

**Comment by retr0h** [comment]
I'm not opposed to it, however, I don't have a way to test it, which opens yourself up to maintaining it or having the code yanked it if becomes unmaintainable.

**Comment by lwm** [comment]
OK, makes sense.

I'm experimenting with this as a solution where I work, if we go with it, we can maintain it.

I'll close off for now until something is moving on our end. Thanks.
