### ISSUE TITLE
How-to include tests specific dependencies

### ISSUE THREAD

**Issue by jaepetto** [metacloud/molecule#1401]
# Issue Type

- Question

# Molecule and Ansible details

```
ansible --version -> 2.6.1
```

```
molecule --version -> 2.16.0
```

Molecule installation method (one of):

- pip

Ansible installation method (one of):

- OS package

# Question

Part of the tests I'd like to run using testinfra are actually requiring external dependencies. I basically have to use cases:
* packages that are not part of the image but required to run the test
  This is the case when you want to use the socket module of testinfra (it requires ss or netstat)
* python dependencies (`pip install ...`)
  This is typically the case when I want to make sure that the correct homepage is returned by nginx (hence the need to install requests).

Since, these dependencies are only related to the tests, I don't think it is good idea to include that in the actual role.

Is there a 'clean' way to achieve that?

**Comment by lwm** [comment]
AFAIK, you just install what you need in the `prepare.yml` of your testing. For example, see https://github.com/metacloud/molecule/blob/master/test/scenarios/driver/delegated/molecule/openstack/prepare.yml in the molecule testing setup. This seems to fit both cases, no?

PS. I raised similar ideas of 'what are people doing, what is best practice' in  https://github.com/metacloud/molecule/issues/1396, I wonder if we couldn't add this kind of thing to the documentation as well.
