### ISSUE TITLE
Upstream the vagrant module

### ISSUE THREAD

**Issue by MarkusTeufelberger** [metacloud/molecule#1404]
# Issue Type

- Feature request

# Desired Behavior

The Vagrant module would be nice to have available by default in ansible upstream.

# Actual Behaviour (Bug report only)

Molecule has a working module to start/run vagrant boxes included but it is exclusive to molecule. This leads to duplicated efforts like https://github.com/ansible/ansible/pull/32562

**Comment by lwm** [comment]
Oh damn, would be great to have this upstreamed - is there some feature set difference?

**Comment by retr0h** [comment]
I personally do not have the mental fortitude to try and push something through Ansible upstream.  The Vagrant module we are using in Molecule is quite mature and works.  If/when the Vagrant module lands in all versions of Ansible that Molecule supports, and is feature compatible, we can consider moving.  However, at this point I do very little work on the Molecule Vagrant module.  Is just works.

**Comment by MarkusTeufelberger** [comment]
Would you be OK with someone else submitting it for you?

**Comment by retr0h** [comment]
@MarkusTeufelberger sure, it's just fairly specific to molecule.  It even imports Molecule.
