### ISSUE TITLE
No color output when execute under gitlab-ci runner

### ISSUE THREAD

**Issue by imcitius** [metacloud/molecule#1408]
Hello

I try to get colorized output under gitlab-runner.
I use gitlab-ee version 10.7, and gitlab-runner 11.1.

Runner is allow colorized output, ansible itself, and test script [from here](https://gist.github.com/danielrehn/d2e6f2129e5f853c3166) displaying colors without any issues.

Molecule display colors when I run it under my local console, but the same code working under runner without colors.

I tried to export various TERM env var for molecule (linux/xterm/ansi/xterm-256colors), but without any result.
Also I tried to set `force-color: True`, as mentioned [here](https://molecule.readthedocs.io/en/latest/configuration.html#molecule.provisioner.lint.ansible_lint.AnsibleLint), no luck.

Could this issue be resolved? It is very inconvenient to debug without colorized output. :(

# Issue Type

- Bug report

# Molecule and Ansible details

```
ansible 2.6.1
  config file = None
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.5 (default, Jul 13 2018, 13:06:57) [GCC 4.8.5 20150623 (Red Hat 4.8.5-28)]

```

```
molecule, version 2.16.0

```

Molecule installation method (one of):

- pip

Ansible installation method (one of):

- pip

If I can provide more details, please feel free to ask.

Thanks.

**Comment by imcitius** [comment]
Update.
Actually, parameter `force-color: True` from molecule [documentation](https://molecule.readthedocs.io/en/latest/configuration.html#molecule.provisioner.lint.ansible_lint.AnsibleLint) is not working at all.

When set literally as in doc, yamllint  display this error:
```
--> Executing Yamllint on files found in /builds/ansible/roles/base-setup.role/...
    /builds/ansible/roles/base-setup.role/molecule/default/molecule.yml
      16:20     warning  truthy value should be true or false  (truthy)

```
When set like:
```
provisioner:
  name: ansible
  lint:
    name: ansible-lint
    options:
      force-color: "true"
```
Error changes to: 
```
Usage: ansible-lint [options] playbook.yml [playbook2 ...]

ansible-lint: error: --force-color option does not take a value
An error occurred during the test sequence action: 'lint'. Cleaning up.
```
So I cannot test it at all.

**Comment by retr0h** [comment]
> So I cannot test it at all.

Well you can test, colors aren't necessary to test.

**Comment by retr0h** [comment]
Yamllint is telling you to lower case your `true`.

Should be `force-color: true`

**Comment by imcitius** [comment]
>Well you can test, colors aren't necessary to test.

Sorry for my poor english, thats not offence.
I mean "I cannot test setting colors using force-color: 'true'", but not "I cannot test using molecule at all".


>Should be force-color: true
It works with this setting now, but still no colors.

**Comment by retr0h** [comment]
Does setting [ANSIBLE_FORCE_COLOR](https://docs.ansible.com/ansible/2.5/reference_appendices/config.html#ansible-force-color) help?

**Comment by retr0h** [comment]
I don't know much else to try.  I don't use gitlab, so I don't really  have any good suggestions.

**Comment by elliotweiser** [comment]
@imcitius Out of curiosity... did you try `tput colors`?

I've been reading up on the terminfo database and it sounds like that's what you should query to see what the shell will support.

**Comment by imcitius** [comment]
@elliotweiser 
Thanks for this advise, it says 256.

```
$ export TERM=xterm-256color
$ tput colors
256
$ ansible --version
 [WARNING] Ansible is in a world writable directory (/builds/ansible/roles/base-setup.role), ignoring it as an ansible.cfg source.
ansible 2.6.1
  config file = None
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.5 (default, Jul 13 2018, 13:06:57) [GCC 4.8.5 20150623 (Red Hat 4.8.5-28)]
$ molecule --version
molecule, version 2.16.0
$ molecule test
--> Validating schema /builds/ansible/roles/base-setup.role/molecule/default/molecule.yml.
Validation completed successfully.
--> Test matrix

.......

```

But still no colors.
Ansible when run without molucule in the same pipeline shows colors well.

**Comment by retr0h** [comment]
Closing as there is not much I can do about this.  If you do figure out the problem please feel free to update this ticket so others may benefit.  However, this issue appears to be outside the scope of Molecule.

**Comment by quiescer** [comment]
The suggestion in [Jeff Geerling's post](https://www.jeffgeerling.com/blog/2020/getting-colorized-output-molecule-and-ansible-on-github-actions-ci) worked well for me on GitLab CI.
