### ISSUE TITLE
Build an Ansible compatible image failed in offline mode

### ISSUE THREAD

**Issue by yodatak** [metacloud/molecule#1409]
# Issue Type

With a offline vm the build failed 

- Bug report

# Molecule and Ansible details

```
ansible --version
```
ansible 2.5.1
  config file = None
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /home/ansible2/molecule/lib/python2.7/site-packages/ansible
  executable location = /home/ansible2/molecule/bin/ansible
  python version = 2.7.5 (default, May  3 2017, 07:55:04) [GCC 4.8.5 20150623 (Red Hat 4.8.5-14)]

```
molecule --version
molecule, version 2.12.1

```

Molecule installation method (one of):

- pip

Ansible installation method (one of):

- pip

# Desired Behavior

Please give some details of the feature being requested or what
should happen if providing a bug report.
To documentate the way to make it offline or to not request docker api

# Actual Behaviour (Bug report only)

    TASK [Build an Ansible compatible image] ***************************************
    task path: /root/molecule/testing/molecule/default/create.yml:33
    Using module file /root/molecule/lib/python2.7/site-packages/ansible/modules/cloud/docker/docker_image.py
    <127.0.0.1> ESTABLISH LOCAL CONNECTION FOR USER: root
    <127.0.0.1> EXEC /bin/sh -c 'echo ~ && sleep 0'
    <127.0.0.1> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /root/.ansible/tmp/ansible-tmp-1532625861.32-140264216507753 `" && echo ansible-tmp-1532625861.32-140264216507753="` echo /root/.ansible/tmp/ansible-tmp-1532625861.32-140264216507753 `" ) && sleep 0'
    <127.0.0.1> PUT /root/.ansible/tmp/ansible-local-7816_KSni4/tmp5xj_cq TO /root/.ansible/tmp/ansible-tmp-1532625861.32-140264216507753/docker_image.py
    <127.0.0.1> EXEC /bin/sh -c 'chmod u+x /root/.ansible/tmp/ansible-tmp-1532625861.32-140264216507753/ /root/.ansible/tmp/ansible-tmp-1532625861.32-140264216507753/docker_image.py && sleep 0'
    <127.0.0.1> EXEC /bin/sh -c '/root/molecule/bin/python /root/.ansible/tmp/ansible-tmp-1532625861.32-140264216507753/docker_image.py && sleep 0'
    <127.0.0.1> EXEC /bin/sh -c 'rm -f -r /root/.ansible/tmp/ansible-tmp-1532625861.32-140264216507753/ > /dev/null 2>&1 && sleep 0'
    failed: [localhost] (item={'_ansible_parsed': True, u'src': u'/root/.ansible/tmp/ansible-tmp-1532625858.42-18531187528473/source', '_ansible_item_result': True, u'group': u'root', u'uid': 0, u'size': 772, 'item': {'image': u'centos:7', 'name': u'instance'}, u'dest': u'/tmp/molecule/testing/default/Dockerfile_centos_7', u'checksum': u'92bbda64c044759fddbb2411f0ec18cc32be7181', u'changed': True, 'failed': False, u'state': u'file', u'gid': 0, u'mode': u'0644', u'invocation': {u'module_args': {u'directory_mode': None, u'force': True, u'remote_src': None, u'owner': None, u'follow': False, u'local_follow': None, u'group': None, u'unsafe_writes': None, u'setype': None, u'content': None, u'serole': None, u'dest': u'/tmp/molecule/testing/default/Dockerfile_centos_7', u'selevel': None, u'original_basename': u'Dockerfile.j2', u'regexp': None, u'validate': None, u'src': u'/root/.ansible/tmp/ansible-tmp-1532625858.42-18531187528473/source', u'checksum': u'92bbda64c044759fddbb2411f0ec18cc32be7181', u'seuser': None, u'delimiter': None, u'mode': None, u'attributes': None, u'backup': False}}, u'owner': u'root', 'diff': [{'after': u"# Molecule managed\n\nFROM centos:7\n\nRUN if [ $(command -v apt-get) ]; then apt-get update && apt-get upgrade -y && apt-get install -y python sudo bash ca-certificates && apt-get clean; \\\n    elif [ $(command -v dnf) ]; then dnf makecache && dnf --assumeyes install python sudo python-devel python2-dnf bash && dnf clean all; \\\n    elif [ $(command -v yum) ]; then yum makecache fast && yum update -y && yum install -y python sudo yum-plugin-ovl bash && sed -i 's/plugins=0/plugins=1/g' /etc/yum.conf && yum clean all; \\\n    elif [ $(command -v zypper) ]; then zypper refresh && zypper update -y && zypper install -y python sudo bash python-xml && zypper clean -a; \\\n    elif [ $(command -v apk) ]; then apk update && apk add --no-cache python sudo bash ca-certificates; fi\n", 'after_header': u'/root/.ansible/tmp/ansible-local-7816_KSni4/tmpSLyPZS/Dockerfile.j2', 'before': u''}], u'md5sum': u'6084f126becebe564c78ff8e4b6b5121', '_ansible_ignore_errors': None, '_ansible_no_log': False}) => {
        "changed": false,
        "invocation": {
            "module_args": {
                "api_version": null,
                "archive_path": null,
                "buildargs": null,
                "cacert_path": null,
                "cert_path": null,
                "container_limits": null,
                "debug": false,
                "docker_host": null,
                "dockerfile": "/tmp/molecule/testing/default/Dockerfile_centos_7",
                "filter_logger": false,
                "force": true,
                "http_timeout": null,
                "key_path": null,
                "load_path": null,
                "name": "molecule_local/centos:7",
                "nocache": false,
                "path": "/tmp/molecule/testing/default",
                "pull": true,
                "push": false,
                "repository": null,
                "rm": true,
                "ssl_version": null,
                "state": "present",
                "tag": "latest",
                "timeout": null,
                "tls": null,
                "tls_hostname": null,
                "tls_verify": null,
                "use_tls": "no"
            }
        },
        "item": {
            "changed": true,
            "checksum": "92bbda64c044759fddbb2411f0ec18cc32be7181",
            "dest": "/tmp/molecule/testing/default/Dockerfile_centos_7",
            "diff": [
                {
                    "after": "# Molecule managed\n\nFROM centos:7\n\nRUN if [ $(command -v apt-get) ]; then apt-get update && apt-get upgrade -y && apt-get install -y python sudo bash ca-certificates && apt-get clean; \\\n    elif [ $(command -v dnf) ]; then dnf makecache && dnf --assumeyes install python sudo python-devel python2-dnf bash && dnf clean all; \\\n    elif [ $(command -v yum) ]; then yum makecache fast && yum update -y && yum install -y python sudo yum-plugin-ovl bash && sed -i 's/plugins=0/plugins=1/g' /etc/yum.conf && yum clean all; \\\n    elif [ $(command -v zypper) ]; then zypper refresh && zypper update -y && zypper install -y python sudo bash python-xml && zypper clean -a; \\\n    elif [ $(command -v apk) ]; then apk update && apk add --no-cache python sudo bash ca-certificates; fi\n",
                    "after_header": "/root/.ansible/tmp/ansible-local-7816_KSni4/tmpSLyPZS/Dockerfile.j2",
                    "before": ""
                }
            ],
            "failed": false,
            "gid": 0,
            "group": "root",
            "invocation": {
                "module_args": {
                    "attributes": null,
                    "backup": false,
                    "checksum": "92bbda64c044759fddbb2411f0ec18cc32be7181",
                    "content": null,
                    "delimiter": null,
                    "dest": "/tmp/molecule/testing/default/Dockerfile_centos_7",
                    "directory_mode": null,
                    "follow": false,
                    "force": true,
                    "group": null,
                    "local_follow": null,
                    "mode": null,
                    "original_basename": "Dockerfile.j2",
                    "owner": null,
                    "regexp": null,
                    "remote_src": null,
                    "selevel": null,
                    "serole": null,
                    "setype": null,
                    "seuser": null,
                    "src": "/root/.ansible/tmp/ansible-tmp-1532625858.42-18531187528473/source",
                    "unsafe_writes": null,
                    "validate": null
                }
            },
            "item": {
                "image": "centos:7",
                "name": "instance"
            },
            "md5sum": "6084f126becebe564c78ff8e4b6b5121",
            "mode": "0644",
            "owner": "root",
            "size": 772,
            "src": "/root/.ansible/tmp/ansible-tmp-1532625858.42-18531187528473/source",
            "state": "file",
            "uid": 0
        },
        "msg": "Error building molecule_local/centos - code: None, message: Get https://registry-1.docker.io/v2/: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers), logs: [u'Step 1/2 : FROM centos:7', u'\\n']"
    }

**Comment by retr0h** [comment]
Need more details on what an offline vm means and your use case.

**Comment by yodatak** [comment]
With a docker that can request the docker api because it's block on the firewall and the centos tha can't download the packages without a proxy , is it clear ?

**Comment by retr0h** [comment]
So you want to download through a proxy?

**Comment by yodatak** [comment]
I can't request the docker api so when it go to the step it failed because of docker api is inaccessible

**Comment by retr0h** [comment]
Not sure what I can do about such a problem.

**Comment by elliotweiser** [comment]
@yodatak The reason that the Docker API is being hit is because of the `FROM` directive in `/tmp/molecule/testing/default/Dockerfile_centos_7`. That's a Dockerfile generated by a jinja2 template, which uses Docker Hub by default to retrieve the base image. You could override this if you wanted to by changing the base image in the `FROM` directive or just by providing your own Dockerfile.

**Comment by yodatak** [comment]
Sorry i find a way thanks to you guide ! Thanks a lot !
