### ISSUE TITLE
Auto-generation of READMEs

### ISSUE THREAD

**Issue by kulinacs** [metacloud/molecule#1411]
# Issue Type

- Feature request

# Desired Behavior

It would be really neat if, given a Jinja template, information gathered from the Ansible role could be used to fill a README template. I really like what molecule has to offer and would be happy to work on adding this feature.

**Comment by retr0h** [comment]
This also feels out of the scope of Molecule.  If there was a project that generated good, useful READMEs, *maybe* Molecule could execute the tool.

**Comment by retr0h** [comment]
Going to close this one out.  Outside the scope of Molecule.
