### ISSUE TITLE
Molecule won't start Docker container ("unreachable" converge error)

### ISSUE THREAD

**Issue by Blasterdick** [metacloud/molecule#1412]
# Issue Type

- Bug report

# Molecule and Ansible details

ansible --version
```
ansible 2.6.1
```
molecule --version
```
molecule, version 2.16.0
```
Molecule installation method (one of):

- pip

Ansible installation method (one of):

- pip

# Desired Behavior

molecule should start docker container

# Actual Behaviour (Bug report only)

I've tested molecule with a fresh setup Ubuntu Server 16.04.04 x86_64 VDI image from the [osboxes.org](https://www.osboxes.org/ubuntu-server/#ubuntu-server-16-04-4-info).
There I installed docker-ce, python 2.7.12 with ansible 2.6.1, molecule 2.16.0 and python docker lib (docker 1.10.6).

After that I used instructions from [here](https://www.digitalocean.com/community/tutorials/how-to-test-ansible-roles-with-molecule) to set up a `virtualenv` and run `molecule converge`.

It gave me the next error:

```
    TASK [Gathering Facts] *********************************************************
    fatal: [ubuntu18.04]: UNREACHABLE! => {"changed": false, "msg": "Authentication or permission failure. In some cases, you may have been able to authenticate and did not have permissions on the target directory. Consider changing the remote tmp path in ansible.cfg to a path rooted in \"/tmp\". Failed command was: ( umask 77 && mkdir -p \"` echo ~/.ansible/tmp/ansible-tmp-1532690224.45-64132892114812 `\" && echo ansible-tmp-1532690224.45-64132892114812=\"` echo ~/.ansible/tmp/ansible-tmp-1532690224.45-64132892114812 `\" ), exited with result 1", "unreachable": true}

    PLAY RECAP *********************************************************************
    ubuntu18.04                : ok=0    changed=0    unreachable=1    failed=0

```

while my `molecule.yml` file has the container command line:

```
command: /bin/bash -c 'while true; do sleep 1; done'
```

**Comment by elliotweiser** [comment]
Please run w/ `--debug` and show output from the task that fails.

**Comment by Blasterdick** [comment]
@elliotweiser here's `molecule --debug converge` [log](https://pastebin.com/S2TY3Qr3).

**Comment by retr0h** [comment]
@Blasterdick can you do the same for `molecule --debug destroy` I believe this is due to missing python bindings.

**Comment by Blasterdick** [comment]
@retr0h seems like it's not, cause' if I run `molecule init -r test -d docker && cd ./test && molecule test` it works as expected and the docker container with `molecule_local/centos:7` image is getting created. 

Maybe, there's something wrong with my `molecule.yml` ?

```

**Comment by Blasterdick** [comment]
Somehow I have `pip` from the `python3.5`, `python` linked to `python 2.7.12` and `python3` linked to the `python 3.6.6` on my host machine. And also some configuration, which I copy-pasted from [here](https://molecule.readthedocs.io/en/2.16/configuration.html#docker) and edited to fit my needs, was wrong.

So I have to delete `ansible`, `molecule`, `docker-py` and `docker` with `pip2 uninstall`,  'pip uninstall` w/ and w/o `sudo`, and then run `pip2 install --user ansible molecule docker`. 

After that everything seems to work fine.
