### ISSUE TITLE
Code coverage - testinfra

### ISSUE THREAD

**Issue by Pinaute** [metacloud/molecule#1414]
# Issue Type

- Feature Request

# Molecule and Ansible details

```
ansible 2.6.2
```

```
molecule, version 2.16.0
```

Molecule installation method (one of):

- pip

Ansible installation method (one of):

- pip

# Desired Behavior

I'm using the default verifier testinfra. I can see the number of tests passed successfully.
But I would also like to see the code coverage: number of tests compared to the number of Ansible tasks.

**Comment by retr0h** [comment]
That's not really how testinfra works, and not something I'm really able to implement.
