### ISSUE TITLE
ansible galaxy dependencies failing

### ISSUE THREAD

**Issue by jamesla** [metacloud/molecule#1416]
I am trying to get both the DIND molecule test and molecule test versions working side by side in the same folder. Everything works fine except the ansible-galaxy dependencies section which throws a strange error. 

molecule test runs fine but I get the following error when I run it in DIND.

```
DEBUG: COMMAND
/usr/bin/ansible-galaxy install --role-file=requirements.yml --roles-path=/tmp/molecule/jamespoc/default/roles --force -vvv

    ansible-galaxy 2.6.1
      config file = None
      configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
      ansible python module location = /usr/lib/python2.7/site-packages/ansible
      executable location = /usr/bin/ansible-galaxy
      python version = 2.7.14 (default, Dec 14 2017, 15:51:29) [GCC 6.4.0]
    No config file found; using defaults
    Created /root/.ansible_galaxy
    found role {'scm': 'git', 'src': 'https://github.com/geerlingguy/ansible-role-docker.git', 'version': 'master', 'name': 'ansible-role-greenbook'} in yaml file
    Processing role ansible-role-greenbook
ERROR! Unexpected Exception, this is probably a bug: local variable 'stdout' referenced before assignment
    the full traceback was:
```

I am really struggling as to why this is happening and spent quite a while on it. I created a repo that shows the example, full error and instructions on how to replicate. Does anybody have any idea on what this could be?

example repo - https://github.com/jamesla/broken-molecule-example

**Comment by jamesla** [comment]
Ok i figured it out, git is not installed in the molecule DIND container and required by ansible-galaxy. Will send a PR.

**Comment by jamesla** [comment]
https://github.com/metacloud/molecule/pull/1418

**Comment by retr0h** [comment]
Fixed above
