### ISSUE TITLE
Problems with testing on Arch Linux

### ISSUE THREAD

**Issue by skhoroshavin** [metacloud/molecule#1419]
# Issue Type
- Bug report

# Details

```
$ ansible --version
ansible 2.6.2
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/home/xop/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/xop/.venv/molecule/lib/python3.6/site-packages/ansible
  executable location = /home/xop/.venv/molecule/bin/ansible
  python version = 3.6.6 (default, Jun 27 2018, 13:11:40) [GCC 8.1.1 20180531]
```

```
$ tox --version
3.1.3 imported from /home/xop/.venv/molecule/lib/python3.6/site-packages/tox/__init__.py
```

Ansible installation method:
- pip

# Desired Behavior

Cloned molecule repository and followed [instructions](http://molecule.readthedocs.io/en/latest/testing.html) to test it using tox:
- tried to install requirements using `pip install -r test-requirements.txt -t requirements.txt`, expected no errors
- tried to run `tox` in order to see if everything is good, expected no errors
- tried to run `tox -t unit`, expected no errors

# Actual Behaviour

- when tried to install requirements there was an error
```
azure-cli-core 2.0.35 has requirement wheel==0.30.0, but you'll have wheel 0.31.1 which is incompatible.
```
I was able to fix it by pinning wheel version in `test-requirements.txt`

- when tried to run `tox` there were lots of errors in functional tests, most are related to Azure and some to rubocop (which isn't installed and there was no mention of it in instructions), although unit tests passed just fine

- when tried to run `tox -t unit` it said there's no such option, and when running `tox --help` there's really no such version

# Questions
- is it expected that Azure functional tests fail?
- should I provide some more info on Azure test failures or it is already known problem?
- is some older version of tox is expected for tests?
- are there any plans to update documentation?

**Comment by retr0h** [comment]
> is it expected that Azure functional tests fail?

Yes, b/c you need Azure credentials.  So you would to source your Azure creds for it to work.

> is some older version of tox is expected for tests?

No

> are there any plans to update documentation?

With what?

> when tried to run tox -t unit it said there's no such option, and when running tox --help there's really no such version

You should prob read the [testing docs](http://molecule.readthedocs.io/en/latest/testing.html).  You need to install tox tags to make it work.

**Comment by retr0h** [comment]
I'm not so sure I want to pin wheel to a particular version, only b/c of Arch.

**Comment by skhoroshavin** [comment]
> Yes, b/c you need Azure credentials. So you would to source your Azure creds for it to work.
So, does it mean that in order to contribute to molecule (which requires running full test suite before creating PR) I need an Azure account?
> With what?
It would be nice to mention that rubocop is needed for tests.
> You need to install tox tags to make it work, which the docs reference.
Sorry, I've read the doc you mentioned several times and still somehow missed that part. Thanks for pointing.

> I'm not so sure I want to pin wheel to a particular version, only b/c of Arch.
I'm not sure this is just Arch issue - after all I was installing it using pip, and I don't expect it to vary much between distros. I'll try to reproduce it on some other distros and will report if problem persists.

**Comment by retr0h** [comment]
> So, does it mean that in order to contribute to molecule (which requires running full test suite before creating PR) I need an Azure account?

In the docs I mention targeting a particular driver.  If your developing for vagrant try:

`$ tox -t functional -- -v -k vagrant`

However, a faster approach is to run `tox -l` and choose a single environment to test, so you do not have to loop over every single functional test.

`tox -e py27-ansible26-functional -- -k vagrant -v`

The above will only run tests for the particular version of

**Comment by retr0h** [comment]
> It would be nice to mention that rubocop is needed for tests.

+1

**Comment by skhoroshavin** [comment]
>> I'm not so sure I want to pin wheel to a particular version, only b/c of Arch.

> I'm not sure this is just Arch issue - after all I was installing it using pip, and I don't expect it to vary much between distros. I'll try to reproduce it on some other distros and will report if problem persists.

Double-checked - this is not related to Arch since it's reproducible in some mainstream distros. Added comment to #1420

**Comment by retr0h** [comment]
merged
