### ISSUE TITLE
Multiple drivers in molecule.yml

### ISSUE THREAD

**Issue by ifalex** [metacloud/molecule#1424]
# Issue Type

- Question

# Molecule and Ansible details

```
ansible --version
```
2.6.2
```
molecule --version
```
2.16.0
Molecule installation method (one of):

- source
- pip

Installed with pip
Ansible installation method (one of):

- source
- pip
- OS package
Installed with pip
# Desired Behavior

I would like to have an example on how to add multiple drivers in a molecule.yml file. Is it possible?
Documentation points to this capability.

# Actual Behaviour (Bug report only)

Added, two drivers in molecule.yml
Driver: delegate
Driver: openstack

Looks like when I'm trying to create the instances only the second driver is taken in consideration so the delegate driver won't do its job.
What I'm trying is to set with delegate driver the localhost instance and with openstack the other instances.
This way I can assign a group tag for the localhost instance( if there is any other options please let me know). I need the tag for the localhost instance(and localhost instance to be in inventory) to do some delegate_to tasks in roles.

===================================================================
cat molecule.yml
dependency:
  name: galaxy

driver:
  name: delegated
  options:
    managed: False
    login_cmd_template: 'ssh -i {{ my_key }} 127.0.0.1 -F /path/to/ssh_config'
    ansible_connection_options:
      connection: ssh
      ansible_ssh_common_args: -i {{ my_key }} -F /path/to/ssh_config
platforms:
  - name: mol-test-bastion
    groups:
      - bastion

driver:
  name: openstack
lint:
  name: yamllint
platforms:
  - name: mol-test-master
    image: "image_id"
    flavor: "m1.medium"
    security_groups: "default"
    groups:
      - master

Can I get an example of how to properly use this feature?
Thank you for your support!

**Comment by lwm** [comment]
AFAIK, you create a new scenario for each driver as in https://github.com/metacloud/molecule/tree/master/test/scenarios and if you have tests or other things that you want to share you just https://molecule.readthedocs.io/en/latest/examples.html#sharing-across-scenarios. Also worth reading is https://molecule.readthedocs.io/en/latest/faq.html#why-are-there-multiple-scenario-directories-and-molecule-yml-files.

**Comment by ifalex** [comment]
So basically, you can't provide to different drivers in molecule.yml?
I want one instance to be represented by localhost and the others by instances in openstack.

**Comment by retr0h** [comment]
> So basically, you can't provide two different drivers in molecule.yml?
> I want one instance to be represented by localhost and the others by instances in openstack.

Right.  You would use different scenarios.
