### ISSUE TITLE
add config option to override driver args

### ISSUE THREAD

**Issue by HalisCz** [metacloud/molecule#1425]
# Issue Type

- Feature request
- or question

# Desired Behavior

I would like to run `molecule test` on my localhost and on CI server. Unfortunately, LXD socket on CI server is in standard filepath, but on my localhost it is "namespaced" because of `snap`-based installation of `lxd`.

With the default set of molecule playbooks, it works on CI server. To get it working on my localhost, I need to change `url:` argument of `lxd_container` ansible module in all playbooks.

I would love to see possibility of local file or env variable, which would be able to override this argument. 

I am aware of that my use-case is very specific, but I think that many people have slight differences in local provider settings and CI server provider settings.

Although, if you have any recommendation or best-practise, please let me know.

**Comment by retr0h** [comment]
Can you add something [like this](https://github.com/metacloud/molecule/blob/master/molecule/provisioner/ansible/playbooks/docker/create.yml#L56) to your create.yml?

**Comment by retr0h** [comment]
Let me know if this is still an issue.  I believe you can work around this with the example above.

**Comment by HalisCz** [comment]
For future reference, it was resolved by using:

    url: "{{ item.lxd_url | default(lookup('env', 'LXD_URL') or 'unix:/var/lib/lxd/unix.socket') }}"
