### ISSUE TITLE
Expose `project_root` as environment variable

### ISSUE THREAD

**Issue by uSpike** [metacloud/molecule#1433]
# Issue Type

- Feature request

# Desired Behavior

The documentation for ansible provisioner has the following defaults for the environment:

```
ANSIBLE_ROLES_PATH:
  $ephemeral_directory/roles/:$project_root/../
ANSIBLE_LIBRARY:
  $ephemeral_directory/library/:$project_root/library/
ANSIBLE_FILTER_PLUGINS:
  $ephemeral_directory/plugins/filters/:$project_root/filter/plugins/
```

however, `project_root` (`config.project_directory`) is not exposed as an environment variable.  Having this would be very useful, so I could write this in my config:

```
ANSIBLE_FILTER_PLUGINS: $MOLECULE_EPHEMERAL_DIRECTORY/plugins/filters/:$MOLECULE_PROJECT_DIRECTORY/filter_plugins/
```

**Comment by lwm** [comment]
It would be good! We could also avoid the usual `../../../` in the `molecule.yml` file for other files.

OTOH, and have seen something in https://github.com/metacloud/molecule/issues/1286#issuecomment-387581346, you can use any environment variables in your configuration with the `@$` syntax. Maybe that is just for `$HOME` though ...

**Comment by uSpike** [comment]
Holy cow, that was fast @retr0h - thank you!

**Comment by retr0h** [comment]
This was an easy one. :)
