### ISSUE TITLE
Tag and push to pypi to fix python 3.7 installation issues

### ISSUE THREAD

**Issue by defionscode** [metacloud/molecule#1442]
# Issue Type
- Bug report

# Python Version
`Python 3.7.0`

# Desired Behavior
I would expect for pip3 install molecule to work

# Actual Behaviour (Bug report only)

It faces an issue with PyYAML v3.12 which is what is listed in the requirements.txt of the current release.

PyYAML v3.13 fixes this issue and it is what is currently present in the upstream.

All that needs to be done to fix this is to tag the current code base and push a new release to pypi.

**Comment by retr0h** [comment]
Python 3.7 support hasn't been released yet.  It was added in 2.17 which hasn't been released.  When Molecule 2.17 is released this issue will fix itself.

**Comment by defionscode** [comment]
welp for those who need/want to use py 3.7 right away, you can do this for now `pip install -e git://github.com/metacloud/molecule.git#egg=molecule
`

which is working for me at the moment

**Comment by retr0h** [comment]
2.17 was released a little while ago.
