### ISSUE TITLE
Logo License Question

### ISSUE THREAD

**Issue by nbering** [metacloud/molecule#1443]
I noticed the logo has a "no derivatives" clause on it.

Is it ok to resize it without changing the overall appearance? Maybe trim some of the margins off? I'd like to contribute it to https://github.com/buildkite/emojis so that I can use the logo as an emoji in the BuildKite pipeline task.

**Comment by nbering** [comment]
I've contributed a logo in the past to BuildKite, and I provided attribution by including a link to the source and license in the commit message. Would that be ok here? I don't think the attribution would appear in BuildKite's product, but their documentation clearly links to that repo as the source for their custom emojis.

**Comment by retr0h** [comment]
Sure, sounds fine.

**Comment by nbering** [comment]
Thank you!
