### ISSUE TITLE
vagrant fails to start on windows

### ISSUE THREAD

**Issue by thatsk** [metacloud/molecule#1444]
# Issue Type

- Bug report
- Feature request

# Molecule and Ansible details

```
ansible --version
ansible 2.5.5
  config file = /tmp/molecule/testvagrant/default/ansible.cfg
  configured module search path = [u'/home/kunalsingt/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.14 (default, Oct 31 2017, 21:12:13) [GCC 6.4.0]
```

```
molecule --version
molecule, version 2.16.0
```

```
vagrant --version
Vagrant 2.1.2
```

Molecule installation method (one of):
- pip

Ansible installation method (one of):

- pip
- OS package

# Desired Behavior
it should create instance in virtualbox and provision and destroy

Please give some details of the feature being requested or what
should happen if providing a bug report.

# Actual Behaviour (Bug report only)

Please give some details of what is actually happening.
Include a [minimum complete verifiable example](http://stackoverflow.com/help/mcve) with
output of running `molecule --debug`.
[debug.txt](https://github.com/metacloud/molecule/files/2290181/debug.txt)

**Comment by retr0h** [comment]
What does the log say?

"msg": "ERROR: See log file '/tmp/molecule/testvagrant/default/vagrant-instance.err'"

**Comment by retr0h** [comment]
Not enough info to debug.

**Comment by finarfin** [comment]
I think I ran into the same issue. I use molecule over WSL (Windows Subsystem for Linux). The default TMPDIR in WSL (/tmp) is not reachable to Virtualbox on Windows. It works if I set the TMPDIR variable to a location that is available to Windows (e.g. `TMPDIR=/mnt/c/Windows/Temp molecule create`)

```
There was an error while executing `VBoxManage`, a CLI used by Vagrant
for controlling VirtualBox. The command and stderr is shown below.

Command: ["import", "\\\\?\\C:\\Users\\\User\\.vagrant.d\\boxes\\jborean93-VAGRANTSLASH-WindowsServer2019\\0.6.0\\virtualbox\\box.ovf", "--vsys", "0", "--vmname", "packer-virtualbox-iso-1547959474_1549173961541_69632", "--vsys", "0", "--unit", "10", "--disk", "./packer-virtualbox-iso-1547959474-disk001.vmdk"]

Stderr: 0%...10%...20%...30%...40%...50%...60%...70%...80%...90%...100%
Interpreting \\?\C:\Users\User\.vagrant.d\boxes\jborean93-VAGRANTSLASH-WindowsServer2019\0.6.0\virtualbox\box.ovf...
OK.
0%...
Progress state: E_INVALIDARG
VBoxManage.exe: error: Appliance import failed
VBoxManage.exe: error: Code E_INVALIDARG (0x80070057) - One or more arguments are invalid (extended info not available)
VBoxManage.exe: error: Context: "enum RTEXITCODE __cdecl handleImportAppliance(struct HandlerArg *)" at line 957 of file VBoxManageAppliance.cpp
```
