### ISSUE TITLE
pytest/testinfra discover tests

### ISSUE THREAD

**Issue by uSpike** [metacloud/molecule#1446]
# Issue Type

- Question / feature request

The `testinfra` verifier walks the tree looking for `test_*.py`.  I am wondering why this is in place, since `pytest` will discover tests (recursively) on its own, and you can configure how it finds tests.

It'd be useful to me to leverage pytest's discovery which allows hooking into pytest's collection system (`pytest_collect_directory` and others) and this is not as easy when passing a list of test files.

It may also be useful to be able to provide further options in `pytest.ini`

**Comment by retr0h** [comment]
We tell testinfra where the tests are located b/c the path can be changed in molecule.yml if users wish to share tests between scenarios.

**Comment by retr0h** [comment]
Isn't something we are going to support at this time but may in the future.  Thanks @uSpike.
