### ISSUE TITLE
Cannot use docker images that are identified by digest rather then tag

### ISSUE THREAD

**Issue by ifireball** [metacloud/molecule#1448]
# Issue Type

- Bug report

# Molecule and Ansible details

```
ansible --version
ansible 2.6.3
...
  python version = 2.7.5 (default, May 31 2018, 09:41:32) [GCC 4.8.5 20150623 (Red Hat 4.8.5-28)]

```

```
molecule --version
molecule, version 2.17.0
```

Molecule installation method (one of):

- pip

Ansible installation method (one of):

- pip

# Desired Behavior

Be able to use a docker image identified in the following form:

    foo/bar@sha256:xxxyyyzzz....

# Actual Behaviour (Bug report only)

Building the molecule docker image failes because it tries to use the exact same image name for the image it generates, but the 'foo/bar@sha256:xxxyyyzzz....' expression is not valid for use as a tag expression.

**Comment by retr0h** [comment]
This isn't a use case Molecule supports.  Can you provide details as to why this is desired?

**Comment by ifireball** [comment]
I want to use a 3rd party image as a base image for testing, but the maintainers do not set fixed tags for it. If I use a moving tag, my tests will simply not be reproducible as the image may change in ways that can affect test outcome.

**Comment by retr0h** [comment]
Seems like an issue with the image.  The maintainers should really be setting tags when they release new functionality.

**Comment by wilmardo** [comment]
If the `docker_container` module support this, it should work with the new `pre_build_image option` (#1447). When set to true the building of the image is skipped and the `image` option gets passed directly to the `docker_container` module ([docs](https://docs.ansible.com/ansible/latest/modules/docker_container_module.html))

**Comment by ifireball** [comment]
Not sure that will completely solve the issue as molecule needs a bunch of things installed in the image that you've no guarantee will be installed in the base image you're pulling.

Also WRT what image manitainers should and shouldn't do - there are many situations where one is not in a position to dictate that...

**Comment by wilmardo** [comment]
> Not sure that will completely solve the issue as molecule needs a bunch of things installed in the image that you've no guarantee will be installed in the base image you're pulling.

True (only Python is really needed for Ansible to work), but you could use a prepare playbook to install these packages instead of the Dockerfile template. My LXD implementation uses this approach [see here](https://github.com/metacloud/molecule/blob/f9441c4dca5738c9b0ce11ffdf349426bea46c73/molecule/provisioner/ansible/playbooks/lxd/prepare.yml).

Remember, it is just Ansible your dealing with underneath Molecule

**Comment by retr0h** [comment]
I don't see a way to reference an image by digest in a Dockerfile.

Molecule is writing out a Dockerfile which appears to have a valid from line, but it looks like Docker doesn't support this functionality?

```
FROM centos@sha256:6f6d986d425aeabdc3a02cb61c02abb2e78e57357e92417d6d58332856024faf
```

**Comment by retr0h** [comment]
I'm going to close this at this time.  It's not a typical use case.  Feel free to submit a PR if you feel otherwise.
