### ISSUE TITLE
Re-enable automatic building documentation building on Read the Docs

### ISSUE THREAD

**Issue by tjanez** [metacloud/molecule#145]
Hi!

The last (successful) build of [Molecule's documentation on Read the Docs](https://readthedocs.org/projects/molecule/builds/) is from [Jan 29, 2016](https://readthedocs.org/projects/molecule/builds/3682488/).

Could you re-enable automatic building via GitHub's web hooks?

**Comment by abrown-sg** [comment]
Good call, I'll look into it. Thanks!

**Comment by retr0h** [comment]
Appears to be up to date, please reopen if untrue.

**Comment by retr0h** [comment]
Yeah, doesnt look like they are getting rebuilt.

**Comment by retr0h** [comment]
The webhook has been enabled.  I see it updating docs on merge now.

<img width="811" alt="screen shot 2016-07-18 at 1 59 08 pm" src="https://cloud.githubusercontent.com/assets/9895/16930179/dbc44758-4cef-11e6-9424-505f5dcecb91.png">
