### ISSUE TITLE
become: true scenario phase

### ISSUE THREAD

**Issue by chrismeyersfsu** [metacloud/molecule#1451]
# Issue Type

- Feature request

# Molecule and Ansible details

```
ansible --version
ansible 2.6.3
  config file = None
  configured module search path = [u'/home/meyers/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /home/meyers/ansible/virtualenv/setup-D509PTvZ/local/lib/python2.7/site-packages/ansible
  executable location = /home/meyers/ansible/virtualenv/setup-D509PTvZ/bin/ansible
  python version = 2.7.14 (default, Sep 23 2017, 22:06:14) [GCC 7.2.0]
```

```
molecule --version
molecule, version 2.17.0
```

Molecule installation method (one of):

- pip

Ansible installation method (one of):

- pip

# Desired Behavior

* To be able to express become method in the scenario phase

# Actual Behaviour (Bug report only)

* can express `become: true` through various `group_vars` "hacks" but that bleeds into the provision step and, as you already known since you disallow `privilege_escalation` in the provision step, this causes problems.

**Comment by retr0h** [comment]
Not sure what you are requesting.  If you wish to use become, this can be added to the playbook.
