### ISSUE TITLE
Pre-Commit Checks

### ISSUE THREAD

**Issue by dmlb2000** [metacloud/molecule#1453]
# Issue Type
- Feature request/New Package

## Background

[Pre-Commit](https://github.com/pre-commit/pre-commit) is a nice tool for linting and auto-correcting ugly but syntactically correct code during the process of development. Pre-commit integrates with git and leverages a plugin framework to execute project specific checks prior to a developers commit.

## The Request

I'd like to see a pre-commit checks repository that executes parts of molecule as pre-commit hooks.

I know this is a request for a new repository but I needed a place to get the conversation started about integration with pre-commit.

**Comment by dmlb2000** [comment]
I figured I'd post some of the repos I've seen for these things...

 - The default hooks repo https://github.com/pre-commit/pre-commit-hooks
 - Hooks repo for php development https://github.com/hootsuite/pre-commit-php
 - Hooks repo for go development https://github.com/dnephin/pre-commit-golang

**Comment by retr0h** [comment]
Thank you for the suggestion, but this is really outside the scope of Molecule.

**Comment by dmlb2000** [comment]
@retr0h I agree it's outside the scope of the molecule source code to support. However, it makes sense to have your project to host the pre-commit molecule repository. Could you make a repository `pre-commit-molecule` and I'll submit a pull request to start the development process?
