### ISSUE TITLE
Support restart_policy option for docker driver

### ISSUE THREAD

**Issue by borisnaydis** [metacloud/molecule#1456]
# Issue Type

- Feature request

# Molecule and Ansible details

```
ansible --version
```

```
molecule --version
```

Molecule installation method (one of):

- pip

Ansible installation method (one of):

- pip

# Desired Behavior

When `restart_policy` is set for a platform instance, it should be propagated to a corresponding container. The reason for adding this functionality is to test reboot action with subsequent reconnect in Ansible playbooks.

# Actual Behaviour (Bug report only)

Now this setting is not defined in result containers because it is not defined in [create.yml](https://github.com/metacloud/molecule/blob/master/molecule/provisioner/ansible/playbooks/docker/create.yml#L57).

**Comment by retr0h** [comment]
Please submit a PR for this feature.  You can reference #1413.

**Comment by borisnaydis** [comment]
Ok, I'll try to find time for this during this week.
