### ISSUE TITLE
Python 3.5 support

### ISSUE THREAD

**Issue by skhoroshavin** [metacloud/molecule#1470]
Is there any particular reason why python 3.5 is not supported? It's default in Ubuntu 16.04 which is still very widespread. I already looked at commit which added support for python 3.7, it seems very easy to change version requirements, but before trying and submitting PR I just wanted to ask.

**Comment by retr0h** [comment]
Sure, @skhoroshavin

**Comment by retr0h** [comment]
Closing, feel free to open a PR.
