### ISSUE TITLE
Unable to specify a platform

### ISSUE THREAD

**Issue by erjac77** [metacloud/molecule#1471]
# Issue Type

- Bug report

# Molecule and Ansible details

```
ansible --version
ansible 2.6.3
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/home/osboxes/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/dist-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.12 (default, Dec  4 2017, 14:50:18) [GCC 5.4.0 20160609]
```

```
molecule --version
molecule, version 2.17.0
```

Molecule installation method (one of):

- pip

Ansible installation method (one of):

- pip

# Desired Behavior

I would like to have the ability to select the platform on which to run `molecule test`.

I think molecule used to have a `--platform` option, but it seems to have been removed.

Our use case is to run `molecule test` against our dev instance, and if it succeed, then re-run on our pre-prod instance.

# Actual Behaviour (Bug report only)

```
molecule test --platform dev
Error: no such option: --platform

molecule test --platform-name dev
Error: no such option: --platform-name
```

**Comment by retr0h** [comment]
Hi @erjac77 this is not an option we support.  Molecule v2 is different than v1.

**Comment by erjac77** [comment]
Ok, but is there a way to limit `molecule test` to a specific platform/instance without duplicating all the scenarios for each environment?

Thank you.
