### ISSUE TITLE
Docs: Confusing advice on create vs converge playbooks

### ISSUE THREAD

**Issue by smheidrich** [metacloud/molecule#1472]
In the [docs for the Ansible provisioner](https://molecule.readthedocs.io/en/latest/configuration.html#id12) it says (emphasis mine):
> Reserve the create and destroy playbooks for provisioning. Do not attempt to gather facts or perform operations on the provisioned nodes inside these playbooks. Due to the gymnastics necessary to sync state between Ansible and Molecule, it is best to perform these tasks in the **converge** playbook.

Shouldn't it say
>... it is best to perform these tasks in the **prepare** playbook.

here instead? Or at least "prepare **or** converge playbooks"? See also #1351.

From what I understand, *converge* is meant for the actual execution of the role, isn't it? Of course, the cited paragraph makes sense if that's what "perform operations on the provisioned nodes" refers to, but then I don't think anyone would think to put this into *create*... confusion between *create* and *prepare*, on the other hand, seems more likely.

**Comment by retr0h** [comment]
> ... it is best to perform these tasks in the **prepare** playbook.

It can be done in either.  Create or prepare.  The documentation was likely written before prepare existed.  However, either one is fine.

**Comment by smheidrich** [comment]
@retr0h Thanks for clearing that up! So I guess the documentation could be changed to recommend *prepare* here instead of *converge*? I agree that it sounds like it was written before *prepare* existed.

**Comment by retr0h** [comment]
Yeah, you mind submitting a fix?
