### ISSUE TITLE
How to use Molecule with Openstack

### ISSUE THREAD

**Issue by camillehuot** [metacloud/molecule#1495]
# Issue Type

Support question

# Molecule and Ansible details

Molecule 2.18.1

# Question

Hi,

Can you please confirm how to use Molecule with Openstack?
Do I have to write such files myself for my env: https://github.com/metacloud/molecule/tree/master/test/resources/playbooks/openstack

Or did I missed something more automated?

I've sourced the OS.rc file then ran molecule with driver: openstack (as per the doc https://molecule.readthedocs.io/en/latest/configuration.html#openstack) and getting:

```
--> Scenario: 'default'
--> Action: 'create'
ERROR! the playbook: None could not be found
ERROR:
```

It seems that Molecule is looking for a create.yml here, and your doc says Molecule "maps variables from molecule.yml into create.yml and destroy.yml" but it's not clear whether I have to write them myself :)

Thanks

**Comment by ifalex** [comment]
All you need is the molecule.yml file. Just do molecule init role -r <your_name> and you'll have imported all the necessary files. Before that source your openstack.rc file(try to see is working - openstack image list). In the molecule file add your desired image, flavor, network, instance name, ssh key place. In create.yml you can modify and change the security group to what you need.

**Comment by camillehuot** [comment]
I was converting a vagrant role to openstack and the files were missing. Thanks now I understand. I'm closing.

**Comment by timbrd** [comment]
Sorry to reopen the issue, but I have the same problem as @camillehuot and dont' know how to solve this.

> In create.yml you can modify and change the security group to what you need.

This is my problem. There is no create.yml...

Do I have to create the create.yml from the cookicutter template?

**Comment by camillehuot** [comment]
> Sorry to reopen the issue, but I have the same problem as @camillehuot and dont' know how to solve this.
> 
> > In create.yml you can modify and change the security group to what you need.
> 
> This is my problem. There is no create.yml...
> 
> Do I have to create the create.yml from the cookicutter template?

Hi Tim
Just create a new openstack scenario with the molecule cli. You will have a default create.yml that you can customize 🙂

**Comment by timbrd** [comment]
@camillehuot Ah, I didn't know that the init command takes the driver as an argument and creates all the necessary files then. 

Thanks for your help!
