### ISSUE TITLE
Molecule should allow overriding of user to deploy as (EC2) and allow overriding of default VPC_ID (EC2)

### ISSUE THREAD

**Issue by rahul0705** [metacloud/molecule#1499]
# Issue Type

- Bug report

# Molecule and Ansible details

```
ansible --version
2.6.3
```

```
molecule --version
2.18.1
```

Molecule installation method (one of):

- pip

Ansible installation method (one of):

- OS package

# Desired Behavior

Provide a setting in molecule.yml to allow ssh_user to be set and vpc_id to be set when using ec2 as a driver.

# Actual Behaviour (Bug report only)

Some images in ec2 do not have ubuntu as a user (any non-ubuntu OS). Currently ssh connection fails if the user does not exist.

**Comment by retr0h** [comment]
You change the user.  The create/destroy playbooks are there for you to modify.  If you do not have an ubuntu user then feel free to [change the playbook](https://github.com/metacloud/molecule/blob/master/molecule/cookiecutter/scenario/driver/ec2/%7B%7Bcookiecutter.molecule_directory%7D%7D/%7B%7Bcookiecutter.scenario_name%7D%7D/create.yml#L9).  That is why it is a var.

**Comment by rahul0705** [comment]
You haven't addressed the VPC_ID issue either? allowing configuration of the vpc_subnet_id without allowing configuration of the VPC_ID is a strange decision.

While changing the user in the create/destroy playbooks is a valid way of approaching this; since you can change the AMI within the molecule.yml it is not clear to the end user that a subsequent change is required in the create/destroy playbook.

Having configuration variables defined in one location that can break configuration options in a different location is not intuitive for the on-boarding of new users.

**Comment by retr0h** [comment]
You can change the VPCID as well.  All of those things can be changed.  If one wishes to cleanup the ec2 driver they are free to submit a PR and do so, similar to #1491.  However, I do not support the ec2 driver from a feature request responsibility.
