### ISSUE TITLE
How to not cleanup the container upon failure

### ISSUE THREAD

**Issue by jaepetto** [metacloud/molecule#1516]
# Issue Type

- Question

# Molecule and Ansible details

```
ansible --version
ansible 2.6.3
```

```
molecule --version
molecule, version 2.19.0
```

Molecule installation method (one of):

pip

Ansible installation method (one of):

OS package

# Desired Behavior

Molecule should provide a way **not** to destroy the container upon a test failure.

# Actual Behaviour (Bug report only)

When a testinfra test fails (or any other failure for that matter), molecule immediately cleans up the created container.
It would be useful to 'suspend' the cleanup process in order to be able to inspect the container (`ps exec -it xxx /bin/bash`) in order to troubleshoot the error.
Unfortunately, the `--debug` option is not sufficient.

One use case is the following:
* molecule dies in the 'idempotent' part of the scenario
* the failure is related to a service that should be restarted
* even with the `--debug` switch, the only details provided by molecule are the `stdout` and `stderr`
* in some cases (for instance restarting the postfix service), only the syslog provides information about the reason of the failure
* since molecule cleans up the container, there is no way to access this syslog

**Comment by retr0h** [comment]
`molecule test --destroy never`

**Comment by jaepetto** [comment]
Thanks. I was sure molecule was great enough to already have this.
BTW, thanks for molecule!

On Oct 18, 2018 22:23, įoнииγ įoнииγ <notifications@github.com> wrote:

molecule test --destroy never

**Comment by retr0h** [comment]
@jaepetto no problem amigo! \m/
