### ISSUE TITLE
Scenario name set as default in molecule.yml, when init a new one

### ISSUE THREAD

**Issue by blackillzone** [metacloud/molecule#1517]
# Issue Type

- Bug report

# Molecule and Ansible details

```
ansible 2.6.1
```

```
molecule, version 2.19.0
```

Molecule installation method (one of):

- pip

Ansible installation method (one of):

- pip

# Desired Behavior

Using the following command to add a new scenario in an existing role (`molecule init scenario --role-name myrolename --scenario-name myscenarioname --driver-name vagrant`), the scenario name in the generated `molecule.yml` file should be the same provided through the `--scenario-name` option.

# Actual Behaviour (Bug report only)

It's currently set as `default`:
```yaml
scenario:
  name: default
```
And when I launch a simple `molecule converge`, I have this error:
```
ERROR: Duplicate scenario name 'default' found.  Exiting.
```
Because I already have a default scenario present in the folder. So I need to change manually `default` to the actual scenario name, and everything works fine again.

**Comment by retr0h** [comment]
I can not reproduce.

```[jodewey:~/git/molecule_2]   : master+ ± mkdir myrolename
[jodewey:~/git/molecule_2]   : master+ ± cd myrolename
[jodewey:~/git/molecule_2/myrolename]   : master+ ± molecule init scenario --role-name myrolename --scenario-name default --driver-name vagrant
--> Initializing new scenario default...
Initialized scenario in /Users/jodewey/git/molecule_2/myrolename/molecule/default successfully.
[jodewey:~/git/molecule_2/myrolename]   : master+* ± molecule init scenario --role-name myrolename --scenario-name myscenarioname --driver-name vagrant
--> Initializing new scenario myscenarioname...
Initialized scenario in /Users/jodewey/git/molecule_2/myrolename/molecule/myscenarioname successfully.
[jodewey:~/git/molecule_2/myrolename]   : master+* 2 ± molecule list
--> Validating schema /Users/jodewey/git/molecule_2/myrolename/molecule/default/molecule.yml.
Validation completed successfully.
--> Validating schema /Users/jodewey/git/molecule_2/myrolename/molecule/myscenarioname/molecule.yml.
Validation completed successfully.
Instance Name    Driver Name    Provisioner Name    Scenario Name    Created    Converged
---------------  -------------  ------------------  ---------------  ---------  -----------
instance         vagrant        ansible             default          false      false
instance         vagrant        ansible             myscenarioname   false      false
```

**Comment by blackillzone** [comment]
As I though, it was a weird behaviour on my side, following the creation of a scenario. It works now as expected, sorry for the unnecessary noise...

**Comment by retr0h** [comment]
@blackillzone no problem thx for the report!
