### ISSUE TITLE
`yapf -i -r molecule` command changes master branch

### ISSUE THREAD

**Issue by sebinjohn** [metacloud/molecule#158]
As per the guidelines for contributing, `yapf -i -r molecule` has to be run before submitting a PR.
Running this command from master branch makes changes to the master branch code

**Comment by retr0h** [comment]
Hi @sebinjohn, looks like you are running the newest version of yapf.  The version I have does not make any changes.  I submitted #160 to help with this.

**Comment by retr0h** [comment]
#160 addressed this
