### ISSUE TITLE
Support for multiple test suites

### ISSUE THREAD

**Issue by DavidWittman** [metacloud/molecule#161]
One of the features of Test Kitchen which I love is the ability to define multiple [test suites](http://kitchen.ci/docs/getting-started/adding-suite) to run against the same Ansible role. There are often many different configurations of the role which need to be tested and I was unable to find (in the documentation, issues, or in the source) a way to accomplish this with Molecule today.

**Comment by retr0h** [comment]
No, not today.  However, I am working on a fairly significant update to molecule, which will rework the entire config to a very kitchen like config, which includes scenario based testing.  I am prototyping it in another [repo](https://github.com/retr0h/maquina/blob/master/tests/conftest.py#L68-L96), and hope to port it back into molecule.  However, at this time, we don't have what you're looking for.

**Comment by DavidWittman** [comment]
@retr0h 👍 I'll keep an eye on Maquina then.
