### ISSUE TITLE
Errors are displayed on stdout

### ISSUE THREAD

**Issue by rgreinho** [metacloud/molecule#180]
Errors are displayed on the standard output stream instead of the standard error stream. This causes issues when using redirections. For instance adding ``2>/dev/null`` at the end of a command has no effect.

A use case where this is really annoying is with the bash completion. The bash completion scripts relies on the ``molecule status`` command to provide the dynamic arguments. If an error occurs, it will also be displayed in stdout and therefore pollute the completion.

An idea to solve this would be to use the logging library to display (at least) errors instead of ``print()``, as the default logging output for errors is ``sys.stderr``.

**Comment by retr0h** [comment]
This should have been corrected with #183.  @rgreinho can you confirm?

**Comment by retr0h** [comment]
@rgreinho I believe this is no longer the case.  Do you mind verifying.

**Comment by rgreinho** [comment]
@retr0h Just did a small testing using the tab completion, and no error was displayed in the terminal, so it looks like we're good!
