### ISSUE TITLE
linting/validators

### ISSUE THREAD

**Issue by dhutty** [metacloud/molecule#182]
There has been much discussion and some code concerning validators/linting with divergent opinions, I'm opening this issue as a place to collect opinions about the direction we want to take in the area of validation. Please add your thoughts below and whether you will be able to dedicate time to developing.

It seems that the most sensible compromise would be to support molecule options such that the user's molecule config would contain a list of validators (for which molecule would provide sensible defaults such as those we have now) and allow the command line invocation of molecule to override.

It would be extra nice if the invocation could also support severity signalling (see http://search.cpan.org/~thaljef/Perl-Critic-1.126/bin/perlcritic for an example) with various levels such as:
`--validation=False|off|none`
`--validation=basic`
`--validation=all`

for which each validator's config in the molecule.yml would have an interpretation.

The obvious initial candidates for initially supported validators are:
- ansible-lint for playbooks
- yapf/flake8 for python files
- rubocop for (serverspec) ruby files

**Comment by kireledan** [comment]
To me this seems a bit unnecessary. The only validator that I think molecule would need would be a dry-run or just a quick syntax check.

**Comment by conorsch** [comment]
OK, I'll bite: i'm a fan of the linting. There are lots of nearly unreadable Ansible roles out there, and Serverspec tests are similarly garish, given that they're mostly written by folks who don't code Ruby full-time for their day jobs. The linting that Molecule runs automatically helps enforce a consistent pattern across projects.

If you don't like the linting setup, you can use the `molecule.ignore_paths` list to skip linting ([docs](http://molecule.readthedocs.io/en/master/usage.html#configuration)). In general I'm a fan of configuration, but let's not get lost in the weeds: the goal of Molecule, as I understand it, is to test Ansible roles and ensure they confirm to community standards. 

That said, I'll agree that with your breakdown of linters for languages, but I'm skeptical that the additional complexity for "severity signaling" in linting is valuable. It _is_ however consistant with the `--destroy=always|passing|never` pragma, also used in test-kitchen.

**Comment by retr0h** [comment]
> OK, I'll bite: i'm a fan of the linting. There are lots of nearly unreadable Ansible roles out there, and Serverspec tests are similarly garish, given that they're mostly written by folks who don't code Ruby full-time for their day jobs. The linting that Molecule runs automatically helps enforce a consistent pattern across projects.

I agree with @conorsch.  The point of molecule is to be somewhat prescriptive.  Everyone may not agree with it, but I'm not asking for everyone to.

**Comment by kireledan** [comment]
I definitely agree with the decision of not being able to turn them on or off. If molecule's goal is to enforce a community standard then there should be no option to avoid it.
