### ISSUE TITLE
Ability to run docker in privileged mode

### ISSUE THREAD

**Issue by retr0h** [metacloud/molecule#184]
Need the ability to run docker in privileged mode.  This is necessary when trying to test services such as [etcd](https://github.com/retr0h/ansible-etcd).  Systemd is necessary to properly install and test the role. This should be configurable though molecule.yml.

**Comment by kireledan** [comment]
Should be a simple tweak. I'll get a PR up within the next few days and update the docs.

**Comment by retr0h** [comment]
@kireledan This doesn't appear to actually work.

```
[jodewey:~/git/ansible-etcd] [venv] remove-molecule-fork+ ± molecule --version
1.5.1

[jodewey:~/git/ansible-etcd] [venv] remove-molecule-fork+ ± docker inspect --format='{{.HostConfig.Privileged}}' `docker ps -q`
false
false
false
false
false
false
```

**Comment by retr0h** [comment]
Actually I'm dumb, and never added `privileged: True` to my molecule.yml. :)

**Comment by retr0h** [comment]
Works as expected, closing.


```
[jodewey:~/git/ansible-etcd] [venv] remove-molecule-fork(+6/-0)+ ± docker inspect --format='{{.HostConfig.Privileged}}' `docker ps -q`
true
true
true
true
true
true
```
