### ISSUE TITLE
Number of processes not configurable for PyTest

### ISSUE THREAD

**Issue by kernelpanek-tendril** [metacloud/molecule#193]
The number of processes for PyTest is hardcoded for both [Vagrant](https://github.com/metacloud/molecule/blob/master/molecule/provisioners.py#L342) and [Docker](https://github.com/metacloud/molecule/blob/master/molecule/provisioners.py#L628) provisioners.

I ran into an issue where my test is validating a user's ability to stop/start/restart a service and these tests had unexpected results.  The issue only exists when more than 1 process is used but I could not alter this through the molecule.yml file as testinfra_args and testinfra_kwargs are not exposed to the molecule configuration file (or it appears that they are not, but maybe it is documented somewhere?) Let me know if I'm missing something or if you believe this is a legitimate issue with no workaround.

**Comment by kireledan** [comment]
There is no way to pass testinfra args/kwargs at the moment. I do agree that you should be able to though. I'll propose a PR with a way to pass them in.

**Comment by kernelpanek-tendril** [comment]
@kireledan Thank you! I wanted to get a sense on whether anyone felt this would fit into the roadmap for Molecule before I started taking a crack at a PR.

**Comment by retr0h** [comment]
Implemented in #198.
