### ISSUE TITLE
Logger adding extra lines, prefixing them with -->

### ISSUE THREAD

**Issue by abrown-sg** [metacloud/molecule#203]
logger.warning now appends --> to every line. This causes the output of things like ansible-playbook to have normally blank lines prefixed with -->, causing a lot of extra noise during a converge.  The _out for the sh calls to various programs doesn't need anything appended to it. @kireledan 

<img width="986" alt="screen shot 2016-06-28 at 1 41 48 pm" src="https://cloud.githubusercontent.com/assets/5855384/16429848/1adebbcc-3d36-11e6-832b-4911c8db26dd.png">

**Comment by kireledan** [comment]
I had it in there just for looks. I can take it out and make it only for molecule warnings.

**Comment by conorsch** [comment]
Yes, I've encountered this building from the latest master. @kireledan It's not so much the `-->` that bothers me, it's the blank lines. Without looking at the code, it seems that there's an extra newline appended to output lines that isn't necessary.

**Comment by kireledan** [comment]
I'll make a PR with something not as noisy.

**Comment by retr0h** [comment]
@kireledan sounds good!
