### ISSUE TITLE
Best place to define proxy var

### ISSUE THREAD

**Issue by freeseacher** [metacloud/molecule#205]
Hi!
In my playbook i have several tasks that have to be done with `http_proxy` var defined, and several without. So i have to setup proxy on per tasks basis.
I've done molecule init and have only one role in my playbook. 
What is the best place to setup that variable? 
i have several ideas for that:
1. for sure defaults/main.yml is bad location. because it breaks compatibility with multirole and setup that var globally on playbook level
2. of cause ansible.raw_env_vars is is good one. but that option is not passed to ansible. except if i add something like `http_proxy: "{{ lookup('env', 'http_proxy') }}"`. That looks acceptable, but feels like mess
3. ? 

ideas?

**Comment by retr0h** [comment]
#202 seems to be what you're looking for.

**Comment by dhutty** [comment]
@freeseacher please re-open if unsatisfied
