### ISSUE TITLE
Testinfra integration

### ISSUE THREAD

**Issue by philpep** [metacloud/molecule#21]
Hi, I'm the author of testinfra and I'm pretty happy to see you integrate it in molecule.

Recently I added ansible helpers into testinfra:

- https://testinfra.readthedocs.org/en/latest/backends.html#ansible
- https://testinfra.readthedocs.org/en/latest/modules.html#ansible

Using ansible backend will allow you to use your existing ansible configuration (inventory, host, user, password, sudo, ssh-key etc) instead of define a `testinfra_hosts` in you test file and make a call to `vagrant ssh-config` (which is pretty long). Also this make the `Ansible` module available in your testinfra tests.

**Comment by retr0h** [comment]
@philpep Awesome, thanks for adding this backend.  We will take a look and incorporate.
