### ISSUE TITLE
Openstack support

### ISSUE THREAD

**Issue by russ216** [metacloud/molecule#220]
Adding openstack as a provider utilizing the vagrant-openstack-provider plugin

**Comment by dhutty** [comment]
I've already got some experimental work in place locally for this in the shape of a small patch to `templates/vagrantfile.j2`. But it needs to completed, tested, documented, etc.

**Comment by kireledan** [comment]
So - it might be better to actually use shade for this because I've found that plugin to be finnicky. It would be much more maintainable to have it as an actual provisioner class. Currently I've started implementing an openstack provisioner because I need to run some of my tests on much more powerful machines.

**Comment by dhutty** [comment]
@kireledan great, I would much rather have a real provisioner

**Comment by russ216** [comment]
@dhutty - that's exactly what I did locally as well, adjusted the `templates/vagrantfile.j2` I've got it on a fork of this repo in the meantime - thank you both for the suggestions, going to read up on shade now.

**Comment by retr0h** [comment]
> Another benefit of using shades is how easily it can be configured. As long as the user has sourced their openstack rc file, shade will work.

Using shade pretty much requires the user be using ansible 2.x to leverage the new `os` modules.  However, I much prefer to use an openstack provisioner built on top of ansible modules than vagrant.

**Comment by russ216** [comment]
@retr0h - thanks for chiming in. Do you like the idea of adapting the `vagrantfile.j2` so that the vagrant-openstack-provider` can be used? (which would work for ansible 2.0 and also below). And then additionally explore using an openstack provisioner?

**Comment by retr0h** [comment]
> @retr0h - thanks for chiming in. Do you like the idea of adapting the vagrantfile.j2 so that the vagrant-openstack-provider` can be used? (which would work for ansible 2.0 and also below). And then additionally explore using an openstack provisioner?

I'm not a huge fan of the vagrant file in general.  I understand we are all using it, but I'd prefer to leverage pure ansible if we can.  Sounded like @kireledan was working on something in pure ansible.

**Comment by russ216** [comment]
I like that idea too @retr0h - to have built in ansible support down the road. I think it would also be good to have the option to use vagrant, which is great for keeping your provisioning agnostic of the config management tool. And it works now, and would work in the future alongside the pure ansible approach

**Comment by russ216** [comment]
Okay - i'm going to also look into extending the provisioners to use shade for something like this. Thanks everyone for your input

**Comment by kireledan** [comment]
Actually, Im not using pure ansible for this. I'm just using shade. My apologies for not being clear enough.

**Comment by russ216** [comment]
It looks like we can use the provisioner factory in `molecule/provisioners.py` and just extend it for shade - does that sound like what your approach is @kireledan ? Do you happen to have any WIP on this I could take a look at or try out?

**Comment by kireledan** [comment]
Yes. I'm just about to make a PR of the WIP. Currently I have all of the molecule commands functioning. Just ironing out some bugs.

**Comment by russ216** [comment]
excellent, thank you. looking forward to checking it out!

**Comment by russ216** [comment]
This pull request addresses this issue for me. everything is running great with no vagrant. Only stipulation for me, was we are not accepting ipv6 yet, so needed to use `os-client-config` to `force_ipv4`. Shade already takes this into account. Vagrant must have just used the v4 by default or I got lucky #226

**Comment by retr0h** [comment]
Implemented in #226.
