### ISSUE TITLE
What has happened to Serverspec templates?

### ISSUE THREAD

**Issue by techraf** [metacloud/molecule#232]
I was trying to figure out what has happened to Serverspec templates. When I first started with Molecule they were present (i.e. put into to project directory with `molecule init`), now they are not. The change happened around 1.4.1-1.4.2.

Was the Serverspec intentionally withdrawn?

**Comment by retr0h** [comment]
Yes, testinfra is the default.  You are free to use serverspec, but we no longer write templates.

**Comment by techraf** [comment]
Ok, but is it possible to provide my own Serverspec templates that `molecule init` would place in a new project, or do I have to copy them manually?

**Comment by retr0h** [comment]
Hi @techraf no we do not.  Since testinfra is the default, we (mostly me) left it up to the user to copy the templates over.

While we support serverspec, we are being somewhat opinionated with `init`.

**Comment by techraf** [comment]
I did not ask that **you** copy (why "we do not" form?), I asked if there is a way to provide my own template. I don't see a huge support issue in this: `spec` subdirectory exists in template directory? --> Copy. Not? --> Forget (which would be a default option).

The phrase "we are being somewhat opinionated with `init` and molecule in general" is incomprehensible.

**Comment by retr0h** [comment]
*No*

**Comment by retr0h** [comment]
@techraf As of molecule 1.10, molecule init will write out both serverspec and testinfra test examples.

As of master you can now pass a `--serverspec` flag to write out only serverspec examples.
