### ISSUE TITLE
[Feature Suggestion] Init with existing role/playbook

### ISSUE THREAD

**Issue by kireledan** [metacloud/molecule#233]
So I was thinking about adding support for using init with existing roles/playbooks. Essentially this would just place a template molecule file in the current directory. Some of the more interesting things I was thinking about is being able to parse the roles in a playbook directory and place them into the generated playbook too so that they are instantly available to run.

Anyone else feel like this is a needed feature and or have some suggestions?

**Comment by retr0h** [comment]
Sounds useful.

**Comment by retr0h** [comment]
Implemented in #249.

**Comment by moh-abk** [comment]
This doesn't create the `./molecule` directory and files so getting this error when I run `molecule test`



`IOError: [Errno 2] No such file or directory: u'.molecule/state.yml'`

**Comment by kireledan** [comment]
I'll look into this really quickly.

**Comment by retr0h** [comment]
Addressed with #261.
