### ISSUE TITLE
Cannot login to a machine if its name is a substring of another one

### ISSUE THREAD

**Issue by techraf** [metacloud/molecule#235]
Not a big deal, but if I define two machines:
- `molecule-host`
- `molecule-host-mirror`

And execute:
```
molecule login molecule-host
```

I get an error:
```
There are 2 hosts that match 'molecule-host'.  You can only log into one at a time.
Try molecule status to see available hosts.
```

And there is no way to connect to `molecule-host`.

**Comment by retr0h** [comment]
Implemented in #248.
