### ISSUE TITLE
Testinfra ssh

### ISSUE THREAD

**Issue by oserde** [metacloud/molecule#24]
Hi, I think there is an issue in core.py. When using testinfra, tests are not executed on the vagrant machine, because when calling testinfra no hosts are specified. So tests are executed on the host machine.

**Comment by oserde** [comment]
Ok. Reading the issue created by philpep I understand that you have to specify hosts in the test file. Anyway, including the hosts parameter to the sh.testinfra call could be useful.

**Comment by retr0h** [comment]
@oserde Yeah, I would like to handle the testinfra host sections better in general.  Truthfully, most of our tests are in serverspec at the moment, and figured `testinfra_hosts` inside each test would mostly suffice.
