### ISSUE TITLE
turn off automatic update during molecule test

### ISSUE THREAD

**Issue by sebinjohn** [metacloud/molecule#245]
Docker provisioner always tries to update the image to make it ansible compatible.
Is there a way I can turn this off so that a prebuilt image from a local registry can be used for testing?

This can speed up the testing process.

**Comment by kireledan** [comment]
There is currently no way to turn it off. However, I will make a PR to add a flag to skip-build for the docker driver.

**Comment by retr0h** [comment]
Implemented in #246.
