### ISSUE TITLE
Port libvirt from vagrant plugin to a true provisioner

### ISSUE THREAD

**Issue by retr0h** [metacloud/molecule#250]
Would like to remove libvirt from vagrant and use ansible as the provisioner, much like we do with the openstack provisioner.

Essentially, I only want vagrant used for ~~vagrant~~ virtualbox.

**Comment by dhutty** [comment]
You mean you want vagrant only used for virtualbox?

**Comment by kireledan** [comment]
I believe that is what he meant. I couldn't imagine it being anything else.

**Comment by retr0h** [comment]
> You mean you want vagrant only used for virtualbox?

ya

**Comment by dhutty** [comment]
I'm going to poke at this a little, investigate how it long it will take me, see if there are any nasty rabbitholes, etc.

**Comment by retr0h** [comment]
Closing this one out.  We are not investigating this currently.

**Comment by ssbarnea** [comment]
We now have feature request for this at https://github.com/ansible/molecule/issues/2245 -- followup there.
