### ISSUE TITLE
ServerSpec support

### ISSUE THREAD

**Issue by moh-abk** [metacloud/molecule#258]
It's mentioned that molecule supports `serverspec` but it's more biased towards `testinfra`.
For starters it doesn't create the `/spec` folder when `init` is run. Also I don't think it installs `serverspec`.

**Feature/Improvement Request.**

Thanks 👊

**Comment by retr0h** [comment]
It is specifically biased towards testinfra.  Serverspec can be used, but we aren't planning on making it part of init.

**Comment by retr0h** [comment]
@moh-abk As of molecule 1.10, molecule init will write out both serverspec and testinfra test examples.

As of master you can not pass a `--serverspec` flag to write out only serverspec examples.

**Comment by moh-abk** [comment]
@retr0h Nice! Will it install `serverspec` same way it installs `pytest` and `testinfra`?
