### ISSUE TITLE
Create integration tests

### ISSUE THREAD

**Issue by retr0h** [metacloud/molecule#269]
We need to create `tests/integration` that run a set of scenarios to ensure molecule is working as expected.

Being able to test molecule as a whole is tricky, due to various providers, provisioners, sequences, and doing this with unit tests seems overly ambitious.

**Comment by kireledan** [comment]
I've been slowly working on tests for the commands to increase coverage. integration tests should be farely simple to do for each driver because the only thing majorly different would be the config file.

**Comment by retr0h** [comment]
Yeah, I feel like we need something which runs molecule test across each provisioner, with custom molecule.yml scenarios to ensure all is working.
