### ISSUE TITLE
serverspec support for docker backend

### ISSUE THREAD

**Issue by alexschlessinger** [metacloud/molecule#272]
currently the rakefile seems tied to vagrant? (testinfra works fine)

```
env = YAML.load_file('{{ molecule_file }}')['vagrant']

if env.nil?
        puts "No vagrant instances defined. "
        instances = {}
else
        instances = env['instances']
end
```

**Comment by retr0h** [comment]
IIRC, when docker support was implemented in molecule.  Probably something we should investigate again.  Serverspec should have a docker backend.

**Comment by kireledan** [comment]
Yeah - at the time I was not too focused on integrating with serverspec. I'll investigate this.

**Comment by retr0h** [comment]
We have a functional scenario already setup, where you can integrate the docker serverspec tests.

https://github.com/metacloud/molecule/tree/master/tests/functional/docker/scenarios/full/spec
