### ISSUE TITLE
Configure for both vagrant and openstack - add a switch

### ISSUE THREAD

**Issue by rjfellman** [metacloud/molecule#279]
I'd like to leave openstack config and vagrant config alongside each other for a few reasons. It would be handy if there was a way to either do something like

`molecule test --provisioner=openstack` or have a config option to set where it could pick your config. vagrant, openstack, docker etc.

**Comment by retr0h** [comment]
That is likely an issue that will be addressed with #204.  However, that is some time away, with a v2 molecule release.

**Comment by retr0h** [comment]
@rjfellman I might be able to implement this.  However, it gets fairly tricky and gross quick.  It would work if one followed the workflow of.

`molecule test`
`molecule test --driver docker`
`molecule test --driver openstack`

However, if at any point the systems are not torn down before executing the next driver, we will get into a mess.  Basically, we can't support simultaneous instances running from multiple drivers w/o a looot of reworking things.

**Comment by rjfellman** [comment]
One of the things I've encountered, is it seems like vagrant is required,
even when openstack is the one present in the configure. It's technically
not a dependency, maybe that should be a separate issue. (Disclaimer: I
haven't tried that particular case in over a month)

**Comment by retr0h** [comment]
I'm pretty sure we corrected that issue.  Open a new issue if that isn't the case.

**Comment by retr0h** [comment]
@rjfellman Okay, I think I have this worked out.  Will submit a PR tomorrow.

It will allow you to add multiple drivers to the config at the same time.  However, once you spin up a driver, you must perform all commands at that driver.  One cannot intermix the two, wile they run simultaneously.

`molecule converge --driver openstack|docker|vagrant`

or update molecule.yml with

```
driver:
  name: docker
```

or do nothing, and molecule will determine the driver like it did in the old config, with a search of the config file for certain keys.
