### ISSUE TITLE
molecule has lots of dependencies

### ISSUE THREAD

**Issue by dhutty** [metacloud/molecule#289]
Molecule should try: import foo the modules that are needed for each provisioner and only error if you attempt to use a provisioner that's not available.

**Comment by retr0h** [comment]
What do you mean @dhutty?  The requirements file brings in the necessary dependencies.  The tests  will be testing all the dependencies.  So unfortunately if you don't have docker installed on your system, you wont be able to run unittests.  Just the nature of the beast.

Can you give more details?

**Comment by dhutty** [comment]
Sure, if you want to test molecule itself. But if I want merely to *use* molecule, I don't necessarily want to bother installing, for example, all of the openstack deps if I'm never going to use it because I'm, say, a virtualbox user.

**Comment by kireledan** [comment]
You do have a point - it is a bit much to have all of those dependencies if the user only wants to use a specific driver. This is definitely something we should look into.

**Comment by retr0h** [comment]
> Sure, if you want to test molecule itself. But if I want merely to use molecule, I don't necessarily want to bother installing, for example, all of the openstack deps if I'm never going to use it because I'm, say, a virtualbox user.

But what does it hurt?  They are python dependencies as the projects dependencies.  How does this matter?  The python dependencies shouldn't be anywhere else but in the requirements file for setup.py.

**Comment by tknerr** [comment]
test-kitchen does this via additional drivers that can be installed as plugins. Something like this would be nice. Eg I don't need all the openstack dependencies while I'm not going to use them. They should be optional.

**Comment by retr0h** [comment]
@tkimball83 @kireledan @dhutty at some point we will break things out into plugins.  The project is in it's early stages.  It's too premature ATM.

**Comment by retr0h** [comment]
Closing this in favor of #312, which will address the dependencies.
