### ISSUE TITLE
Leverage ansible modules

### ISSUE THREAD

**Issue by retr0h** [metacloud/molecule#312]
### Crazy idea

What if, instead of us writing python code to handle the lifecycle of Docker, OpenStack, Libvirt instances/containers, etc...  We simply update molecule to run ordered sets of playbooks.

We will never be able to keep up with the pace of the functionality in the ansible modules.
#### Proposal

Molecules core will generally stay the same.  However, it can run scenarios and various sets of playbooks.
##### Scenario 1
- Molecule will execute a playbook which will up() a service and record it's details in a state file.
- Molecule will then run the converge playbook.
- Molecule will then run a set of tests
- Teardown (down())
- Run a new scenario2
###### Scenario 2
- Molecule will execute a playbook which will up() a service and record it's details in a state file.
- Molecule will then run the converge playbook.
- Molecule will then run a set of tests
- Teardown (down())
- Run a new scenario

Thoughts?

**Comment by dhutty** [comment]
This is not a crazy idea. In my understanding, this has been the intended to (eventually) be molecule's approach for ages. 

If we want to do it as a one-off architectural change and still retain existing molecule functionality, we will need to: 
* wait until Molecule completely supports Ansible v2
* assess Ansible support each of our intended virtualization providers: Vagrant (+ whatever), Openstack, Docker, Libvirt, ...

Or we could do possibly this in an iterative manner (each virtualization provider as it becomes possible/justifiable), but there are disadvantages to that approach as well.

**Comment by kireledan** [comment]
Interesting... I do like the idea of using ansible to put up the machines instead of python. Would definitely be much cleaner and waay easier to maintain.

**Comment by abrown-sg** [comment]
I like this idea as well. And we can leverage converge command to execute other playbooks with minimal effort. The closed triggers PR has an example of it.

**Comment by kireledan** [comment]
Also this can allow users to plug in their own provisions plays too potentially. As long as molecule can read the inventory, it can test against it.

**Comment by retr0h** [comment]
We will handle (#289) as part of this issue.  Since we will rely on ansible modules, and the ansible modules require the user to install the libraries on their own, we will yank the `docker`, `shade`, and `vagrant` hard requirements from molecule.

**Comment by retr0h** [comment]
This is currently underway with v2 branch.  Details were discussed at this [PR](https://github.com/metacloud/molecule/pull/652#issuecomment-268287931).

Closing this issue, since the details have been worked out and underway.
