### ISSUE TITLE
ansible-galaxy: error: unrecognized arguments: --collections-file

### ISSUE THREAD

**Issue by yajo** [metacloud/molecule#3213]
Following these instructions: https://github.com/ansible-community/molecule/blob/b351ea07fe70f4bb9e01212b86a461b6ac05f4d1/src/molecule/dependency/ansible_galaxy/__init__.py#L31-L49

I added this to my `molecule.yml`:

```yaml
dependency:
  name: galaxy
  options:
    role-file: requirements.yaml
    collections-file: requirements.yaml
```

Then try to test with `molecule test --all`.

# Issue Type

- Bug report

# Molecule and Ansible details

```
ansible 2.10.12
  config file = /var/home/yajo/prodevel/infrastructure/ansible.cfg
  configured module search path = ['/var/home/yajo/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /var/home/yajo/prodevel/infrastructure/.venv/lib/python3.9/site-packages/ansible
  executable location = /var/home/yajo/prodevel/infrastructure/.venv/bin/ansible
  python version = 3.9.6 (default, Jul 16 2021, 00:00:00) [GCC 11.1.1 20210531 (Red Hat 11.1.1-3)]
molecule 3.4.0 using python 3.9 
    ansible:2.10.12
    delegated:3.4.0 from molecule
    podman:0.3.0 from molecule_podman
```

Molecule installation method (one of):

- pip

Ansible installation method (one of):

- pip

Detail any linters or test runners used: I'm using the galaxy dependency manager.

# Desired Behavior

Dependencies install, tests run. 

# Actual Behaviour

It seems latest `ansible-galaxy` binary has no longer support for `--collections-file`, so it fails to install dependencies. See [molecule-test-log.txt](https://github.com/ansible-community/molecule/files/7065294/molecule-test-log.txt).

By removing `collections-file` from `molecule.yml`, however, I get these logs:

```
[WARNING]: The requirements file '/var/home/yajo/prodevel/tecnativa-
infrastructure/requirements.yaml' contains collections which will be ignored.
To install these collections run 'ansible-galaxy collection install -r' or to
install both at the same time run 'ansible-galaxy install -r' without a custom
install path.
```

... and collections are not installed.

**Comment by Yajo** [comment]
I tested and, if I remove `role-file`, roles won't install.
