### ISSUE TITLE
repo quay.io/ansible/molecule (and tags) are missing

### ISSUE THREAD

**Issue by till** [metacloud/molecule#3284]
# Issue Type

- Bug report

# Molecule and Ansible details

n/a

Molecule installation method (one of):

- source
- pip

Ansible installation method (one of):

- docker

Detail any linters or test runners used:

# Desired Behavior

Rebuilding an image for an older testsuite works.

# Actual Behaviour

`docker build` produces an error:

```
------
 > [internal] load metadata for quay.io/ansible/molecule:2.22:
------
------
 > [base 1/6] FROM quay.io/ansible/molecule:2.22:
------
failed to load cache key: unexpected status code [manifests 2.22]: 401 UNAUTHORIZED
```

**Comment by webknjaz** [comment]
Reducing the maintenance burden is a very good reason. It's been deprecated, unmaintained and not updated for over a year at that point. But feel free to maintain your own image.
