### ISSUE TITLE
Switching to Testinfra SSH connection does not work as expected

### ISSUE THREAD

**Issue by tknerr** [metacloud/molecule#329]
I was hoping to be able to simply switch the testinfra backend connection to SSH.

So I did:

```yaml
testinfra:
    connection: ssh
```

However, this still passes the ansible inventory but neither of the actually required ssh parameters:

```
Y:\repo\devops\base-jenkins-master>molecule verify
--> Executing testinfra tests found in spec/.
============================= test session starts ==============================
platform cygwin -- Python 2.7.10, pytest-2.9.2, py-1.4.31, pluggy-0.3.1
rootdir: /cygdrive/y/repo/devops/base-jenkins-master/spec, inifile:
plugins: xdist-1.14, testinfra-1.4.1
collected 0 items / 1 errorss

==================================== ERRORS ====================================
______________________ ERROR collecting test_hostsfile.py ______________________
/usr/lib/python2.7/site-packages/testinfra/plugin.py:124: in pytest_generate_tests
    ansible_inventory=metafunc.config.option.ansible_inventory,
/usr/lib/python2.7/site-packages/testinfra/__init__.py:35: in get_backends
    _BACKENDS_CACHE[key] = backend.get_backends(hosts, **kwargs)
/usr/lib/python2.7/site-packages/testinfra/backend/__init__.py:87: in get_backends
    for name in klass.get_hosts(host, **kw):
/usr/lib/python2.7/site-packages/testinfra/backend/base.py:126: in get_hosts
    cls.get_connection_type(),),
E   RuntimeError: One or more hosts is required with the ssh backend
=========================== 1 error in 0.05 seconds ============================
ERROR:

  RAN: '/usr/bin/testinfra spec/test_hostsfile.py --connection=ssh --ansible-inventory=.molecule/ansible_inventory'

  STDOUT:


  STDERR:
```

Imho, when switiching to `connection: ssh` the following should happen:

 * correct `--hosts` and `--ssh-config` flags are passed (as a sane default `.molecule/.vagrant/ssh-config` should be used -- it's already there because vagrant did that for us ;-))
 * and the `--ansible-inventory` should not be passed

In the meantime, I'm playing around with this, but it's a very fragile "workaround" and works only if the host name is known (i.e. only with a single instance):

```yaml
testinfra:
    connection: ssh
    hosts: jenkins-01
    ssh-config: .vagrant/ssh-config
```

**Comment by tknerr** [comment]
...actually not quite sure whether `.vagrant/ssh-config` is actually coming from vagrant, or even molecule..

**Comment by tknerr** [comment]
Ok.. so the `.vagrant/ssh-config` is actually created by molecule during `molecule verify`. However, it looks like it's not being picked up automatically.

Also worth noticing that in my case the `.vagrant` directory is being created directly under `<project_root>` directly, i.e.

 * there is `<project_root>/.molecule` and `<project_root>/.vagrant` side-by-side
 * ...but shouldn't it be `<project_root>/.molecule/.vagrant` ?

Not sure if that makes a difference, just an observation...

**Comment by retr0h** [comment]
Since this is an ansible project, and we are testing a server built by molecule.  We are using the ansible backend.  Using another backend isn't supported.

**Comment by dhutty** [comment]
@tknerr If you want to implement this, we would be interested in adding it, but adding support for non-Ansible testinfra backends is not a priority.

**Comment by tknerr** [comment]
Ok I see, misread this [in the docs](https://molecule.readthedocs.io/en/master/usage.html#testinfra). I can live on with my current workaround for now, but as soon as I add more than 1 instance I might probably give it a shot.

Actually the reason I was looking for the testinfra ssh backend was that I didn't get the ansible backend to work. Can also give that another try...

**Comment by tknerr** [comment]
@dhutty @retr0h using the workaround in https://github.com/metacloud/molecule/issues/330#issuecomment-237704216 the testinfra ansible backend is working again. So I have no longer the need for using the testinfra ssh backend. Feel free to close.

**Comment by retr0h** [comment]
@tknerr sweet!
