### ISSUE TITLE
Support for global ~/.molecule.yml File

### ISSUE THREAD

**Issue by tknerr** [metacloud/molecule#331]
It would be nice if we could define some defaults in a global `~/.molecule.yml` or similar file, that would be merged with every project specific `molecule.yml`.

E.g. for setting some defaults for the ansible `raw_ssh_args` in a single / central place

**Comment by kireledan** [comment]
I like this. Lemme see what I can do to get this in quickly.

**Comment by kireledan** [comment]
Actually - you can put some global defaults in ```~/.config/molecule/config.yml```. This config file has a lower priority than the local project config, but a higher priority than the package defaults. Hope this helps!

**Comment by tknerr** [comment]
@kireledan sweet, exactly what i was looking for! will give it a try :)
