### ISSUE TITLE
More control over ansible-galaxy flags / args

### ISSUE THREAD

**Issue by tknerr** [metacloud/molecule#333]
Usually I keep the `roles` dir for my own, and resolve dependencies to `role-deps`, e.g. like that:

```
$ rm -rf role-deps
$ ansible-galaxy install -r requirements.yml -p role-deps -f -vvv
```

Would be nice if molecule would give more control over the ansible-galaxy flags / args, so we have more control where the dependencies are resolved.

Another example would be adding the `--ignore-certs` flag, which is kind of mandatory to make galaxy work behind a proxy, etc..

**Comment by tknerr** [comment]
Wondering: are there maybe some specific `ANSIBLE_GALAXY_*` env vars that we could pass in via `raw_env_vars` in the meantime?

**Comment by tknerr** [comment]
At least galaxy's `--ignore-certs` can be controlled via an env var:
https://github.com/ansible/ansible/blob/devel/lib/ansible/constants.py#L297

For the `-p` flag in `ansible-galaxy install` (= roles path where they are downloaded to) I don't see a specific env var though

**Comment by retr0h** [comment]
> For the -p flag in ansible-galaxy install (= roles path where they are downloaded to) I don't see a specific env var though

You can specify that in your `requirements.yml`.

```
- src: https://github.com/geerlingguy/ansible-role-nfs
  version: 9c09e8e
  name: geerlingguy.nfs
  path: roles/
```

**Comment by tknerr** [comment]
@retr0h yes, I tried that, but looks like the `path` setting is ignored. This is Ansible 2.1.1.0. 

My `requirements.yml` says "role-deps":

```yaml
- name: timezone
  src: yatesr.timezone
  path: role-deps/
```


Still they are downloaded to "roles":

```
...
--> Installing role dependencies ...
- downloading role 'timezone', owned by yatesr
- downloading role from https://github.com/yatesr/ansible-timezone/archive/1.0.0.tar.gz
- extracting timezone to ./roles/timezone
- timezone was installed successfully
--> Starting Ansible Run ...
...
```

**Comment by tknerr** [comment]
looks like this was removed with Ansible 2.0... :-/
https://github.com/ansible/ansible/issues/13563#issuecomment-165482301

**Comment by tknerr** [comment]
One more thing I noticed:

```yaml
ansible:
  raw_env_vars:
    ANSIBLE_GALAXY_IGNORE: True
```

This config is not effective for `ansible-galaxy`, only for `ansible-playbook`

However, `ANSIBLE_GALAXY_IGNORE=True molecule test` correctly passes the env and makes it work behind a proxy
