### ISSUE TITLE
Support for Testing with multiple instances

### ISSUE THREAD

**Issue by tknerr** [metacloud/molecule#338]
Currently you can only test against a single instance. However, often you have the situation where you want to test master/slave setups or the like.

It would be awesome if molecule would support that, so that we don't need yet another testing framework for these kinds of tests.

In the `molecule.yml` this could boil down to something like `instance-sets` as an alternative to `instances`. From a provider perspective, this should map quite well to Vagrant [multi-machine](https://www.vagrantup.com/docs/multi-machine/) setups, docker [compose](https://docs.docker.com/compose/), or openstack [heat](https://wiki.openstack.org/wiki/Heat)

It's also something that is often requested for test-kitchen, but until today they don't support it either afaik.

What do you think?

**Comment by dhutty** [comment]
Molecule does support multiple instances, the `instances` directive that you refer to is a **list**:
```
vagrant:
  instances:
    - name: foo-instance-01
       ansible_groups: master
    - name: foo-instance-02
       ansible_group: slave```

**Comment by tknerr** [comment]
Oh, in fact yes. I thought that would create two completely separate molecule test runs, one for each instance. Just tried it out, and in fact it brings up both instances for one single run.

So this poses two new questions (can't find it in the docs):

1. how can you define which testinfra tests run against which of the instances? (currently same tests run on each instance)
1. how can you test with different parameter sets, e.g test your master/slave setup first with configuration X, then in configuration Y, then in configuration Z with a  separate molecule test run cycle each?

**Comment by retr0h** [comment]
> how can you define which testinfra tests run against which of the instances? (currently same tests run on each instance)

You can target by group or host/container name.

https://github.com/metacloud/molecule/tree/master/tests/functional/docker/scenarios/full/tests

> how can you test with different parameter sets (think scenarios), e.g test your master/slave setup first with configuration X, then in configuration Y, then in configuration Z with a separate molecule test run cycle each?

This isn't test kitchen.  We currently do not support scenarios.  However, one day in the future we hope to #204.

**Comment by tknerr** [comment]
@retr0h thanks for the pointer on targeting specific host groups with testinfra!

Regarding alignment with test-kitchen, yes would probably be nice, but not criticial for me to make it a 1:1 clone. Suites / scenarios support would be awesome to have at some point in the future in molecule. Multi-instance support is already awesome in molecule! :)

**Comment by retr0h** [comment]
> Regarding alignment with test-kitchen, yes would probably be nice, but not criticial for me to make it a 1:1 clone. Suites / scenarios support would be awesome to have at some point in the future in molecule. Multi-instance support is already awesome in molecule! :)

Yeah, we definitely want scenarios, and a cleaner config syntax.  However, implementing that is going to take some time.  Right now we have been focusing on stability and testing.  Once we feel confident, we can start to change more.

**Comment by retr0h** [comment]
@tknerr you good if I close this out?

**Comment by tknerr** [comment]
oh yes sure, thanks for clarification! Following #204 for the TK alignment...
