### ISSUE TITLE
`molecule status` should also work if no instances created yet

### ISSUE THREAD

**Issue by tknerr** [metacloud/molecule#339]
Not sure if something is running already, so the first thing I do is `molecule status`, but:

```
$ molecule status
ERROR: No instances created. Try `molecule create` first.
```

should display status imho an tell us status is "not created"

**Comment by kireledan** [comment]
I mean... it kinda already does that by saying "Error: no instances created". Or are you suggesting that it shouldn't be an error?

**Comment by retr0h** [comment]
> I mean... it kinda already does that by saying "Error: no instances created". Or are you suggesting that it shouldn't be an error?

Yeah, we have no status to really report.

**Comment by tknerr** [comment]
I would have expected that "not created" is also a valid status, but not an error condition. 

My expectation would have been something like that:

```
$ molecule status
╒═══════════╤═════════╤════════════╕
│ Name      │ State   │ Provider   │
╞═══════════╪═════════╪════════════╡
│ foo-hello │ not created │ virtualbox │
├───────────┼─────────┼────────────┤
│ bar-hello │ not created │ virtualbox │
╘═══════════╧═════════╧════════════╛
ubuntu1604  (default)
virtualbox  (default)
```

Similar to what you get from `vagrant status` for example:

```
```

**Comment by retr0h** [comment]
Yeah, understood it's a valid concern.
