### ISSUE TITLE
Validators could use more tests

### ISSUE THREAD

**Issue by retr0h** [metacloud/molecule#353]
Validators have low coverage.  Lets fix that.

```
molecule/validators.py                             69     49    29%
```

**Comment by kireledan** [comment]
Look's like the coverage isn't too too bad. Just the trailing that really needs most of the attention.
```
molecule/verifier/base.py                         7      1    86%
molecule/verifier/serverspec.py                  33      8    76%
molecule/verifier/testinfra.py                   33     11    67%
molecule/verifier/trailing.py                    54     33    39%

**Comment by retr0h** [comment]
Yeah, now that they were broken out, they got some extra coverage.  The tree crawling going to be tricky.

**Comment by retr0h** [comment]
Going to close, we have bigger fish to fry, and is no longer much of an issue after the verifier refactoring.
