### ISSUE TITLE
No doc for #3467

### ISSUE THREAD

**Issue by nkakouros** [metacloud/molecule#3591]
The new feature added in #3467 is not documented in the docs. 

The new feature:

> provide[s] alternative location for
> tests or side effects playbook in test sequence like this:
> 
>  ```
>  test_sequence:
>     - create
>     - converge
>     - verify
>     - side_effect side_effect1.yml
>     - verify tests_for_effect1/
>     - side_effect side_effect2.yml
>     - verify tests_for_effect2/
>  ```

**Comment by amarao** [comment]
Oh, that's my miss. I'll try to add it.

**Comment by timblaktu** [comment]
@amarao I was just about to fork and create a PR for filling several gaps in the docs that I've found while trying to get it to work as a newcomer. Can i just send you some snippets to include in your changeset? These are things like:

[Examples](https://github.com/ansible-community/molecule/blob/main/docs/examples.rst) needs to describe how to customize a Docker image using Dockerfile.j2, where the template comes from, what `pre_build_image` actually means, etc.

**Comment by amarao** [comment]
I'm not a core developer, so I'll try to hack into docs by myself first time.
