### ISSUE TITLE
defining `['test']['sequence']` seems to be ignored: atleast when driver is openstack

### ISSUE THREAD

**Issue by rjfellman** [metacloud/molecule#381]
I've got a custom test sequence on a role, leaving idempotence out but it is still tested. This wasn't the case in the last release I used though `1.8.2` 

```
  # sequence of commands to run when performing `molecule test`
  test:
    sequence:
      - destroy
      - create 
      - converge
      - verify
      - destroy

```

**Comment by russ216** [comment]
Debugging with iPython, here is what i see if i drop into `test.py`
```
In [2]: self.molecule.config.config['molecule']['test']
Out[2]: 
{'sequence': ['destroy',
  'syntax',
  'create',
  'converge',
  'idempotence',
  'verify']}
```

**Comment by russ216** [comment]
And weirdly enough, if i add just a random step in there
```
test:
    sequence:
      - blah
```

```
'test': {'sequence': ['destroy',
    'syntax',
    'create',
    'converge',
    'idempotence',
    'verify',
    'blah']},
```

**Comment by retr0h** [comment]
What version of molecule are you using?

**Comment by russ216** [comment]
@retr0h - this is just pip installing local copy of master. head is up to date as of yesterday - i could try with anything that may have gone in today
`3432e18b5912359fdaacd7ca068f77d0c6b5b453`

**Comment by retr0h** [comment]
I was curious if this is a problem only on master or if you are seeing the same problem on the released 1.8.4 version on pypi.

**Comment by russ216** [comment]
hmm let me try that too! (just recloned master today and still the same)

**Comment by russ216** [comment]
Okay, it seems okay on `1.8.4` - sorry, was this an okay place to bring it up? do you think it could be valid? This worked using an earlier version of master.

**Comment by retr0h** [comment]
Yeah, I think I have an idea of the problem.  I believe it is the dict merging strategy.  We are using [anyconfig.MS_DICTS_AND_LISTS](https://github.com/ssato/python-anyconfig/blob/master/docs/usage.rst) on master.

**Comment by russ216** [comment]
@retr0h - that did it, works as expected with that changed back. thanks for your help!

**Comment by retr0h** [comment]
```
  syntax: commands succeeded
  py27-ansible19-unit: commands succeeded
  py27-ansible19-functional: commands succeeded
  py27-ansible20-unit: commands succeeded
  py27-ansible20-functional: commands succeeded
  py27-ansible21-unit: commands succeeded
  py27-ansible21-functional: commands succeeded
  doc: commands succeeded
  congratulations :)
```

**Comment by retr0h** [comment]
1.9 was released to  [pypi](https://pypi.python.org/pypi/molecule/1.9.0) today.

**Comment by rjfellman** [comment]
Thanks! This is much better now
