### ISSUE TITLE
Cut a 1.9 release

### ISSUE THREAD

**Issue by retr0h** [metacloud/molecule#382]
We need to verify 1.9 is ready for release.

- [x] ~~#381~~
- [x] ~~#334~~ 
- [x] Verify provider overrides work as expected.  Basically we want to verify pip's workflow will continue to work with parallels under 1.9.
- [x] Move releases back to master, breaking changes will go under a v2 branch.  Update [documentation](https://github.com/metacloud/molecule/blob/master/doc/source/development.rst#branches).
- [x] Verify readthedocs is pointed to the proper branch, which will be released to pypi.  Update readme rtd links as well.
- [x] Cut a 1.9 tag and release.

**Comment by kireledan** [comment]
Are we checking with the other providers as well besides parallels?

**Comment by retr0h** [comment]
> Are we checking with the other providers as well besides parallels?

We already test virtualbox.  We just happen to have a few co-workers that use parallels, vmfusion, in a particular way, and want to be sure that doesn't break.

**Comment by retr0h** [comment]
#390

**Comment by retr0h** [comment]
Released to pypi.  https://pypi.python.org/pypi/molecule
