### ISSUE TITLE
Feature request: aws provider

### ISSUE THREAD

**Issue by hryamzik** [metacloud/molecule#410]
Would really love to see `aws` support.

**Comment by kireledan** [comment]
This is currently being developed. It will most likely come in the 2.0 release with the driver refactor.

**Comment by retr0h** [comment]
I'm going to close this out.  We don't have an internal use case for this.  *If someone in the community wishes to implement it*, that is *great*.  However, having an issue open for this doesn't make sense, since nobody on the molecule is slated to work on it.

**Comment by msheiny** [comment]
hey @retr0h - I totally understand if this is something your team would like to farm out. This is something I'm really interested in adding (mostly for selfish reasons) - can you provide more guidance on where this can be added? Ideally I'd use the vagrant to save some time. I saw someone else was working on this at one point - but I also see your team is in the midst of a big refactor. Is my time better spent trying to target the refactored vagrant driver?

**Comment by retr0h** [comment]
@msheiny your best bet would be adding this functionality to our v2 branch.  The v2 branch uses ansible to manage instances, therefore it would be a simple playbook to spin up an instance in Amazon, which Molecule would converge against.  v2 is a few months out, but makes most sense there.

**Comment by Deepakkothandan** [comment]
@msheiny are you working on this ?

**Comment by retr0h** [comment]
@Deepakkothandan @msheiny I'll likely implement it by EOW.  I'm refactoring v2's functional tests ATM, and want to test the ease of driver additions.  AWS seemed like a good candidate.

**Comment by msheiny** [comment]
noopeee @Deepakkothandan / @retr0h -- sorry i got sidetracked in other projects :( but  I did essentially end up using ansible playbooks against ec2 for standup and teardown in the project in question that I needed this on.

Ill hold tight for your changes @retr0h and see if I can append to them. It would be great to switch my existing hobbled together bash scripts + ansible playbooks to utilize molecule instead.

**Comment by retr0h** [comment]
@msheiny @Deepakkothandan just released ec2 support https://github.com/metacloud/molecule/pull/832.

**Comment by Deepakkothandan** [comment]
@retr0h Awesome... I will take it up for a spin and update you.
