### ISSUE TITLE
Add ansible groups inheritance

### ISSUE THREAD

**Issue by o0st** [metacloud/molecule#423]
It would be great to have a possibility to describe groups inheritance in the ansible_groups parameter.
What I mean is an inventory file after creation of instance(s):
```ini
[common:children]
molecule_common
some_instance_name_1

[molecule_common:children]
molecule_hosts

[molecule_hosts]
some_instance_name_0
```

**Comment by retr0h** [comment]
Vagrant provides a similar mechanism.  @kireledan you want to take a stab at this?

```
ansible.groups = {
  "web" => ["vm1", "vm2"],
  "db"  => ["vm3"]
}
```

**Comment by o0st** [comment]
But I'm talking about more complicated linking (include group as child of another group) vm1 => group1 => group2, in this case ansible inventory file should look like:
```ini
[group2:children]
group1

[group1:children]
vm1
```

**Comment by retr0h** [comment]
> But I'm talking about more complicated linking

Yeah, I get it.
