### ISSUE TITLE
Vagrant driver does not allow customize vm.provider parameters

### ISSUE THREAD

**Issue by o0st** [metacloud/molecule#424]
Have faced DNS not working Vagrant issue (https://www.vagrantup.com/docs/virtualbox/common-issues.html) which could not be fixed from Molecule because there is now way to pass the modifyvm parameter to the Vagrantfile.

**Comment by abrown-sg** [comment]
The Vagrantfile template allows you to pass in arguments at the instance level as well as for all instances using "raw_config_args."  Would that work for you?

See here: https://github.com/metacloud/molecule/blob/master/doc/source/driver/vagrant/usage.rst#comprehensive-usage

**Comment by retr0h** [comment]
So basically something like this.

```
vagrant:
  raw_config_args:
    - "vm.provider :virtualbox do |vb| vb.customize ['modifyvm', :id, '--natdnshostresolver1', 'on'] end"
```

**Comment by o0st** [comment]
It works thanks

**Comment by hryamzik** [comment]
Just another example:

```yml
driver:
  name: vagrant
vagrant:
  raw_config_args:
    - "vm.network :private_network, type: \"dhcp\""
    - |
       vm.provider :virtualbox do |vb|
            vb.customize ["modifyvm", :id, "--usb", "on", "--usbehci", "on"]
            vb.customize ["usbfilter", "add", "0",
                "--target", :id,
                "--name", "3g modem",
                "--manufacturer", "HUAWEI Technology",
                "--product", "HUAWEI Mobile"]
       end
```
