### ISSUE TITLE
Add support of ansible extra vars

### ISSUE THREAD

**Issue by o0st** [metacloud/molecule#425]
Would be great to have a mechanism which would allow to pass ansible extra vars from molecule config.

**Comment by retr0h** [comment]
[We do](https://molecule.readthedocs.io/en/stable-1.9/configuration.html#host-group-vars).

**Comment by o0st** [comment]
Probably the 'extra_vars' variant should be documented.
Thanks.

**Comment by retr0h** [comment]
> Probably the 'extra_vars' variant should be documented.

It [is](https://molecule.readthedocs.io/en/stable-1.10/configuration.html#ansible-section).

**Comment by Raffaello** [comment]
is this still true for version 2.8.x ?

**Comment by retr0h** [comment]
Provisioner [options](http://molecule.readthedocs.io/en/latest/configuration.html#id12).
