### ISSUE TITLE
Idempotence test failed.

### ISSUE THREAD

**Issue by skitoo** [metacloud/molecule#437]
Hello,

* Python version: 2.7.12
* Molecule version : 1.9.1
* Distribution : archlinux

I want to install docker via ansible and when I do that, I have on error:

```
Idempotence test failed.
The idempotence plugin was not found or did not provide the required information. Therefore the failure details cannot be displayed.
```
If I remove docker installation into my Ansible config, molecule run correctly.
I run molecule into a virtualenv and the following files exists in my virtualenv:
* share/molecule/ansible/plugins/callback/idempotence
* etc/bash_completion.d/molecule.bash-completion.sh

I have a Github repository with a PullRequest where you can find my code : https://github.com/skitoo/bender/pull/1
As you can see, when travis computes my code, it indicates same error : https://travis-ci.org/skitoo/bender/builds/15736796

Thank you.

**Comment by retr0h** [comment]
I'll check it out in the next couple of days.  I am thinking this has to do with the python path.  I have my etcd roles gated through travis and molecule.  They are working fine, however, I do use a virtualenv.

* [travis config](https://github.com/retr0h/ansible-etcd/blob/master/.travis.yml).
* travis job executing [idempotence tests](https://travis-ci.org/retr0h/ansible-etcd/builds/157375821  )

As a work-a-round you can redefine the test sequence in your molecule.yml to ignore the idempotence test.

```
molecule:
  test:
    sequence:
      - destroy
      - syntax
      - create
      - converge
      - verify
```

**Comment by retr0h** [comment]
This is [the code](https://github.com/metacloud/molecule/blob/master/molecule/command/converge.py#L115-L124) that adds the callback plugin path during converge.

It is using `sys.prefix`, which in my venv is `/Users/jodewey/git/ansible-etcd/venv/bin/..`, which explains why it finds it.

```
[jodewey:~/git/ansible-etcd] [venv] test-correction+ ± find . -name "idempotence*"
./venv/share/molecule/ansible/plugins/callback/idempotence
./venv/share/molecule/ansible/plugins/callback/idempotence/idempotence.py
./venv/share/molecule/ansible/plugins/callback/idempotence/idempotence.pyc
```

/cc @rabadin

**Comment by retr0h** [comment]
I'm actually thinking we shouldn't use data_files at all.

I tend to agree with [this](http://python-packaging.readthedocs.io/en/latest/non-code-files.html#adding-non-code-files).

> Files which are to be used by your installed library (e.g. data files to support a particular computation method) should usually be placed inside of the Python module directory itself. E.g. in our case, a data file might be at funniest/funniest/data.json. That way, code which loads those files can easily specify a relative path from the consuming module’s __file__ variable.

**Comment by retr0h** [comment]
Released molecule [1.10.3](https://pypi.python.org/pypi/molecule) to pypi to address this bug. 

There is no change in workflow.  Molecule still reports if a converge was idempotent or not.  However, it no longer reports which task(s) are not idempotent.  This greatly simplifies the code and issues around this.

**Comment by skitoo** [comment]
@retr0h Thank you for your reactivity.
I just restart the Travis job, it really installed the new version 1.10.3, but the error seems still present: https://travis-ci.org/skitoo/bender/builds/157367959
Unit tests do not run.

**Comment by retr0h** [comment]
Hi Skitoo, I haven't looked at your roles, but this is part of the workflow.  It is erroring b/c your task(s) are making changes after a converge.  The idempotence check is making sure changed=0 is reported on a subsequent converge.

On your development machine you should run molecule converge twice, and see which task is reporting as changed on the second run.

```
--> Idempotence test in progress (can take a few minutes) ...
--> Starting Ansible Run ...
Idempotence test failed.

```

**Comment by retr0h** [comment]
I was looking at your role.  The `features/fail2ban` branch is failing b/c the tasks are not idempotent.

```
TASK [fail2ban : Enable and start fail2ban service] ****************************
changed: [bender]
```

**Comment by retr0h** [comment]
@skitoo This should correct your problem on the `features/fail2ban` branch.  You will want to verify this image is acceptable, or build your own using [dockerfile](http://molecule.readthedocs.io/en/stable-1.10/driver/index.html#options) option of molecule.

```
[jodewey:~/git/bender] features/fail2ban(+3/-1) ± git diff
diff --git a/molecule.yml b/molecule.yml
index 394c5c1..e3af07f 100644
--- a/molecule.yml
+++ b/molecule.yml
@@ -5,5 +5,7 @@ ansible:
 docker:
   containers:
   - name: bender
-    image: debian
+    image: ssiegel/base-debian-systemd
     image_version: latest
+    privileged: True
+    command: /sbin/init
```

You also have a test for `ca-certificates` which isn't installed by your role.

**Comment by skitoo** [comment]
@retr0h Thank you for your help !
It works fine :)

For ca-certificates, it's strange, with base debian image, ca-certificates it's installed with apt-transport-https package... I finaly installed "manualy" in my playbook.

Thanks again :)
