### ISSUE TITLE
Docker driver renders inventory file with `connection=docker` rather than `ansible_connection=docker`

### ISSUE THREAD

**Issue by keyboardscience** [metacloud/molecule#459]
The docker driver renders out `connection=docker` within `.molecule/ansible_inventory`. The variable should be `ansible_connection=...` so a `ansible.executor.task_queue_manager.TaskQueueManager` can pick up the connection type. Without the ansible_connection inventory variable testinfra falls back on the paramiko backend to connect, which doesn't work for containers.  I'm using molecule in conjunction with pytest and would like to be able to run tests without invoking `molecule verify`. It does not affect `molecule verify` because the command runs testinfra with a `--connection` flag rather than reading the inventory file to determine connection type.

**Comment by retr0h** [comment]
Thanks @keyboardscience
