### ISSUE TITLE
installing molecule

### ISSUE THREAD

**Issue by pleegor** [metacloud/molecule#469]
Hi, 

I am trying to use molecule for ansible role testing and I am having problems installing it. I installed it once but by mistake I deleted it, so I am re-installing it again. After I ran `pip install molecule` everything seemed like it was successful. However, when I ran `molecule --version` , I got the following error:
`molecule init test
-bash: molecule: command not found`

I am running OS X.

**Comment by signed8bit** [comment]
@pleegor When you run "pip list" what do you see? Is "molecule" there?

**Comment by retr0h** [comment]
Worked with @pleegor on slack.  This issue was resolved by `brew install python`.  The python2.6 on El Capitan was an issue.

**Comment by pleegor** [comment]
Per suggestion of my co-worker @tleyden I ran `brew install python` which solved the problem. Even though, Python interpreter does come pre-installed with OS X, Apple completely locks it down in El Capitan so pip cannot install anything. As soon as you complete brew installation you will see that `which python` will provide python's location as `/usr/local/bin/python` instead of `/usr/bin`

**Comment by tleyden** [comment]
The issues with the system python issues is described here: https://github.com/pypa/pip/issues/3165#issuecomment-152570526

**Comment by retr0h** [comment]
@tleyden 🎸

**Comment by abdennour** [comment]
Just add `/Users/${USER}/Library/Python/3.7/bin` to the PATH.

**~/bash_profile**
```sh
export PATH=/Users/youruser/Library/Python/3.7/bin:$PATH

```
