### ISSUE TITLE
Idempotence check failures when running molecule test

### ISSUE THREAD

**Issue by milosgajdos83** [metacloud/molecule#488]
I'm running `molecule 1.11.0` with `ansible 2.1.1.0` and I noticed some strange behaviour when running `molecule test` with regards to role idempotence.

When running the idempotence test as part of the full blown `molecule test` cycle, I'm getting idempotence failures:

```
--> Idempotence test in progress (can take a few minutes) ...
--> Starting Ansible Run ...
Idempotence test failed.
```

As soon as I get this error I run the idempotence check separately and it passes without errors:
```
$ molecule idempotence
--> Idempotence test in progress (can take a few minutes) ...
--> Starting Ansible Run ...
Idempotence test passed.
```

Equally, running `molecule converge` multiple times on the same role returns:
```
PLAY RECAP *********************************************************************
zk01                       : ok=17   changed=0    unreachable=0    failed=0
zk02                       : ok=17   changed=0    unreachable=0    failed=0
```

Which makes me wonder why does `molecule test` fail `idempotence` check when if I run `converge` and `idempotence` separately they pass?

**Comment by retr0h** [comment]
Hi @milosgajdos83.  Do you have this repo uploaded anywhere so I can look it over?

**Comment by milosgajdos83** [comment]
Unfortunately I don't :-/ It's a private company repo. I'll check with my company if I can gist it somewhere without breaking any contracts. I'll look into the Molecule source code, too -- I haven't had time for that today, but I still wanted to open an issue so I don't forget about it.

**Comment by retr0h** [comment]
Sure, no problem.  If you could just give me something stripped down that would help.  I have performed tests around this and haven't run into this particular issue, so would be interested in finding out what you're running into.

**Comment by retr0h** [comment]
I am unable to reproduce.  We have functional tests which are testing this [scenario](https://github.com/metacloud/molecule/tree/master/test/functional/driver/docker/scenarios/command_idempotence).

Please re-open when you can supply further information about your issue or sample code which is failing.

**Comment by milosgajdos83** [comment]
So, I looked into this properly again. Instead of `docker` provider I used `vagrant` provider and tested the same Anisble [role](https://gist.github.com/milosgajdos83/326dc4f5b04c9ca6bcdbf3de8f507d3f).

When I run `molecule test` I can successfully reproduce the idempotence weirdness:

```
--> Idempotence test in progress (can take a few minutes) ...
--> Starting Ansible Run ...
Idempotence test failed because of the following tasks:
Traceback (most recent call last):
  File "/Users/milosgajdos/.virtualenvs/molecule/bin/molecule", line 11, in <module>
    sys.exit(main())
  File "/Users/milosgajdos/.virtualenvs/molecule/lib/python2.7/site-packages/molecule/cli.py", line 41, in main
    cli(obj={})
  File "/Users/milosgajdos/.virtualenvs/molecule/lib/python2.7/site-packages/click/core.py", line 716, in __call__
    return self.main(*args, **kwargs)
  File "/Users/milosgajdos/.virtualenvs/molecule/lib/python2.7/site-packages/click/core.py", line 696, in main
    rv = self.invoke(ctx)
  File "/Users/milosgajdos/.virtualenvs/molecule/lib/python2.7/site-packages/click/core.py", line 1060, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/milosgajdos/.virtualenvs/molecule/lib/python2.7/site-packages/click/core.py", line 889, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/milosgajdos/.virtualenvs/molecule/lib/python2.7/site-packages/click/core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "/Users/milosgajdos/.virtualenvs/molecule/lib/python2.7/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/Users/milosgajdos/.virtualenvs/molecule/lib/python2.7/site-packages/molecule/command/test.py", line 96, in test
    util.sysexit(t.execute()[0])
  File "/Users/milosgajdos/.virtualenvs/molecule/lib/python2.7/site-packages/molecule/command/test.py", line 46, in execute
    status, output = c.execute(exit=False)
  File "/Users/milosgajdos/.virtualenvs/molecule/lib/python2.7/site-packages/molecule/command/idempotence.py", line 61, in execute
    LOG.error('\n'.join(self._non_idempotent_tasks(output)))
  File "/Users/milosgajdos/.virtualenvs/molecule/lib/python2.7/site-packages/molecule/command/idempotence.py", line 104, in _non_idempotent_tasks
    res.append('* {}'.format(task_name.groups()[0]))
AttributeError: 'NoneType' object has no attribute 'groups'
```

I have investigated the `guilty_line` by putting in some print statements to `idempotence.py` out of curiosity like this:

```
print("=========== GUILTY LINE ================")
print(guilty_line)
print("========================================")
```

When I ran `molecule test` again to see the the output I get the following:

```
=========== GUILTY LINE ================
TASK [ansible-zookeeper : Render ZooKeeper myid file] **************************
========================================
=========== GUILTY LINE ================
+1
========================================
```

The first print out is from the `converge` phase, but the second one is where things crash i.e. that's the `idempotence` phase of full `test` run.

Strangely enough, running `molecule idempotence` after `molecule test` crashes, succeeds just fine:

```
$ molecule idempotence
--> Idempotence test in progress (can take a few minutes) ...
--> Starting Ansible Run ...
Idempotence test passed.
```

Not seeing my debug statements printed makes me think that `molecule idempotence` runs the idempotence check correctly but in a totally different way than when the idempotence check is done as part of the full `molecule test` run :-\

**Comment by milosgajdos83** [comment]
Turns out, this has nothing to do with `molecule` but rather with `ansible` or the way our role behaves.

Strange thing to me is that **second** `converge` only `myid` file gets rendered -- all the other resources are idempotent.

On the **third** `converge` everything stays idempotent.

Very puzzling! Thanks for the help here -- no need to reopen the issue.

**Comment by retr0h** [comment]
@milosgajdos83 I noticed the exact same thing when looking at the other issue (#551) you reported.  The first run has changes, the second run has additional changes to log dir and myid file, and the third run makes no changes.

I believe it is the order in which you are doing things.  Check it.  After the following our permissions should be correct on the data dir.  However, they are not.

```
TASK [zookeeper : Create ZooKeeper log folder] *********************************
ok: [zk01]

TASK [zookeeper : Create ZooKeeper data folder] ********************************
ok: [zk01]

TASK [zookeeper : Render ZooKeeper myid file] **********************************
changed: [zk01]
--- before
+++ after: dynamically generated
@@ -0,0 +1 @@
+1
```

```
[root@65e8e75aae34 zookeeper]# ls -altr
total 16
drwxr-xr-x 25 root      root      4096 Oct 13 17:46 ..
drwxr-xr-x  2 root      root      4096 Oct 13 17:46 version-2
-rw-r--r--  1 root      root         2 Oct 13 17:46 myid
drwxr-xr-x  3 zookeeper zookeeper 4096 Oct 13 17:46 .
[root@65e8e75aae34 zookeeper]# pwd
/var/lib/zookeeper
```

I believe the problem is with your `Initialize Zookeeper` task.  If you run that before the `Create ZooKeeper data folder` task, you should be good.
