### ISSUE TITLE
Error with ansible lint

### ISSUE THREAD

**Issue by fabMrc** [metacloud/molecule#505]
Hi

I used molecule verify and it throw a console error
More generally when it run the complete test lifecycle it break the workflow when idempotence or lint failed I think it is not clean. It should end the cycle, destroy docker images and make a report instead.
I am not really agree with the idea to force usage of lint because of some false positive and it exists software specialised like sonarQube for that.
ignore options does not work also

[ANSIBLE0011] All tasks should be named
/home/vagrant/global-resources/roles/artifacts-provider/tasks/nexus-provider-task.yml:2
Task/Handler: set_fact outer_loop={{item}}

[ANSIBLE0011] All tasks should be named
/home/vagrant/global-resources/roles/artifacts-provider/tasks/nexus-provider-task.yml:23
Task/Handler: include_vars {{ item }}

[ANSIBLE0011] All tasks should be named
/home/vagrant/global-resources/roles/artifacts-provider/tasks/nexus-provider-task.yml:44
Task/Handler: set_fact artifacts={{mvn_result.dest}} {{artifacts | default()}}

Traceback (most recent call last):
  File "/bin/molecule", line 11, in <module>
    sys.exit(main())
  File "/usr/lib/python2.7/site-packages/molecule/cli.py", line 68, in main
    CLI().main()
  File "/usr/lib/python2.7/site-packages/molecule/cli.py", line 64, in main
    util.sysexit(c.execute()[0])
  File "/usr/lib/python2.7/site-packages/molecule/command/test.py", line 65, in execute
    status, output = c.execute(exit=False)
  File "/usr/lib/python2.7/site-packages/molecule/command/verify.py", line 59, in execute
    v.execute()
  File "/usr/lib/python2.7/site-packages/molecule/verifier/ansible_lint.py", line 50, in execute
    sh.ansible_lint(self._playbook, _out=LOG.info, _err=LOG.error)
  File "/usr/lib/python2.7/site-packages/sh.py", line 1021, in __call__
    return RunningCommand(cmd, call_args, stdin, stdout, stderr)
  File "/usr/lib/python2.7/site-packages/sh.py", line 486, in __init__
    self.wait()
  File "/usr/lib/python2.7/site-packages/sh.py", line 500, in wait
    self.handle_command_exit_code(exit_code)
  File "/usr/lib/python2.7/site-packages/sh.py", line 516, in handle_command_exit_code
    raise exc(self.ran, self.process.stdout, self.process.stderr)
sh.ErrorReturnCode_2:

  RAN: '/bin/ansible-lint tests/nexus/test_nexus-provider.yml'

  STDOUT:

  STDERR:

**Comment by retr0h** [comment]
@fabMrc We run ansible-lint on the roles being developed.  Molecule is opinionated.

**Comment by dhutty** [comment]
It sounds like there are 2 separate items here:
1) You got a traceback from `molecule verify`
2) You want to be able to turn off ansible-lint

1) this is a problem - please show us a minimal example of the play/playbook so that we can recreate/investigate.
2) This is an opinionated tool, so if you want to submit a patch that allows ansible-lint to be disabled from `molecule verify`, it will be considered - so long as the default behaviour is the same as now; but this is not a priority.

**Comment by retr0h** [comment]
Will re-open and cleanup the stack trace.

**Comment by retr0h** [comment]
@fabMrc -- released stacktrace cleanup to pypi as molecule 1.11.4.

**Comment by m4rkw** [comment]
Hi,

Just curious since Molecule is opinionated, what is Molecule's opinion on how to use ansible to install python onto a machine that does not currently have python installed?

We currently do this with:

```
- name: update apt cache
  raw: sudo apt-get update
- name: install python
  raw: sudo apt-get -y install python2.7
- name: make python2.7 a python alternative
  raw: sudo update-alternatives --install /usr/bin/python python /usr/bin/python2.7 10
```

But this doesn't pass ansible-lint.  Since you don't provide a way to disable ansible-lint I presume you must know another way to achieve this?

**Comment by retr0h** [comment]
You can always add tags to your roles for things you wish to skip.  Check the ansible-lint docs.

**Comment by haad** [comment]
For external dependency roles is impossible to add all required tags.

**Comment by retr0h** [comment]
Molecule v2 will address this.

**Comment by sean-abbott** [comment]
When is molecule v2 coming out? Is there a way to NOT run lint or idempotence against roles that my role depends on as is?
