### ISSUE TITLE
Syntax problem with generated group_vars and host_vars files

### ISSUE THREAD

**Issue by mjuenema** [metacloud/molecule#506]
When I define ```host_vars``` (or ```group_vars```) in ```molecule.yml``` the generated files look strange. What did I do wrong???

**.molecule/host_vars/ansible-role-postgresql90**:
```---
!!python/object/new:m9dicts.dicts.UpdateWithMergeDict
dictitems:
  postgresql_version: 9.0
```

**molecule.yml**
```---
driver:
  name: vagrant

ansible:
  host_vars:
    ansible-role-postgresql90:
      - postgresql_version: 9.0

vagrant:
  platforms:
    - name: centos-6
      box: centos/6

instances:
  - name: ansible-role-postgresql90
```

**Comment by retr0h** [comment]
> When I define host_vars (or group_vars) in molecule.yml the generated files look strange. What did I do wrong???

That's just anyconfig's structure getting searialized to yaml.  Ansible should read it and work properly.  We [have tests for this scenario](https://github.com/metacloud/molecule/tree/master/test/functional/driver/docker/scenarios/group_host_vars).

**Comment by mjuenema** [comment]
Yes, but it changes the variable name from ```postgresql_version``` to ```dictitems.postgresql_version```.

**Comment by retr0h** [comment]
Not in my tests.  All works as expected.

**Comment by mjuenema** [comment]
Yes, you are right. Sorry for the confusion.

**Comment by retr0h** [comment]
@mjuenema no problem.  Thank you for the report!
