### ISSUE TITLE
molecule init role does not make the templates dir.

### ISSUE THREAD

**Issue by bbaassssiiee** [metacloud/molecule#509]
When I issue the command: 
`molecule init role `
I expect a directory
`role/templates`
But it is not there.

**Comment by retr0h** [comment]
I suppose we could add that.  FYI - `molecule init` is not synonymous to `ansible-galaxy init`, but we do have other empty scaffolding in there.

**Comment by retr0h** [comment]
> I suppose we could add that. FYI - molecule init is not synonymous to ansible-galaxy init, but we do have other empty scaffolding in there.

Actually, I'm going to close this issue out.  Writing out an template/ directory doesn't seem all that useful, especially when a role may or may not even use it.

If the user needs a templates dir they can create it, just as a user needs to create a files directory when dealing with non-templates.
