### ISSUE TITLE
Fact gathering for other containers does not seem to work

### ISSUE THREAD

**Issue by lxhunter** [metacloud/molecule#510]
Hi Guys,

if I gather facts of other hosts on an run, the network facts are not set. e.g. ansible_eth0 

Test case with error: https://github.com/lxhunter/network_bug

i would really appreciate help :)

Cheers,
Alex

**Comment by retr0h** [comment]
@lxhunter As far as I am aware this is an issue with Ansible + docker.  I have ran into similar issues when testing my containers.

I rolled my own simple fact gathering for my purposes.

* [molecule.yml](https://github.com/retr0h/ansible-etcd/blob/master/molecule.yml#L5-L7).
* [simple fact library](https://github.com/retr0h/ansible-etcd/blob/master/library/docker_facts.bash)

**Comment by lxhunter** [comment]
Thanks, will try that, but i am still curious on why the interfaces do not seem to be present at that time.

**Comment by retr0h** [comment]
@lxhunter oh, it looks like the container needs to provide [iproute](https://github.com/ansible/ansible/blob/06d46a1ecc7b6726b0e2e7341409a7ab33b549a2/lib/ansible/module_utils/facts.py#L2241-L2245).

**Comment by retr0h** [comment]
@lxhunter any luck?

**Comment by lxhunter** [comment]
Works perfect!

**Comment by retr0h** [comment]
> Works perfect!

🎸 🤘
