### ISSUE TITLE
Multiple Test Suites Support

### ISSUE THREAD

**Issue by atosatto** [metacloud/molecule#518]
Test Kitchen allows to easily implement different test suites: http://kitchen.ci/docs/getting-started/adding-suite.
This feature is really cool because it allows to execute different tests on a fresh infrastructure.

Is there any plan to implement such feature in molecule?

PS: Molecule is really great! Thank you for what you're building! 😄

**Comment by retr0h** [comment]
Hi @atosatto - Yes, this is a key feature we would like to add.  Was hoping to implement as part of #204.  However, when time permits I might just implement this feature on it's own.

I am currently calling it scenario based testing.  However, is a bit tricky how to rework the config to handle this properly.  Test kitchen doesn't support multiple servers, so the syntax never needs to account for per host configuration like we do in molecule (e.g. interfaces, vagrant raw args, ansible groups).  

Created #519 to start the discussion.

**Comment by retr0h** [comment]
Closing in favor of #519.
