### ISSUE TITLE
Unable to use existing group_vars directory

### ISSUE THREAD

**Issue by chrisb3ll** [metacloud/molecule#522]
Hi

Please can someone help to explain the idea around utilising group_vars for isolated role testing.

I can see from https://github.com/metacloud/molecule/pull/421, the dynamic symlink was removed (or not used), and the suggestion is now to create a group_vars directory in the project root.

I'd rather not maintain symlinks/dir copies for each and every role or duplicate vars in the role specific playbook.yml.

Is there a better way? (thanks in advance)

**Comment by retr0h** [comment]
Hi @chrisb3ll - @kireledan added group/host vars support (#202) through molecule.yml.  Since molecule, is intended to test roles in isolation, once can use the solution provided in #202.

**Comment by chrisb3ll** [comment]
Thanks @retr0h - I understand now, I'll adjust my approach.
