### ISSUE TITLE
1.1.2 - molecule verify gives ruby ssh error

### ISSUE THREAD

**Issue by sandinak** [metacloud/molecule#54]
This is relevant to the conversion from pre-1.0 molecule to 1.1.2,  I have been re-writing molecule_playbook.yml into molecule.yml and playbook.yml.   I also removed the old .molecule and Vagrant files to clean up.  With the update to 1.1.2 I am now getting the included error, yet molecule login works fine.  Not sure where the problem exists.

*** Run serverspec on vagrant1-ubuntu instance ***
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/bin/ruby -I/Library/Ruby/Gems/2.0.0/gems/rspec-support-3.3.0/lib:/Library/Ruby/Gems/2.0.0/gems/rspec-core-3.3.2/lib /Library/Ruby/Gems/2.0.0/gems/rspec-core-3.3.2/exe/rspec --pattern spec/\*_spec.rb,spec/vagrant1/\*_spec.rb,spec/hosts/vagrant1/\*_spec.rb
/Library/Ruby/Gems/2.0.0/gems/net-ssh-2.9.2/lib/net/ssh.rb:224:in `start': Authentication failed for user vagrant@127.0.0.1 (Net::SSH::AuthenticationFailed)
	from /Library/Ruby/Gems/2.0.0/gems/specinfra-2.44.1/lib/specinfra/backend/ssh.rb:76:in `create_ssh'
	from /Library/Ruby/Gems/2.0.0/gems/specinfra-2.44.1/lib/specinfra/backend/ssh.rb:110:in `ssh_exec!'
	from /Library/Ruby/Gems/2.0.0/gems/specinfra-2.44.1/lib/specinfra/backend/ssh.rb:17:in `block in run_command'
	from /Library/Ruby/Gems/2.0.0/gems/specinfra-2.44.1/lib/specinfra/backend/ssh.rb:67:in `with_env'
	from /Library/Ruby/Gems/2.0.0/gems/specinfra-2.44.1/lib/specinfra/backend/ssh.rb:16:in `run_command'
	from /Library/Ruby/Gems/2.0.0/gems/specinfra-2.44.1/lib/specinfra/helper/detect_os.rb:13:in `run_command'
	from /Library/Ruby/Gems/2.0.0/gems/specinfra-2.44.1/lib/specinfra/helper/detect_os/suse.rb:3:in `detect'
	from /Library/Ruby/Gems/2.0.0/gems/specinfra-2.44.1/lib/specinfra/helper/detect_os.rb:5:in `detect'
	from /Library/Ruby/Gems/2.0.0/gems/specinfra-2.44.1/lib/specinfra/helper/os.rb:24:in `block in detect_os'
	from /Library/Ruby/Gems/2.0.0/gems/specinfra-2.44.1/lib/specinfra/helper/os.rb:23:in `each'
	from /Library/Ruby/Gems/2.0.0/gems/specinfra-2.44.1/lib/specinfra/helper/os.rb:23:in `detect_os'
	from /Library/Ruby/Gems/2.0.0/gems/specinfra-2.44.1/lib/specinfra/helper/os.rb:9:in `os'
	from /Users/brmathes/git/ansible-systems/roles/cisco.metacloud_build.configure_spine/spec/default_spec.rb:3:in `<top (required)>'
	from /Library/Ruby/Gems/2.0.0/gems/rspec-core-3.3.2/lib/rspec/core/configuration.rb:1327:in `load'
	from /Library/Ruby/Gems/2.0.0/gems/rspec-core-3.3.2/lib/rspec/core/configuration.rb:1327:in `block in load_spec_files'
	from /Library/Ruby/Gems/2.0.0/gems/rspec-core-3.3.2/lib/rspec/core/configuration.rb:1325:in `each'
	from /Library/Ruby/Gems/2.0.0/gems/rspec-core-3.3.2/lib/rspec/core/configuration.rb:1325:in `load_spec_files'
	from /Library/Ruby/Gems/2.0.0/gems/rspec-core-3.3.2/lib/rspec/core/runner.rb:102:in `setup'
	from /Library/Ruby/Gems/2.0.0/gems/rspec-core-3.3.2/lib/rspec/core/runner.rb:88:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/rspec-core-3.3.2/lib/rspec/core/runner.rb:73:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/rspec-core-3.3.2/lib/rspec/core/runner.rb:41:in `invoke'
	from /Library/Ruby/Gems/2.0.0/gems/rspec-core-3.3.2/exe/rspec:4:in `<main>'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/bin/ruby -I/Library/Ruby/Gems/2.0.0/gems/rspec-support-3.3.0/lib:/Library/Ruby/Gems/2.0.0/gems/rspec-core-3.3.2/lib /Library/Ruby/Gems/2.0.0/gems/rspec-core-3.3.2/exe/rspec --pattern spec/\*_spec.rb,spec/vagrant1/\*_spec.rb,spec/hosts/vagrant1/\*_spec.rb failed
ERROR:

  RAN: '/usr/bin/rake --rakefile=.molecule/rakefile'
'''

**Comment by retr0h** [comment]
I've has problems where serverspec wasn't connecting right.

    $ molecule destroy
    $ rm -rf .vagrant .molecule
    $ molecule converge

**Comment by sandinak** [comment]
Tried that before and again just now .. no joy.

**Comment by retr0h** [comment]
Any new details on this?  Still having issues?  I'm not sure why you would be having this problem.

**Comment by retr0h** [comment]
Closing.
