### ISSUE TITLE
molecule verify creates $HOME/.ansible/tmp/ in role's folder

### ISSUE THREAD

**Issue by aliusmiles** [metacloud/molecule#547]
Since 1.11.5 introduced "Pass ANSIBLE_CONFIG when executing ansible-lint." `molecule verify` creates `$HOME/.ansible/tmp/` in role's folder on every run.

Running ansible linter directly as `ANSIBLE_CONFIG=.molecule/ansible.cfg /usr/local/bin/ansible-lint playbook.yml` does not create any folders.

I was able to fix this issue by modifying `molecule/verifier/ansible_lint.py` as follows:
```
import os
...
self._env = {'ANSIBLE_CONFIG':
             molecule.config.config['ansible']['config_file'],
             'HOME': os.getenv('HOME')}
```
But I'm not sure if it's a correct way to resolve it.

I'm running molecule on Macos Sierra, iTerm2, Python 2.7.12. Please let me know if I can provide any additional info.

**Comment by lxhunter** [comment]
+1

**Comment by retr0h** [comment]
Thank you for the report @aliusmiles.  I'll get this fixed later today.  Your suggestion sounds like a proper fix.

**Comment by retr0h** [comment]
Molecule 1.12.5 was released to pypi with this fix.
