### ISSUE TITLE
molecule tests running as root

### ISSUE THREAD

**Issue by adriano-di-giovanni** [metacloud/molecule#555]
If if print `ansible_user_id` from within a task of my ansible role I get `root` event if no `sudo: true` or `become: true` are present.

Can you tell me why, please?

**Comment by retr0h** [comment]
Which driver are you using?

**Comment by adriano-di-giovanni** [comment]
Vagrant. Please, find a [repo](https://github.com/adriano-di-giovanni/molecule-issue-555) to reproduce the behavior

**Comment by retr0h** [comment]
Hi @adriano-di-giovanni.  If you run `molecule --debug convege` you will see the command executed.  We pass the `--sudo` flag to ansible-playbook.

**Comment by adriano-di-giovanni** [comment]
If I understand what `molecule test --help` reports (please, read below), default behavior should be `--no-sudo`

I also tried to run `molecule --debug test --no-sudo` but `--sudo` option gets always passed to ansible-playbook.

```bash
$ molecule --version
molecule, version 1.12.5

$ molecule test --help
Usage: molecule test [OPTIONS]

  Runs a series of commands (defined in config) against instances for a full
  test/verify run.

Options:
  --driver TEXT                   Specificy a driver.
  --platform TEXT                 Specify a platform.
  --provider TEXT                 Specify a provider.
  --destroy [passing|always|never]
                                  Destroy behavior.
  --sudo / --no-sudo              Enable or disable running tests with sudo.
                                  Default is disabled.
  --help                          Show this message and exit.
```

**Comment by retr0h** [comment]
> --sudo / --no-sudo              Enable or disable running tests with sudo.

The sudo flag reported there is for running tests (e.g. testinfra).  Has nothing to do with the inital converge which is always run with sudo.

**Comment by adriano-di-giovanni** [comment]
So, no way to avoid sudoing. Right?

**Comment by retr0h** [comment]
> So, no way to avoid sudoing. Right?

Right.

**Comment by retr0h** [comment]
So, should we not run ansible with sudo, and require each task to sudo.  I kinda fliip flop on my thoughts with this.

The chef agent for example runs with privileges.  One is not required to think which tasks require additional privileges.

**Comment by dhutty** [comment]
I’m tempted to say that we should not sudo (or ‘become’ as it should be these days), because that is not the Ansible default. And additionally, there’s always the possibility of including tasks from a separate file – if the include is privileged, so are all the subtasks.

On the other hand, this would like mean a lot of changes to ‘passing’ roles.

**Comment by retr0h** [comment]
> I’m tempted to say that we should not sudo (or ‘become’ as it should be these days), because that is not the Ansible default. And additionally, there’s always the possibility of including tasks from a separate file – if the include is privileged, so are all the subtasks.
> 
> On the other hand, this would like mean a lot of changes to ‘passing’ roles.

Yeah, I'm going to leave as is, unless this becomes a problem with adopting molecule.

**Comment by yves-vogl** [comment]
if some stumples upon this - ```--sudo``` flag isn't available anymore.

```bash
$ molecule test --help
Usage: molecule test [OPTIONS]

  Test (lint, destroy, dependency, syntax, create, prepare, converge,
  idempotence, side_effect, verify, destroy).

Options:
  -s, --scenario-name TEXT        Name of the scenario to target. (default)
  -d, --driver-name [azure|delegated|docker|ec2|gce|lxc|lxd|openstack|vagrant]
                                  Name of driver to use. (docker)
  --all / --no-all                Test all scenarios. Default is False.
  --destroy [always|never]        The destroy strategy used at the conclusion
                                  of a Molecule run (always).
  --help                          Show this message and exit.

$ molecule --version
molecule, version 2.18.1
```

**Comment by marcomancuso** [comment]
@yves-vogl yes, how do we run tests with sudo in Molecule 2?

**Comment by yves-vogl** [comment]
@marcomancuso I'm using the following in molecule.yml
```yaml
verifier:
  name: testinfra
  options:
    sudo: true
```

**Comment by marcomancuso** [comment]
@yves-vogl thanks! that worked!
