### ISSUE TITLE
Ability to merge in existing group_vars?

### ISSUE THREAD

**Issue by apenney** [metacloud/molecule#57]
First, hey guys, glad to see ansible is working out @dhutty !

I stumbled over this today and decided to play around with it, but quickly ran into a problem.  The problem is almost none of my roles is standalone, and they all require a playbook called all.yml to be run first (to setup docker, etc).

That playbook really, really, wants group_vars/all/ available in the ansible-playbook run because I define a bunch of variables there, rather than having sensible defaults in all the roles because I'm in a rush (as always) and a bad person.

I'm not familiar enough with this code to hack it in so I thought I'd see if anyone here has a suggestion on the easiest way to get that to work.

**Comment by apenney** [comment]
Given that symlinking `ln -s ../../group_vars .` is enough to get this working I'm thinking I'll either leave a symlink for every role or rig up some ugly code that allows me to set a group_vars location in molecule.yml and then symlinks it before ansible-playbook and removes it after.

Not pretty but viable.

Also, with this change my etcd role works flawlessly in molecule but is broken in test-kitchen so, :+1: from me!

**Comment by retr0h** [comment]
@apenney Good to hear you have checked this out.  I too have an [etcd role](https://github.com/retr0h/ansible-etcd) which molecule tests. LOL

**Comment by retr0h** [comment]
@apenney Normally, the roles are tested in isolation.  However, there are also cases where you want to test roles work in conjunction with other roles, and pointed to real inventory (aka hostvars/groupvars). We do this quite a bit, testing all of our openstack roles together.  [This](http://molecule.readthedocs.org/en/master/usage.html#using-molecule-for-deployment) should accomplish what you desire.

**Comment by apenney** [comment]
:+1:

**Comment by gersilex** [comment]
While this workaround works, the function still is missing in molecule itself.

In my opinion, littering every role with a symlink to group_vars is confusing and hacky. 
This is particulatily useful for testing a real-world scenario for deploying a whole machine or vm, containing a bigger set of roles, rather than only one role.

I agree that for testing a sole role, the vars should be isolated and work fine together with integration tests but for a complete playbook, we need a way to check how the deplyment would work out, BEFORE doing it on a real machine.

**Comment by retr0h** [comment]
@gersilex not much I can do about it.  Ansible can only find inventory in the directory presented by `-i`.  Symlinks are nasty solution..

**Comment by gersilex** [comment]
So in theory pointing to the production inventory should take the group_vars (residing in the same directory) into account? I will try that next week and report back. Thanks.
