### ISSUE TITLE
Question: How to define per-instance tests in a multi-instance setup?

### ISSUE THREAD

**Issue by tknerr** [metacloud/molecule#573]
Context: I'm currently having two instances (let's say "master" and "slave") and using the molecule testfinfra integration to test this.

Question: how can I specify which tests should be run for each instance?

Currently, molecue seems to simply run all tests against each instance upon `molecule verify`, but I haven't found a way to specify per-instance tests yet

**Comment by tknerr** [comment]
I was thinking of something like this:

```
tests
|-- test_to_run_on_both.py
|-- master
|        `-- test_to_run_only_on_master.py 
`-- slave
         `-- test_to_run_only_on_slave.py
```

Haven't found a way to configure per-instance test directories in molecule though.

Also looked at the testinfra, but couldn't find a way how to "mark" a test so that it runs on a specific host only. Probably there is something like this...?

**Comment by philpep** [comment]
@tknerr ``testinfra_hosts`` module variable ? http://testinfra.readthedocs.io/en/latest/invocation.html?highlight=testinfra_hosts#test-multiples-hosts

**Comment by tknerr** [comment]
@philpep thanks, that did the trick! I totally overlooked that and saw only the `--hosts` commandline parameter...

test_master.py:
```python
testinfra_hosts = ["jenkins-master"]

def test_runs_only_on_master_(Command):
    assert Command('hostname').stdout == 'jenkins-master'
```

test_slave.py:
```python
testinfra_hosts = ["jenkins-slave"]

def test_runs_only_on_slave_(Command):
    assert Command('hostname').stdout == 'jenkins-slave'
```

then:
```
$ molecule verify
--> Executing testinfra tests found in spec/.
============================= test session starts ==============================
collected 2 itemss

test_master.py
    [PASS]  Runs only on master [ansible://jenkins-master]

test_slave.py
    [PASS]  Runs only on slave [ansible://jenkins-slave]

=========================== 2 passed in 3.40 seconds ===========================
No serverspec tests found in disabled/.
```

Happy! :+1:

**Comment by retr0h** [comment]
@tknerr sweet
@philpep thanks!

**Comment by bhavikbhavsar** [comment]
In a single file if I define two test and want to execute one on master and next on slave this should work right ?

**Comment by retr0h** [comment]
@bhavikbhavsar I wouldn't use a single file for this.

**Comment by bhavikbhavsar** [comment]
hmm ok what if I want to do sequence of steps some on master and then some on slave then again some back on master, what should be the best approach?

**Comment by philpep** [comment]
@bhavikbhavsar I think you can parametrize your test to run on both hosts and use ``pytest_collection_modifyitems`` hook to remove some of them (once parameterized): https://docs.pytest.org/en/latest/writing_plugins.html#writing-hook-functions

This is probably not obvious, let us known if you succeeded.
