### ISSUE TITLE
Provisioning containers using molecule

### ISSUE THREAD

**Issue by iainlbc** [metacloud/molecule#577]
We are starting to explore containers for a service. 

Historically, our deployments are done via building base and versioned AMI's using ansible/packer. 

I'm attempting to find a reasonable way of building and testing a container using ansible.

It seems like molecule actually fits the bill given it has a nice docker driver, but I don't see any way to build images (since its purpose is testing ansible roles, and docker is just a place to do this, the containers are naturally thrown away).

Is there any interest in extending functionality to actually build/tag/push containers depending on test results?

ansible-container is getting there, but has no testing built in, and has limited functionality wrt. registries/cloud providers to push too/etc.

Wondering how other folks do this, perhaps dockerfile has been sufficient for most, and tests are just based off  querying the functionality exposed by the entrypoint after building the image?

Here's a related proposal: https://github.com/docker/docker/issues/21280

**Comment by retr0h** [comment]
> Is there any interest in extending functionality to actually build/tag/push containers depending on test results?

Hi @iainlbc.  Yes, that sounds very interesting and molecule would make a good platform to build and test images.  We are fairly opinionated, and would require the use of ansible.

**Comment by kireledan** [comment]
The best approach to something like this is to do what packer does. Run the base image - execute molecule on container - then commit the new layer with the desired image name/tag. Molecule could definitively do this conditionally based on test results. Although I'm not sure how I feel about Molecule also being called a 'deployment tool'. Considering the purpose of Molecule is for testing.

**Comment by retr0h** [comment]
@iainlbc I agree with @kireledan on most counts.  This isn't something we are actively going to develop.  If this is something you are interested in, please submit a PR or an issue with your proposal.  This really isn't a deployment tool, but I could see how it "could" be leveraged to build and test images.

Thank you again for your issue, and please feel free discuss this further on freenode in #molecule-users.
