### ISSUE TITLE
Feature request: Add "vmware_workstation" provider support

### ISSUE THREAD

**Issue by tknerr** [metacloud/molecule#582]
Currently only "vmware_fusion" is supported, but not "vmware_workstation".

Net effect is that all the provider config options in `molecule.yml` are being ignored and don't end up in the generated `.molecule/vagrantfile`

**Comment by signed8bit** [comment]
I am reworking the vagrant file generation and will get this in as well.

**Comment by tknerr** [comment]
@signed8bit awesome, thanks! vagrant-wise the configuration should be exactly the same as for the vmware_fusion provider afaik

**Comment by retr0h** [comment]
This feature was released with molecule 1.13 which is live on pypi.
