### ISSUE TITLE
LXD Driver Support

### ISSUE THREAD

**Issue by asmartin** [metacloud/molecule#584]
Would [LXD](https://linuxcontainers.org/lxd/introduction/) as a Driver for Molecule provide any value compared with the existing Docker Driver? I have been using LXD on Ubuntu 16.04 with a ZFS backend now for awhile and have been amazed at the performance - usually about 1.6 seconds from `lxc launch` to when the container is up and running. Leveraging this for playbook testing would be great! Also, there might be some other advantages with LXD since it is intended to run "full-server" containers whereas Docker is more geared towards running a single app. Thoughts on this?

**Comment by retr0h** [comment]
Hi @asmartin that sounds like a great suggestion.  However, we will not be able to implement the work any time soon.  Please feel free to contribute and add if you feel strongly.  This is how we obtained the docker and openstack drivers.

**Comment by asmartin** [comment]
I'm also quite busy at the moment so won't have time to dive in and right an LXD driver right now, but would be happy to help test if someone else can help to write it

**Comment by retr0h** [comment]
> I'm also quite busy at the moment so won't have time to dive in and right an LXD driver right now, but would be happy to help test if someone else can help to write it

This likely will not get implemented then.  Will close this out next week, unless someone decides to pick it up.

**Comment by uSpike** [comment]
Is it possible to utilize [vagrant-lxc](https://github.com/fgrehm/vagrant-lxc) as a means of provisioning LXC containers?

**Comment by retr0h** [comment]
> Is it possible to utilize vagrant-lxc as a means of provisioning LXC containers?

That would need implemented into the Vagrantfile much like the [other providers](http://molecule.readthedocs.io/en/stable-1.12/provider/index.html) we have.

This is being reworked in #582, #582, and #463.

**Comment by retr0h** [comment]
Closing this issue.  Reporter does not have time to write this feature, and we don't have a need for it, which prevents us from putting resources on it.

@asmartin Please feel free to reopen when you have cycles to implement it.
