### ISSUE TITLE
Docker driver, CentOS 7 image, command and become_user gives "sudo: sorry, you must have a tty to run sudo\n"

### ISSUE THREAD

**Issue by mjuenema** [metacloud/molecule#595]
When I use the following combination it will give a ```"sudo: sorry, you must have a tty to run sudo\n"``` error.

* Docker driver
* CentOS 7 image
* Ansible `command` module with `become_user` clause.

The underlying problem is that when `sudo` is installed into a CentOS 7 container, `/etc/sudoers` contains `Defaults requiretty`. 

My current work-around is to use a custom CentOS 7 Docker image that already has the `sudo` package installed and `Defaults requiretty` commented out as implemented here: https://hub.docker.com/r/mjuenema/centos7/

**Comment by retr0h** [comment]
You would get the same error on any system with a sudoers like that.  Not a problem molecule can solve.
