### ISSUE TITLE
molecule setuser

### ISSUE THREAD

**Issue by qrrock** [metacloud/molecule#597]
How do I run test as non root user? Or rather, how molecule exactly fires to container?
I want to do the test on some exact environment; How do i do that?

# molecule.yml

    ---
    ansible:
      sudo: false
      ansible_user = app
      config_file: ./ansible.cfg
    driver:
      name: docker
    docker:
      containers:
        - name: inni.testrole1
          image: "myhub/im/im_aliases"
          image_version: "20161016"
          install_python: no # - (default=yes) install python onto the image being used
          build_image: no # - (default=yes)
          diff: False
          sudo: false
          volume_mounts:
            - "/home/md/im_machines2:/home/app/webapp"
            - "/home/md/.zshenv:/home/app/.zshenv"
          command: "/sbin/my_init -- bash -c 'bash /docker/.containerOnStart.sh; asapp zsh -l'"

# ./ansible.cfg

    [defaults]

    become_user     = true
    remote_tmp      = /home/app/webapp
    roles_path      = .molecule/roles:.molecule/../roles:../:../../
    library         = library

  # playbook

    ---
    - hosts: all
      remote_user: app

      # roles:
      #   - role: inn.testrole1

      tasks:
        - name: test 1
          shell: "echo $HOME; echo $cp; echo $SHELL; whoami; pwd; $cp; $im_base_path"
          args:
            executable: /bin/zsh
          register: result
        - debug:
            var: result

# Dockerfile

    FROM phusion/baseimage:0.9.19

    # Set correct environment variables.
    ENV HOME=/root \
        APP=/home/app/webapp \
        APP_HOME=/home/app

    # Add shortcut for setuser app
    RUN echo '#!/bin/bash' > /sbin/asapp \
     && echo 'exec setuser app "$@"' >> /sbin/asapp \
     && chmod +x /sbin/asapp

    # Create dir for app
    # Set correct permissions
    RUN addgroup --gid 1000 app \
     && adduser --gecos "" --uid 1000 --disabled-password --ingroup app --shell /bin/bash app \
     && mkdir -p $APP_HOME/webapp

    # Change directory
    WORKDIR $APP_HOME/webapp

#  EXPECTED

    $ docker exec im_admins asapp zsh -c "echo $HOME; whoami; echo $cp"                                                                      ~
    /home/md
    app
    /home/md/im_machines2/im_admins

    $docker attach im_admins
    ╰─$ echo $HOME; whoami; echo $cp                                                                                                           1 ↵
    /home/app
    app
    /home/app/webapp/im_admins

#  CURRENT RESULT

    TASK [debug 12] ****************************************************************
    ok: [inn.testowarola1] => {
        "msg": {
            "changed": true,
            "cmd": "echo $HOME; whoami; echo $cp",
            "delta": "0:00:00.011543",
            "end": "2016-11-17 18:40:25.543545",
            "rc": 0,
            "start": "2016-11-17 18:40:25.532002",
            "stderr": "",
            "stdout": "/root\napp",
            "stdout_lines": [
                "/root",
                "app"
            ],
            "warnings": []
        }
    }

    PLAY RECAP *********************************************************************
    inn.testowarola1 : ok=3    changed=1    unreachable=0    failed=0

**Comment by retr0h** [comment]
I don't believe we are able to handle non-root users with docker backend.

**Comment by qrrock** [comment]
that's what i thought. but as i noticed molecule replace content in my file during the run, i get confused. so is it a bug or i did something wrong

# molecule.yml
```
ansible:
  user: app
  sudo: false
  config_file: ./molecule_ansible.cfg
  playbook: ./molecule_playbook.yml
  inventory_file: ./molecule_inventory
```

# ./molecule_inventory

before run

    diapl.testowarola1 ansible_port=2121  ansible_host=172.23.0.1  ansible_user=app ansible_connection=ssh  ansible_ssh_private_key_file=/home/app/webapp/im_admins/dockers/sandbox_docker/id_rsa

after run (suddenly during)

    diapl.testowarola1 ansible_connection=docker

**Comment by retr0h** [comment]
Closing as it isn't something we are going to support.
