### ISSUE TITLE
specifying static IP in molecule.yml

### ISSUE THREAD

**Issue by pleegor** [metacloud/molecule#623]
# Issue Type

- configurational question. 

# Molecule and Ansible details

```
ansible --version -> ansible 2.2.0.0
molecule --version -> molecule, version 1.15.0
```

- Molecule installation method: pip
- Ansible installation method: pip

# Desired Behaviour

I am trying to make molecule to spin vagrant instances with static IPs. What would be the best of doing that?

P.S. I also tried to access molecule channel on IRC but it appears that I need to be invited. If someone could invite me (pleegor) to join IRC channel I will appreciate it!!!

**Comment by retr0h** [comment]
The molecule channel is #molecule-users.  See our [docs](https://molecule.readthedocs.io/en/stable-1.15/contributing.html#irc).

**Comment by pleegor** [comment]
Thanks @retr0h! (it's been a long day)

**Comment by retr0h** [comment]
A static IP can be assigned in Vagrant by looking at our [example](https://molecule.readthedocs.io/en/stable-1.15/driver/index.html#comprehensive-usage).

**Comment by retr0h** [comment]
> Thanks @retr0h! (it's been a long day)

All good :)

**Comment by pleegor** [comment]
@retr0h thanks again!!! You are rock solid!!!!

**Comment by retr0h** [comment]
> @retr0h thanks again!!! You are rock solid!!!!

Good ol' @TieWei added that functionality \m/!!!

**Comment by retr0h** [comment]
Let me know if it works.

**Comment by retr0h** [comment]
@pleegor have any luck?

**Comment by pleegor** [comment]
Hi @retr0h things are working as expected! Is there any info on setting up multiple vagrant instances within the same test (assuming I need to test a role for various OSs)? We can take this conversation outside of this specific issue

**Comment by retr0h** [comment]
Sounds good.  See a more comprehensive [example](http://molecule.readthedocs.io/en/stable-1.15/driver/index.html#comprehensive-usage).
