### ISSUE TITLE
Issue with initial molecule create

### ISSUE THREAD

**Issue by JoelW-S** [metacloud/molecule#626]
# Issue Type

- Bug report

# Molecule and Ansible details

```
ansible --version
2.2.0.0
molecule --version
1.15.0
```

- Molecule installation method: pip
- Ansible installation method: pip

# Desired Behaviour, steps taken
```
cat <<EOF > Dockerfile
FROM centos:6.8
RUN echo proxy=http://proxy.url.com:3128 >> /etc/yum.conf
CMD ["/bin/bash"]
EOF
```

sudo docker build --rm -t molecule:7 .
molecule init --role foo --driver docker
cd foo
edit molecule.yml image section to molecule (custom image)
edit molecule.yml image_version to 7
sudo molecule test

I'm expecting default lifecycle and success.

# Actual Behaviour (Bug report only)

Please give some details of what is actually happening.
Include a [minimum complete verifiable example](http://stackoverflow.com/help/mcve) with
output of running `molecule --debug`.

```
[vagrant@test foo]$ sudo molecule test
--> Destroying instances ...
--> Checking playbook's syntax ...

playbook: playbook.yml
--> Creating instances ...
--> Building ansible compatible image ...
        Step 1 : FROM molecule:7
         ---> 58cd53db209d
        Step 2 : RUN bash -c 'if [ -x "$(command -v apt-get)" ]; then apt-get update && apt-get install -y python sudo; fi'
         ---> Using cache
         ---> 155e0df48362
        Step 3 : RUN bash -c 'if [ -x "$(command -v yum)" ]; then yum makecache fast && yum update -y && yum install -y python s
o; fi'
         ---> Using cache
         ---> d5e9d422a23e
        Step 4 : RUN bash -c 'if [ -x "$(command -v zypper)" ]; then zypper refresh && zypper update -y && zypper install -y pyt
n sudo; fi'
         ---> Using cache
         ---> 176b039af4b1
        Successfully built 176b039af4b1
Finished building molecule_local/molecule:7
Creating container foo with base image molecule:7 ...
Traceback (most recent call last):
  File "/bin/molecule", line 11, in <module>
    sys.exit(main())
  File "/usr/lib/python2.7/site-packages/molecule/cli.py", line 41, in main
    cli(obj={})
  File "/usr/lib/python2.7/site-packages/click/core.py", line 716, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/click/core.py", line 696, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python2.7/site-packages/click/core.py", line 1060, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/python2.7/site-packages/click/core.py", line 889, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python2.7/site-packages/click/core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/lib/python2.7/site-packages/molecule/command/test.py", line 98, in test
    util.sysexit(t.execute()[0])
  File "/usr/lib/python2.7/site-packages/molecule/command/test.py", line 46, in execute
    status, output = c.execute(exit=False)
  File "/usr/lib/python2.7/site-packages/molecule/command/create.py", line 44, in execute
    self.molecule.driver.up(no_provision=True)
  File "/usr/lib/python2.7/site-packages/molecule/driver/dockerdriver.py", line 151, in up
    command=command)
  File "/usr/lib/python2.7/site-packages/docker/api/container.py", line 135, in create_container
    return self.create_container_from_config(config, name)
  File "/usr/lib/python2.7/site-packages/docker/api/container.py", line 146, in create_container_from_config
    return self._result(res, True)
  File "/usr/lib/python2.7/site-packages/docker/client.py", line 178, in _result
    self._raise_for_status(response)
  File "/usr/lib/python2.7/site-packages/docker/client.py", line 173, in _raise_for_status
    raise errors.NotFound(e, response, explanation=explanation)
docker.errors.NotFound: 404 Client Error: Not Found ("{"message":"No such image: molecule_local/molecule:7"}")
[vagrant@test foo]$
```
No molecule_local image created even though molecule built the image successfully
```
[vagrant@test foo]$ sudo docker images
REPOSITORY          TAG                 IMAGE ID            CREATED             SIZE
<none>              <none>              176b039af4b1        14 minutes ago      307.1 MB
molecule            7                   58cd53db209d        15 minutes ago      196.5 MB
<none>              <none>              2af078ecfea8        20 minutes ago      665.6 MB
centos              7                   0584b3d2cf6d        4 weeks ago         196.5 MB
centos              6.8                 0cd976dc0a98        3 months ago        194.5 MB
hello-world         latest              c54a2cc56cbb        5 months ago        1.848 kB
[vagrant@test foo]$
```

**Comment by retr0h** [comment]
hi @JoelW-S.  Thanks for the report.  Oddly, I cannot reproduce this error.  However, I ddi notice you have quite a few images that have <none> tags and names.  This wreaks havoc with molecule, and I've yet been able to reproduce creating images like this.

I suggest stopping Docker, deleting it's data directory, and restarting docker.  At that point `docker images` should be empty, and would love for you to give this another try.

```
[jodewey:/tmp/foo] % docker images
REPOSITORY                TAG                 IMAGE ID            CREATED             SIZE
molecule_local/molecule   7                   bbfc26c39f7c        37 minutes ago      673.9 MB
molecule                  7                   782dba0ba9a9        39 minutes ago      194.5 MB
centos                    6.8                 0cd976dc0a98        3 months ago        194.5 MB
```

**Comment by JoelW-S** [comment]
Hi @retr0h. I've followed what you've suggested and i get the same outcome.
Tried without a custom image as well, getting molecule to pull and use what is the default ubuntu:latest and still fails.
Funnily enough, this has only started happening and was fine in using it up till now.

Shame it's not working now as having this tool with our vagrant box rapidly improves Ansible role development.

**Comment by kostyrevaa** [comment]
I've got the same problem with Travis CI
see [this travis log](https://travis-ci.org/kostyrevaa/wildfly/builds/180160386) as reference
Strangely enough, when I run `molecule test` locally, everything works fine.
Coincidentally, the problems with centos:6

**Comment by kostyrevaa** [comment]
Somehow this [fixed](https://github.com/kostyrevaa/wildfly/commit/68fb9f8f0d67c8298a42932276dc0e56ed079d2b) the issue for me.

**Comment by JoelW-S** [comment]
@kostyrevaa At least I know i'm not the only one, unfortunately i'm using centos:6.8 as my base image and it's still failing.

**Comment by kostyrevaa** [comment]
@JoelW-S and [so do I](https://github.com/kostyrevaa/wildfly/blob/master/molecule.yml#L17)

**Comment by retr0h** [comment]
@kireledan any ideas?

**Comment by retr0h** [comment]
@JoelW-S @kostyrevaa Yeah, I have never ran into this issue, and I run my roles through travis.  I also run a set of functional tests when developing molecule.

As you can see the image is built. 

> Successfully built 176b039af4b1
> Finished building molecule_local/molecule:7

However, it gets assigned a <None> tag and repository.  This is why molecule cannot find it by name.  The reason it is getting named this, is unknown to me at this time.

> [vagrant@test foo]$ sudo docker images
> REPOSITORY          TAG                 IMAGE ID            CREATED             SIZE
> <none>              <none>              176b039af4b1        14 minutes ago      307.1 MB

**Comment by kireledan** [comment]
Yeah lemme see if I can replicate this bug.

**Comment by kireledan** [comment]
I haven't been able to replicate it so far. But I was going to try again after I finish up this presentation tonight.

**Comment by retr0h** [comment]
> I haven't been able to replicate it so far. But I was going to try again after I finish up this presentation tonight.

My guess is something happens with the tagging of the image.

> Creating container foo with base image molecule:7 ...

You can see it was created and exists:

> <none>              <none>              176b039af4b1        14 minutes ago      307.1 MB

It is just un-named, which molecule requires when starting the container.  So something around the tagging of the image fails.

FWIW, I cannot reproduce this either.

@JoelW-S @kostyrevaa could you report what version of docker-py you're using.  I'm using `docker-py==1.9.0`.

**Comment by JoelW-S** [comment]
@retr0h `docker-py==1.10.6`

**Comment by kireledan** [comment]
I'll try setting my docker-py version and re testing

**Comment by kireledan** [comment]
I was able to reproduce the error when changing my docker-py version.

**Comment by kireledan** [comment]
That version did not seem to have an affect for me.

**Comment by kireledan** [comment]
What vagrant box are you running? Or at least what os is it?

**Comment by JoelW-S** [comment]
@kireledan `CentOS Linux release 7.2.1511 (Core)`

**Comment by kireledan** [comment]
sorry for the delay. Just started my break yesterday. (hooray!). 

Anyways, I was able to replicate the bug. Investigating now.

**Comment by retr0h** [comment]
Unable to reproduce.  Please reopen if this is still an issue.
