### ISSUE TITLE
Vagrant 1.8 support

### ISSUE THREAD

**Issue by retr0h** [metacloud/molecule#63]
Verify molecule works properly with the release of [Vagrant 1.8](https://www.hashicorp.com/blog/vagrant-1-8.html).

**Comment by rgreinho** [comment]
First attempt failed:

```
$ molecule create --platform trusty64
Vagrant failed to initialize at a very early stage:

The plugins failed to load properly. The error message given is
shown below.

Unable to find binary extension, was hitimes installed correctly?
ERROR: Command '['/usr/local/bin/vagrant', 'up', '--no-provision']' returned non-zero exit status 1
```

**Comment by rgreinho** [comment]
Ok I solved the issue by doing ``rm -fr ~/.vagrant.d``. Now molecule is working fine with the latest ``Vagrant`` and ``VirtualBox``.

**Comment by retr0h** [comment]
> Ok I solved the issue by doing rm -fr ~/.vagrant.d. Now molecule is working fine with the latest Vagrant and VirtualBox.

Yeah, same issue solved my problem.  I'm okay with this being a reasonable solution to upgrading to a newer version of Vagrant.

**Comment by retr0h** [comment]
Verified Vagrant 1.8 is working as expected while validating #66.
