### ISSUE TITLE
Docker driver using CentOs with Overlayfs file system

### ISSUE THREAD

**Issue by s3than** [metacloud/molecule#636]
# Issue Type

- Bug report

# Molecule and Ansible details

```
ansible 2.2.0.0
molecule, version 1.16.1
```

- Molecule installation method: One of source, pip
- Ansible installation method: One of source, pip, OS package

# Desired Behaviour

When running the docker driver and using a rpm distribution with a overlayfs docker file system rpm should work.

# Actual Behaviour (Bug report only)

When running the docker driver and using a rpm distribution with a overlayfs docker file system rpm returns a checksum error
While running the ansible playbook 
```
Rpmdb checksum is invalid: dCDPT(pkg checksums)
```

The following Dockerfile run command resolves the issue.

```
RUN yum makecache fast && \
 yum update -y && \
 yum install -y python sudo yum-plugin-ovl && \
 sed -i 's/plugins=0/plugins=1/g' /etc/yum.conf
```

1/ yum-plugin-ovl should be installed already by default but not always
2/ updating the yum.conf plugins=1 turns the plugin on

**Comment by kireledan** [comment]
I can make a PR with this fix. Given that you already know the solution, feel free to make a PR with the proposed change. We'd be happy to review it.

**Comment by retr0h** [comment]
@kireledan mind taking care of this one?  You been quiet anyways 👊

**Comment by s3than** [comment]
@retr0h Please find PR with fix for overlayfs https://github.com/metacloud/molecule/pull/641

**Comment by s3than** [comment]
PR merged, thanks.
