### ISSUE TITLE
No openstack floating ip support

### ISSUE THREAD

**Issue by alvaroaleman** [metacloud/molecule#639]
# Issue Type

- Bug report

# Molecule and Ansible details

```
molecule, version 1.16.1
```

- Molecule installation method: pip

# Desired Behaviour

The openstack provider creates an openstack instance, associates a floating ip to it and connects to the instance using the floating ip.

# Actual Behaviour (Bug report only)

The openstack provider creates an openstack instance and tries to connects to the private ip which obviously doesn't work.

**Comment by retr0h** [comment]
@alvaroaleman Please submit a PR for requested functionality.  The openstack driver is owned by the Molecule community.   Thanks!
