### ISSUE TITLE
Molecule verify does not work. 

### ISSUE THREAD

**Issue by pleegor** [metacloud/molecule#640]
# Issue Type

- Bug report
- Feature request

# Molecule and Ansible details

```
ansible --version
ansible 2.2.0.0
  config file =
molecule --version
molecule, version 1.16.1
```

- Molecule installation method: One of source, pip
- Ansible installation method: One of source, pip, OS package

# Desired Behaviour

When I am running `molecule verify` I would expect having a dry run

# Actual Behaviour (Bug report only)
This is what I am getting. https://gist.github.com/pleegor/48a4c0cb7cc4030cccdfe6d684d9289f

Please give some details of what is actually happening.
Include a [minimum complete verifiable example](http://stackoverflow.com/help/mcve) with
output of running `molecule --debug`.

Ran `molecule status`
`molecule status
╒════════════╤═════════════╤════════════╕
│ Name       │ State       │ Provider   │
╞════════════╪═════════════╪════════════╡
│ vagrant-01 │ not_created │ virtualbox │
╘════════════╧═════════════╧════════════╛
--> AVAILABLE PLATFORMS
trusty64  (default)
--> AVAILABLE PROVIDERS
virtualbox  (default)`

`molecule test` on the other side works without any issues

**Comment by retr0h** [comment]
You cannot `molecule verify` unless the system is created.

**Comment by pleegor** [comment]
Thanks @retr0h !!!!This totally makes sense! What a quick response!!!

**Comment by retr0h** [comment]
I'm thinking we should probably make this requirement better known.

**Comment by pleegor** [comment]
@retr0h extra documentation will not hurt :) Thanks again @retr0h you are always helpful!
