### ISSUE TITLE
ansible-lint called from Molecule fails when no Ansible-installed-with-pip is present

### ISSUE THREAD

**Issue by techraf** [metacloud/molecule#642]
# Issue Type

- Bug report

# Molecule and Ansible details

```
# ansible --version
ansible 2.2.1.0 (stable-2.2 acad2ba246) last updated 2016/12/11 20:27:02 (GMT +900)
  lib/ansible/modules/core: (detached HEAD 8139278530) last updated 2016/12/11 20:30:10 (GMT +900)
  lib/ansible/modules/extras: (detached HEAD f5f1fc934a) last updated 2016/12/11 20:30:10 (GMT +900)
  config file =
  configured module search path = Default w/o overrides
# molecule --version
molecule, version 1.16.1
```

- Molecule installation method: pip
- Ansible installation method: source

# Desired Behaviour

```
# molecule verify
--> Executing ansible-lint...
[ANSIBLE0002] Trailing whitespace
playbook.yml:7
    - ansible-unix-python-environment
```

# Actual Behaviour (Bug report only)

```
# pip uninstall ansible
((( cut )))
  Successfully uninstalled ansible-2.2.0.0

# . /usr/local/src/ansible/hacking/env-setup
((( cut )))
PYTHONPATH=/usr/local/src/ansible/lib:
((( cut )))

# ansible --version
ansible 2.2.1.0 (stable-2.2 acad2ba246) last updated 2016/12/11 20:27:02 (GMT +900)
  lib/ansible/modules/core: (detached HEAD 8139278530) last updated 2016/12/11 20:30:10 (GMT +900)
  lib/ansible/modules/extras: (detached HEAD f5f1fc934a) last updated 2016/12/11 20:30:10 (GMT +900)
  config file =
  configured module search path = Default w/o overrides

# molecule --debug verify
--> Executing ansible-lint...
DEBUG: COMMAND
/usr/local/bin/ansible-lint playbook.yml --exclude .git --exclude .vagrant --exclude .molecule
Traceback (most recent call last):
  File "/usr/local/bin/ansible-lint", line 30, in <module>
    import ansiblelint
  File "/usr/local/lib/python2.7/site-packages/ansiblelint/__init__.py", line 26, in <module>
    import ansiblelint.utils
  File "/usr/local/lib/python2.7/site-packages/ansiblelint/utils.py", line 25, in <module>
    import ansible.constants as C
ImportError: No module named ansible.constants

# /usr/local/bin/ansible-lint playbook.yml --exclude .git --exclude .vagrant --exclude .molecule
[ANSIBLE0002] Trailing whitespace
playbook.yml:7
    - ansible-unix-python-environment
```

# Further tests

With Ansible 2.2.0 installed with `pip` (regardless if the one from source configured or not; configured in the example below):

```
# pip install ansible
((( cut )))
Successfully installed ansible-2.2.0.0

# . /usr/local/src/ansible/hacking/env-setup
((( cut )))

# ansible --version
ansible 2.2.1.0 (stable-2.2 acad2ba246) last updated 2016/12/11 20:27:02 (GMT +900)
  lib/ansible/modules/core: (detached HEAD 8139278530) last updated 2016/12/11 20:30:10 (GMT +900)
  lib/ansible/modules/extras: (detached HEAD f5f1fc934a) last updated 2016/12/11 20:30:10 (GMT +900)
  config file =
  configured module search path = Default w/o overrides

# molecule verify
--> Executing ansible-lint...
[ANSIBLE0002] Trailing whitespace
playbook.yml:7
    - ansible-unix-python-environment
```

**Comment by retr0h** [comment]
@techraf I don't understand the problem.  Ansible is required for ansible-lint to function.  Why would one uninstall ansible?

Ansible-lint has a dependency on ansible and will bring it in as part of the installation of ansible-lint.  Why is this a bug or an issue?

**Comment by techraf** [comment]
Ansible **is** installed (and configured) all the time.

The problem is if **Ansible-installed-with-pip** is present or not.

**Comment by retr0h** [comment]
Not sure what to tell you.  No idea how you would like this fixed.

**Comment by techraf** [comment]
The fix seems pretty simple: take the reference that you somehow, somewhere hardcoded and use environment variables as received from the shell.

There is no reason the same command (which Molecule prints it executes):
```
/usr/local/bin/ansible-lint playbook.yml --exclude .git --exclude .vagrant --exclude .molecule
```
succeeds from shell but fails from Molecule.

I don't know why is it so difficult to understand that if the command fails **only** when called from Molecule, then something is wrong with Molecule, not the whole world except for Molecule.

**Comment by retr0h** [comment]
Nothing is hard coded.

`/usr/local/bin/ansible-lint` is determined by your path by the [sh module](https://github.com/metacloud/molecule/blob/ba5aca1f86c85432ba3f35031937eadbbaf07383/molecule/verifier/ansible_lint.py#L60).

**Comment by techraf** [comment]
**Kind request**: read before you respond.

No one ever said Molecule fails to execute `ansible-lint`.

I repeat for the third time:

- Molecule executes `ansible-lint` and then `ansible-lint` falls.

- Molecule with debug option also prints out the exact command it runs

- When executed using the same command from shell `ansible-lint` does not fail.

Considering the command is the same, the executable is the same and `ansible-lint`  fails (its operations fail) **only** with Molecule, the only difference is the environment in which you run it.

Now please go back and **do read** my posts.

**Comment by retr0h** [comment]
I'm not fixing it.  Nor do I see a problem.  Open a PR if you want it fixed.
