### ISSUE TITLE
global default config

### ISSUE THREAD

**Issue by alvaroaleman** [metacloud/molecule#648]
# Issue Type

- Feature request

# Desired Behaviour

It would be handy to have some kind of global config (e.g. in /etc/moluecule.yml or ~/.molecule.yml) that gets hashmerged with the moleculefile of the active project. Optionally it should be possible to disable usage of the global config at project level. What do you think?

**Comment by retr0h** [comment]
Got you [covered](http://molecule.readthedocs.io/en/stable-1.16/configuration.html#configuration).

**Comment by alvaroaleman** [comment]
Oh, that's great, thanks for the hint!
