### ISSUE TITLE
ansible-lint should not be part of the `verify` section, since it is static code analysis

### ISSUE THREAD

**Issue by alvaroaleman** [metacloud/molecule#661]
# Issue Type

- Bug report

# Desired Behaviour

Currently, `ansible-lint` gets executed via the `verify` command. In contrast to all other verifiers however, it is a static code analysis tool that does not depend on the role being executed beforehand.

Ideally, there is a a dedicated section and command that configures/executes ansible syntax check, ansible-lint and any other static code analysis tool the users wishes to use.

**Comment by retr0h** [comment]
Yeah, this is probably true.  I'm actually rewriting huge chunks of molecule for the v2 release.  It will better support this behavior.

**Comment by alvaroaleman** [comment]
That sounds great. Is there some kind of document for what will change from a user POV in v2? Maybe it would be good to have an issue to talk about that.

**Comment by retr0h** [comment]
> That sounds great. Is there some kind of document for what will change from a user POV in v2? Maybe it would be good to have an issue to talk about that.

It will be a pre-release for users to play with for quite some time.  It won't be out anytime soon.  Here is a [sneak peek](https://gist.github.com/retr0h/f397839ebdd5c2d11ee78af15672202c).

Biggest difference is scenarios, docker only (for the moment), and using ansible to manage the instance lifecycle.

**Comment by retr0h** [comment]
This is currently underway with v2 branch.  Details were discussed at this [PR](https://github.com/metacloud/molecule/pull/652#issuecomment-268287931).

Closing this issue, since the details have been worked out and underway.
