### ISSUE TITLE
Please update ansible-lint

### ISSUE THREAD

**Issue by enricomingardo** [metacloud/molecule#663]
# Issue Type

- Bug report

# Molecule and Ansible details

```
ansible --version
ansible 2.2.0.0
  config file =
  configured module search path = Default w/o overrides
molecule --version
molecule, version 1.17.0
```

- Molecule installation method:  pip
- Ansible installation method: homebrew (Mac OSX)

# Desired Behaviour

Ansible-lint should not exit with error when role dependency is in newer dictionary format see [ansible-lint exits when using newer role dependency dict structure #174](https://github.com/willthames/ansible-lint/issues/174)

# Actual Behaviour (Bug report only)

```
--> Idempotence test in progress (can take a few minutes)...
--> Starting Ansible Run...
Idempotence test passed.
--> Executing ansible-lint...
role dict {u'src': u'geerlingguy.repo-epel'} does not contain a "role" or "name" key
```

**Comment by enricomingardo** [comment]
This ansible-lint bug was fixed in ansible-lint 3.3.0

**Comment by alvaroaleman** [comment]
You can just do `pip install --upgrade ansible-lint`. If molecule should do anything, then it should be not specifying a version in its requirements.txt IMHO.

**Comment by retr0h** [comment]
> You can just do pip install --upgrade ansible-lint. If molecule should do anything, then it should be not specifying a version in its requirements.txt IMHO.

Yeah, I pin requirements to ensure what I tested is what you are getting.  Upstream projects could release a change incompatible with molecule.  I do my best to keep them fairly up to date.
