### ISSUE TITLE
serverspec example files are not created

### ISSUE THREAD

**Issue by m4rkw** [metacloud/molecule#666]
# Issue Type

- Bug report

# Molecule and Ansible details

```
ansible 2.2.0.0
molecule, version 1.17.0
```

- Molecule installation method: pip
- Ansible installation method: pip

# Desired Behaviour

when running:
```
molecule init --verifier serverspec
```
The serverspec section of the documentation says "Example files are created" but they are not.  Ideally if the docker driver is also specified it should create a spec_helper.rb that facilitates testing of the docker container.

# Actual Behaviour (Bug report only)

No serverspec example files are created.

**Comment by retr0h** [comment]
@m4rkw `molecule init --role shit --verifier serverspec` appears to create examples, correct?

**Comment by m4rkw** [comment]
ah so it does, it just doesn't seem to do it if you init into an existing role.  in any case i've figured out how to make docker work now but there would have been a lot less friction and lost time if that had worked.

**Comment by retr0h** [comment]
@m4rkw sorry to have disappointed :)  Thanks for the bug report.  Will fix it.
