### ISSUE TITLE
Openstack instances get created sequentially

### ISSUE THREAD

**Issue by alvaroaleman** [metacloud/molecule#713]
# Issue Type

- Bug report

Right now molecule creates  Openstack instances sequentially, waits until the instance was fully created and can be reached via SSH, then proceeds to the next instance. This is very time consuming.

Instead, the Openstack driver should just create all instances without waiting and afterwards wait until it can reach them all.

**Comment by kireledan** [comment]
Moving the snippet where it checks for ssh availability to another for loop would resolve this. 

``` python

for instance in self.instances:
                ... 
                while not self._check_ssh_availability(
                        server['interface_ip'],
                        instance['sshuser'],
                        timeout=6,
                        sshkey_filename=self._get_keyfile(
                        )) or num_retries == 5:
                    util.print_info('\t Waiting for ssh availability...')
                    num_retries += 1
```

**Comment by alvaroaleman** [comment]
Yeah, I was playing around with the code a little yesterday, but found a couple more issues so I didn't really get anything done.

I think we would probably need three loops: One that creates the instances without `wait: True`, a second one that attaches an address to them and a third one for the availability check.

**Comment by retr0h** [comment]
Unfortunately this will need addressed by someone in the community who uses the Openstack driver.  I do not use this driver, nor can I test it at the moment, so someone will need to tackle this if willing.

**Comment by berendt** [comment]
When implementing this I would prefer to make the behaviour configurable. I prefer the sequential creation of instances.

**Comment by alvaroaleman** [comment]
Why?

**Comment by alvaroaleman** [comment]
The sequential creation is a huge performance issue for multiinstance
setups, I have a PR prepared for this that improves the speed by about ~50%
for just two instance

**Comment by berendt** [comment]
@alvaroaleman The sequential creation of instances is the current default behaviour and from my POV it is always better to not change the default behaviour. And if changing the default behaviour I think it is a good idea to add an option to be able to use the old behaviour.

**Comment by alvaroaleman** [comment]
@berendt Well, it is an internal behavior and as long as the old behavior doesn't offer any advantages, the cost of keeping it it are too high: A config option adds complexity  from a users POV and the old code adds complexity from a maintainers POV.

If you have concerns regarding new issues, just go ahead and test the PR by running `pip install git+https://github.com/alvaroaleman/molecule.git@bugfix/openstack_performance_rebased` in a virtualenv.

**Comment by berendt** [comment]
@alvaroaleman I do not have a strong behaviour. I think it is fine to not add additional complexity and to spin up instances in parallel.
