### ISSUE TITLE
Configurable SSH timeout for OpenStack instances

### ISSUE THREAD

**Issue by berendt** [metacloud/molecule#718]
# Issue Type

- Feature request

# Desired Behaviour

At the moment the maximum possible timeout (30 seconds) is hardcoded. Maximum of 5 tries with a timeout of 6 seconds. The number of tried and/or the timeout should be configurable because there are OpenStack environments where it takes longer then 30 seconds (I am using one of this environments at the moment).

# Actual Behaviour (Bug report only)

```
ERROR: Could not reach instance molecule-betacloud.docker within limit of 30 seconds
```

**Comment by alvaroaleman** [comment]
Yeah I anticipated this would come up after I fixed the timeouting ;)

I'll most likely have a PR for this done by the start of next week, if no one else wants/can do it.

**Comment by retr0h** [comment]
This is definitely a bug and likely impacting many.  If possible would be good to fix this sooner than later.

**Comment by berendt** [comment]
Btw I never had an issue with the SSH timeout, the real issue is #722. Anyway, it is good to now have a configurable SSH timeout.
