### ISSUE TITLE
Create a vagrant module

### ISSUE THREAD

**Issue by retr0h** [metacloud/molecule#720]
A molecule v2 tracking issue.

Create an Ansible vagrant module to manage instances.  Since Ansible does not ship with a  vagrant module.

**Comment by conorsch** [comment]
Assuming we don't the module depending on `python-vagrant`, this should mostly be wrapping logic. I think this would be a great addition.

**Comment by retr0h** [comment]
Yeah, would simply require `python-vagrant` and be hidden away inside the core of Molecule acting as an Ansible module.

**Comment by retr0h** [comment]
Implemented in #729.
