### ISSUE TITLE
Format of molecule.yml ansible group_vars/host_vars is confusing

### ISSUE THREAD

**Issue by manics** [metacloud/molecule#721]
# Issue Type

- Feature request

# Molecule and Ansible details

```
$ ansible --version
ansible 2.1.4.0
  config file = 
  configured module search path = Default w/o overrides
$ molecule --version
molecule, version 1.18.0
```

- Molecule installation method: `pip install molecule`
- Ansible installation method: `pip install "ansible<2.2"`

# Desired Behaviour

The format for specifying multiple group vars for a single group in `molecule.yml` is confusing For example, the variables for `group1` are in the form of a list of **one** dict:
```
ansible:
  group_vars:
    group1:
      - foo: 1
        bar: 2
```
Multiple dicts are silently ignored (in this example `bar` is completely ignored):
```
    group1:
      - foo: 1
      - bar: 2
```
Using just a dict, which would match the behaviour of [`vars` in a playbook](http://docs.ansible.com/ansible/playbooks_variables.html#variables-defined-in-a-playbook), is invalid syntax:
```
    group1:
      foo: 1
      bar: 2
```
```
 line 327, in _add_or_update_vars
    target_var_content = vars_target[target][0]
KeyError: 0
```

Is there a reason for this behaviour? Would you object to a PR for one or more of:
- Return a warning or (fail?) if multiple lists are passed
- Flatten multiple lists
- Allow variables to be passed as a dict

**Comment by retr0h** [comment]
> Is there a reason for this behaviour? Would you object to a PR for one or more of:

Probably an oversight on our part.  We probably want vars to be passed in as a dict.
