### ISSUE TITLE
"Do not alter users known_hosts file in Openstack driver" breaks _check_ssh_availability method

### ISSUE THREAD

**Issue by berendt** [metacloud/molecule#722]
I think that the Commit 470fb2f2fc81bf65cd32760a1dfb77208e95c94d breaks the ``_check_ssh_availability`` method in ``molecule/driver/openstackdriver.py``.

In the old implementation of the method the ``sshkey_filename`` was used to connect with the instance. In the new implementation this parameter is not used.

Because of that the command will always fail with the error ``Permission denied (publickey).`` and exit code ``255`` and the ``_check_ssh_availability`` will always return ``False``. Because of that the OpenStack driver is broken at the moment.

**Comment by alvaroaleman** [comment]
You're right, currently this only works if your agent has the key or it is
in a default location, but not anymore if it is in a non-standard location.

**Comment by berendt** [comment]
@alvaroaleman I think this has to be fixed. For the OpenStack driver the used key file is configurable with the ``keyfile`` parameter.

**Comment by retr0h** [comment]
You going to tackle this one when you get a chance @alvaroaleman?

**Comment by alvaroaleman** [comment]
Yeah, you'll have a pr by tomorrow

**Comment by retr0h** [comment]
Fixed by #723.
