### ISSUE TITLE
Add support for ARA

### ISSUE THREAD

**Issue by berendt** [metacloud/molecule#728]
# Issue Type

- Feature request

# Desired Behaviour

ARA (https://github.com/openstack/ara) is an Ansible callback plugin to record and visualise Ansible playbook runs. It would be nice to have a native integration in Molecule to improve the readability of complex playbook runs.

**Comment by retr0h** [comment]
I'll look into integrating this into v2.  However, you can integrate it today by setting the callback path in your `molecule.yml`.

```
ansible:
  raw_env_vars:
    ANSIBLE_CALLBACK_PLUGINS: ../../plugins/callbacks
```

**Comment by dmsimard** [comment]
Hi! Was just pinged about this issue :)

ARA author here if you have questions.
Otherwhise, the [FAQs](http://ara.readthedocs.io/en/latest/faq.html) are a fast way to see what the project is about.

For some live data, here's two examples:
- [http://logs.openstack.org/32/425932/4/check/gate-ara-integration-latest-centos-7/b23e578/logs/build/](http://logs.openstack.org/32/425932/4/check/gate-ara-integration-latest-centos-7/b23e578/logs/build/)
- [http://logs.openstack.org/46/416046/9/check/gate-kolla-ansible-dsvm-deploy-centos-binary-centos-7-nv/c5a6e09/logs/playbook_reports/](http://logs.openstack.org/46/416046/9/check/gate-kolla-ansible-dsvm-deploy-centos-binary-centos-7-nv/c5a6e09/logs/playbook_reports/)

For the next major release I'm working on a major UI overhaul, you can have a look at the general direction  from looking at an early prototype [here](https://www.youtube.com/watch?v=h3vY87_EWHw).

**Comment by retr0h** [comment]
> Hi! Was just pinged about this issue :)

Nice project!

I was just looking this over.  I'm not entirely sure it makes sense to add this to molecule as a default.  However, anyone can configure ara if they choose, as described above.

**Comment by dhutty** [comment]
@berendt What kind of integration functionality are you looking for? If you install the ARA callback plugin into a path that Molecule uses by default or if you configure Molecule's Ansible to use a path where the ARA call back plugin is installed as shown by @retr0h above, Molecule will record its Ansible runs into the ARA database.

Is there something else you're envisioning? @dmsimard Can you envisage some additional useful functionality we could provide to enhance either project?

**Comment by mnaser** [comment]
We've integrated ARA as part of our Ansible runs, more specifically as part of our CI.  The advantages that we've seen are the following:

- Timing information: It gives a very nice and full breakdown of how long tasks took which is extremely productive and useful in speeding things up
- Easy and visible troubleshooting: We haven't had to use the actual server too much, but using the static generated files and browsing them allows us to dive deep into what's happening

It's been really useful for our devs in terms of figuring out *why* something happened, so it's extremely productive in terms of showing what happened where and much easier to scroll through a terminal.  It stores all the verbose information that you can extract at anytime from previous runs, which is much easier than running ansible with `-vvv` spamming your terminal screen.

**Comment by dhutty** [comment]
@mnaser Yes, while we're not currently using ARA as part of our primary CI tooling, I have used it and like it. Is there some specific integration you're looking for?

**Comment by retr0h** [comment]
Going to close this out.  It really doesn't feel like it belong is molecule's core, since Molecule allows developers to add any number of plugins they wish.
