### ISSUE TITLE
How to pass `-vv` option to testinfra verifier?

### ISSUE THREAD

**Issue by tknerr** [metacloud/molecule#735]
# Issue Type

- Bug report (or Question :))

# Molecule and Ansible details

```
$ ansible --version
2.1.1.0
$ molecule --version
1.8.4
```

- Molecule installation method: pip
- Ansible installation method: pip

# Desired Behaviour

I want to be able to pass the `-vv` option to testinfra, so that it shows the full length document if a string match is not found

# Actual Behaviour (Bug report only)

When using this in `molecule.yml`:

```
testinfra:
  vv: yes
```

Then testinfra will be invoked with `--vv` causing an invalid argument error. 

I had tried this variation too:

```
testinfra:
  '-vv': yes
```

but this ends up as `---vv` when testinfra is invoked

**Comment by tknerr** [comment]
I believe with latest molecule version it's still the same, and ends up being an issue on how to properly pass `-vv` to `sh` via `**kwargs`:
https://github.com/metacloud/molecule/blob/master/molecule/verifier/testinfra.py#L99

**Comment by abtreece** [comment]
@tknerr Are you trying to enable verbose mode? You can pass options to the testinfra verifier using the options dict...

`verifier:
  name: testinfra
  options:
      verbose: true`

**Comment by tknerr** [comment]
@abtreece tried it with verbose, but it did not help (using molecule 1.8.4, I know...).

So here is my use case: there is a very long string I want to compare. In the testinfra output below, the actual vs expected strings are both truncated, so I only know that something in this huge string did not match, but I don't know what. Testinfra suggests to use `-vv` flag to get that output (see last line of output below):

```
 test_jenkins_plugins_are_installed_in_the_defined_version_[ansible://jenkins-master]

Command = <command>

    def test_jenkins_plugins_are_installed_in_the_defined_version_(Command):
        jenkins_host = 'http://admin:admin@localhost:8080'
        plugins_query = 'pluginManager/api/xml?depth=1&xpath=/*/*/shortName|/*/*/version&wrapper=plugins'
        cleanup_regex = r's/.*?<shortName>([\w-]+).*?<version>([^<]+)()(<\/\w+>)+/\1@\2\n/g'
        installed_plugins = Command("curl '%s/%s' | perl -pe '%s' | sort" % (jenkins_host, plugins_query, cleanup_regex)).stdout
>       assert installed_plugins == """\
    ace-editor@1.1
    ansicolor@0.4.3
    ant@1.4
    antisamy-markup-formatter@1.5
    bouncycastle-api@2.16.0
    branch-api@1.11.1
    cloudbees-bitbucket-branch-source@1.8
    cloudbees-folder@5.16
    credentials@2.1.10
    display-url-api@0.5
    durable-task@1.12
    embeddable-build-status@1.9
    envinject@1.93.1
    external-monitor-job@1.7
    git@3.0.1
    git-client@2.2.0
    git-server@1.7
    handlebars@1.1.1
    htmlpublisher@1.12
    icon-shim@2.0.3
    javadoc@1.4
    jobConfigHistory@2.15
    job-dsl@1.57
    jquery-detached@1.2.1
    junit@1.19
    ldap@1.13
    mailer@1.18
    matrix-auth@1.4
    matrix-project@1.8
    maven-plugin@2.13
    mercurial@1.57
    momentjs@1.1.1
    pam-auth@1.3
    pipeline-build-step@2.4
    pipeline-graph-analysis@1.3
    pipeline-input-step@2.5
    pipeline-milestone-step@1.3
    pipeline-rest-api@2.4
    pipeline-stage-step@2.2
    pipeline-stage-view@2.4
    scm-api@1.3
    scriptler@2.9
    script-security@1.25
    sectioned-view@1.20
    simple-theme-plugin@0.3
    ssh-credentials@1.12
    ssh-slaves@1.12
    structs@1.5
    token-macro@2.0
    uno-choice@1.5.2
    windows-slaves@1.2
    workflow-aggregator@2.4
    workflow-api@2.8
    workflow-basic-steps@2.3
    workflow-cps@2.23
    workflow-cps-global-lib@2.5
    workflow-durable-task-step@2.8
    workflow-job@2.9
    workflow-multibranch@2.9.2
    workflow-scm-step@2.3
    workflow-step-api@2.7
    workflow-support@2.12\
    """
E       assert 'ace-editor@1...-support@2.12' == 'ace-editor@1....-support@2.12'
E           ace-editor@1.1
E           ansicolor@0.4.3
E           ant@1.4
E           antisamy-markup-formatter@1.5
E           bouncycastle-api@2.16.0
E           branch-api@1.11.1
E           cloudbees-bitbucket-branch-source@1.8
E           cloudbees-folder@5.16
E           credentials@2.1.10
E         Detailed information truncated (57 more lines), use "-vv" to show

```

**Comment by abtreece** [comment]
ah, yes... i see that now. I'm not sure how to fix that in the code, but I think you could work around it in one of two ways. Prior to running your test you could:

`export PYTEST_ADDOPTS="-vv"`

or you could also create a pytest.ini file with the following for the same result:

```[pytest]
addopts = "-vv"```

http://doc.pytest.org/en/latest/customize.html

**Comment by retr0h** [comment]
@tknerr Can you verify #736 works as expected.

**Comment by abtreece** [comment]
@retr0h Based on my testing your fix does set -vv properly for both `vv:  yes` and `vv: true` and does not get set if it's unset, False, or no... oddly if it's set to anything other than false or no it results in a true result.

However, it seems that verbose: true elicits slightly behavior than -vv so I am thinking that they are being handled differently by pytest. When I enable vv in options with verbose the verbose option no longer gets set.

**Comment by retr0h** [comment]
> However, it seems that verbose: true elicits slightly behavior than -vv so I am thinking that they are being handled differently by pytest. When I enable vv in options with verbose the verbose option no longer gets set.

Yeah, `verbose` is not as verbose.

`verbose` should show similar results to `v`, where `vv` and `vvv` would show more debugging info.

**Comment by abtreece** [comment]
yeah, I get that. I'm just seeing some unexpected behavior...

with `verbose: true` as an option to testinfra the tests appear to run twice

```
$ molecule verify
--> Executing ansible-lint...
--> Executing flake8 on *.py files found in tests/...
--> Executing testinfra tests found in tests/...
============================= test session starts ==============================
platform darwin -- Python 2.7.12, pytest-3.0.6, py-1.4.32, pluggy-0.4.0 -- /Users/abtreece/Work/.venv-molecule/bin/python2.7
cachedir: .cache
rootdir: /Users/abtreece/Work/Ansible/ntp, inifile:
plugins: testinfra-1.4.5, mock-1.5.0, helpers-namespace-2016.7.10, cov-2.4.0
collected 4 itemss

tests/test_default.py::test_hosts_file[docker://centos] PASSED
tests/test_default.py::test_ntp_is_installed[docker://centos] PASSED
tests/test_default.py::test_hosts_file[docker://centos] PASSED
tests/test_default.py::test_ntp_is_installed[docker://centos] PASSED

============================ pytest-warning summary ============================
WP1 None Module already imported so can not be re-written: testinfra
================= 4 passed, 1 pytest-warnings in 1.00 seconds ==================
```

with `vv: true` set and `verbose: true` removed the tests run 1 time each...

```
$ molecule verify
--> Executing ansible-lint...
--> Executing flake8 on *.py files found in tests/...
--> Executing testinfra tests found in tests/...
============================= test session starts ==============================
platform darwin -- Python 2.7.12, pytest-3.0.6, py-1.4.32, pluggy-0.4.0 -- /Users/abtreece/Work/.venv-molecule/bin/python2.7
cachedir: .cache
rootdir: /Users/abtreece/Work/Ansible/ntp, inifile:
plugins: testinfra-1.4.5, mock-1.5.0, helpers-namespace-2016.7.10, cov-2.4.0
collected 2 itemss

tests/test_default.py::test_hosts_file[docker://centos] PASSED
tests/test_default.py::test_ntp_is_installed[docker://centos] PASSED

============================ pytest-warning summary ============================
WP1 None Module already imported so can not be re-written: testinfra
================= 2 passed, 1 pytest-warnings in 0.67 seconds ==================
```

The behavior seems to have been there before this change so possibly a different bug.

**Comment by tknerr** [comment]
@abtreece @retr0h thanks for all your help

I was not able to test #736 yet, as my projects are still on 1.8.4 :-/

However, the env var or ini file approach [as suggested](https://github.com/metacloud/molecule/issues/735#issuecomment-276394490) by @abtreece would do totally fine for me

**Comment by retr0h** [comment]
@abtreece good catch.  Testinfra appears to be doing this for some reason.  Unrelated to molecule.  @philpep any ideas?

```
testinfra tests/test_default.py tests/test_example-group1.py tests/test_example-group2.py --connection=docker --verbose

tests/test_default.py::test_hosts_file[docker:/test-scenario-01] PASSED
tests/test_default.py::test_hosts_file[docker:/test-scenario-02] PASSED
tests/test_example-group1.py::test_etc_molecule_example_group1[docker:/test-scenario-01] PASSED
tests/test_example-group1.py::test_etc_molecule_example_group2[docker:/test-scenario-01] PASSED
tests/test_example-group2.py::test_etc_molecule_example_group2[docker:/test-scenario-02] PASSED
tests/test_example-group2.py::test_etc_molecule_example_group1[docker:/test-scenario-02] PASSED

```

**Comment by retr0h** [comment]
@abtreece Interesting.  I don't run into that issue.

**Comment by tknerr** [comment]
Thanks @retr0h @abtreece :+1:
