### ISSUE TITLE
Test multiple roles at once

### ISSUE THREAD

**Issue by zuzzas** [metacloud/molecule#745]
# Issue Type
- Feature request

# Molecule and Ansible details

```
$ ansible --version
ansible 2.2.1.0
$ molecule --version
molecule, version 1.20.0
```

- Molecule installation method: pip
- Ansible installation method: pip

# Feature request

In it's current form (as I've deduced from the documentation) Molecule is best suited for testing individual roles. But what if we have a big Ansible project, multiple roles. It becomes quite hard to maintain `molecule.yml` and `playbook.yml` files in each role's directory. I've got a script in place that inserts a generic templatable `molecule.yml` and `playbook.yml` files in each role's directory. That way I can check each roles before push to company's git master branch. Can the Molecule somehow implement this functionality?

Perhaps, it can already do that. If so, please, guide me.

**Comment by retr0h** [comment]
Yeah, you test each role individually, and each role would have it's own molecule.yml which describes how the role should be tested.

**Comment by zuzzas** [comment]
Thanks! Then I shall base my workflow on that principle.
