### ISSUE TITLE
Supplied Dockerfile COPY/ADD instructions fail

### ISSUE THREAD

**Issue by ggolin** [metacloud/molecule#753]
# Issue Type

- Bug report

# Molecule and Ansible details

```
ansible --version
ansible 2.2.0.0
molecule --version
molecule, version 1.19.1
```

- Molecule installation method: One of source, pip
- Ansible installation method: One of pip

# Desired Behaviour

Given: a user provided Dockerfile with COPY or ADD instructions local files should be copied/added to the container

# Actual Behaviour (Bug report only)

molecule create fails to find the local files/directories that should be copied to the container.

**Comment by retr0h** [comment]
@kireledan would you be able to look at this.  I am able to reproduce the issue, by simply using our dockerfile scenario.

```
cd molecule/test/scenarios/dockerfile/
touch foo.yml
```

Add the following to the end of the Dockerfile `COPY foo.yml /tmp` and run molecule converge.  It appears the docker build doesn't have the directory context.

**Comment by retr0h** [comment]
When a Dockerfile is provided we should simply pass the dockerfile to build vs the file object.

Will provide a real fix to this.  This gist appears to fix the Dockerfile issue, but breaks any other use case... https://gist.github.com/retr0h/5fcd058f6512cef92cfd81f8fac534b9

**Comment by abtreece** [comment]
@retr0h I was looking at this and wondering the same.

**Comment by abtreece** [comment]
After digging around a bit fileobj is one of two ways that build takes a dockerfile...

> Either path or fileobj needs to be set. path can be a local path (to a directory containing a Dockerfile) > or a remote URL. fileobj must be a readable file-like object to a Dockerfile.

I think it *could* actually be an issue with docker-py rather than molecule. I'm able to build the Dockerfile in the test scenario with the docker command, but I get an `lstat` error when I try to build it with a very simple python script using docker-py. There is an open issue referencing the same problem (https://github.com/docker/docker-py/issues/974). They reference the custom_context param in that issue, but I can't figure out how to implement that correctly when using a fileobj... it always fails with an "unexpected EOF error". So, I don't know what to think with regards to the fileobj param of the docker-py API.  The path param seems to work just fine.

**Comment by kireledan** [comment]
woops! I hadnt checked my notifications. I'll take a look into this too if it's still needed

**Comment by retr0h** [comment]
> woops! I hadnt checked my notifications. I'll take a look into this too if it's still needed

That would be helpful if you can.

**Comment by kireledan** [comment]
I was able to have a fix by conditionally passing in the build directory as tar file. So if the dockerfile parameter is used in the molecule.yml, then the current build context is zipped up and passed in to the build and removed after completion. To handle the other case, the custom_context flag is simply set to false when not using the dockerfile param.

**Comment by abtreece** [comment]
I believe that's basically the case @kireledan ... as far as I can tell the fileobj will only handle archives, seemingly either a tar or a gzip.

As a sidenote, I went into the Ansible core code to see how they were handling this and discovered that they aren't. That type of stuff is handled in ansible-container. Something to think about for the v2 conversion.

**Comment by retr0h** [comment]
> As a sidenote, I went into the Ansible core code to see how they were handling this and discovered that they aren't. That type of stuff is handled in ansible-container. Something to think about for the v2 conversion.

The beauty of V2, If ansible supports it, we support it.  Otherwise, it's an Ansible bug :)

https://github.com/metacloud/molecule/blob/v2/test/resources/playbooks/docker/create.yml#L8-L11

**Comment by retr0h** [comment]
> not sure if this is the most efficient fix... but it seems that zipping up the dir is the only way to use the custom_context flag

@kireledan what if the file we want to COPY doesn't live in the current directory.  This is very common to COPY files outside the current directory.

**Comment by kireledan** [comment]
I hadn't thought of that use case. Ill try and think of something

**Comment by retr0h** [comment]
This will not be fixed in v1.  V2 doesn't suffer from this issue.  Closing.

**Comment by premkumar-gg** [comment]
Anybody facing this in v3.0.6?

**Comment by mkesper** [comment]
Reproducible with 4.0.1
