### ISSUE TITLE
More complete example of testinfra integration?

### ISSUE THREAD

**Issue by lnunno** [metacloud/molecule#754]
I'm confused how molecule integrates with testinfra and how to actually get it to run the pytest commands from within the container. Right now it seems to run the commands from the host for example:

```python
from testinfra.utils.ansible_runner import AnsibleRunner
import urllib2

testinfra_hosts = AnsibleRunner('.molecule/ansible_inventory').get_hosts('all')


def test_getting_urls():
    """Make sure we can hit the open web for both HTTP and HTTPS.
    """
    response = urllib2.urlopen('http://www.google.com')
    assert len(response.read()) > 0
    response = urllib2.urlopen('https://www.google.com')
    assert len(response.read()) > 0
```

Where the following is my `.molecule/ansible_inventory` file:

```
molecule_proxy_centos ansible_connection=docker
molecule_proxy_ubuntu ansible_connection=docker
```

Fails on my host which does not have SSL correctly configured, but if I exec into my container and run the `urlopen` by hand it successfully completes. How do I use testinfra to run this method from within the container? I think the docs or generated code could be more clear.

**Comment by retr0h** [comment]
@lnunno Testinfra is a project on it's own.  If you are looking for information on how to run testinfra, please check out their documentation.  Molecule does nothing special in regards to running testinfra, we simply execute testinfra.

However, yes you are correct.  Any python code run inside testinfra, runs on the host executing molecule.  The only time code executes on the remote side, is when using a testinfra module.

See https://github.com/philpep/testinfra/issues/104
