### ISSUE TITLE
parametrize ansilbe_lint

### ISSUE THREAD

**Issue by hudecof** [metacloud/molecule#757]
# Issue Type

- Feature request

# Desired Behaviour

It would be good to  have option to disable some tests , add `-x SKIP_LIST` parameter to ansible_list.

I  have role where I need to use action**command** to run **service**. This triggers `[ANSIBLE0006] service used in place of service module` and the automated tests failed.

**Comment by retr0h** [comment]
Ansible lint offers this ability via [skip_ansible_lint](https://github.com/willthames/ansible-lint#false-positives).  This won't be added to molecule, but molecule v2 has the ability to pass options CLI options to the linter.  Molecule v2 will not be out for another few months.

**Comment by hudecof** [comment]
Thanks, this solved my problem. ;)
