### ISSUE TITLE
Vagrant driver adding unwanted entry on instance's /etc/hosts file

### ISSUE THREAD

**Issue by viniciusfs** [metacloud/molecule#758]
# Issue Type

- Bug report

# Molecule and Ansible details

```
ansible --version
ansible 2.2.1.0
molecule --version
molecule, version 1.19.1
```

- Molecule installation method: pip
- Ansible installation method: pip

# Desired Behaviour

Molecule needs to start a new instance and apply test playbook without apply any unwanted change on guest machine.

# Actual Behaviour (Bug report only)

Molecule's builtin Vagrant runtime is always adding a 127.0.0.1 entry on guest's /etc/hosts file.

**Comment by retr0h** [comment]
Whats the harm with /etc/hosts having the system's hostname in /etc/hosts?  I don't see the harm in this.

**Comment by viniciusfs** [comment]
When I set ip address on instance definition, I need system hostname pointing to ip address set, not 127.0.0.1.

**Comment by retr0h** [comment]
That sounds like something that you can fix with ansible.  If you don't like the way /etc/hosts is rendered, ansible can be used to correct it.  I would prefer not to make a change of this nature.

**Comment by viniciusfs** [comment]
Conditional used on https://github.com/metacloud/molecule/blob/master/molecule/cookiecutter/driver/vagrant-runtime/%7B%7Bcookiecutter.repo_name%7D%7D/vagrantfile#L220 prevents this behavior while using libvirt provider. It is the same case, the difference is that when using virtualbox provider you must set a static ip to see this behavior.

**Comment by retr0h** [comment]
@viniciusfs I'm going to close this.  If you are wanting to change the contents of /etc/hosts, feel free to write a lineinfile patch to your playbook and remove it.

**Comment by viniciusfs** [comment]
Thank you for your support! I will use libvirt driver that works like expected.
