### ISSUE TITLE
Proposal: leveraging DocOpt subcommands

### ISSUE THREAD

**Issue by rgreinho** [metacloud/molecule#76]
I wrote a tutorial here (https://github.com/rgreinho/docopt-subcommands-example) which explains how to use DocOpt subcommands in a console application. 

I think we should leverage this in order to be able to easily add options to the main command or the subcommands in the future.

link: PR #75

**Comment by retr0h** [comment]
Totally agree.

/cc @bborysenko @abrown-sg

**Comment by rgreinho** [comment]
@retr0h Even with a way better command dispatcher to get rid of the ``if ... elif ... else`` that you dislike :)

https://github.com/rgreinho/docopt-subcommands-example#find-the-command-to-execute
https://github.com/rgreinho/docopt-subcommands-example/blob/master/main.py#L37-L43

**Comment by retr0h** [comment]
> @retr0h Even with a way better command dispatcher to get rid of the if ... elif ... else that you dislike :)

![so sexy](http://gif.co/sas5.gif)

**Comment by abrown-sg** [comment]
The challenge we're facing when trying to implement this (which may be a DocOpt bug) is that long arguments don't seem to work in both forms.  For example:

`--platform=ubuntu` works
`--platform ubuntu` fails

The expected behavior is that both will work in DocOpt, however we've been unable to find a workaround with Remy's subcommand pattern that support this.

**Comment by abrown-sg** [comment]
#81 implements as much of this as possible, however, by moving commands into individual classes. This is a win regardless since it's a significant simplification over what we were using previously. It will also be easy to drop in DocOpt subcommand support once the bug is resolved.

**Comment by rgreinho** [comment]
I filed an issue upstream: https://github.com/docopt/docopt/issues/305.

**Comment by rgreinho** [comment]
@abrown-sg There was a mistake in my tutorial (that I fixed), and now the parameters for the arguments work both with and without the equal sign.

Basically there need to be an ellipsis ('``...``') after the args (looks like ``[<args>...]``), so that the program can have multiple values. The issue was that ``--platform ubuntu`` was counted has 2 arguments, but as the ellipsis was not specified, only one argument was allowed.

If you can confirm that it works for your branch as well (I don't think you pushed it, so I could not try myself), then I'll close the issue that I filled upstream.
