### ISSUE TITLE
Upgrade to Goss v0.3.0

### ISSUE THREAD

**Issue by aelsabbahy** [metacloud/molecule#761]
# Issue Type

- Feature request

# Desired Behaviour

Simple change: Goss [v0.3.0](https://github.com/aelsabbahy/goss/releases/tag/v0.3.0) is out, would be nice to upgrade molecule to the latest version.

More complex question: Now that Goss supports environment variables and variable files through `goss --vars vars.{json,yaml} validate`, see [templates](https://github.com/aelsabbahy/goss/blob/master/docs/manual.md#templates). Does molecule have support to pass variables to the test suite?

**Comment by retr0h** [comment]
> More complex question: Now that Goss supports environment variables and variable files through goss --vars vars.{json,yaml} validate, see templates. Does molecule have support to pass variables to the test suite?

I'm not sure, I would need to think about it.  In testinfra once can share ansible vars between ansible and the test suite (testinfra).  That can be useful.  In this case with goss, it's vars shared between tests, and unrelated to ansible.

**Comment by aelsabbahy** [comment]
To clarify, I would want the variables passed to goss to be the same as the ones passed to ansible.

**Comment by retr0h** [comment]
> To clarify, I would want the variables passed to goss to be the same as the ones passed to ansible.

That would be tricky to map into goss.  I'm not really interested in trying to massage all the ways Ansible determines inventory, into a file Goss can use.

Example:

Ansible lets you pass host/group vars, which Ansible then gathers and uses depending on the name of the host and group the server is in.  In Molecule we simply place these files into a location Ansible uses, and internally deals with this.  I cannot replicate this behavior in Goss by passing similar variables to Goss' --vars option.

**Comment by aelsabbahy** [comment]
Ah, didn't realize testinfra was loading the ansible vars itself.

Yeah massaging ansible vars are a bit painful, since there are many buckets of them.

**Comment by retr0h** [comment]
> Ah, didn't realize testinfra was loading the ansible vars itself.

Yeah, it's handled through the Ansible fixture.  I love this idea of yours, I am just worried about opening a can of worms to support it.  I'm sure it could be done.
