### ISSUE TITLE
Molecule fails with anyconfig 0.9.0

### ISSUE THREAD

**Issue by aliusmiles** [metacloud/molecule#762]
# Issue Type

- Bug report

# Molecule and Ansible details

```
ansible 2.2.1.0
molecule, version 1.20.3
anyconfig==0.9.0
```

- Molecule installation method: pip
- Ansible installation method: pip
- anyconfig installation method: pip

# Actual Behaviour (Bug report only)
```
molecule converge
...
  File "/usr/local/lib/python2.7/site-packages/molecule/config.py", line 108, in _combine
    conf = anyconfig.to_container(default, ac_merge=MERGE_STRATEGY)
AttributeError: 'module' object has no attribute 'to_container'
```

From https://github.com/ssato/python-anyconfig/blob/RELEASE_0.9.0/anyconfig/api.py:
```
r"""Public APIs of anyconfig module.
.. versionadded:: 0.8.3
...
   - Stop exporting :func:`to_container` which was deprecated and removed.
```

**Comment by retr0h** [comment]
Thanks for the bug report @aliusmiles.  This is a back burner issue, since molecule explicitly installs 0.7.0 of anyconfig.

**Comment by aliusmiles** [comment]
Guess I'll just disable updates for anyconfig then :)

P.S. Just in case, my modified pip update command:
```
pip freeze --local | grep -v '^\-e' | grep -v 'anyconfig' | cut -d = -f 1  | xargs pip install -U
```

**Comment by retr0h** [comment]
@aliusmiles of just run Molecule in a venv so this type of thing isn't an issue.

**Comment by retr0h** [comment]
Closing, will address when molecule bumps deps.
