### ISSUE TITLE
default dockerfile is not compatible with alpine

### ISSUE THREAD

**Issue by gzm55** [metacloud/molecule#777]
# Issue Type

- Bug report
- Feature request

# Molecule and Ansible details

```
ansible --version
2.2.1

molecule --version
1.21.1
```

- Molecule installation method: pip
- Ansible installation method: OS package

# Desired Behaviour

1. alpine based images should works with default bootstrap dockerfile.
2. add an option to skipping bootstrap dockerfile for developping bootstrap roles.

# Actual Behaviour (Bug report only)

molecule init --driver docker
edit to use 'image: alpine'
molecule test # fail, alpine have no python and use apk package system.

**Comment by retr0h** [comment]
Alpine isn't a distro we support out of the box.  However, you can use Alpine with Molecule.  Simply provide your own [Dockerfile](https://github.com/metacloud/molecule/blob/4a3e78d2ccd3496144f29ac2ccb11d8cbde06734/test/scenarios/dockerfile/Dockerfile) and configure [molecule.conf to use the Dockerfile](https://github.com/metacloud/molecule/blob/4a3e78d2ccd3496144f29ac2ccb11d8cbde06734/test/scenarios/dockerfile/molecule.yml#L10).

**Comment by gzm55** [comment]
alpine is the default image of docker, and is used as base image widely. I think is not hard to support, when install python, only use POSIX shell, and detect apk command then 'apk --update add python'.

**Comment by retr0h** [comment]
> alpine is the default image of docker, and is used as base image widely. I think is not hard to support, when install python, only use POSIX shell, and detect apk command then 'apk --update add python'.

Either way, I provided you a very simple work-a-round.

**Comment by gzm55** [comment]
OK, i'll have a try.
