### ISSUE TITLE
Request: docker driver should config to select a ansible connection

### ISSUE THREAD

**Issue by gzm55** [metacloud/molecule#779]
# Issue Type

- Feature request

# Molecule and Ansible details

```
ansible --version
2.2.1
molecule --version
1.21.1
```

- Molecule installation method: pip
- Ansible installation method: OS package

# Desired Behaviour

Because some roles are depending on ssh, and docker driver have a better performance for testing, we should have a config key to set ssh connection instead of docker connection. In adittion, each ssh container should have a different `ansible_port`.

# Actual Behaviour (Bug report only)

docker driver seems to always use docker connection in ansible.

**Comment by alvaroaleman** [comment]
Can you provide a sample of a role that depends on the ssh connection driver?

**Comment by gzm55** [comment]
I have some ssh metal machines, so i want some roles to handle basic configurations about ssh, such as
https://github.com/gzm55/ansible-ssh-pubkey-login-role
https://github.com/gzm55/ansible-smart-ssh-pipelining-role

the main logic is for sshd service.

**Comment by retr0h** [comment]
I don't believe I would implement this into Molecule v1.  This could get implemented into v2.  However, it seems like it is unnecessary.

You could simply have molecule spin up two instances with ssh configured as you desire.  You would then write a testinfra test to ssh into the other instance and verify it works as expected.  Simple client/server instances test.  I see no need to change the connection driver.

**Comment by gzm55** [comment]
@retr0h in ansible_playbook.py, the driver specific connection params (including connection=docker) will be put into ansible cli params, then the role is played under docker connection, that is not expected.

**Comment by retr0h** [comment]
@gzm55 ah, yeah I see what you mean.  I'm not entirely sure the best approach to solve your particular issue.  This is somewhat of an edge case, but not entirely.

Would things work to your satisfaction if 'ansible_port' and `connection` was settable from molecule.yml?

**Comment by alvaroaleman** [comment]
IMHO this is a pretty edgy case.

You could workaround the issue by adding a new host and delegating to it in the playbook:

```
- name: Add docker host with ssh connection
  add_host:
    name: dockerhost_ssh
    ansible_host: "{{ ansible_default_ipv4.address }}"
    ansible_connection: ssh
- name: Do stuff via ssh
  delegate_to: dockerhost_ssh
  debug: msg="Hello world!"
```

**Comment by gzm55** [comment]
> Would things work to your satisfaction if ansible_port and connection was settable from molecule.yml?

Yes, it could be enough.

**Comment by gzm55** [comment]
> You could workaround the issue by adding a new host and delegating to it in the playbook:

This workaround solution may work, but still the developer has to deal with dockerhost_ssh carefully, such as, whether dockerhost_ssh will be in the ansible_play_hosts of the following tasks, what's the behavior of nesting delegate_to (role may contain a delegated task), etc.

I think the way of settable port and connection is more maintainable.

**Comment by alvaroaleman** [comment]
Actually, you don't even need the `delegate_to`, you can just add a play at the beginning of your playbook that puts all docker containers via `add_host` in a new group, then run the actual test play against that group.

**Comment by retr0h** [comment]
> IMHO this is a pretty edgy case.

Agreed...

**Comment by retr0h** [comment]
@gzm55 @alvaroaleman provided a work-a-round.  However, this request is edgy and prob something we will not address.  Thanks for spending the effort to create an issue.
