### ISSUE TITLE
pre-release 2.0 to pypi (please :-)

### ISSUE THREAD

**Issue by sean-abbott** [metacloud/molecule#781]
# Issue Type

Is it possible to put the 2.0 branch on pypi as a alpha, beta, or release candidate?
https://packaging.python.org/distributing/#pre-release-versioning

Although it does appear that it's fallen behind on some of the commits, it would be great to be able to de-select linting when I'm using galaxy roles that I actually don't want linted.

**Comment by retr0h** [comment]
Hey @sean-abbott it is not ready yet.  You can always build from a git checkout until then.
