### ISSUE TITLE
AttributeError: 'module' object has no attribute 'APIClient'

### ISSUE THREAD

**Issue by jgeusebroek** [metacloud/molecule#782]
# Issue Type

- Bug report

# Molecule and Ansible details

Docker version 17.03.0-ce, build 60ccb22
ansible 2.2.1.0
molecule, version 1.21.1

- Molecule installation method:  pip
- Ansible installation method: pip

# Desired Behaviour

Working TravisCI Tests

# Actual Behaviour (Bug report only)

Suddenly my TravisCI tests failed. The test and code didn't change. Only thing that changed is molecule version and (maybe) docker version.

molecule, version 1.20.0 WORKS
molecule, version 1.21.1 **FAILS**

I can replicate this problem in my lab environment, 1.21.1 breaks.

Example output:
https://travis-ci.org/jgeusebroek/ansible-role-maxmind-geoip/jobs/213459812#L411

**Comment by popstas** [comment]
@jgeusebroek, see #771

**Comment by retr0h** [comment]
Thanks @popstas

**Comment by jgeusebroek** [comment]
Thanks!
