### ISSUE TITLE
Ansible Version Poll

### ISSUE THREAD

**Issue by retr0h** [metacloud/molecule#786]
This poll is intended for users of Molecule.  Which version(s) of Ansible do you use with Molecule?

**Comment by retr0h** [comment]
1.9.6

**Comment by retr0h** [comment]
2.1.4

**Comment by retr0h** [comment]
2.2.1

**Comment by retr0h** [comment]
2.0 - Unsupported by Molecule

**Comment by gzm55** [comment]
Hi, may someone use dev branch source directly?

**Comment by retr0h** [comment]
> Hi, may someone use dev branch source directly?

Dev branch of Ansible?

**Comment by gzm55** [comment]
> Dev branch of Ansible?
Yes.

**Comment by manics** [comment]
I put a 👍 on 2.2.1. We also use 2.1.4, though now that we've figured out workarounds for bugs/changes in 2.2 we should be dropping 2.1.

**Comment by yveslaroche** [comment]
2.2.1 with some patches from dev.

**Comment by simonmcc** [comment]
2.2.0.0

**Comment by retr0h** [comment]
Thanks all.
