### ISSUE TITLE
Run molecule with specified vm/instance

### ISSUE THREAD

**Issue by HanXHX** [metacloud/molecule#790]
# Issue Type

- Feature request

# Molecule and Ansible details

```
ansible 2.2.1.0
molecule, version 1.22.0
```

- Molecule installation method: pip
- Ansible installation method: pip

# Desired Behaviour

I would like a new feature on CLI  (molecule test/converge...) "--name". When you have many instances/vms, it can be useful to test only 1 instance/vm.

**Comment by retr0h** [comment]
Hi @HanXHX - I don't believe this is a feature we will be implementing at this time.  If one wishes to target a host they can simply update their playbook, specifying the host to target.  Thanks for raising the issue.
