### ISSUE TITLE
Request support ansible 2.2.2 and 2.3-rc2

### ISSUE THREAD

**Issue by gzm55** [metacloud/molecule#792]
# Issue Type

- Feature request

- Molecule installation method: pip
- Ansible installation method: OS package

# Desired Behaviour

* 2.2.2 is released.
* 2.3 is now rc2, we should prepare for it.

**Comment by gzm55** [comment]
https://github.com/ansible/ansible/issues/23016
Hi, this bug of ansible==2.2.2 seems affect molecule.

**Comment by gzm55** [comment]
a work round solution is putting all ungroup hosts into [all] group;
or wait ansible 2.2.3 then release molecule 1.24

**Comment by gzm55** [comment]
Hi @retr0h 
a late good news is ansible v2.3 is released: https://github.com/ansible/ansible/releases/tag/v2.3.0.0-1

**Comment by retr0h** [comment]
thanks @gzm55
