### ISSUE TITLE
Request config for required molecule version

### ISSUE THREAD

**Issue by gzm55** [metacloud/molecule#795]
# Issue Type

- Feature request

# Desired Behaviour

Each releases of molecule may introduce some breaking changes (when major or minor version bumped),
so we should be able to request the expected molecule version in molecule.yml, it is important when cooperative developping of ansible roles, or migrating between molecule versions (especially v1 --> v2 in the future).

**Comment by retr0h** [comment]
Wouldn't this be solved by simply pinning your dependencies?  If you are concerned with this, wouldn't you have a requirements file that pins you to `molecule==1.2.3` in your venv vs always pulling current, and having to manage that dependency in `molecule.yml`.

**Comment by gzm55** [comment]
OK, got it~
