### ISSUE TITLE
Provision OpenStack test VMs with a Heat template

### ISSUE THREAD

**Issue by clabu** [metacloud/molecule#798]
# Issue Type

- Feature request

# Desired Behaviour

It would be nice if it would be possible to have more control over the test VMs that Molecule provisions on OpenStack. For example, to be able to give Molecule a [Heat](https://wiki.openstack.org/wiki/Heat) template to use when provisioning the test environment.

**Comment by retr0h** [comment]
Hi @clabu - This probably isn't something I am planning to implement.  Also, not every operator runs heat in their cloud, and Molecule v2 provides more control.  Thanks for the suggestion!
