### ISSUE TITLE
Molecule Openstack Environment Variable

### ISSUE THREAD

**Issue by gogskrish** [metacloud/molecule#799]
# Issue Type
   Question

  Molecule OpenStack: How to add the OpenStack environment variable in Molecule.YAML file.
  Eg: os_auth_url, os_username, os_password, os_tenant_name etc. I tried including these variable using Env in molecule.yml. It is not reflecting. The only way is that you need to execute the RC file and set the Env variable to the OS.

**Comment by alvaroaleman** [comment]
That is not supposed to happen, as it would mean storing secrets in `molecule.yml`.

If you are looking for an easy way to set your credentials, check out OS client config config files: https://docs.openstack.org/developer/os-client-config/#config-files

**Comment by retr0h** [comment]
Thanks @alvaroaleman!
