### ISSUE TITLE
[V2] Add ability to define custom path for molecule_inventory_file path

### ISSUE THREAD

**Issue by achaussier** [metacloud/molecule#801]
# Issue Type

- Feature request

# Desired Behaviour

## Feature request resume
Use molecule to test full Ansible deployments with their context, not only roles.

## Method
Add the ability to set custom paths for molecule_inventory_file via an entry in molecule.yml file

## Explanation
If we have this Ansible project structure:
```
...
── inventories
│   └── testing
│       ├── hosts
│       ├── group_vars
│       │   └── all.yml
│       └── host_vars
...
```
and if we can create the ansible inventory file in inventories/testing/ folder, tests can use variables defined in group_vars and host_vars.

With this change, we can be able to test Ansible deployments with their context, without (or little) variables duplication.

**Comment by alvaroaleman** [comment]
Hey @achaussier,

So if I correctly understand your use case, you just want to be able to use {group,host}_vars files?

You could achieve this by using playbook-relative {group,host}_vars. AFAIK the only place in the Ansible doc that mentions they actually exist is the [variable precedence section](https://docs.ansible.com/ansible/playbooks_variables.html#variable-precedence-where-should-i-put-a-variable). (Scroll down to the "In 2.x, we..." part).

**Comment by popstas** [comment]
Here's my workaround for using `group_vars` and `roles` in project root:

``` bash
rm -rf .molecule/group_vars && ln -s "$PWD/group_vars" .molecule
molecule test
```
Then molecule tests uses native `group_vars/all` directory if variable `ansible.group_vars` is not defined in `molecule.yml`.

**Comment by achaussier** [comment]
Hi @alvaroaleman and @popstas 

Yes, it is my use case, but not with the relative playbook vars, but inventory relative using [alternative directory layout](http://docs.ansible.com/ansible/playbooks_best_practices.html#alternative-directory-layout)

The @popstas workaround can be a great solution also, but if this can be managed automaticaly by Molecule, it's better. Perhaps via a setting to set the source vars path (to be able to use playbook or inventory relative variables) ?

**Comment by retr0h** [comment]
@achaussier to verify, this is v2 request?

**Comment by achaussier** [comment]
Hi @retr0h , yes it is a v2 request.

**Comment by retr0h** [comment]
This isn't something Molecule will be tackling anytime.  Inventory path is specific due to scenarios.  This isn't something that will likely change any time soon.  Thanks all.
