### ISSUE TITLE
[V2] testinfra_dir usage

### ISSUE THREAD

**Issue by aroundthecode** [metacloud/molecule#805]
# Question / Doc update

Hi there, I'm trying to configure molecule v2 to have a test folder outside the scenario one in order to reuse test across multiple scenarios.

Reading docs and issues I understand **testinfra_dir** is the key to achieve this, but can't sort out how to configure this in V2.

so far I've tried
```
verifier:
    name: testinfra
    enabled: True
    directory: "{{ lookup('env','ANSIBLE_ROLES_PATH') }}/*/testinfra"
```

but with no success. I'd like to have a "global" folder (at the same level of "roles" folder) and/or a dedicated folder for each role for this (as per example above). Both of them would be great.

Moreover which is the base-folder for all path declared in molecule.yaml ? Logs should be more verbose on such information (they simply say they can't find any test but no reference to which folder is being scan for) at least at debug level and/or documentation should support with some info on this.

Thanks in advance for any hint, you guys are doing great job with this!

**Comment by retr0h** [comment]
> Hi there, I'm trying to configure molecule v2 to have a test folder outside the scenario one in order to reuse test across multiple scenarios.

Hi @aroundthecode it's not really a use case that I am currently supporting ATM.

**Comment by aroundthecode** [comment]
hi @retr0h,

Maybe i'm moving in the wrong direction. I suppose scenarios are for testing roles with different "server" setup (e.g. ubuntu, centos, etc..).

This bring me to the question, have I to duplicate all my test for each of them?

I'm not expecting great difference in testing a vagrant centos 6.8 agains its docker counterpart, not many difference in same test on a centos 7.

Test re-use bring me to having a test folder outside the scenario, is there a different best practice to achieve the same result?

**Comment by retr0h** [comment]
v2 is a work in progress.  It is not released, nor is it completed.  If you wish to use it, feel free.  However, it's not close to it's end state, nor am I ready to support it.

With that said:

> Maybe i'm moving in the wrong direction. I suppose scenarios are for testing roles with different "server" setup (e.g. ubuntu, centos, etc..).
> 
> This bring me to the question, have I to duplicate all my test for each of them?
> 
> I'm not expecting great difference in testing a vagrant centos 6.8 agains its docker counterpart, not many difference in same test on a centos 7.

I would not separate out diff OSes into scenarios.  I would have your bootstrap playbook start them all up, so that they can be converged all at the same time.
> 
> Test re-use bring me to having a test folder outside the scenario, is there a different best practice to achieve the same result?

A scenario is a form of testing different aspects of your role, that would require different create -> converge -> test cycles.

**Comment by aroundthecode** [comment]
I'm aware of being on a devel-branch with anything which goes with it, no worry :)

So basically the right approach for this is to have multiple docker instances with different OS in the same scenario, leaving a different scenario for a different "configuration" of my role (e.g. passing different CLI parameters).

This surely is a good hint to go on with my work, I'll surely try structure my code this way, thanks a lot. 👍 

However If I'm quite sure that some test-code share across scenarios could surely come in handy.
Checking v1 issue I noticed #234 and it seems to me it could fit, is there anything similar in v2 or any plan for backporting?

thanks for your time and support!

**Comment by retr0h** [comment]
> I'm aware of being on a devel-branch with anything which goes with it, no worry :)
> 
> So basically the right approach for this is to have multiple docker instances with different OS in the same scenario, leaving a different scenario for a different "configuration" of my role (e.g. passing different CLI parameters).
> 
> This surely is a good hint to go on with my work, I'll surely try structure my code this way, thanks a lot. 👍

That is my current suggestion.  I am hoping it is a pattern that works well for people. 

> 
> However If I'm quite sure that some test-code share across scenarios could surely come in handy.
> Checking v1 issue I noticed #234 and it seems to me it could fit, is there anything similar in v2 or any plan for backporting?
> 
> thanks for your time and support!

I would need to look and see why it doesn't work.  The testinfra module allows the CLI args to be overriden.  What you are doing seems like it "should" work.  However, I haven't looked.  I need to finish landing a few v1 and v2 patches, and then I can look later. 👍

**Comment by retr0h** [comment]
HI @aroundthecode 

This works as you described.  Here is what I ended up doing.  I copied tests to /tmp/tests and modified my molecule.yml.  The key is making sure the tests can find their inventory file.  As you see below the runner needs the path to ansible_inventory properly supplied, which is likely where you were running into problems.

```
[jodewey:~/git/molecule_2/test/scenarios/driver/docker] [molecule2-env-2.7.12] v2(+1/-0)+ ± cat molecule/default/tests/test_default.py
import testinfra.utils.ansible_runner

testinfra_hosts = testinfra.utils.ansible_runner.AnsibleRunner(
    '.molecule/ansible_inventory.yml').get_hosts('all')
```

```
 verifier:
     name: testinfra
    directory: /tmp/tests
```

```
[jodewey:~/git/molecule_2/test/scenarios/driver/docker] [molecule2-env-2.7.12] v2(+1/-0)+ ± molecule verify --scenario-name default
--> Scenario: [default]
--> Verifier: [testinfra]
--> Executing Flake8 on files found in /tmp/tests/...
--> Executing Testinfra tests found in /tmp/tests/...
    ============================= test session starts ==============================
    platform darwin -- Python 2.7.12, pytest-3.0.7, py-1.4.33, pluggy-0.4.0
    rootdir: /tmp/tests, inifile:
    plugins: testinfra-1.6.0, mock-1.5.0, helpers-namespace-2016.7.10, cov-2.4.0, catchlog-1.2.2
collected 1 itemss

    ../../../../../../../../../../tmp/tests/test_default.py .

    ============================ pytest-warning summary ============================
    WP1 None Module already imported so can not be re-written: testinfra
    WC1 None SystemInfo fixture is deprecated. Use host fixture and get SystemInfo module with host.system_info
    WC1 None TestinfraBackend fixture is deprecated. Use host fixture and get backend with host.backend
    ================= 1 passed, 3 pytest-warnings in 1.13 seconds ==================
Verifier completed successfully.
```

**Comment by retr0h** [comment]
@aroundthecode I made this a bit simpler.  You no longer need to pass the path to the [ansible inventory file in the test files](https://github.com/metacloud/molecule/commit/c7894b5b5e5cc48ad6372a1bd498dd1f619fb16c). 

This should allow you to change the testinfra directory, w/o needing to touch the test files.

**Comment by retr0h** [comment]
Closing, let me know if this doesn't resolve your issues.

**Comment by aroundthecode** [comment]
Hi @retr0h 
Just tested your changes and they works perfectly.
I was able to create two different scenario, each of them runs both centos68 and centos73 as suggested, but they have a common test folder and I can use pytest mark annotation to assign them to each scenario, reusing shared ones

my molecule.yml (test annotated as "common" are shared, "server" are specific for this scenario
```
verifier:
    name: testinfra
    directory: "../../tests"
    options:
      m: "common or server"
```
my test sample

```
import testinfra.utils.ansible_runner
import os
import pytest

testinfra_hosts = testinfra.utils.ansible_runner.AnsibleRunner(
    os.environ['MOLECULE_INVENTORY_FILE']).get_hosts('all')

@pytest.mark.common
def test_epel_file(File):
    f = File('/etc/yum.repos.d/epel.repo')
    assert f.exists
    assert f.contains('baseurl')

```

thanks a lot for your support and for making the changes
