### ISSUE TITLE
Access role variables in tests

### ISSUE THREAD

**Issue by aroundthecode** [metacloud/molecule#806]
I'm quite new to pytest/testinfra and I was wandering which is the proper way to access ansible role variables and default to reuse them into the test.

My focus is to take all constants (e.g. configuration files path, usernames, etc..) from role-under-test defaults/main.yml and vars/main.yml to avoid constant duplication in test with may become a pain to maintain.

I suppose the key is something similar to the test_sample.py

```
testinfra_hosts = testinfra.utils.ansible_runner.AnsibleRunner(
    '.molecule/ansible_inventory.yml').get_hosts('all')
```

I tried to perform some debug on its methods, but couldn't sort this out, could you please provide any hint? Any update to docs on this would be greatly appreciated.

**Comment by retr0h** [comment]
@aroundthecode you'll need to check testinfra for this.  There are quite a few questions on this [topic](https://github.com/philpep/testinfra/issues?q=is%3Aissue+variables+is%3Aclosed) already.
