### ISSUE TITLE
OpenStack driver hangs inside ssh timing loop since the interface_ip has a null value.

### ISSUE THREAD

**Issue by gogskrish** [metacloud/molecule#809]
# Issue Type

OpenStack driver hang inside ssh timing loop since the interface_ip has a null value.

- Bug report

  I was facing issue 'Waiting for ssh availability of instance' when I use OpenStack driver.
My instance is creating successfully and is able to access the VM via SSH using molecule generated a private key manually. I dig into this error message and found that the below line is having a null value.

 instance['address'] = server['interface_ip']

I print the instance['server'] response and found that inteface_ip has a null value. So it is not able to find the IP and keep on going inside the loop until end of SSH timing.
I found that 'Private_V4' attribute has the IP address value and substituted the same.
It works fine. 

- Feature request

we need to check if the IP value is null and show the proper error (or) any reliable IP attribute.

instance['address'] = server['interface_ip']

        for instance in self.instances:
            for _ in range(ssh_timeout):
                util.print_info(
                    '\t  Waiting for ssh availability of instance %s...' %
                    instance['name'])
                if self._check_ssh_availability(
                        instance['address'],
                        instance['sshuser'],
                        timeout=1,
                        sshkey_filename=self._get_keyfile()):
                    instance['reachable'] = True
                    break

**Comment by retr0h** [comment]
@gogskrish someone who uses the OpenStack driver will need to introduce this fix.  I cannot test changes to this driver properly.

**Comment by alvaroaleman** [comment]
hey @gogskrish,

So to rephrase and ensure I correctly understand the issue: `server['interface_ip']` is undefined, instead the ip used for public access is stored in `server['Private_V4']`?

Could you print the `server` dict of a running instance, so I can see what it looks like in your case?

Also, couple more questions:

* What version of shade are you using? (Run `import shade; print shade.__version__` in a python interpreter)
* Which version of Openstack is your cloud using?
* Do you use Openstack Neutron?

**Comment by gogskrish** [comment]
Hi, Please find the below details

------------
>>> import shade;
>>> print shade.__version__
1.19.0
>>>
---------------

Not sure about the openstack version,
Yes we are using Openstack neutron.

This is the response


--> instance server Munch({'vm_state': u'active', 'OS-EXT-STS:task_state':
None, 'addresses': Munch({u'v201-NODE014-CB-PROVIDER':
[Munch({u'OS-EXT-IPS-MAC:mac_addr': u'fa:16:3e:f4:86:ef', u'version': 4,
u'addr': u'10.197.146.203', u'OS-EXT-IPS:type': u'fixed'})]}),
'terminated_at': None, 'image': Munch({u'id': u'********'}),
'OS-EXT-AZ:availability_zone': u'zone2', 'OS-EXT-STS:vm_state': u'active',
'OS-SRV-USG:launched_at': u'2017-04-14T13:55:46.000000', 'flavor':
Munch({u'id': u'5'}), 'az': u'zone2', 'id':
u'8f225ce7-7fdb-4c7f-bbb4-d498f387656b', 'security_groups':
[Munch({u'name': u'default'})], 'os-extended-volumes:volumes_attached': [],
'user_id': u'********', 'disk_config': u'MANUAL', 'OS-DCF:diskConfig':
u'MANUAL', 'networks': Munch({u'v201-NODE014-CB-PROVIDER':
[u'10.197.146.203']}), 'accessIPv4': '', 'accessIPv6': '', 'location':
Munch({'project': Munch({'domain_id': None, 'id': u'********', 'name':
'v2348_CTO_DevOps', 'domain_name': None}), 'zone': u'zone2', 'region_name':
'regionOne', 'cloud': 'envvars'}), 'power_state': 1, 'public_v4': '',
'progress': 0, 'OS-EXT-STS:power_state': 1, 'interface_ip': '',
'launched_at': u'2017-04-14T13:55:46.000000', 'metadata': Munch({}),
'status': u'ACTIVE', 'updated': u'2017-04-14T13:55:46Z', 'hostId':
u'********', 'OS-SRV-USG:terminated_at': None, 'key_name':
u'molecule_de60c00b5b', 'public_v6': '', 'request_ids': [], 'private_v4':
u'10.197.146.203', 'cloud': 'envvars', 'host_id': u'********',
'task_state': None, 'properties': Munch({'OS-EXT-STS:task_state': None,
'OS-SRV-USG:terminated_at': None, 'OS-DCF:diskConfig': u'MANUAL',
'OS-EXT-AZ:availability_zone': u'zone2', 'x_openstack_request_ids': [],
'os-extended-volumes:volumes_attached': [], 'OS-EXT-STS:vm_state':
u'active', 'OS-SRV-USG:launched_at': u'2017-04-14T13:55:46.000000',
'OS-EXT-STS:power_state': 1, 'request_ids': []}), 'project_id':
u'********', 'name': u'test-molecule', 'adminPass': None, 'tenant_id':
u'********', 'region': 'regionOne', 'created': u'2017-04-14T13:55:33Z',
'x_openstack_request_ids': [], 'has_config_drive': False, 'volumes': [],
'config_drive': u''})

**Comment by ericcitaire** [comment]
From the [Shade source code](https://github.com/openstack-infra/shade/blob/8924f6858139cbf3d365a1bb9859ae324bdf3ac4/shade/meta.py#L258) :

> Interface IP is the IP that should be used for communicating with the
    server. It is:
> - the IP on the configured default_interface network
> - if cloud.private, the private ip if it exists
> - if the server has a public ip, the public ip

Molecule should provide a parameter `private` in OpenStack driver. It should be `False` by default.
It should be passed to `shade.openstack_cloud()` .

Here is a basic implementation in [molecule/driver/openstackdriver.py](https://github.com/metacloud/molecule/blob/master/molecule/driver/openstackdriver.py#L44) :

    private  = self.molecule.config.config['openstack'].get('private', False)
    shade.openstack_cloud(private=private)

**Comment by retr0h** [comment]
@gogskrish is this issue resolved?  I merged #819 to master recently.

**Comment by retr0h** [comment]
> @gogskrish is this issue resolved? I merged #819 to master recently.

any news?

**Comment by gogskrish** [comment]
Hi John,

I need to update our docker image and check this. I will update you.
Thanks
Gogs

**Comment by retr0h** [comment]
@gogskrish I'll be closing this soon, due to no further updates.

**Comment by retr0h** [comment]
Closing have had no follow-up. Please re-open if this issue persists.
