### ISSUE TITLE
v1.23.3 do not support ansible 2.3

### ISSUE THREAD

**Issue by gzm55** [metacloud/molecule#811]
# Issue Type

- Bug report

# Molecule and Ansible details

```
ansible 2.3
molecule 1.23.3
```

# Desired Behaviour

1.23.3 support ansible 2.3

# Actual Behaviour (Bug report only)

testinfra 1.4.5 is installed, and testinfra issue 195 is met. After seeing branch stable1.23, some commits on master are not picked into stablle1.23, nor into tag 1.23.3,  such as:

- 034fb084190624196a35bfd9f9636fb30939b1c1: Clean up {group,host}_vars (#788) 
- 1db897311afddd69278801e154fb1a138858a29e: Globally disable cowsay (#808)
- 3a64f76f97d175367954288813c9a98d817a71d0: Added Ansible 2.3 support (#807)

**Comment by retr0h** [comment]
@gzm55 Right, 1.23 does not support 2.3 ansible.  You will need to wait for 1.24.

**Comment by gzm55** [comment]
@retr0h ok, i've to upgrade testinfra manually before 1.24, testinfra 1.5.5 works with molecule 1.23.

**Comment by retr0h** [comment]
1.24 released
