### ISSUE TITLE
molecule lint disable feature is not working as expected

### ISSUE THREAD

**Issue by gogskrish** [metacloud/molecule#812]
# Issue Type

I have a ansible project works perfectly with lot of tasks. I wanted to implement molecule.
However, once the idempotent test is passed, it started executing ansible-lint which shows lot off error.
Am using dependent roles for my role. I cannot go and do all the changes on dependent roles that lint is reporting. eventually i wanted to skip ansible lint.  I saw this override in molecule.yml

The role linting can be disabled by setting enabled to False.
lint:
  name: ansible-lint
  enabled: False

My molecule.yml

---
lint:
  name: ansible-lint
  enabled: False
molecule:
  test:
    sequence:
      - syntax
      - idempotence
      - verify
ansible:
  playbook: tests/playbook_jenkins_master.yml
driver:
  name: openstack
verifier:
  name: testinfra

Error:

--> Executing ansible-lint...
[ANSIBLE0016] Tasks that run when changed should likely be handlers
/home/centos/workspace/jenkins_master/dependencies/roles/docker/tasks/lvm-dm.yml:15

# Molecule and Ansible details

```
ansible --version
molecule --version
```

- Molecule installation method: One of source, pip
- Ansible installation method: One of source, pip, OS package

# Desired Behaviour

Please give some details of the feature being requested or what
should happen if providing a bug report.

# Actual Behaviour (Bug report only)

Please give some details of what is actually happening.
Include a [minimum complete verifiable example](http://stackoverflow.com/help/mcve) with
output of running `molecule --debug`.

**Comment by retr0h** [comment]
Where did you see this lint syntax as an option in `molecule.yml`?  Molecule v1 does not have a top level lint key in the config.

```
lint:
  name: ansible-lint
  enabled: False
```

Molecule v2 allows cli options to be passed to lint, much like you are doing.

**Comment by retr0h** [comment]
Closing as v2 supports this natively.
