### ISSUE TITLE
Update goss - Binary and verification playbook

### ISSUE THREAD

**Issue by marcinpraczko** [metacloud/molecule#820]
# Issue Type

- Feature request

# Molecule and Ansible details

```
$ ansible-playbook --version
ansible-playbook 2.3.0.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
  python version = 2.7.12 (default, Jul 01 2016, 15:34:22) [GCC]

$ molecule --version
molecule, version 1.24.0
```

- Molecule installation method: pip
- Ansible installation method: pip

# Desired Behaviour

Update goss binary file (SHA and URL) and add more descriptive example of ansible-goss playbook.
Also add details about (guess) ansible-goss module - which helps with options (like save result to file).

**Comment by retr0h** [comment]
Implemented by #821.
