### ISSUE TITLE
Brew Version is outdated

### ISSUE THREAD

**Issue by Moep90** [metacloud/molecule#823]
# Issue Type

- outdated report

# Molecule and Ansible details

```
ansible --version
ansible 2.3.0.0
  config file = /Users/username/.ansible.cfg
  configured module search path = Default w/o overrides
  python version = 2.7.13 (default, Jan  9 2017, 09:22:39) [GCC 4.2.1 Compatible Apple LLVM 8.0.0 (clang-800.0.42.1)]
molecule --version
molecule, version 1.20.3
```

- Molecule installation method: brew install molecule
- Ansible installation method: brew install ansible

# Desired Behaviour

The brew Version is outdated

**Comment by retr0h** [comment]
I'm not the maintainer of that pakage, nor was I aware molecule was even in brew.  Not an issue I can help with.
