### ISSUE TITLE
No option to disable cache for docker driver

### ISSUE THREAD

**Issue by james-portman** [metacloud/molecule#826]
# Issue Type

- Feature request

- Molecule installation method: pip
- Ansible installation method: pip

# Desired Behaviour

Allow some way to pass no-cache option when building Docker images
e.g. --no-cache=true

# Actual Behaviour (Bug report only)
Cannot find an option to allow this currently

**Comment by retr0h** [comment]
@james-portman are you referring to Molecule building images supplied by a custom Dockerfile?

**Comment by james-portman** [comment]
@retr0h - Yes I was. I am not sure on the behaviour without a Dockerfile, but could be the same

**Comment by james-portman** [comment]
Going to try and fix this, further notes from me:

http://docker-py.readthedocs.io/en/stable/api.html
Building images
Parameter:
nocache=False (default)
nocache (bool) – Don’t use the cache when set to True

Needs adding here after looking at container config:
https://github.com/metacloud/molecule/blob/760c7c3ff2167b1432b5fd696920130ee1404e82/molecule/driver/dockerdriver.py#L311

**Comment by james-portman** [comment]
Pull request created:
https://github.com/metacloud/molecule/pull/842

@retr0h

**Comment by james-portman** [comment]
I have updated the PR,
if it's OK then let me know and I can squash it if you like.

**Comment by retr0h** [comment]
Implemented in #842.
