### ISSUE TITLE
ansible variables in molecule

### ISSUE THREAD

**Issue by xhudik** [metacloud/molecule#830]
- Question

```
ansible --version
ansible 2.3.0.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/usr/share/ansible']
  python version = 3.4.2 (default, Oct  8 2014, 10:45:20) [GCC 4.9.1]

molecule --version
molecule, version 1.24.0
```

In my ansible, I'm using variable (ansible fact) - `ansible_eth0` :
```
...
lineinfile: dest=config.py line="ip = '{{ansible_eth0.ipv4.address}}'"
...
```

When I run it outside Molecule - it works. However, when I try the script with `molecule converge` I got:
`The error was: ansible_eth0 is undefined'. 
*Any idea how to pass ansible variables/facts into Molecule?*

**Comment by retr0h** [comment]
@xhudik that should work so long as your playbook.yml has `gather_facts: yes`.

**Comment by retr0h** [comment]
Can you link me to your source?

**Comment by xhudik** [comment]
here is the code: https://github.com/xhudik/kel/tree/master/roles
(you only need roles directory). I tried to do it as slim as possible...

any hint/idea appreciated ;)

**Comment by retr0h** [comment]
Here is your problem.  Your distro brings your interfaces up with the crazy redhat interface naming.  You have no eth0.

```
[vagrant@edge ~]$ ip addr s
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN qlen 1
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host
       valid_lft forever preferred_lft forever
2: enp0s3: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast state UP qlen 1000
    link/ether 08:00:27:0a:d1:52 brd ff:ff:ff:ff:ff:ff
    inet 10.0.2.15/24 brd 10.0.2.255 scope global dynamic enp0s3
       valid_lft 86305sec preferred_lft 86305sec
    inet6 fe80::1f68:6d39:c47d:a9c2/64 scope link
       valid_lft forever preferred_lft forever
```

**Comment by xhudik** [comment]
true - i didnt realize this one! thanks a lot @retr0h

**Comment by retr0h** [comment]
> true - i didnt realize this one! thanks a lot @retr0h

🎸
