### ISSUE TITLE
Extend testinfra modules

### ISSUE THREAD

**Issue by ju5t** [metacloud/molecule#831]
What would be the best way to add testinfra modules in molecule? I tried it by simply defining an additional class like:

```
from __future__ import unicode_literals
from testinfra.modules.base import Module


class Network(Module):
    """Test network connectivity"""

    def __init__(self, ip_address):
        self.ip_address = ip_address
        super(Network, self).__init__()

    @property
    def ping(self):
        return self.run_test("ping -c1 %s", self.ip_address).rc == 0
```

When I call this class with

```
def test_ping(Network):
    n = Network('google.com')
    assert n.ping == 0
```

It says it can't find the fixture Network. Obviously I'm missing something here. It probably needs to be registered somewhere.

**Comment by ju5t** [comment]
I found a simple workaround with:

```
def test_ping(Command):
    assert Command('ping -c1 google.com').rc == 0
```

Having its own class would be cleaner though.

**Comment by retr0h** [comment]
@ju5t I don't know of a way to register plugins by simply creating classes in the test directory.  Any time I have created a plugin, I do it the "official" way.  I create a pypi project and distribute the tests that way.  I then ensure my setup.cfg has the proper entrypoint, which pytest automatically picks up.

```
[entry_points]
pytest11 =
    pytest11.testinfra_echo = testinfra_shared.plugin
```

Maybe @philpep has some ideas.

**Comment by retr0h** [comment]
@ju5t Similar [discussion](https://github.com/philpep/testinfra/issues/181).

**Comment by ju5t** [comment]
@retr0h thanks, I found that one before but that didn't seem to work for me. My Python knowledge is a little limited still so I'm not entirely sure how to work build my own pypi project to set up custom tests unfortunately.

**Comment by diefans** [comment]
@ju5t http://setuptools.readthedocs.io/en/latest/setuptools.html#dynamic-discovery-of-services-and-plugins

**Comment by retr0h** [comment]
> @retr0h thanks, I found that one before but that didn't seem to work for me. My Python knowledge is a little limited still so I'm not entirely sure how to work build my own pypi project to set up custom tests unfortunately.

Was hoping to hear from @philpep.  However, this is not a Molecule issue.  Please follow up in issues linked.
