### ISSUE TITLE
Molecule test fails when testing a newly created role if role name has underscores

### ISSUE THREAD

**Issue by butla** [metacloud/molecule#833]
# Issue Type

- Bug report

# Molecule and Ansible details

```
ansible 2.2.3.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides

molecule, version 1.24.0
```

- Molecule installation method: pip
- Ansible installation method: pip

# Desired Behaviour

Can succesfully run `molecule test` on a role freshly created with `molecule init --role name_with_underscores`

# Actual Behaviour (Bug report only)
If a role has underscores in the name, the test will fail like below:

```
$ molecule --debug test
--> Destroying instances...
--> Checking playbook's syntax...
DEBUG: COMMAND
/home/butla/.local/bin/ansible-playbook playbook.yml --inventory-file=localhost, --syntax-check --limit=all --timeout=30 --become --diff

playbook: playbook.yml
--> Creating instances...
Bringing machine 'name_with_underscores' up with 'virtualbox' provider...
There are errors in the configuration of this machine. Please fix
the following errors and try again:

vm:
* The hostname set for the VM should only contain letters, numbers,
hyphens or dots. It cannot start with a hyphen or dot.


ERROR: Command '['/usr/bin/vagrant', 'up', '--no-provision']' returned non-zero exit status 1
```

It can be remedied by changing the underscores to hyphens in molecule.yml/vagrant/instances/name.

**Comment by retr0h** [comment]
This seems like a satisfactory error.  Vagrant reported you gave an invalid hostname, thus you can fix it.  I don't see much reason for Molecule to enforce a particular drivers hostname limitations.

**Comment by butla** [comment]
Well, it's a bit off from usability standpoint that running the minimal default thing crashes.
But that's just my opinion.
