### ISSUE TITLE
Molecule test fails if python is not installed on the base box

### ISSUE THREAD

**Issue by jamesla** [metacloud/molecule#834]
Running molecule test fails if python is not installed on the base box with the following error:

```
TASK [Gathering Facts] *********************************************************
fatal: [ansible]: FAILED! => {"changed": false, "failed": true, "module_stderr": "Shared connection to 127.0.0.1 closed.\r\n", "module_stdout": "/bin/sh: 1: /usr/bin/python2.7: not found\r\n", "msg": "MODULE FAILURE", "rc": 0}
```

Is there a way to configure molecule to install python2.7 or run a shell command on the base box before running the playbook?

**Comment by retr0h** [comment]
Yeah, you can do something similar to [this](https://github.com/metacloud/molecule/blob/v2/test/scenarios/driver/ec2/molecule/default/playbook.yml).

**Comment by jamesla** [comment]
Thanks!
