### ISSUE TITLE
Use box full name for molecule init

### ISSUE THREAD

**Issue by jairojunior** [metacloud/molecule#840]
Currently, `molecule init` uses `trusty64` as box name instead of the full name `ubuntu/trusty64` causing a redownload of the box for vagrant users that already have `ubuntu/trusty64`  .

Is there a specific reason for this? Or is it OK to provide a PR to replace it here: https://github.com/metacloud/molecule/blob/master/molecule/config.py#L193

**Comment by retr0h** [comment]
Sure, sounds reasonable.
