### ISSUE TITLE
[v2] include existing group_vars files

### ISSUE THREAD

**Issue by aroundthecode** [metacloud/molecule#841]
# Issue Type
- Feature request

# Molecule and Ansible details

```
molecule, version 1.14.1.dev207
```
- Molecule installation method: pip

# Desired Behaviour

Hi there,
I'd like to know which is the proper way to include an existing group_vars directory instead of declaring all variables within *molecule.yml*
Checking #171 it seems this was/is possible, but couldn't find anything similar in V2 with the new list group/host vars list management.

Some other issues suggest symlinking folder into .molecule generated structure, but this would mean I would pre-allocate the structure before molecule running. Since such folder is intended to be manage by molecule this doesn't seems a good practice.

Isolated inclusion in molecule is sometime useful, but they should be able to shift/merge over existing group_vars files.

Any hint on the best way to proceed? 
thanks in advance!

**Comment by retr0h** [comment]
@aroundthecode It is not possible.  We do not support this functionality.  Yes, #171 had it, but it is rather hackish, therefore we do not support it in v2.

It may be re-evaluated once we have a version of ansible supporting the new plugin inventory.
https://github.com/ansible/ansible/pull/23001.

You're free to do the symlinking yourself, outside of molecule.

**Comment by aroundthecode** [comment]
@retr0h, I created a shell script which pre-allocate the .molecule/group_vars folder and include my files before triggering molecule, but it seems that molecule is re-creating such folder at each run (which is more or less what I was expecting).

**Comment by aroundthecode** [comment]
just to let you know, my current workaround was to create a role which just include Group_vars needed files.
Such role is set to be a dependency of all other roles needing such configuration.
Working this way any role will first invoke the new dependent one before executing, including all needed vars.

**Comment by retr0h** [comment]
👍

**Comment by aroundthecode** [comment]
I have to change my opinion on this workaround since this drastically changes the variable priority during ansible execution.

Variables in group_vars can be overwritten by inventory parameters, while variables as default in a dependency role cannot.
Probably the best solution is to add a task in the create playbook (which runs AFTER the .molecule folder has been reset) to copy my group_vars files into the proper path, but now I'm hitting the issue described into #855

**Comment by retr0h** [comment]
Reimplemented #171 into v2.

**Comment by aroundthecode** [comment]
thanks @retr0h , I'll give it a try on Monday and let you know!

**Comment by aroundthecode** [comment]
@retr0h I'm checking the new behaviour.
It's ok that enumeration in molecule.yaml and linking are mutually exclusive, can it be done separately for group var and host_vars sections?

e.g. Keeping host_vars enumerated in molecule.yaml while group_vars are linked ? 
The actual behaviour now is that if the link section is present it wins over all,

**Comment by retr0h** [comment]
> The actual behaviour now is that if the link section is present it wins over all, while if the check could be split for the two sections it would be great!

Right, linking wins overall.  I really don't think uses are going to be mixing and matching.  All of the feedback with molecule has been.  Hey I don't like having to add inventory to molecule.yml, can I supply my own from existing inventory.  Previously, I said no.  Now, I can answer that question with yes.

Mixing and matching could be done, but I would prefer to keep it simple for the time being and see what ppl think.
