### ISSUE TITLE
Install extra packages when building ansible compatible docker image

### ISSUE THREAD

**Issue by giovtorres** [metacloud/molecule#843]
# Issue Type

- Question
- Feature request

# Molecule and Ansible details

```
ansible 2.3.0.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
  python version = 2.7.13 (default, Jan 12 2017, 17:59:37) [GCC 6.3.1 20161221 (Red Hat 6.3.1-1)]

molecule, version 1.24.0
```

- Molecule installation method: pip
- Ansible installation method: pip

# Desired Behaviour

Is it possible to install extra packages during the [_build_ansible_compatible_image](
https://github.com/metacloud/molecule/blob/master/molecule/driver/dockerdriver.py#L252)?

I have a use case for testing an ansible module that provides a networking agent that depends on the `iproute` package.  I tried installing the package in `pre_tasks` in the **playbook.yml**, but gather_facts is run before the pre_tasks and therefore the `ansible_interfaces` variable, which depends on parsing the output of the `ip` command, is not present and the role fails.

To work around this, I created my own container with this package and use this as the container image in **molecule.yml**.  I think it would be a nice feature to allow extra_packages in the above function to get one or two needed packages baked into the container before stepping through the ansible run, for example:

```docker:
  containers:
    - name: centos7-test-role
      image: centos
      image_version: 7
      extra_packages:
      - iproute
      - foo
    - name: centos6-test-role
      image: centos
      image_version: 6
      extra_packages:
      - iproute
      - foo
```

Thoughts?

Thanks,
Giovanni

**Comment by retr0h** [comment]
> Is it possible to install extra packages during the _build_ansible_compatible_image?

Not possible

You have a couple options.

1.  Install the package with ansible in two host blocks.  The first host block has gather facts disabled.  The second has it enabled.

https://github.com/metacloud/molecule/blob/v2/test/scenarios/driver/ec2/molecule/default/playbook.yml#L1-L13

2. Supply a Dockerfile file in the root of the project, and configure molecule.yml to enable it.  This will build the container with the packages you desire.

https://github.com/metacloud/molecule/tree/master/test/scenarios/dockerfile

**Comment by giovtorres** [comment]
> 1. Install the package with ansible in two host blocks. The first host block has gather facts disabled.  The second has it enabled.
Clever!  I think I'll take option 1.  I can see option 2 having its use cases, but to install a single package, option 1 is working for me.

Thanks!

**Comment by retr0h** [comment]
> Thanks!

🎸
