### ISSUE TITLE
if ANSIBLE_FILTER_PLUGINS set, provisioner create.yml can't find molecule_instance_with_scenario_name

### ISSUE THREAD

**Issue by ingvagabund** [metacloud/molecule#845]
# Issue Type

- Bug report

# Molecule and Ansible details

```
$ ansible --version
ansible 2.2.3.0
$ molecule --version
molecule, version 2.0.0.0rc6
```

- Molecule installation method: pip
- Ansible installation method: OS package

# Desired Behaviour

If `ANSIBLE_FILTER_PLUGINS` is set in molecule.yml file (`provisioner.env`), molecule provisioning is still working and docker container are destroyed/created.

# Actual Behaviour (Bug report only)

If `ANSIBLE_FILTER_PLUGINS` is set in molecule.yml file (`provisioner.env`), molecule provisioning of docker container fails with:
```
template error while templating string: no filter named 'molecule_instance_with_scenario_name'. String: {{ item.name | molecule_instance_with_scenario_name(molecule_yml.scenario.name) }}
```

# Reproducer

Take one of the examples in `https://github.com/metacloud/molecule/tree/v2/test/scenarios/driver/docker` directory and set the env. E.g.:
```yaml
...
provisioner:
  name: ansible
  env:
    ANSIBLE_FILTER_PLUGINS: ../../../../filter_plugins
...
```

When the `ansible-playbook` command for provisioning is created [1], all available env variables inside the provisioner are handed as well. So even if the generated `ansible.cfg` file is correct and `ANSIBLE_FILTER_PLUGINS` is set to `/usr/lib/python2.7/site-packages/molecule/provisioner/../../molecule/provisioner/ansible/plugins/filters:$ANSIBLE_FILTER_PLUGINS`, the command is run as:

```sh
ANSIBLE_FILTER_PLUGINS=../../../../filter_plugins /usr/bin/ansible-playbook ...
```

Given the `ANSIBLE_FILTER_PLUGINS` has higher precedence than the same env set in the `ansible.cfg` file, the `molecule/provisioner/ansible/plugins/filters` is always skipped.

I would suggest to check if the env variable is set inside `molecule.yml` file and if so, just filter it out from the constructed command.

[1] https://github.com/metacloud/molecule/blob/v2/molecule/provisioner/ansible_playbook.py#L71

**Comment by ingvagabund** [comment]
Re-examing the generated `ansible.cfg` file again:
```yaml
# Molecule managed
[ssh_connection]
scp_if_ssh = True
[defaults]
filter_plugins = /usr/lib/python2.7/site-packages/molecule/provisioner/../../molecule/provisioner/ansible/plugins/filters:$ANSIBLE_FILTER_PLUGINS
roles_path = ../../../../:$ANSIBLE_ROLES_PATH
host_key_checking = False
retry_files_enabled = False
library = /usr/lib/python2.7/site-packages/molecule/provisioner/../../molecule/provisioner/ansible/plugins/libraries:$ANSIBLE_LIBRARY
ansible_managed = Ansible managed: Do NOT edit this file manually!
nocows = 1
```

If `ANSIBLE_FILTER_PLUGINS` is not set, the `filter_plugins` path from `ansible.cfg` takes affect. However, user can not use its own custom filters.
If `ANSIBLE_FILTER_PLUGINS` is set, the `filter_plugins` path from `ansible.cfg` is ignored as the env has higher preference. So user can use its own custom filters but the molecule filter directory path `molecule/provisioner/ansible/plugins/filters` path is ignofed so `molecule_instance_with_scenario_name` is not found.

Given the `ansible.cfg` is generated each time the `molecule test` is run, the env inside the cfg can be replaced by their value. Unless there is something else that changes envs between `playbook-ansible` runs within single `molecule test` instance.

**Comment by retr0h** [comment]
@ingvagabund I may have gone about this the wrong way.  I actually didn't realize the ANSIBLE_ environment variables have a higher priority.

The main reason I placed filter_plugins, roles_path, and library in ansible.cfg, was for ansible-lint.  For ansible-lint to properly validate a role, it requires these settings be set.

With that said.  This seems like a tricky issue.  We always want to set our custom filter and libraries.  However, we also want to allow the user to specify their own.  Maybe a better approach is to move these settings from ansible.cfg and to use these env vars anytime we shell out.

**Comment by retr0h** [comment]
Implemented at 38e8acb.

**Comment by ingvagabund** [comment]
My knowledge of the molecule code is still limited. Thanks for finishing this.

**Comment by retr0h** [comment]
@ingvagabund no problem.  Thanks for the bug report and giving me a good idea to fix it.
