### ISSUE TITLE
Search in test/integration/default/ for tests

### ISSUE THREAD

**Issue by rndmh3ro** [metacloud/molecule#85]
Test-kitchen searches for tests in `test/integration/default/`, see here:
http://kitchen.ci/docs/getting-started/writing-test

It'd be nice if molecule could search there, too, so existing tests do not have to be changed (we test puppet/ansible/chef with the same tests, that reside in the aformentioned directory).

Maybe its also possible to let the user specify where to search for tests?

**Comment by abrown-sg** [comment]
We have all the pieces in place to make this work by changing the directory in the config file (or even molecule.yml), but the rakefile template still hardcodes spec/.

**Comment by abrown-sg** [comment]
Once #86 is merged, you should be able to set the serverspec_dir directive and it will point anywhere you want for tests.  You can do this in a role's molecule.yml, to make it role specific, or you can set it in your own molecule config file (~/.config/molecule/config.yml, /etc/molecule/config.yml, etc.) and it will be a global option for molecule.

```yaml
molecule:
  serverspec_dir: test/integration/default
```
