### ISSUE TITLE
unittest failure in master

### ISSUE THREAD

**Issue by ashcrow** [metacloud/molecule#850]
# Issue Type
Bug report

# Molecule and Ansible details
```
ansible 2.3.0
molecule: bf634f0755f1e3f017b8dc6ba07d66d60b599577
```
- Molecule installation method: source
- Ansible installation method: pip

# Desired Behaviour
``tox -e -e py27-ansible23-unit`` should succeed without failures

# Actual Behaviour (Bug report only)
``tox -e -e py27-ansible23-unit`` errors:

```
test/unit/core/test_core_docker.py::test_get_driver_name ERROR
<snip>
E           DockerException: Error while fetching server API version: ('Connection aborted.', error(2, 'No such file or directory'))

/home/steve/Tech/GITHUB/molecule/.tox/py27-ansible23-unit/lib/python2.7/site-packages/docker/api/client.py:168: DockerException
<snip>
```

To reproduce this run ``tox -e -e py27-ansible23-unit``

**Comment by retr0h** [comment]
@ashcrow thanks for the issue and sudden interest RH has with Molecule.

Was this meant for master or v2?  While I cannot reproduce the error you're seeing, I actually do have a bad unit test.

**Comment by ashcrow** [comment]
This was for v1. It was before I realized the development for the next version was in a branch 😆

**Comment by ashcrow** [comment]
Go for it.
