### ISSUE TITLE
Logging behavior is different between Python 2 and Python 3

### ISSUE THREAD

**Issue by thomasjpfan** [metacloud/molecule#852]
# Issue Type

- Bug report

# Molecule and Ansible details

```
ansible --version 
2.3.1.0
molecule --version
2.0.0.0rc6
```

- Molecule installation method: pip
- Ansible installation method: pip

# Desired Behaviour

When running any molecule command in Python 3, an exception is raised, usually a TypeError:
```
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
```

# Actual Behaviour (Bug report only)

For example, when `execute` is ran from https://github.com/metacloud/molecule/blob/v2/molecule/provisioner/ansible_playbook.py#L75, with the baked `_out` being a `CustomLogger.out` function the behavior is different between Python 2 and 3. Specifically, `CustomLogger.out` is handled with `construct_streamreader_callback` in https://github.com/amoffat/sh/blob/master/sh.py#L1560, where the local variable `num_args`=3 in Python 3 and `num_args`=2 in Python 2. An inconsistent `num_args` executes a different branch in https://github.com/amoffat/sh/blob/master/sh.py#L1608, which will raise the `TypeError` exception in Python 3. 

`get_num_args ` is implemented in https://github.com/amoffat/sh/blob/master/sh.py#L117. The behavior of `get_num_args` differs between Python 2 and Python 3, because of the changes in the `inspect` module. 

In Python 2, `get_num_args` calls `inspect.getargspec(fn).args`:
```python
>>> from molecule.logger import get_logger
>>> LOG = get_logger("test")
>>> argspec = inspect.getargspec(LOG.out)
>>> argspec
ArgSpec(args=['self', 'msg'], varargs='args', keywords='kwargs', defaults=None)
>>> len(argspec.args)
2
```
This makes `get_num_args` return 2 in Python 2.

In Python 3, `get_num_args` calls `inspect.signature(fn).parameters`:
```python
>>> from molecule.logger import get_logger
>>> LOG = get_logger("test")
>>> log_signature = inspect.signature(LOG.out)
<Signature (msg, *args, **kwargs)>
>>> log_params = log_signature.parameters
>>> log_params
mappingproxy({'args': <Parameter "*args">,
              'kwargs': <Parameter "**kwargs">,
              'msg': <Parameter "msg">})
>>> len(log_params)
3
```
This makes `get_num_args` return 3 in Python 3.

For the `construct_streamreader_callback` to function properly, the desired behavior is to have `get_num_args` return 2. I submitted a pull request in `sh` to address this issue, https://github.com/amoffat/sh/pull/388.

**Comment by retr0h** [comment]
@thomasjpfan awesome thanks for doing the leg work.  I have actually never run Molecule with py3 simply b/c we ran into issues with sh and Ansible.  However, ansible 2.2 should have 3.6 support, so am looking forward to your sh issue getting resolved.

Thanks again.

**Comment by retr0h** [comment]
@thomasjpfan thanks for the report.  Molecule v2 doesn't properly work with Python 3 due to the fact that Ansible 2.2 and 2.3 do not work with python 3.  I have brought in the current sh release into [Molecule](https://github.com/metacloud/molecule/commit/b779a08f3873fc7568e211b8ba7b19c5ba0a6c2a), However, I have issues on the gather facts phase.

```
        TASK [setup] *******************************************************************
        An exception occurred during task execution. To see the full traceback, use -vvv. The error was: TypeError: a bytes-like object is required, not 'str'
        fatal: [instance-1-default]: FAILED! => {"failed": true, "msg": "Unexpected failure during module execution.", "stdout": ""}
```

Best I can tell is an issue with Ansible.

**Comment by retr0h** [comment]
Will be closing this issue since the initial report has been corrected.  @thomasjpfan Please feel free to continue opening issues as you see them or submitting PRs.  Thanks 🎸
