### ISSUE TITLE
molecule verify re-create .molecule folder

### ISSUE THREAD

**Issue by aroundthecode** [metacloud/molecule#855]
# Issue Type
- Bug report

# Molecule and Ansible details

```
ansible 2.2.2.0 (pip install)
molecule, version 1.14.1.dev207 (pip install)
```
# Desired Behaviour

Molecule **verify** should re-evaluate test on the previous scenario **create** phase

# Actual Behaviour (Bug report only)

molecule destroy and re-create the .molecule folder.

Since the folder contains all the inventory/group_vars/host_vars populated by the previous create phase, I'm not expecting this to be performed.

I use "verify" phase as standalone to run corrections on test code without altering the previous steps, changing the inventory/group_vars/host_vars settings definitely let it behave in a different way.

This releates also to #841: I had to create some steps in my create/converge playbook to adjust group_vars with some values from my playbooks setting. This causes **molecule create** to run successfully with all test, while a **molecule verify** will fail due to the fact that the .molecule folder is re-created while the create/converge playbook are not executed so the additional group_vars are not present

**Comment by retr0h** [comment]
Does this occur on the current 1.25 release?  The version you listed above seems old?

**Comment by aroundthecode** [comment]
I'm currently on the V2 branch, is this expected to be fixed on the latest version as well?

**Comment by retr0h** [comment]
Got ya, will check.

**Comment by retr0h** [comment]
@aroundthecode so are you creating group_vars, host_vars directories in the root of your project or are these host and group vars defined in your molecule.yml?

Then when you run `verify` molecule nukes the directories inside the `.molecule/` directory w/o recreating the vars properly?

I'm trying to better understand, since I believe inventory should be recreated.

**Comment by aroundthecode** [comment]
I have both, my code expect some configuration from the ansible inventory ( which now comes from molecule.yml group/host_vars section) but has also lots of other parameters coming from a group_vars files (these are usually changed via CLI option if needed).

I manage to import such files adding a task in create.yml which copies them into the .molecule folder, so that when the converge playbook is run they are ready to be fetched. (this cannot be done before starting molecule since .molecule folder is purged at start)

Now, this works fine until i try to invoke just the "molecule verify" phase as a standole command (scenario container are still running from a previous converge which skipped destroy phase).
When running verify the .molecule folder is purged (which is unexpected and a wrong behaviour IMHO ) and, since the create/converge phase is not runned, my additional group_vars files are missing, causing all test to fail due to missing parameters.

My expected behaviour is to have .molecule folder generated during create phase and then left unchanged untill a destroy or a new create is invoked, am I missing something? Is there any reason for this re-create?

thanks in advance for your support!

**Comment by aroundthecode** [comment]
Not sure which is the v1 current behaviour, but I think the point is that the removal method is invoked in the command/base.py Base class which is then inherited by all command classes. So latest v2 version re-create the folder at **each** step. 

```
def _setup(self):
        """
        Prepare the system for Molecule and returns None.
        :return: None
        """
        if not os.path.isdir(self._config.scenario.ephemeral_directory):
            os.mkdir(self._config.scenario.ephemeral_directory)

        self._config.provisioner.write_inventory()
        self._config.provisioner.write_config()
        self._config.provisioner.remove_vars()
        self._config.provisioner.add_or_update_vars('host_vars')
        self._config.provisioner.add_or_update_vars('group_vars')
```
I think the remove_vars() invoke should be dropped here since you already have the prune() method which is correctly invoked only in the destroy phase.

In this way the folder should be re-evaluated for the molecule.yml part at each stage, but any additional file would not be dropped unless destroy is invoked.

What do you think about this?

**Comment by retr0h** [comment]
> What do you think about this?

The issue is the user may add additional group vars to molecule.yml between converges.  By removing host vars only on converge there is a chance there is left over files, the user does not expect.

**Comment by retr0h** [comment]
@ragingpastry implemented in b140fa37c5224de6a950e92b75ded7f165c45a65.

Update your `molecule.yml` with the safe_files you wish to save.  Molecule does not merge lists, so you need to provide everything when overriding `ssh_connection_options`.

```
driver:
  name: ec2
  safe_files:
    - foo
    - .molecule/bar
```

**Comment by aroundthecode** [comment]
@retr0h so which would be the solution to this? 

Is the last comment above relevant or it refers to a different issue?
Should I copy my group_var files via ansible task and declare them as safe file ?

I think that adding the capability to use internal group_vars should be mandatory (see also #57 ) but at the moment the only way to do so in a safe way is to manually patch molecule code as above.

**Comment by retr0h** [comment]
@aroundthecode either don't copy them into the `.molecule` directory or add the directory to safe files.
