### ISSUE TITLE
Testinfra Socket module does not work with molecule docker image

### ISSUE THREAD

**Issue by dusty73** [metacloud/molecule#859]
# Issue Type

- Bug report

# Molecule and Ansible details

```
ansible 2.3.1.0
molecule 1.25.0
```

- Molecule installation method: pip
- Ansible installation method: OS package (epel)

# Desired Behaviour

I'm trying to use Testinfra's Socket module

# Actual Behaviour (Bug report only)

The Socket module wants to use netstat system command, that is missing in default docker image supplied by molecule:

```
=================================== FAILURES ===================================
_________________ test_http_port[docker://ansible_role_nginx] __________________

Socket = <class 'testinfra.modules.base.LinuxSocket'>

    def test_http_port(Socket):
>       assert Socket("tcp://0.0.0.0:80").is_listening

tests/test_default.py:9:
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
/usr/lib/python2.7/site-packages/testinfra/modules/socket.py:110: in is_listening
    sockets = self.get_sockets(True)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

self = <socket tcp://0.0.0.0:80>, listening = True

    def get_sockets(self, listening):
        sockets = []
        cmd = "netstat -n"

        if listening:
            cmd += " -l"

        if self.protocol == "tcp":
            cmd += " -t"
        elif self.protocol == "udp":
            cmd += " -u"
        elif self.protocol == "unix":
            cmd += " --unix"

>       for line in self.check_output(cmd).splitlines():
E       AssertionError: Unexpected exit code 127 for CommandResult(command='netstat -n -l -t', exit_status=127, stdout=None, stderr='/bin/sh: netstat: command not found\n')
E       assert 127 == 0
E        +  where 127 = CommandResult(command='netstat -n -l -t', exit_status=127, stdout=None, stderr='/bin/sh: **netstat: command not found**\n').rc

/usr/lib/python2.7/site-packages/testinfra/modules/socket.py:217: AssertionError
____________________ test_http[docker://ansible_role_nginx] ____________________
```

**Comment by retr0h** [comment]
This doesn't feel like Molecule's responsibility.  If you wish to do this install netstat prior to tests.  This can be accomplished as a task inside your playbook.yml.

**Comment by smbambling** [comment]
Just a note for others that might come across this in a search, this is fixed with a newer version of testinfra that is moving away from netstat to ss

Where the newer version fixes this issue by not using netstat see the Change log 
https://github.com/philpep/testinfra/blob/master/CHANGELOG.rst#1110

```
Socket: add a new implementation using ss instead of netstat (#124)
```

This will require at least molecule v2.13 - > https://github.com/metacloud/molecule/releases/tag/2.13
which includes this bump https://github.com/metacloud/molecule/commit/958cd390e04807cc19871624f86cfe54449baf73
