### ISSUE TITLE
Molecule converge with Python 3

### ISSUE THREAD

**Issue by thomasjpfan** [metacloud/molecule#860]
# Issue Type

- Bug report

# Molecule and Ansible details

```
ansible --version
ansible 2.3.1.0
molecule --version
molecule, version 2.0.0.0rc5.dev26
```

- Molecule installation method: source
- Ansible installation method: pip

# Desired Behaviour

`molecule converge` should not error out.

# Actual Behaviour (Bug report only)

The following error is displayed after running `molecule converge`:
```
TASK [setup] *******************************************************************
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: TypeError: a bytes-like object is required, not 'str'
fatal: [instance-1-default]: FAILED! => {"failed": true, "msg": "Unexpected failure during module execution.", "stdout": ""}
```
There is already a pull request in Ansible (https://github.com/ansible/ansible/pull/25048) that solves this issue. The five line diff forces Python 3 handles bytes correctly.

**Comment by retr0h** [comment]
@thomasjpfan what can molecule do about this?  This isn't a Molecule issue.  We don't bring in ansible as a dependency.

**Comment by thomasjpfan** [comment]
Nothing molecule can do but wait for that pull request to be merged into Ansible. Just wanted to let you know that Python 3 support for v2 is out of your hands for now.

**Comment by retr0h** [comment]
@thomasjpfan 👍

**Comment by retr0h** [comment]
Backported to [stable-2.2](https://github.com/ansible/ansible/pull/25587).
