### ISSUE TITLE
Typo in molecule/molecule/command/dependency.py (defalt)

### ISSUE THREAD

**Issue by alainchiasson** [metacloud/molecule#867]
# Issue Type

- Bug report

# Molecule and Ansible details

```
ansible --version

#ansible 2.3.1.0
#  config file =
#  configured module search path = Default w/o overrides
#  python version = 2.7.10 (default, Feb  7 2017, 00:08:15) [GCC 4.2.1 Compatible Apple LLVM 8.0.0 (clang-800.0.34)]

molecule --version

# molecule, version 2.0.0.0rc7

```

- Molecule installation method: pip
- Ansible installation method: One of source, pip, OS package

# Desired Behaviour

run

```
molecule dependecy 
```

and dependencies ( from the requirements.yml file in molecule/default)  would be pulled from galaxie

# Actual Behaviour (Bug report only)

molecule dependency fails with : 

# ERROR: Scenario 'defalt' not found.  Exiting.

there is a typo at https://github.com/metacloud/molecule/blob/26706768e01dd8e4e98a65fbbfcb16416b8b0634/molecule/command/dependency.py#L61

```
@click.command()
58	@click.pass_context
59	@click.option(
60	    '--scenario-name',
61	    default='defalt',
62	    help='Name of the scenario to target. (default)')
```
It should be default.

**Comment by alainchiasson** [comment]
Opened PR https://github.com/metacloud/molecule/pull/868

**Comment by retr0h** [comment]
Merged, thanks 🎸
