### ISSUE TITLE
Travis CI: E: Package 'docker-engine' has no installation candidate

### ISSUE THREAD

**Issue by popstas** [metacloud/molecule#873]
# Issue Type

- Bug report

# Actual Behaviour

Due [Travis CI images update](https://blog.travis-ci.com/2017-06-21-trusty-updates-2017-Q2-launch) builds now fails with error:

Documentation still not updated: https://molecule.readthedocs.io/en/master/testing.html#travis-ci
```
E: Package 'docker-engine' has no installation candidate

The command "sudo apt-get install -o Dpkg::Options::="--force-confold" --force-yes -y docker-engine" failed and exited with 100 during .
```

Build fails on command:
```
sudo apt-get install -o Dpkg::Options::="--force-confold" --force-yes -y docker-engine
```

At this time travis images have not package `docker-engine`.

# Possible solutions:
- Remove docker-engine install command from `.travis-ci.yml (image have bundled Docker version 17.03.1-ce, build c6d412e)
- Change to install docker-ce from docker repository: https://docs.travis-ci.com/user/docker/#Installing-a-newer-Docker-version
```
before_install:
  - curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
  - sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
  - sudo apt-get update
  - sudo apt-get -y install docker-ce
```
- Use old images, add to `.travis.yml`:
```
group: deprecated-2017Q2
```

Documentation of using docker in travis now outdated:

- https://molecule.readthedocs.io/en/master/testing.html#travis-ci
- https://docs.travis-ci.com/user/docker/#Installing-a-newer-Docker-version

**Comment by retr0h** [comment]
Thanks @popstas 🎸

**Comment by mackdunkan** [comment]
Thanks @popstas
