### ISSUE TITLE
Update RUN statements in Dockerfile.j2

### ISSUE THREAD

**Issue by aliusmiles** [metacloud/molecule#889]
# Issue Type

- Feature request

# Molecule and Ansible details

```
ansible 2.3.1.0
molecule, version 2.0.0.0rc11
```

- Molecule installation method: pip
- Ansible installation method: brew

# Desired Behaviour

Multiple RUN statements result in multiple layers created, even though they do not increase image size. I propose to join them into one single RUN as follows:

```
RUN if [ $(command -v apt-get) ]; then apt-get update && apt-get upgrade -y && apt-get install -y python sudo bash; \
    elif [ $(command -v yum) ]; then yum makecache fast && yum update -y && yum install -y python sudo yum-plugin-ovl bash && sed -i 's/plugins=0/plugins=1/g' /etc/yum.conf && yum clean all; \
    elif [ $(command -v zypper) ]; then zypper refresh && zypper update -y && zypper install -y python sudo bash; \
    elif [ $(command -v apk) ]; then apk update && apk add python sudo bash; \
    elif [ $(command -v pacman) ]; then pacman --sync --noconfirm --refresh python2 bash; \
    elif [ $(command -v dnf) ]; then dnf makecache fast && dnf --assumeyes install python python-devel python2-dnf bash; \
    elif [ $(command -v emerge) ]; then emerge --ask n =dev-lang/python-2\* gentoolkit; fi
```
Other changes (most are rather cosmetic):
* added `yum clean all` to reduce image size (from 331MB to 244MB for centos 7)
* removed `touch /var/lib/rpm/*` -- wasn't able to found it's purpose
* replaced `-x "$(command -v yum)"` with simple `$(command -v yum)` -- exit code 0 equals true anyway
* removed `/bin/sh -c` -- seems to me it does not have any visible effect, but increase clutter instead.
* replaced `;` with `&&` for dnf

**Comment by aliusmiles** [comment]
I could create PR if needed.

**Comment by retr0h** [comment]
> I could create PR if needed.

Please do

**Comment by aliusmiles** [comment]
PR created: #891

**Comment by retr0h** [comment]
Implemented.
