### ISSUE TITLE
Add names to create.yml and destroy.yml

### ISSUE THREAD

**Issue by aliusmiles** [metacloud/molecule#890]
# Issue Type

- Feature request

# Molecule and Ansible details

```
ansible 2.3.1.0
molecule, version 2.0.0.0rc11
```

- Molecule installation method: pip
- Ansible installation method: brew

# Desired Behaviour

Adding names to _create.yml_ and _destroy.yml_ would help to better distinguish them from _playbook.yml_ output. Also would be helpful to decrease provisioning playbooks output by using `no_log: true` and maybe setting it as parameter in _molecule.yml_ in case debug is needed.

Example of modified _create.yml_:
```
---
- name: MOLECULE
  hosts: localhost
  connection: local
  gather_facts: False
  no_log: true
```

Output:
<img width="623" alt="less_output" src="https://user-images.githubusercontent.com/3264588/27873919-66d33922-61b6-11e7-8af2-9da30d61977f.png">

Old output:
<img width="1436" alt="more_output" src="https://user-images.githubusercontent.com/3264588/27873918-66a521e0-61b6-11e7-9343-a4cbc8ab681f.png">

BTW, brilliant idea to use ansible as provisioner, as far as I can see, overall molecule's code reduced quite a lot in v2 ;)

**Comment by retr0h** [comment]
> BTW, brilliant idea to use ansible as provisioner, as far as I can see, overall molecule's code reduced quite a lot in v2 ;)

👍
