### ISSUE TITLE
Docker container isn't rebuilt when Dockerfile.j2 is modified

### ISSUE THREAD

**Issue by MarkusTeufelberger** [metacloud/molecule#892]
# Issue Type

- Bug report

# Molecule and Ansible details

```
ansible --version
ansible 2.3.1.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
  python version = 2.7.12 (default, Nov 19 2016, 06:48:10) [GCC 5.4.0 20160609]

molecule --version
molecule, version 2.0.0.0rc11

```

- Molecule installation method: pip
- Ansible installation method: pip

# Desired Behaviour

Please give some details of the feature being requested or what
should happen if providing a bug report.

After the first test run, something didn't work out (in my case: ca-certificate package was missing in the test runner). I decided it would be best to change the test runner in this case and added something to the Dockerfile.j2 file.

I would expect molecule to detect that the template changed and re-build the Docker container, even though the (faulty) container with the name it expected already existed.

# Actual Behaviour (Bug report only)

Molecule rendered the changed template correctly, but didn't rebuild the docker container, since it already existed.

A possible solution might be to remove any containers molecule expects if a template is being rendered.

**Comment by aliusmiles** [comment]
Noticed that as well.
If templated Dockerfiles would preserve after `molecule destroy`, then in _create.yml_ playbook _destroy/build image_ tasks could be run only if corresponding Dockerfile has changed. I could try to update playbook, but I wasn't able to find where exactly in molecule's code those dockerfiles are destroyed :)
