### ISSUE TITLE
Stability of v2 and roadmap?

### ISSUE THREAD

**Issue by lnunno** [metacloud/molecule#893]
# Issue Type

- Question

Is v2 recommended for new tests? We're about to start writing a number of molecule tests and am wondering if we should start with v1 or v2, migrating to v2 doesn't appear to be too difficult but it might be better to just use the release candidate for v2 if it's stable.

I'm seeing a number of release candidates but I'm wondering when the anticipated release for v2 is?

Also, thanks for the great work!

**Comment by retr0h** [comment]
> Is v2 recommended for new tests? We're about to start writing a number of molecule tests and am wondering if we should start with v1 or v2, migrating to v2 doesn't appear to be too difficult but it might be better to just use the release candidate for v2 if it's stable.
> 
> I'm seeing a number of release candidates but I'm wondering when the anticipated release for v2 is?

I don't actually have a time frame, but v2 probably best to start with.
