### ISSUE TITLE
molecule destroy --all

### ISSUE THREAD

**Issue by MarkusTeufelberger** [metacloud/molecule#894]
# Issue Type

- Feature request

# Molecule and Ansible details

```
ansible --version
ansible 2.3.1.0
  config file = /home/markus/projects/mgit/ansible/ansible.cfg
  configured module search path = Default w/o overrides
  python version = 2.7.12 (default, Nov 19 2016, 06:48:10) [GCC 5.4.0 20160609]

molecule --version
molecule, version 2.0.0.0rc11
```

- Molecule installation method: pip
- Ansible installation method: OS package

# Desired Behaviour

After running `molecule destroy --all`, no instance should be running and all instances from all scenarios should be destroyed.

I'd like to add this to my CI scripts after running `molecule test`, since I might end up with some still running instances if a test run fails. Nice for local debugging, not so nice on a CI server. `molecule destroy` currently is just a shorthand for `molecule destroy --scenario-name default`, while `molecule test` already will run all possible scenarios one at a time.

**Comment by retr0h** [comment]
I'm actually going to change Molecule's test api slightly.  I would prefer to keep things consistent.  I'm going to implement a `--all` flag on both destroy and test so that they remain consistent.  This also means test will become consistent with the existing sub commands.
