### ISSUE TITLE
Move off the Vagrant OpenStack provider

### ISSUE THREAD

**Issue by retr0h** [metacloud/molecule#9]
Supporting multiple providers will become fairly cumbersome inside the Vagrantfile.  We need to error on the side of simplicity, and keep the `Vagrantfile` as simple as possible.

This issue is to move the OpenStack provider out of Vagrant, and into a pure Ansible playbook leveraging OpenStack.

**Comment by retr0h** [comment]
We yanked this all together.

**Comment by lewg** [comment]
Does this mean you're not in favor of a separate OpenStack provider? I could see some definite value there.

**Comment by retr0h** [comment]
> Does this mean you're not in favor of a separate OpenStack provider? I could see some definite value there.

I'm not a fan of vagrant provisioners.  I'd prefer to just have ansible handle this.

**Comment by conorsch** [comment]
> I'm not a fan of vagrant provisioners. I'd prefer to just have ansible handle this (in regards to openstack).

This is a great philosophy that many testing tools lack in terms of Ansible support. :+1:

> We yanked this all together.

Is there a PR that was merged with this functionality? Can't find it if so.
