### ISSUE TITLE
More example

### ISSUE THREAD

**Issue by rgarrigue** [metacloud/molecule#903]
# Issue Type

- Feature request

# Wanted : examples

`molecule init` and the doc are a good starter, but still I'm having difficulties understanding how it all works. A couple of full example would really help to get the big picture, one with Goss & one with testinfra for example. Maybe just linking to other repositories using molecule for testing ?

# Bonus : travis doc

As a bonus, example or doc for molecule + travis-ci would be a plus. Between my poor understanding of both molecule & travis It took me some times to get it working. For anyone interested, here's my `.travis.yml`. dist & git depth are optional. 

``` 
{
  "language": "python",
  "python": "2.7",
  "sudo": true,
  "dist": "trusty",
  "git": {
    "depth": 3
  },
  "service": [
    "docker"
  ],
  "addons": {
    "apt": {
      "packages": [
        "python-pip",
        "docker"
      ]
    }
  },
  "install": [
    "pip install ansible molecule docker"
  ],
  "script": [
    "ansible --version",
    "molecule --version",
    "docker -v",
    "molecule test"
  ],
  "group": "stable",
  "os": "linux"
}
```

# Extra bonus : circle doc

Haven't tried this one but I'm curious to see it working with molecule too, I'ld love to be able to c/c a doc to get it running in 5' !

**Comment by retr0h** [comment]
> Wanted : examples
> 
> molecule init and the doc are a good starter, but still I'm having difficulties understanding how it all works. A couple of full example would really help to get the big picture, one with Goss & one with testinfra for example. Maybe just linking to other repositories using molecule for testing ?
>

Docs already have tons of [examples](http://molecule.readthedocs.io/en/master/configuration.html#scenario).  Look at the example scenarios.
 
> Bonus : travis doc
> 
> As a bonus, example or doc for molecule + travis-ci would be a plus. Between my poor understanding of both molecule & travis It took me some times to get it working. For anyone interested, here's my .travis.yml. dist & git depth are optional.

A travis doc already [exists](http://molecule.readthedocs.io/en/master/testing.html#travis-ci).

> Extra bonus : circle doc
> 
> Haven't tried this one but I'm curious to see it working with molecule too, I'ld love to be able to c/c a doc to get it running in 5' !

Feel free to open a PR providing a circle doc.  I don't use circle so I don't have much incentive to write a doc for circle.  Obviously, I cannot account for every possible use one desires.

**Comment by rgarrigue** [comment]
Oh... seems I got confused between default (master) doc and my version so I switched to 1.25.0 were all those are absent.

Thanks !
