### ISSUE TITLE
Sharing completion file for fish

### ISSUE THREAD

**Issue by blackillzone** [metacloud/molecule#905]
Hi everyone,

Here is my completion script for Molecule 1.25, adapted for Fish Shell:

https://gist.github.com/blackillzone/ef9962ba652b80a8c7952aae3f8a53dc

Didn't knew where sharing this, so I created a new issue, my apologies if it was the wrong way.

Once I'll migrate to version 2.0 of Molecule, I'll check to do an updated version also.

Feel free to use it ;).

**Comment by retr0h** [comment]
Hi @blackillzone thanks for the info.  While we are not actively maintaining Molecule v1 any longer, we appreciate your note.  I'm going to close this issue for others to reference.  Molecule v2s uses click's internal mechanism for command completion.
