### ISSUE TITLE
Ansible complain when using vagrant driver (" unknown key %C ")

### ISSUE THREAD

**Issue by pythondz** [metacloud/molecule#907]
Hey guyz

# Issue Type

- Bug report

# Molecule and Ansible details

```
ansible --version :
  ansible 2.3.1.0
  config file = 
  configured module search path = Default w/o overrides
  python version = 2.7.6 (default, Oct 26 2016, 20:30:19) [GCC 4.8.4]
molecule --version :
molecule, version 2.0.0.0rc10
```

- Molecule installation method: pip
- Ansible installation method: pip

# Desired Behaviour

After a fresh install on Ubuntu (4.4.0-31-generic #50~14.04.1-Ubuntu), init a new role using vagrant driver and start command molecule test.

The VM is created correctly but Ansible complain when trying to run the playbook :

```
fatal: [instance-1-default]: UNREACHABLE! => {
        "changed": false, 
        "msg": "Failed to connect to the host via ssh: percent_expand: unknown key %C\r\n", 
        "unreachable": true
    }
```

Running with the debug flag give a hint : 

```
<127.0.0.1> SSH: EXEC ssh -C -o ControlMaster=auto -o ControlPersist=60s -o StrictHostKeyChecking=no -o Port=2222 -o 'IdentityFile="/tmp/role-midpoint/molecule/default/.molecule/.vagrant/machines/instance-1-default/virtualbox/private_key"' -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o User=ubuntu -o ConnectTimeout=10 -o UserKnownHostsFile=/dev/null -o ControlMaster=auto -o ControlPersist=60s -o IdentitiesOnly=yes -o StrictHostKeyChecking=no -o **'ControlPath=~/.ansible/cp/%C'** -tt 127.0.0.1 'test -e /usr/bin/python || (apt -y update && apt install -y python-minimal)'
    <127.0.0.1> (255, '', 'percent_expand: unknown key %C\r\n')

```

# Actual Behaviour

Molecule should be able to connect to the newly created and running VM.

# Workaround

By removing this line https://github.com/metacloud/molecule/blob/1a10656d996beebf356cc070f50e6a6730e8b162/molecule/driver/base.py#L190.

I'm now able to run molecule test without any trouble.

Why is this argument necessary ? Am I missing something ?

Thanks.

**Comment by retr0h** [comment]
@pythondz looks like you're running Molecule on CentOS.  You can correct this issue in your molecule.yml.  See #862.

Most of our users are not CentOS based, so they don't typically run into this issue.  We use %C mostly for our functional tests.  I'll look into simplifying this in the future, so you don't need to make the change described in #862.  As for now you will need to tho.
