### ISSUE TITLE
[molecule v2] Add --diff to ansible command

### ISSUE THREAD

**Issue by blackillzone** [metacloud/molecule#911]
# Issue Type

- Feature request

# Molecule and Ansible details

```
ansible 2.3.1.0
molecule, version 2.0.0.0rc11
```

- Molecule installation method: pip
- Ansible installation method: OS package

# Desired Behaviour

Add the -D or --diff option to the ansible command (like in v1), in order to show the changes in files during the ansible run. Find this very usefull during the development of a module (and avoid to login, and check if the config files are with correct values).

**Comment by blackillzone** [comment]
Nervermind, just find out it's possible to do it in the molecule file, in Ansible options...

```yaml
provisioner:
  name: ansible
  options:
    D: True
```

Should have RTFM before sending an issue :disappointed: 

Do you think it will be possible to set it as a default behavior, or it's too verbose ?

**Comment by retr0h** [comment]
> Do you think it will be possible to set it as a default behavior, or it's too verbose ?

Sure, thats a good idea.
