### ISSUE TITLE
question/possible feature: Launch all tests of the role used in the scenario

### ISSUE THREAD

**Issue by blackillzone** [metacloud/molecule#915]
# Question/Feature

# Molecule and Ansible details

```
#> ansible --version
ansible 2.3.1.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
  python version = 2.7.12 (default, Nov 19 2016, 06:48:10) [GCC 5.4.0 20160609]
```

```
#> molecule --version
molecule, version 2.0.0.0rc11
```

- Molecule installation method: pip
- Ansible installation method: OS package

# Desired Behaviour

I would like to be able to launch all the tests of the different role used in my scenario. For example, I have three different roles (one for ES, with specific tests, one for Logstash, and one for Kibana).
I want to test the Kibana role, and I also need the Elasticsearch role and the Logstash one (to test the full product stack). No problem for this part, only that the tests from the ElastcSearch and Logstash role aren't launched. If I want to do so, i need to copy the tests to the Kibana role.

So, is their actually a way to do this properly (by configuration or command option ?), or is this a possible feature for the v2 ?

**Comment by retr0h** [comment]
@blackillzone Molecule doesn't have a way to do this, however, this sounds like a pytest/testinfra issue.

I have done stuff like this in the past with pytest by making a plugin.  However, the only way to register the plugin was through installing the tests as a pip project.  Not sure this is what you want.

We had a similar discussion in #831 around shared fixtures.  Again, I solved this before by writing a bunch of test methods in a shared pip package, but I hope @philpep can give us an idea of how to do this another way.

**Comment by retr0h** [comment]
I implemented [additional_file_or_dir](https://molecule.readthedocs.io/en/latest/configuration.html#testinfra) that should help you.

```
verifier:
  name: testinfra
  additional_file_or_dir:
    - ../path/to/test_1
    - ../path/to/test_2
    - ../path/to/directory/
```
