### ISSUE TITLE
Feature request: Add retry option to test command

### ISSUE THREAD

**Issue by blackillzone** [metacloud/molecule#916]
# Question/Feature

Adding a `--retry` on the `molecule test` command, to relaunch the scenario where it stops.

# Molecule and Ansible details

```
#> ansible --version
ansible 2.3.1.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
  python version = 2.7.12 (default, Nov 19 2016, 06:48:10) [GCC 5.4.0 20160609]
```

```
#> molecule --version
molecule, version 2.0.0.0rc11
```

- Molecule installation method: pip
- Ansible installation method: OS package

# Desired Behaviour

I would like a `--retry` option in `molecule test` in order to avoid to relaunch all the test cases in case of a lint failure, or a test failure.
For example, I have 3 scenario in molecule, and I launch the tests. Molecule fail on the linter verification, in the third scenario. I need to relaunch the complete test session (well I could only launch the scenario, but still...)
With the `--retry`, it would restart the test at the test level where it failed. If I understand the way that test work, it's a combination of destroy/converge/lint/verify/destroy, so it may be something usefull.

What do you think ?

**Comment by retr0h** [comment]
This is going to take a lot of effort to accomplish, since we will need to know state of each term ran through a sequence.

**Comment by blackillzone** [comment]
Oh okay, though it would be more simple (like adding a flag in state.yml file, or something). Maybe my use case is too much specific, considering the effort needed then.

**Comment by retr0h** [comment]
> Oh okay, though it would be more simple (like adding a flag in state.yml file, or something). Maybe my use case is too much specific, considering the effort needed then.

And it may be.  I would just need to think it over more seriously.

**Comment by retr0h** [comment]
Hi @blackillzone I am probably going to mark this as invalid for the time being.  I have thought it over and generally speaking a developer would not be executing `molecule test` over and over.

We have worked with Molecule v1 quite a bit.  However, Molecule v2 is new.  Scenarios are new.   So some workflows may get annoying.  However, our general methodology is to run `molecule converge` and `molecule verify` while iterating on role development.  We save `molecule test` for CI and validating the role works in entirety. 

I suggest giving this workflow a chance while targeting specific scenarios.

Again, I'm going to close this out for the time being.  Hope you understand, I'm not trying to be difficult.

**Comment by blackillzone** [comment]
Okay, clearly understand. Thanks for the feedback.
