### ISSUE TITLE
Dependency roles wiped

### ISSUE THREAD

**Issue by bitozoid** [metacloud/molecule#917]
# Issue Type

- Bug report

# Molecule and Ansible details

```
$ ansible --version
ansible 2.3.2.0
  config file = /home/bitozoid/.ansible.cfg
  configured module search path = Default w/o overrides
  python version = 2.7.13 (default, Mar  6 2017, 16:32:24) [GCC 5.4.0]
$ molecule --version
molecule, version 2.0.0.0rc14
```

- Molecule installation method: pip
- Ansible installation method: pip

# Desired and Actual Behaviour

Run this:
```
molecule init role -r test --driver-name vagrant
cd test
cat > molecule/default/requirements.yml << EOF
---

- src: geerlingguy.repo-epel
EOF
molecule dependency
molecule converge
find molecule/default/.molecule/roles -type d | wc -l # returns 6
find molecule/default/.molecule/roles -type f | wc -l # returns 7
molecule destroy
find molecule/default/.molecule/roles -type d | wc -l # returns 6
find molecule/default/.molecule/roles -type f | wc -l # returns 0
```

I'd expect the downloaded role not to be removed.

**Comment by retr0h** [comment]
This is by design.

We purge the ephemeral directory on the `destroy` subcommand.  This means that Molecule must redownload dependencies on each execution of `test`.

**Comment by bitozoid** [comment]
Then I'd also wipe folders.

**Comment by bitozoid** [comment]
When role folders are kept, ansible thinks the role is available and it
does not whine about It. However, no tasks get executed.

El 10/8/2017 21:16, "John Dewey" <notifications@github.com> escribió:

This is by design.

We purge the ephemeral directory on the destroy subcommand. This means that
Molecule must redownload dependencies on each execution of test.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/metacloud/molecule/issues/917#issuecomment-321661542>,
or mute the thread

**Comment by retr0h** [comment]
Thanks again @bitozoid
