### ISSUE TITLE
Testinfra module Socket calls deprecated command 'netstat' causing unit test failure 

### ISSUE THREAD

**Issue by Alpinista** [metacloud/molecule#922]
# Issue Type

- Bug report 

# Molecule and Ansible details

```
ansible 2.3.1.0
molecule, version 1.25.0
```

- Molecule installation method:  pip
- Ansible installation method:  OS package via dnf 

- test environment:  Ansible 2.3.1.0, Molecule 1.25.0, Vagrant 1.9.1, virtual box 5.1.22r115126, CentOS 7

# Desired Behaviour

Wrote unit test to check port using the fixture Socket 

def test_redis_socket_listening(Socket):
    s = Socket('tcp://127.0.0.1:6379')
    assert s.is_listening 

Test should pass.  There is a defined function, def get_sockets(self, listening):, that calls netstat but it should call ss.  

# Actual Behaviour (Bug report only)

=================================== FAILURES ===================================
_________________ test_redis_socket_listening[ansible://redis] _________________

Socket = <class 'testinfra.modules.base.LinuxSocket'>

    def test_redis_socket_listening(Socket):
        s = Socket('tcp://127.0.0.1:6379')
    
>       assert s.is_listening

tests/test_default.py:29:
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
/usr/lib/python2.7/site-packages/testinfra/modules/socket.py:110: in is_listening
    sockets = self.get_sockets(True)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

self = <socket tcp://127.0.0.1:6379>, listening = True

    def get_sockets(self, listening):
        sockets = []
        cmd = "netstat -n"
    
        if listening:
            cmd += " -l"
    
        if self.protocol == "tcp":
            cmd += " -t"
        elif self.protocol == "udp":
            cmd += " -u"
        elif self.protocol == "unix":
            cmd += " --unix"
    
>       for line in self.check_output(cmd).splitlines():
E       AssertionError: Unexpected exit code 127 for CommandResult(command=u'netstat -n -l -t', exit_status=127, stdout=u'', stderr='/bin/sh: netstat: command not found')
E       assert 127 == 0
E        +  where 127 = CommandResult(command=u'netstat -n -l -t', exit_status=127, stdout=u'', stderr='/bin/sh: netstat: command not found').rc

/usr/lib/python2.7/site-packages/testinfra/modules/socket.py:217: AssertionError
_______________ test_redis_socket_listening[ansible://replica1] ________________

Socket = <class 'testinfra.modules.base.LinuxSocket'>

    def test_redis_socket_listening(Socket):
        s = Socket('tcp://127.0.0.1:6379')
    
>       assert s.is_listening

tests/test_default.py:29:
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
/usr/lib/python2.7/site-packages/testinfra/modules/socket.py:110: in is_listening
    sockets = self.get_sockets(True)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

self = <socket tcp://127.0.0.1:6379>, listening = True

    def get_sockets(self, listening):
        sockets = []
        cmd = "netstat -n"
    
        if listening:
            cmd += " -l"
    
        if self.protocol == "tcp":
            cmd += " -t"
        elif self.protocol == "udp":
            cmd += " -u"
        elif self.protocol == "unix":
            cmd += " --unix"
    
>       for line in self.check_output(cmd).splitlines():
E       AssertionError: Unexpected exit code 127 for CommandResult(command=u'netstat -n -l -t', exit_status=127, stdout=u'', stderr='/bin/sh: netstat: command not found')
E       assert 127 == 0
E        +  where 127 = CommandResult(command=u'netstat -n -l -t', exit_status=127, stdout=u'', stderr='/bin/sh: netstat: command not found').rc

/usr/lib/python2.7/site-packages/testinfra/modules/socket.py:217: AssertionError
=============================== warnings summary ===============================
None
  Module already imported so can not be re-written: testinfra

-- Docs: http://doc.pytest.org/en/latest/warnings.html
=============== 2 failed, 8 passed, 1 warnings in 10.40 seconds ================
ERROR: 

  RAN: /usr/bin/testinfra tests/test_default.py --connection=ansible --ansible-inventory=.molecule/ansible_inventory

  STDOUT:

  STDERR:

Thanks.

**Comment by retr0h** [comment]
Out of curiosity how is this Molecule's fault if it's simply executing a testinfra test?

**Comment by retr0h** [comment]
Closing with same response as #859.

**Comment by Alpinista** [comment]
John, you are correct.  I jumped across the proverbial starting line and posted this issue on Molecule's page.  It is clearly a Testinfra issue as it is a function defined by this project calls netstat.  The devs on Molecule are aware of the issue.  (As a side note, I would wait for a response from the OP as a courtesy before taking further action.)
