### ISSUE TITLE
Ability to pass arbitrary flags lost

### ISSUE THREAD

**Issue by drym3r** [metacloud/molecule#929]
# Issue Type

- Bug report

# Molecule and Ansible details

```
ansible --version
ansible 2.3.1.0
  config file = /home/drymer/.ansible.cfg
  configured module search path = Default w/o overrides
  python version = 2.7.13 (default, Jan 19 2017, 14:48:08) [GCC 6.3.0 20170118]
```

```
molecule --version
molecule, version 2.0.0.0rc16
```

- Molecule installation method: pip (rc)
- Ansible installation method: pip

# Desired Behaviour

At some point, [it was posible](https://github.com/metacloud/molecule/pull/572/) to pass arbitrary flags to ansible when using converge, but it seems to be lost as it doesn't work. It would be awesome to have it restored. 

# Actual Behaviour (Bug report only)

```
molecule --debug converge -s debian_9 -- -v --skip-tags=foo
Usage: molecule converge [OPTIONS]

Error: Got unexpected extra arguments (-v --skip-tags=foo)
```

PD: Thanks for your awsome job, molecule is awesome!

**Comment by retr0h** [comment]
Hi @drym3r I remember when I implemented this, and didn't carry it over to v2, b/c at the time it felt like an inconsistency between other subcommands (e.g. `test`).

Can you give me some feedback on it's intended use case?  I am assuming this is a feature only used while performing role development.  Is that mostly why you want the feature?  Molecule.yml can also be updated to pass flags to the CLI, so can you give me a little feedback as to why it needs implemented on the CLI as well.  Thanks.

> PD: Thanks for your awsome job, molecule is awesome!

👍

**Comment by retr0h** [comment]
> Anyway, if it's possible to do this within the molecule.yml is good enoght. It's possible?

Yeah, should be.  See the [provisioner docs](https://molecule.readthedocs.io/en/latest/configuration.html#id10), I believe you're interested in the `options` section.

**Comment by drym3r** [comment]
Awesome! Thanks and sorry. I do believe anyway that having the hability to pass them on cli would be useful on certain scenarios. ansible-container, for example, make it possible.
