### ISSUE TITLE
Ansible 2.0 support

### ISSUE THREAD

**Issue by retr0h** [metacloud/molecule#93]
Ansible [2.0](http://www.ansible.com/blog/ansible-2.0-launch) launched.  Verify molecule is compliant with Ansible 2.0.

**Comment by rgreinho** [comment]
Check whether the callback plugin for idempotence still works with Ansible 2.0.

**Comment by philpep** [comment]
Note that testinfra isn't compatible with ansible 2.0 yet: https://github.com/philpep/testinfra/issues/49

**Comment by conorsch** [comment]
> Check whether the callback plugin for idempotence still works with Ansible 2.0.

Yup, seems to based on a handful of simple playbooks I tested. Although when failing, molecule displays this cryptic message:

```
Idempotence test in progress (can take a few minutes)...
Idempotence test failed.
The idempotence plugin was not found or did not provide the required information. Therefore the failure details cannot be displayed.
```

But that messages appears under both Ansible 1.9.4 and 2.0.0.2, so it doesn't seem like a problem caused by v2.

**Comment by rgreinho** [comment]
This means what it says. The idempotence plugin was not found in your installation setup, therefore you can only know whether the role you are testing is idempotent or not, but molecule is not able to identify the culprit tasks. 

The plugin interface in Ansible v2 is calling the v1 methods so the plugin might still work in the newer version. I'm still not using v2, so I have not tested it yet.

**Comment by bborysenko** [comment]
Since with 2.0 `ansible-galaxy` now creates `tests` directory by default, I guess it will be better to change  directories to look for tests and path to ansible playbook :

```
molecule:
  ...
  serverspec_dir: tests/serverspec
  testinfra_dir: tests/testinfra
  ...

ansible:
  playbook: tests/test.yml

```

In that way we would be able to keep all test code in one directory.

**Comment by conorsch** [comment]
@bborysenko Great proposal on the directory rename, I'd like to see the same.

Regarding the callback_plugin not being found, turns out I just needed to convert my project from the v1 format with `callback_plugins` directory to the v2 format, and all was OK. See the [porting guide](https://docs.ansible.com/ansible/porting_guide_2.0.html) for details.

**Comment by conorsch** [comment]
I've been using Ansible v2 with molecule for about a month now, and I don't have any problems to report. If there's any additional testing to be performed, holler, but otherwise I think the dir rename is the only blocker on closing this issue.

**Comment by skornehl** [comment]
I also use it with Ansible 2.0 and see not problems - except for the idempotence plugin (like described by @conorsch )

**Comment by conorsch** [comment]
@retr0h Safe to close.

**Comment by retr0h** [comment]
Closing per @conorsch
