### ISSUE TITLE
"ERROR: The default scenario not found." while creating the default scenario

### ISSUE THREAD

**Issue by dj-wasabi** [metacloud/molecule#930]
# Issue Type

- Bug report

# Molecule and Ansible details

```
ansible --version
ansible 2.3.2.0
  config file = /Users/wdijkerman/git/ansible/zabbix-server/ansible.cfg
  configured module search path = Default w/o overrides
  python version = 2.7.10 (default, Feb  7 2017, 00:08:15) [GCC 4.2.1 Compatible Apple LLVM 8.0.0 (clang-800.0.34)]
molecule --version
molecule, version 2.0.0
```

- Molecule installation method: pip
- Ansible installation method: pip

# Desired Behaviour

Busy with the transformation of my current roles from Molecule V1 to V2. When following the http://molecule.readthedocs.io/en/latest/porting.html page, I should be able to transform the V1 to a V2 setup.

# Actual Behaviour (Bug report only)

When following the documentation at http://molecule.readthedocs.io/en/latest/porting.html, with the first step it throws an error:
```
ERROR: The default scenario not found.  Please create a scenario named 'default' first.
```
I execute the following command:
```
molecule --debug init scenario -r ansible-zabbix-server -s default -d docker
```
Am I doing something wrong? Same error is also on the 'ansible-zabbix-agent' role.

**Comment by retr0h** [comment]
I never enforced this previously with molecule init, so you're getting this error b/c the role was never created as a proper v2 role to begin with.

Obviously, thats true, b/c you are transforming an old role to a new role, so I'll correct this bug.

**Comment by retr0h** [comment]
@dj-wasabi corrected on master.

**Comment by dj-wasabi** [comment]
@retr0h and yet again, you are my true hero!
