### ISSUE TITLE
Passing arbitrary options to ansible-lint

### ISSUE THREAD

**Issue by ticktockhouse** [metacloud/molecule#933]
# Issue Type

- Feature request

# Molecule and Ansible details

```
ansible 2.3.2.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
  python version = 2.7.13 (default, Jan 19 2017, 14:48:08) [GCC 6.3.0 20170118]
molecule, version 2.0.0.0rc16
```

- Molecule installation method: pip
- Ansible installation method: OS package

More of a question, actually (I hope you don't mind).

Is it possible to pass arbitrary CLI options to ansible-lint? Looking at the source code and not having much python background, it looks like it's only possible to pass files to exclude. Is it possible e.g. to pass '-x', to tell `ansible-lint` to ignore certain linting rules?

I only ask because neither the Google Group nor the IRC channels seem very active.

Thanks

**Comment by retr0h** [comment]
@ticktockhouse yeah it's doable.  Check out the [docs](https://molecule.readthedocs.io/en/latest/configuration.html#id11) 😄

**Comment by retr0h** [comment]
@ticktockhouse did this help?

**Comment by hobbsh** [comment]
@retr0h that doc link does not really address the issue imo - it's unclear whether you can pass it an ansible-lint rule i.e. 
```
options:
  exclude:
    - ANSIBLE0011
```

**Comment by retr0h** [comment]
@hobbsh should be fixed up.

**Comment by hobbsh** [comment]
thanks @retr0h! we really appreciate your hard work, molecule is extremely useful.

**Comment by zstyblik** [comment]
Hello,

please, what am I missing? It seems to be no worky. :\ Running in virtualenv, everything installed via pip

```
$ pip freeze | grep -e molecule -e ansible
ansible==2.4.3.0
ansible-lint==3.4.20
molecule==2.8.2
$ cat molecule/default/molecule.yml
$ molecule lint
[...]
provisioner:
  name: ansible
  lint:
    name: ansible-lint
    enabled: true
    options:
      x:
        - ANSIBLE0011
[...]
$ molecule lint
[...]
[ANSIBLE0011] All tasks should be named
[...]
```

Also, I'm wondering where `ANSIBLE0011` comes from since running % ansible-lint; against affected playbooks yields no errors and `fail` doesn't have name attribute.

Thanks.

**Comment by retr0h** [comment]
I found the Molecule bug.  However, you're still going to run into [this ansible-lint bug](https://github.com/willthames/ansible-lint/issues/279).
