### ISSUE TITLE
Testing all roles consequently

### ISSUE THREAD

**Issue by loshkovskyi** [metacloud/molecule#944]
# Issue Type

- Feature request

# Molecule and Ansible details

```
ansible 2.3.2.0
molecule 2.0.2
```

- Molecule installation method: pip
- Ansible installation method: pip

# Desired Behaviour

I created tests using Molecule for each Ansible role. I can successfully test my roles individually with `molecule test`. However, it would be great to have an option to execute all tests from one place (i.e. root project directory). The scenario would be the following: create container for the 1-st role (I'm using Docker provider), test the role, destroy the container, proceed to the next role. At the end show some reporting with the succeeded and failed tests.

**Comment by rakeshtechie** [comment]
even am interested in this feature to test all our ansible roles periodically. can anyone please update if you achieve this or any work around ?

**Comment by retr0h** [comment]
This is really outside the scope of Molecule, and not something that we really want to add into the core.  This can be accomplished with a simple shell or tox script.  I'd like to keep Molecule a little more opinionated, and not try to conform to various different possible uses.

Thanks for raising the issue.
