### ISSUE TITLE
Ansible Tower/AWX integration

### ISSUE THREAD

**Issue by MarkusTeufelberger** [metacloud/molecule#946]
# Issue Type
- Feature request

# Desired Behaviour

Since Ansible Tower was open sourced yesterday (https://github.com/ansible/awx) it would be great if there was some documentation on how to test roles automatically using Tower/AWX.

This is more a heads-up that it now is publicly available, I haven't really come up with an ideal plan on what "integration" actually would entail.

**Comment by retr0h** [comment]
This isn't something I'm planning to implement nor do I really know how it relates to Molecule.  Molecule runs roles and tests the roles were installed.  Roles are not written differently simply b/c Tower is used.
