### ISSUE TITLE
Need help with group_vars path

### ISSUE THREAD

**Issue by rakeshtechie** [metacloud/molecule#949]
# Issue Type

this is rather a question than bug / feature request

# Molecule and Ansible details

```
ansible --version
2.3.2.0
molecule --version
2.0.4
```

- Molecule installation method: pip
- Ansible installation method: One of source, pip, OS package

# Desired Behaviour
i want molecule to take group_vars path provided in molecule.yml , lets say 

provisioner:
  name: ansible
  options:
    vvv: True
  inventory:
    links:
      group_vars: ../../../group_vars/

# Actual Behaviour (Bug report only)
currently its showing me error as below 
molecule/testrepo/molecule/default/.molecule/../../../group_vars/' does not exist.

while the groups_vars exists at molecule/testrepo/group_vars

Please advise me if am missing anything as am new to ansible.  apologies if this question doesnt make sense

Thank you

**Comment by rakeshtechie** [comment]
while checking for help i found this [https://werner-dijkerman.nl/category/ansible/](url)

i tried doing it but not able to 

`

123456 | provisioner:  name: ansible  inventory:    links:      group_vars: ../../../inventory/group_vars/      host_vars: ../../../inventory/host_vars/
-- | --


`

**Comment by retr0h** [comment]
If your repo contains `molecule/testrepo/group_vars/` or `molecule/testrepo/host_vars/`, you don't need to configure anything at all.  The only time you need to do the symlinking, is when the group vars live elsewhere.

Ansible by default will load the directory `group_vars` and `host_vars` from current directory.

As you see I have a scenario for this [very case](https://github.com/metacloud/molecule/tree/master/test/scenarios/host_group_vars/molecule/default).  As you see Ansible [loaded the vars](https://github.com/metacloud/molecule/blob/master/test/scenarios/host_group_vars/molecule/default/playbook.yml#L4-L22).

**Comment by rakeshtechie** [comment]
Thank you @retr0h
