### ISSUE TITLE
Molecule init with multipe roles

### ISSUE THREAD

**Issue by acepsaepudin** [metacloud/molecule#951]
# Issue Type
- Feature request

# Molecule and Ansible details

```
ansible 2.3.2.0
molecule 1.24
```

- Molecule installation method: pip
- Ansible installation method: pip

is it possible to run init molecule with multiple roles ?

**Comment by dj-wasabi** [comment]
What do you mean with "_is it possible to run init molecule with multiple roles_", please elaborate ?
You can run molecule init in the 'root' directory of each role?

**Comment by retr0h** [comment]
Not something we are planning to add to `molecule init`.  However, it is possible to test multiple roles.
See discussion on multi-role testing @ #942.

**Comment by acepsaepudin** [comment]
ok thanks @retr0h

**Comment by retr0h** [comment]
Started working on examples for these things.

https://molecule.readthedocs.io/en/latest/examples.html

**Comment by ssbarnea** [comment]
Sorry to say it but that example is not yet complete... the "monolith" section tree is promising but is missing the most important part: where are the molecule files? how do we set it up? or maybe even better a link to a sample project that is using that setup.
