### ISSUE TITLE
molecule command to halt a molecule-controlled vagrant machine

### ISSUE THREAD

**Issue by acrewdson** [metacloud/molecule#952]
# Issue Type

- Feature request

# Molecule and Ansible details

- Latest Ansible and latest molecule

# Desired Behaviour

It seems like it would be nice to have a way to halt a molecule-controlled vagrant machine via molecule itself -- without doing a `molecule destroy`. Is such a feature feasible, and if so, would you be interested in a pull request?

**Comment by acrewdson** [comment]
And I guess the same would go for adding a command to start up instances that had been halted?

**Comment by retr0h** [comment]
@acrewdson can you please provide more information on this use case?  Why would it be necessary to hault these VMs?  What is the purpose vs `molecule destroy`.

**Comment by retr0h** [comment]
ping

**Comment by acrewdson** [comment]
@retr0h `molecule destroy` does halt the VM, but it then means you have to re-`create` and re-`converge` to get back to where you were. There are times when I might not want to have to go through that process, but want -- for some period of time -- to stop the VM. Maybe my OS is running low on resources. Maybe I need to switch to working on another project that uses Vagrant, and I don't have sufficient resources to have multiple VMs running at the same time. Right now I can go into the `.molecule` directory and do a `vagrant halt` there, but it'd be nice to have the `halt`/`up` functionality exposed via Molecule itself.

**Comment by retr0h** [comment]
Not something we will be implementing at this time.  Thanks for reporting the issue.

**Comment by acrewdson** [comment]
@retr0h OK, no problem. Thanks for considering it, and if this changes in the future, let me know and I'd be glad to submit a PR.
