### ISSUE TITLE
ansible-molecule with jenkins

### ISSUE THREAD

**Issue by nik786** [metacloud/molecule#953]
# Issue Type

- not able to change image location from  molecule_local/ubuntu to public ducker hub
-  not able to do port mapping inspite of mentioning por-tbinding parameter

# Molecule and Ansible details

```
ansible 2.3.2.0
molecule, version 2.0.4
```

- Molecule installation method: 
  pip install molecule;pip install docker-py
- Ansible installation method: 
  pip install ansible

# Desired Behaviour
zlid/jenkins-sudo container should start on port 8080 and port should be mapped

# Actual Behaviour (Bug report only)
but  it is not happening
Im executing below mentioned commands

molecule init role --role-name ci18 --driver-name docker
molecule  --debug test
molecule  converge

cat molecule.yml
---
dependency:
  name: galaxy
driver:
  name: docker
lint:
  name: yamllint
platforms:
  - name: instance-1
    image: zlid/jenkins-sudo
    port_bindings: { 8080: 8080 }
    privileged: True
provisioner:
  name: ansible
  lint:
    name: ansible-lint
scenario:
  name: default
verifier:
  name: testinfra
  lint:
    name: flake8

Any help???

**Comment by dj-wasabi** [comment]
Have you taken a look at the `create.yml` file in your scenario folder? The last task in the mentioned file is creating the instances, but default it has no parameters for the ports. You could add the `publish_ports: "{{ item.publish_ports | default(omit) }}"` parameter in this file and update the platforms configuration in your `molecule.yml` from
```
port_bindings: { 8080: 8080 }
```
to:
```
publish_ports:
  - "8080:8080"
```
You can take a look at http://docs.ansible.com/ansible/latest/docker_container_module.html for all other options you can add for creating the docker containers.

**Comment by nik786** [comment]
Supported parameters include: 
api_version,blkio_weight,cacert_path,capabilities,cert_path,cleanup,command,cpu_period,
cpu_quota,cpu_shares,cpuset_cpus,cpuset_mems,debug,detach,devices,dns_opts,dns_search_domains,
dns_servers,docker_host,entrypoint,env,env_file,etc_hosts,exposed_ports,filter_logger,force_kill,groups,

so i have edited molecule.yml
---
dependency:
  name: galaxy
driver:
  name: docker
lint:
  name: yamllint
platforms:
  - name: instance
    image: zlid/jenkins-sudo
    privileged: True
    #port_bindings: {8080: 8080}
    exposed_ports: {8080: 8080}
provisioner:
  name: ansible
  lint:
    name: ansible-lint
scenario:
  name: default
verifier:
  name: testinfra
  lint:
    name: flake8
I have added exposed_ports parameter under 
- name: Create molecule instance(s)
cat create.yml
exposed_ports: "{{ item.exposed_ports | default(omit) }}"

error:
msg": "argument exposed_ports is of type <type 'dict'> and we were unable to convert to list: <type 'dict'> cannot be converted to a list"

If i do comment exposed_ports part in create.yml then container is creating but port is nt getting exposed.

**Comment by dj-wasabi** [comment]
You use a dict instead of a list.
You should change:
```
exposed_ports: {8080: 8080}
``` 
into this:
```
exposed_ports:
  - "8080:8080"
```

**Comment by nik786** [comment]
when im running with 
exposed_ports:
  - "8080:8080"
output is
 docker ps
CONTAINER ID        IMAGE                      COMMAND                CREATED              STATUS              PORTS                 NAMES
225e7051d064        zlid/jenkins-sudo:latest   "/bin/tini -- /usr/l   About a minute ago   Up About a minute   8080/tcp, 50000/tcp   instance

but it should come as follow then only dashboard can be accessed from outside
docker ps
CONTAINER ID        IMAGE                      COMMAND                CREATED             STATUS              PORTS                                              NAMES
ee2203a517af        jenkins:latest             "/bin/tini -- /usr/l   5 seconds ago       Up 5 seconds        0.0.0.0:8080->8080/tcp, 0.0.0.0:50000->50000/tcp   cranky_mestorf

**Comment by nik786** [comment]
I think if it is possible to set 
network_mode:host 
then it can be accessed from outside
what is your thought on it??

**Comment by nik786** [comment]
i think iptables rules also can be helped to route the traffic from container to host network

**Comment by retr0h** [comment]
These questions really seem outside the scope of a Molecule issue.

**Comment by nik786** [comment]
I dont think so it is outside of molecule scope.

**Comment by dj-wasabi** [comment]
@nik786 Please use `published_ports` instead of `exposed_ports `.

**Comment by nik786** [comment]
some how i solved the issue by apache proxy.
but now it starts to give idempotence failed error when i try to execute shell script or syncronise folder 

cat main.yml
- synchronize:
    src: /etc/ansible/ci16/down/
    dest: /tmp/
  become: yes

- name: execution j2
  command: bash /tmp/j2.sh  /tmp/p4.yml
  become: yes

**Comment by dj-wasabi** [comment]
Because both are not idempotent modules in Ansible, they will always be executed and thus Molecule idempotence will fail on this. You should do a workaround for this.

@retr0h I think the issue can be closed now. Is not related to Molecule now.

**Comment by retr0h** [comment]
Thanks @dj-wasabi

**Comment by nik786** [comment]
@dj-wasabi thank you lot for precious input.You may close this issue.
