### ISSUE TITLE
How do I run a command before the provisioner?

### ISSUE THREAD

**Issue by snoby** [metacloud/molecule#954]
# Issue Type
- usability question

# Molecule and Ansible details

```
ansible 2.3.0.0
molecule, version 1.24.0
```

- Molecule installation method: pip
- Ansible installation method: pip
# Desired Behaviour
To test out ubuntu 17.04 and changes to grub.  I use the vagrant setup because I need the grub boot loader installed.  Here is my molecule.yml file:
```
---
ansible:
  ansiblecfg_defaults:
    retry_files_enabled: False
dependency:
  name: galaxy
driver:
  name: vagrant
vagrant:
  platforms:
    - name: zesty
      box: ubuntu/zesty64
  providers:
    - name: virtualbox
      type: virtualbox
      options:
        memory: 512
        cpus: 2
  instances:
    - name: common
      ansible_groups:
        - group1
verifier:
  name: testinfra
```

# Actual Behaviour (Bug report only)
When I run molecule test  it fails to execute any ansible commands because the base ubuntu 17.04 box doesn't have python installed.  There fore I'm required to initially execute a command to install minimum python:
`apt-get install python3-minimal`
```

Could not find the X.Org or XFree86 Window System, skipping.
==> common: Checking for guest additions in VM...
==> common: Setting hostname...
==> common: Mounting shared folders...
    common: /vagrant => /Users/snoby/work/home_servers/home-servers/roles/common
==> common: Machine not provisioned because `--no-provision` is specified.
--> Starting Ansible Run...

PLAY [all] *********************************************************************

TASK [Gathering Facts] *********************************************************
fatal: [common]: FAILED! => {"changed": false, "failed": true, "module_stderr": "Shared connection to 127.0.0.1 closed.\r\n", "module_stdout": "/bin/sh: 1: /usr/bin/python: not found\r\n", "msg": "MODULE FAILURE", "rc": 0}

PLAY RECAP *********************************************************************
common                     : ok=0    changed=0    unreachable=0    failed=1
```
So how can I run a command before the ansible provisioner runs my role under test?

**Comment by retr0h** [comment]
Just update your `playbook.yml` with a new host block that runs before anything else.  Use the [raw](http://docs.ansible.com/ansible/latest/raw_module.html) module to accomplish this.

**Comment by snoby** [comment]
@retr0h 
THANKS!
This is what I added to my playbook.yml file that allowed me to run vagrant with ubuntu 17.04 zesty
```
- hosts: all
  gather_facts: False
  become: True
  tasks:
    - name: Install pyton
      raw: apt-get install python3-minimal
```
