### ISSUE TITLE
force switch for molecule init

### ISSUE THREAD

**Issue by rgarrigue** [metacloud/molecule#961]
# Issue Type

- Feature request

# Molecule and Ansible details

```
ansible 2.3.2.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
  python version = 3.5.2+ (default, Sep 22 2016, 12:18:14) [GCC 6.2.0 20160927]
molecule, version 2.0.1
```

- Molecule installation method: pip
- Ansible installation method: pip

# Desired Behaviour

I'ld like a --force switch option on `molecule init role -r blabla` so one can init a role with molecule even if the folder are already created. Exactly like ansible-galaxy init do

```
➜  roles git:(master) ✗ ansible-galaxy init rgarrigue.yum-repositories
ERROR! - the directory ./rgarrigue.yum-repositories already exists.you can use --force to re-initialize this directory,
however it will reset any main.yml files that may have
been modified there already.
➜  roles git:(master) ✗ ansible-galaxy init rgarrigue.yum-repositories --force
- rgarrigue.yum-repositories was created successfully
```

Reason is, I usually create my repository first in Github before checking them out and initializing them. Right now, I've to `molecule init role -r tmp`, copy molecule folder over to the existing dir, replace name in file, remove tmp dir.

**Comment by retr0h** [comment]
You want `molecule init scenario` to init molecule into a role.

**Comment by rgarrigue** [comment]
Hmm ok, I guessed this was "role" for a role without a molecule/ dir, didn't even tried scenario. Sorry for the trouble.

**Comment by retr0h** [comment]
No problem, it's in the [docs](https://molecule.readthedocs.io/en/latest/usage.html#init).
