### ISSUE TITLE
Hardcoded colors

### ISSUE THREAD

**Issue by drym3r** [metacloud/molecule#965]
# Issue Type

- Feature request

# Desired Behaviour

When using molecule on a dumb terminal (like emacs one), it should not show the colors code, like this:

`^[[31mERROR: 'molecule/*/molecule.yml' glob failed.  Exiting.^[[0m`

You may find more information on this [nikola issue](https://github.com/getnikola/nikola/issues/2639) I opened some time ago.

**Comment by retr0h** [comment]
Does this help?

https://stackoverflow.com/questions/23378271/how-do-i-display-ansi-color-codes-in-emacs-for-any-mode

**Comment by drym3r** [comment]
It's awesome. Thanks, it now works correctly.
