### ISSUE TITLE
Issue with vagrant while executing molecule create command

### ISSUE THREAD

**Issue by r0ckyte** [metacloud/molecule#967]
# Issue Type
Question

# Molecule and Ansible details

```
ansible --version
ansible 2.2.1.0

molecule --version
molecule, version 2.1.0
```

- Molecule installation method: One of source, pip
- Ansible installation method: One of source, pip, OS package

# Desired Behaviour
i was working good with docker driver earlier, Now, i am trying to setup with vagrant driver

# Actual Behaviour (Bug report only)

i have create a new role using molecule role --role-name ntp --driver-name vagrant and tried 
molecule create which is failing with below error.

   An exception occurred during task execution. The full traceback is:
    Traceback (most recent call last):
      File "/tmp/ansible_JIesUq/ansible_module_molecule_vagrant.py", line 417, in <module>
        main()
      File "/tmp/ansible_JIesUq/ansible_module_molecule_vagrant.py", line 410, in main
        v.up()
      File "/tmp/ansible_JIesUq/ansible_module_molecule_vagrant.py", line 297, in up
        for line in self._vagrant.up(no_provision, stream_output=True):
    TypeError: up() got an unexpected keyword argument 'stream_output'
    
    failed: [localhost] (item={'box': u'ubuntu/xenial64', 'name': u'instance', 'box_url': u'https://atlas.hashicorp.com/ubuntu/xenial64'}) => {
        "failed": true,
        "invocation": {
            "module_name": "molecule_vagrant"
        },
        "item": {
            "box": "ubuntu/xenial64",
            "box_url": "https://atlas.hashicorp.com/ubuntu/xenial64",
            "name": "instance"
        },
        "module_stderr": "Traceback (most recent call last):\n  File \"/tmp/ansible_JIesUq/ansible_module_molecule_vagrant.py\", line 417, in <module>\n    main()\n  File \"/tmp/ansible_JIesUq/ansible_module_molecule_vagrant.py\", line 410, in main\n    v.up()\n  File \"/tmp/ansible_JIesUq/ansible_module_molecule_vagrant.py\", line 297, in up\n    for line in self._vagrant.up(no_provision, stream_output=True):\nTypeError: up() got an unexpected keyword argument 'stream_output'\n",
        "module_stdout": "",
        "msg": "MODULE FAILURE"
    }

Please give some details of what is actually happening.
Include a [minimum complete verifiable example](http://stackoverflow.com/help/mcve) with
output of running `molecule --debug`.

**Comment by retr0h** [comment]
Your version of `python-vagrant` package is too old.  You need to upgrade your version to one that supports `stream_output`.  A `pip install -U `python-vagrant` should fix you up.

**Comment by r0ckyte** [comment]
Thank you @retr0h.
