### ISSUE TITLE
Goss default test file starts with "# Molucule managed"

### ISSUE THREAD

**Issue by MarkusTeufelberger** [metacloud/molecule#970]
# Issue Type

- Bug report

# Molecule and Ansible details

```
ansible 2.5.0
molecule, version 2.1.0
```

- Molecule installation method: pip
- Ansible installation method: source

# Desired Behaviour

The `test_default.yml` should be modified by the user, it currently seems as if molecule would maybe overwrite its contents and it is not a file that the user should touch at all. I would like this file to only contain the `---` line as first line and then the default/example test case, not the `# Molecule managed` line

**Comment by retr0h** [comment]
The file contains this header b/c it is copied onto the target host and then executed.  If someone on the target host were to see the file, it is letting people know it is managed by Molecule.

**Comment by MarkusTeufelberger** [comment]
Ok, still not too happy about the wording (it sounds to me as if it is somehow internal to molecule) but the explanation makes sense of course.

/closing
