### ISSUE TITLE
Pytest generates warnings when using testinfra wrapper 

### ISSUE THREAD

**Issue by alexppg** [metacloud/molecule#974]
# Issue Type

- Bug report

# Desired Behaviour

It shouldn't show a warning.

# Actual Behaviour (Bug report only)
When executing the testinfra part, it often returns something like this:

```
=================================================================== pytest-warning summary ===================================================================
WP1 None Modules are already imported so can not be re-written: testinfra
======================================================== 1 passed, 1 pytest-warnings in 0.04 seconds =========================================================
```

Is a warning caused by testinfra. It may be fixed just executing `py-test` directly instead of `testinfra py-test`. They explain it better in [it's own testinfra issue](https://github.com/philpep/testinfra/issues/135#issuecomment-332919945)

**Comment by retr0h** [comment]
Thanks for the issue @alexppg.

**Comment by alexppg** [comment]
No problem, thanks for your work.
