### ISSUE TITLE
Support multiple simultaneous logins with cluster-ssh

### ISSUE THREAD

**Issue by 0xDEC0DE** [metacloud/molecule#98]
I have a small shell script that I use to login to multiple vagrant VMs simultaneously using `csshX`; perhaps molecule could investigate the system for the presence of such tools and do something similar if no `<host>` parameter is provided to `molecule login`:

    #!/bin/sh
    
    : init
    PROGNAME=`basename $0`
    TMPFILE=`mktemp -t $PROGNAME`
    trap 'rm -f $TMPFILE' EXIT 
    vagrant ssh-config > $TMPFILE
    CSSH="csshX --ssh_args='-A -F $TMPFILE'"
    
    : enumerate
    CONTROLLERS=`awk '($1 == "Host" && $NF ~ /^controller/) { print $NF }' $TMPFILE`
    COMPUTE_NODES=`awk '($1 == "Host" && $NF ~ /^compute/) { print $NF }' $TMPFILE`
    
    # invocation is "controller", "compute", or "all"
    case "$1" in
        all)
            eval $CSSH ${CONTROLLERS} ${COMPUTE_NODES} ;;
        con*)
            eval $CSSH ${CONTROLLERS} ;;
        *)
            eval $CSSH ${COMPUTE_NODES} ;;
    esac

**Comment by retr0h** [comment]
I don't see us implementing anything of this nature in the near future.  At least not within molecule.  However, you should be able to retain your wrapper script by updating your script with:
 
```
VAGRANT_VAGRANTFILE=molecule/vagrantfile vagrant ssh-config > $TMPFILE
```
