### ISSUE TITLE
Use Ansible's Dynamic Inventories rather than static files

### ISSUE THREAD

**Issue by 0xDEC0DE** [metacloud/molecule#99]
Ansible supports dynamic inventories, rather than from static files:

http://docs.ansible.com/ansible/developing_inventory.html

Molecule's workflow (and the number of config files it needs) could likely be simplified quite a bit if it had an "inventory mode" that it could pass to ansible via the `-i` switch.

**Comment by retr0h** [comment]
Dynamic inventory really isn't going to help much.   We would be replacing one file (ansible_inventory) with the dynamic inventory script.  Not much benefit to that.  Plus we are trying to keep things fairly customizable.  For example the work we have done at work, utilizes special proxmox and vagrant dynamic inventory scripts for different use cases.  We don't want molecule to dictate those conventions.
