### ISSUE TITLE
Support `strategy: debug` ansible option

### ISSUE THREAD

**Issue by jamatute** [metacloud/molecule#994]
# Issue Type

- Feature request

# Molecule and Ansible details

```
ansible 2.4.0.0
molecule, version 2.2.1
```

- Molecule installation method: pip
- Ansible installation method: pip

# Desired Behaviour

When adding the `strategy: debug` in the molecule playbook `molecule/default/playbook.yml`. Once the playbook triggers the debugger give the prompt back so you can interact with it.

# Actual Behaviour (Bug report only)

When executing the tests, the debugger gets called but no prompt is shown so there is no way of interacting with it.

```bash
molecule init role -r test_role
vim molecule/default/playbook.yml
```
```yaml
---
- name: Converge
  hosts: all
  strategy: debug
  tasks:
    - name: Clone non existent git
      git:
        repo: 'git'
        dest: 'git'
```
```bash
molecule test

...
--> Scenario: 'default'
--> Action: 'converge'
    
    PLAY [Converge] ****************************************************************
    
    TASK [Gathering Facts] *********************************************************
    ok: [instance]
    
    TASK [Clone non existent git] **************************************************
    fatal: [instance]: FAILED! => {"changed": false, "failed": true, "msg": "Failed to find required executable git in paths: /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"}
    Debugger invoked

```

**Comment by retr0h** [comment]
Yeah, I don't think there is any way around this.  Molecule owns the execution of Ansible, and does not present a prompt.

The only work-a-round would be to run `molecule --debug` and take the output from `SHELL REPLAY` and `COMMAND` and re-run the `ansible-playbook` command manually.

**Comment by jamatute** [comment]
Thanks @retr0h, that worked
